### ISSUE TITLE
messages cause more than one instance to be kicked off

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#1003]
sasha said, "I just tried to test it where the process was triggered by an incoming message (Travel start event). As a result - got looped creation of new instances with wrong logic. A new instance keeps getting created every 10 sec."

https://dev.app.spiff.status.im/process-models/misc:prototypes:upload-expenses-start:send-message-to-start-event-travel is "Process A" and is the one that has the message intermediate send event and kicks off "Process B" repeatedly (https://dev.app.spiff.status.im/process-models/misc:prototypes:upload-expenses-start:upload-expense-evidense-v2).

**Comment by jasquat** [comment]
Fixed with #1005.

**Comment by dinithihj** [comment]
Tested and verified on dev.app (version 333/335)
Now multiple instances are not generated.

**Comment by dinithihj** [comment]
Tested and verified on test.app (version 193/195).
Tested using below sample models

- https://test.app.spiff.status.im/process-models/misc:qa:multiple-start-event-test-model
- https://test.app.spiff.status.im/process-models/misc:qa:multiple-start-events-test-call-1
- https://test.app.spiff.status.im/process-models/misc:qa:multiple-start-events-test-call-2

**Comment by madhurrya** [comment]
Released to Prod on 2024 February 20th
