### ISSUE TITLE
ProcessInstanceIsAlreadyLocked error - dev.mod (Celery)

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1006]
During my pp3 testing in dev.mod, noticed the the ProcessInstanceIsAlreadyLocked error few times. (about 4,5 times with around 40-45 instances)

![Image](https://github.com/sartography/spiff-arena/assets/110527567/fe12a4e9-ac66-4dbe-946b-52cb72b465d0)

**Comment by madhurrya** [comment]
Starting to notice this error in time tracker site also frequently. It seems the frequency of the error increases as the number of instances increase.

**Comment by madhurrya** [comment]
KB/Jason, is it possible to get this deployed to the time tracker site also, so it get tested over time.

**Comment by jasquat** [comment]
timetracking has had celery for a couple months. Alex did get this error there yesterday and we made a change we hope will help to resolve this. That has been deployed to dev.mod.

**Comment by madhurrya** [comment]
@jasquat So the latest fix is deployed to timetracker also?

**Comment by jasquat** [comment]
@madhurrya yep it's there now.

**Comment by harmeet-status** [comment]
@madhurrya can you test this as a priority? This fix should hopefully fix this ticket: https://github.com/sartography/spiff-arena/issues/1177

If not, let me know and we will need to prioritise the ticket above.

**Comment by madhurrya** [comment]
@burnettk I think we'll need to get this issue fixed first https://github.com/sartography/spiff-arena/issues/1235 to start testing this ticket, as we have to keep on creating instances to test this.
Also could you please copy the current dev.app models to dev.mod. So we can run some of those models.

**Comment by burnettk** [comment]
force pushed models from dev.app to dev.mod. need to go back and delete https://github.com/status-im/process-models/tree/mod-dev-bak-20240328 at some point.

**Comment by madhurrya** [comment]
Didn't notice this error recently.
