### ISSUE TITLE
Coworking limits - Data Store

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1007]
Create a process allowing the addition of entries to the data store during a period and check new entries vs accumulated amounts.

Use Case:
- there is a monthly limit per month
- every time a user uploads a receipt per period - need to check if there is an available amount left
- the Data store should be erased for each period
- the Data Store should not have static CC list, the list should be created every period on the go - when a user submits their first receipt within the period - the entry for the CC is created

**Comment by calexh-sar** [comment]
@sashayar13 in which Process Group should this Data Store be created?

**Comment by sashayar13** [comment]
@calexh-sar https://dev.app.spiff.status.im/process-groups/manage-finance:accounts-payable:process-expense-reports

**Comment by calexh-sar** [comment]
@sashayar13 is the monthly limit per calendar month or x days from their last purchase?

**Comment by sashayar13** [comment]
@calexh-sar per calendar month
