### ISSUE TITLE
Find recently errored process instances

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#1021]
new feature request: be able to view a list of process instances by date errored. i guess errors are currently stored in two database tables: process instance event and task event.
it would also be useful to be able to see the error in the same interface, but seeing the ones that have errored most recently is the first priority.
note that process models can be configured to go into the "suspended" status instead of "error."

**Comment by madhurrya** [comment]
These couple of days 100s of instances are getting errored due to the waku issue and it becomes a nightmare to go through each instance to check the error message.
So having the ability to see the latest errored instances with the error message on the same table will be really helpfull. Otherwise we'll still have to go inside each instance one by one for 100s instances when scenarios like this happens and it happens once in every few months.


![Image](https://github.com/sartography/spiff-arena/assets/110527567/fa1bd602-b1bf-46e4-be8e-15e3fed64123)

**Comment by burnettk** [comment]
try hitting /extensions/recent-error-events on dev.app, and you can find the process model that defines it by searching for "recent error events" in the process model search.

**Comment by jasquat** [comment]
@madhurrya the full url is https://dev.app.spiff.status.im/extensions/recent-error-events. This is an extension and needs to be run as an extension rather than from starting the model. We did add a ui component so the only way to get to it is by going to the url directly. We could add that to a README in the model.

**Comment by madhurrya** [comment]
@jasquat ah ok. So I should just use https://dev.app.spiff.status.im/extensions/recent-error-events ?

This is what I see there. Are all these entries supposed to show as table rows here? I am seeing only one row.
![image](https://github.com/sartography/spiff-arena/assets/110527567/87f39ded-1fba-4377-b0e6-d6a7c24844d7)

**Comment by jasquat** [comment]
Yep, and yeah. We are looking into fixing the markdown sensitization to fix this.

**Comment by jasquat** [comment]
@madhurrya it should be working now.

**Comment by madhurrya** [comment]
This is looking nice :-) Thank you.
we'll use this in all the environments for this release and will let you know if we need to change/update anything.

Can we easily add the Started by column to the table? So we can ignore Sasha/Alex/Marius test errors easily when going through the list.
![image](https://github.com/sartography/spiff-arena/assets/110527567/e620de1d-f798-42d4-b1f1-be70a227c25e)

**Comment by burnettk** [comment]
updated columns a bit per feedback. if you hover over the process instance id, it lists the event id and type.

**Comment by madhurrya** [comment]
Thank you.

**Comment by madhurrya** [comment]
Please add this to the other environments also (assuming it's not related to the general code deployment.)

**Comment by burnettk** [comment]
https://github.com/status-im/process-models/pull/1610

**Comment by madhurrya** [comment]
I am seeing multiple entries for some instances.
e.g

https://test.app.spiff.status.im/extensions/recent-error-events
![Image](https://github.com/sartography/spiff-arena/assets/110527567/56a65430-e4a0-4e4f-8dd5-8d1adc298f60)

**Comment by madhurrya** [comment]
All these instances seems to be missing in the list
https://test.app.spiff.status.im/extensions/recent-error-events

![Image](https://github.com/sartography/spiff-arena/assets/110527567/f9c7ba2a-f261-4d85-b9ba-ab969977d1a9)



![Image](https://github.com/sartography/spiff-arena/assets/110527567/2696da0c-a0f8-49c8-8681-4c054f8f2007)

**Comment by jasquat** [comment]
@madhurrya I think it's working as expected. We do not query process instances instead we query the error events that are attached to them. For process instance 33, there are indeed 4 error events attached to it: https://test.app.spiff.status.im/process-instances/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:request-new-role/33?tab=2&log-list-events_page=1&log-list-events_per_page=50&event_type=process_instance_error

For the missing process instances I'm not seeing any error events associated with those instances. For example PI 214: https://test.app.spiff.status.im/process-instances/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:request-new-role/214?tab=2&log-list-events_page=1&event_type=task_failed and https://test.app.spiff.status.im/process-instances/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:request-new-role/214?tab=2&log-list-events_page=1&event_type=process_instance_error.

**Comment by madhurrya** [comment]
@jasquat Ok. got it.
Yeah it looks like those missing ones were manually suspended ones. Not errored ones.

**Comment by madhurrya** [comment]
@burnettk If the model related to this is updates could you please send PRs to update it in test.app and test.mod to Sasha. (I think you have updated the table format in dev.app. I don't see it like that in test.app)

**Comment by burnettk** [comment]
@sashayar13 i think i may have forgotten how the status process model promotion process works. does it work for you if you promote this model from https://test.app.spiff.status.im/process-models/misc:extensions:recent-error-events ?
