### ISSUE TITLE
Assistance with new BBHR API calls

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1023]
1. Need a process which gets Department list updates from BBHR and creates a line in the Iplicit (create new item)
2. Need to have a process which gets CC’s current Department and Team details with their BBHRids from Bamboo.
3. Need a process which gets Team list updates from BBHR and creates a line in the Iplicit (Bamboo support ticket is WIP) (create new item)

**Comment by calexh-sar** [comment]
@sashayar13 the lists created by this process will most likely be placed in a Data Store for reference and comparison at a later time.  Will this information need to be used anywhere else?  If so, in which Process Group should I create the Data Store?  If not, I will create it in the Process Group where this Process Model will reside.  Please advise where that should be.

**Comment by sashayar13** [comment]
@sashayar13 I expect that this data will be used across a number of process models. Shall we create it at the same level as Dynamic Enums?

**Comment by calexh-sar** [comment]
@sashayar13 would you please clarify where in Iplicit the `create new item` needs to be placed.  Am I correct that #1 would update Iplicit using the Department endpoint?  If so, which of these entries would you like to include:

![Image](https://github.com/sartography/spiff-arena/assets/54854669/820f1a4b-aa3c-4b31-9f6c-1e442a64713d)

Do you need any Cost Center updates if a department is added or removed?

And am I correct that the CC's Team information would be added to Iplicit as a Contact Resource?  If so, will the initial entry for the CC already be in implicit or will a new Iplicit Contact Reource need to be created?  if this latter, what information needs to be added:

![Image](https://github.com/sartography/spiff-arena/assets/54854669/e70fd89d-5ae5-4a18-8921-ad189a8c38c1)

**Comment by sashayar13** [comment]
@calexh-sar 
Regarding the item 1 - Departments - correct, this is the endpoint we need to use
<img width="1429" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/b4b30c0b-edd7-4144-b594-7f637b4f26eb">

We will need to supply the code (BBHRid of Department), description (BBHR Department name) and parent id (should be always equal  to "NA")

**Comment by sashayar13** [comment]
regarding the item 2 - no need to write this to the Iplicit, this data will be needed for other processes within Spiff

Only 1 and 3 - will need to be written to the Iplicit

**Comment by calexh-sar** [comment]
@sashayar13 please confirm for me that (Bamboo Division = Status Department) and (Bamboo Department = Status Team).

**Comment by sashayar13** [comment]
@calexh-sar Bamboo Division = Status program, Bamboo Department = Status Project, Bamboo Team = Status team

Yes, only active entities are needed

**Comment by calexh-sar** [comment]
@sashayar13 for the bullet point `add BBHRids`, are you asking for the BBHR ids of all the employees assigned to each Division/Department/Team?  If so, do you want the BBHR API id automatically assigned, the ID assigned manually or both?

**Comment by sashayar13** [comment]
@calexh-sar BBHR ids of the Division-Department-Team

**Comment by calexh-sar** [comment]
@sashayar13 would be helpful if the dev BBHR could be updated with additional Team assignments that mirror the current hierarchy.

**Comment by calexh-sar** [comment]
@sashayar13 I created PR #1093 with the latest updates in case you want to push to prod to check the output instead of updating the dev BBHR Teams.

**Comment by calexh-sar** [comment]
@sashayar13 would you please answer a few questions to clarify what is needed for #1 and #3. 

For #1:
- Do you want BBHR Divisions (Status Programs) included as Iplicit Departments and listed as the parentDepartmentId for BBHR Departments (Status Projects)?

For #3:
- Is this no longer needed since the relationship between Departments and Teams in BBHR is implied by the employee assignments or do you want me to use the report created in #2 to establish the relationships?

**Comment by sashayar13** [comment]
@calexh-sar #1 and #3 are not needed anymore. The solution you created for the Bamboo hierarchy report should cover our needs. The only improvement I suggested for the report is to move the BBHRids into separate columns.

**Comment by calexh-sar** [comment]
@sashayar13 PR #1097 has the updates to "move the BBHRids into separate columns".

**Comment by calexh-sar** [comment]
@sashayar13 I had started working on the Process Models `Bamboo Department Sync` and `Bamboo Division Sync` in the [Iplicit Process Group](https://dev.app.spiff.status.im/process-groups/misc:service-tests:iplicit) for #1 and #3.  Please let me know if you would  like for me to delete those Process Models.

**Comment by sashayar13** [comment]
thanks, @calexh-sar Yes, there is no need for the automated sync at this stage; the report you created covers the current needs. Please go ahead with deleting the process models

**Comment by calexh-sar** [comment]
Deleted `Bamboo Department Sync` and `Bamboo Division Sync` process models.  @sashayar13 please let me know if the latest updates to the report are all you need and if this issue can be closed.

**Comment by sashayar13** [comment]
thanks @calexh-sar 
All looks good. The issue can be closed

**Comment by calexh-sar** [comment]
Closing per @sashayar13's previous comment.
