### ISSUE TITLE
It is not possible to move a message start event to a new process

### ISSUE THREAD

**Issue by danfunk** [sartography/spiff-arena#1027]
If you create a process with a message start event, then that process is assocated with that message forever.  You can't change the messaage name or delete the start event, and then re-use it in a different process.

**Comment by jasquat** [comment]
Implementation in #1070

**Comment by madhurrya** [comment]
Tested using these 2 models and now we can change the message and delete the message start event and re use it in another model.

https://dev.app.spiff.status.im/process-models/misc:qa:message-start-model-1
https://dev.app.spiff.status.im/process-models/misc:qa:message-start-model-2

**Comment by madhurrya** [comment]
Released to Prod on 2024 February 26th
