### ISSUE TITLE
Process instance list filtering/user experience - Admin user

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1030]
Currently, an Admin user cannot interact/process instances effectively through the "All process instances" list.

The Use Case - Admin needs to review and apply admin actions to a list of process instances based on certain criteria.
The steps (as is):
1. Go to the All process instance list
2. Set filters + apply Perspective
3. The list of process instances matching the criteria is displayed
4. Admin needs to open each process instance to check task data and, if needed, to rewind the process to a certain step or assign a new user to a task.
5. When Admin opens the process instance and completes the activities, she needs to go back to the previously filtered list and repeat this set of actions to the other process instance.
6. BUT the process instance list needs to be filtered again, all the configurations needs to be set again. And this needs to be repeated all XXX times

How the UX for Admins can be improved:
- To allow opening a process instance in a new tab (a button or by right-click)
- To allow keeping the filtered list and refreshing it (for example, through a button at the top of the screen or as part of the filters section)
- any other ideas are welcome

**Comment by calexh-sar** [comment]
Initial 1 DD estimate for prototype.

**Comment by madhurrya** [comment]
This is working as expected.
Only issue I had with the new update is I have been accidently clicking the Process model link to open the process instance. Hope  the users will get used to it. 
And for a normal user I am not sure whether they really need the link to the process model.

@sashayar13 do you have any feedback on this ticket or can we mark this as complete?

**Comment by burnettk** [comment]
in proposal, 1: if a user accidentally clicks on the process model link to open the process instance, that sucks and we don't want confused users, but they can click the back button and click the correct thing (either the process instance id or the button, if there is something they need to do).

in status quo:
1: if a user wants to open a process instance in a new tab, it is not technically possible
2: if a user wants to open the process model, it is not technically possible
3: if a user wants to copy and paste contents of table cells, it is not technically possible
4: the html is invalid

**Comment by madhurrya** [comment]
@sashayar13 where should I move this ticket? as completed or to the backlog? (since we reverted the opening in tab feature)

**Comment by harmeet-status** [comment]
@burnettk can we just put a button like this instead?
<img width="1680" alt="Screenshot 2024-03-12 at 6 30 36 PM" src="https://github.com/sartography/spiff-arena/assets/104047049/e591b0e3-000d-47c9-9b6d-348ba311b619">

**Comment by jasquat** [comment]
@harmeet-status so you mean we keep the whole row clickable but add a button that opens the instance in a new tab?

**Comment by harmeet-status** [comment]
Yes!

**Comment by jasquat** [comment]
@harmeet-status that has been implemented in #1234

**Comment by harmeet-status** [comment]
Found a bug
![Image](https://github.com/sartography/spiff-arena/assets/104047049/9a137f8a-09e7-4d93-af8e-3e3c37839de3)

**Comment by harmeet-status** [comment]
Could you also switch the order of these columns so the arrow appear at the end (to the right)
![Image](https://github.com/sartography/spiff-arena/assets/104047049/e77f72c4-f291-4085-be14-91d3559e1d61)

**Comment by burnettk** [comment]
we also prefer the arrow to the right, but since the Go button is optional, that's the reason we decided to put the the arrow first. this way like elements are always in the same place, if present. not sure if you agree that it's better this way on balance.

**Comment by madhurrya** [comment]
I can see the full tool tip. Checked with smaller sized pages also.
![image](https://github.com/sartography/spiff-arena/assets/110527567/1423b57a-934d-4646-b8c8-7d992639df75)
![image](https://github.com/sartography/spiff-arena/assets/110527567/4d9279b3-cd1b-48f1-b071-aaa69ba7a104)

@harmeet-status Can I close this ticket now based on KB's comment.

**Comment by harmeet-status** [comment]
@madhurrya the text is truncated on the process instances page, error still here.
<img width="1680" alt="Screenshot 2024-03-25 at 9 58 47 PM" src="https://github.com/sartography/spiff-arena/assets/104047049/2c148131-b07e-43dc-a75f-35bf3d26a5dc">

**Comment by harmeet-status** [comment]
> we also prefer the arrow to the right, but since the Go button is optional, that's the reason we decided to put the the arrow first. this way like elements are always in the same place, if present. not sure if you agree that it's better this way on balance.

I understand your logic, it makes sense. But visually I would prefer to have arrow in the right side, since to me that makes it visually consistent from the right. The arrow won't move as it will always be the first thing when looking at the table from the right.

Another thing is that is it possible to make the arrow closer to the right edge, just like we do for the icons on the process model page?
<img width="1680" alt="Screenshot 2024-03-25 at 10 07 32 PM" src="https://github.com/sartography/spiff-arena/assets/104047049/89608c5d-8ed2-4548-a49a-ce4f27b1bae0">
<img width="898" alt="Screenshot 2024-03-25 at 10 08 40 PM" src="https://github.com/sartography/spiff-arena/assets/104047049/a9c36b70-efb6-4747-b6e4-f42c4ee8706e">

**Comment by madhurrya** [comment]
@harmeet-status  do you need these changes done for the Prod release? I mean is it OK to do the release with what we have or do you prefer it changed before the release?

**Comment by burnettk** [comment]
could do this:

![image](https://github.com/sartography/spiff-arena/assets/18027/2c551594-404c-4b7d-ac8c-2fd51374d619)

getting them to float right doesn't work when there is a mix of buttons and icons (it shoves the button on top of the icon, rather than next to it, which looks bad). perhaps we pick either like this screenshot or like it is now, and then consider changing it with the UI redesign?

**Comment by harmeet-status** [comment]
Yeah that looks good @burnettk

**Comment by madhurrya** [comment]
The tool tip truncate issue happens when the arrow is in the last column (if there's no Action button)
![image](https://github.com/sartography/spiff-arena/assets/110527567/e73ce899-1fbc-4cbd-90b3-0a2a049dba0b)

**Comment by harmeet-status** [comment]
This is still broken on the process instances page, the arrow is suppose to be right aligned. How did you do this on the process model page for the files? @burnettk 
<img width="1249" alt="Screenshot 2024-03-26 at 11 40 54 PM" src="https://github.com/sartography/spiff-arena/assets/104047049/dcee9a33-2602-4208-ab20-c73db62aea80">

**Comment by burnettk** [comment]
CSS is silly. It works without a buttonset on the process model page because it is all icons. On this page, where it is a button and an icon, that approach does not work. Should we put it back to the left?

**Comment by harmeet-status** [comment]
Leave as-is, let go to prod.

**Comment by madhurrya** [comment]
@harmeet-status do you mean we'll go with what we have in Dev? 
![image](https://github.com/sartography/spiff-arena/assets/110527567/4eab24ce-defd-47b5-8ad0-acd73ddbd31b)

**Comment by harmeet-status** [comment]
@madhurrya yes

**Comment by madhurrya** [comment]
Released to Prod on April 2nd
