### ISSUE TITLE
Iplicit API Calls - New operators

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#1032]
We need defined operators for PATCH, PUT and DELETE as included in the swagger documentation
https://api.iplicit.com/api-docs/index.html#/

**Comment by MarD0607** [comment]
> this is in reference to the http connector, which has historically only supported GET and POST?

Yes

**Comment by calexh-sar** [comment]
@burnettk yes, Marius discussed this with @jbirddog and me.  I have this tickets as a poet-scrum discussion today.  I think it is primarily a dev ticket, with some process work to confirm the new http connector updates.

**Comment by jasquat** [comment]
The additional http methods have been added to https://github.com/sartography/connector-http. They can be selected from a service task.

**Comment by MarD0607** [comment]
@Kayvon-Martinez Please help with building additional test processes and testing out all the endpoints needed for the Iplicit Integration

**Comment by madhurrya** [comment]
@Kayvon-Martinez @MarD0607 Is there any ongoing work related to this or is all the work complete and can I start testing this?

**Comment by calexh-sar** [comment]
@madhurrya please take a look at https://dev.app.spiff.status.im/process-groups/misc:service-tests:iplicit and if this assists you with testing this issue let me know if you questions.

**Comment by madhurrya** [comment]
Tested GET/POST/PUT/PATCH/DELETE using the Models here https://dev.app.spiff.status.im/process-models/misc:qa:iplicit-api-calls-test

![image](https://github.com/sartography/spiff-arena/assets/110527567/11032d49-8b45-44d0-a59b-a40d4d1d9548)

![image](https://github.com/sartography/spiff-arena/assets/110527567/b63eb7df-4a49-4525-ba0f-f951d0f37b16)


@calexh-sar  @burnettk do you think there is anything else I need to test under this ticket?

**Comment by burnettk** [comment]
nah, sounds good.
