### ISSUE TITLE
Persist data store definitions in the process_group.json file

### ISSUE THREAD

**Issue by jbirddog** [sartography/spiff-arena#1037]
Currently when a data store is added in a given environment, there is no way to promote its definition along with process model changes. Adding the data store definition to the process_group.json file where the data store resides will allow us to detect add/update/deletes and sync the database during the promotion process. Just to note data store data will not promote, just the definition (name, identifier, type, schema, description).

**Comment by dinithihj** [comment]
Tested on dev.app ( Version 334/336).

Noticed that the process_group.json file only gets updated when we create/update process groups/models, not when we create or update data stores. 

The team decided to move forward with this and agreed to add a feature in the future that auto-commit any changes made to the data store into the process_group.json file. Created a new ticket https://github.com/sartography/spiff-arena/issues/1084 for the implementation of auto-commit feature.

**Comment by madhurrya** [comment]
Added a new issue related to Data store promotion as it is currently not working. https://github.com/sartography/spiff-arena/issues/1094

**Comment by madhurrya** [comment]
Released to Prod on 2024 February 22nd
