### ISSUE TITLE
Data store reference property window shows all the datastores created in the system

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1041]
The Data store reference property window shows all the datastores created in the system. It should only show the data stores that match the path of the specific process model.

![Image](https://github.com/sartography/spiff-arena/assets/123297840/74ef75c5-8cd9-48a4-a0d0-a8a22eb661ff)

**Comment by dinithihj** [comment]
Tested and verified on dev.app (Version 343/345)
Now it's showing the data stores that match the path of the specific process model.



![Screenshot 2024-03-04 130714](https://github.com/sartography/spiff-arena/assets/123297840/0a39023d-283c-4683-b377-76e278ca564d)
![Screenshot 2024-03-04 130858](https://github.com/sartography/spiff-arena/assets/123297840/dfd48476-0611-4c59-a505-fce1248dd15f)

**Comment by madhurrya** [comment]
Released to Prod on March 11th
