### ISSUE TITLE
Add/Edit Data Store page - Schema is not marked as required

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1043]
On the Add/Edit Data Store Page, the Schema Field is validated as Required but in the user interface, it is not indicated as Mandatory with the * sign

![Image](https://github.com/sartography/spiff-arena/assets/123297840/a70b1ae0-8bb7-4b8e-8122-eee366be4207)

**Comment by tcoz** [comment]
Updated the label to reflect required. (Schema*)

**Comment by burnettk** [comment]
addressed in https://github.com/sartography/spiff-arena/pull/1049

**Comment by dinithihj** [comment]
Verified on dev.app (version 334/336)

![image](https://github.com/sartography/spiff-arena/assets/123297840/1aef80e8-a6db-4e60-b1e8-b62795459e24)

**Comment by madhurrya** [comment]
Release to Prod on 2024 February 22nd
