### ISSUE TITLE
Programmatically Update Secrets

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#1044]
Provide a means to programmatically update a secret.

The Use Case for this request is to be able to store the Iplicit session token as a secret and have a process with a timer that periodically updates the session token stored in a secret before it expires.

**Comment by calexh-sar** [comment]
Provide a means to programmatically update a secret.

The Use Case for this request is to be able to store the Iplicit session token as a secret and have a process with a timer that periodically updates the session token stored in a secret before it expires.

**Comment by jbirddog** [comment]
A new function `set_secret(name, value)` is now available to script tasks. The script requires that the process is run by a user with admin permissions.

**Comment by madhurrya** [comment]
Added and Updated a Secrete using this model. https://dev.app.spiff.status.im/process-models/misc:qa:update-secret

**Comment by madhurrya** [comment]
@jbirddog what is the check we are doing related to this statement 'The script requires that the process is run by a user with admin permissions.'?
The support users can also run this model since they have access to all the models. But since support doesn't have access to Configurations, I think he shouldn't be able to run this and update it.

**Comment by madhurrya** [comment]
Ok Thanks Jon.
@jbirddog @burnettk Since Status does care a lot about these security/permission related things, what can we do to allow this script to be run only by the admins and not by Support or anyone else?

**Comment by burnettk** [comment]
what user are you testing with specifically and on what environment? on dev.app, for example, there are lots of users in the "Support" group who are also in the "admin" group, and since the "admin" group on dev.app has access to literally everything...

**Comment by madhurrya** [comment]
@burnettk I am using the fin@status.im account. It is only a support user and not an admin. He doesn't have access to the Configs menu. 
![image](https://github.com/sartography/spiff-arena/assets/110527567/79f739fc-512d-4c48-ae13-b1f97c70b8b7)

**Comment by burnettk** [comment]
right, we found it. it's this line in the DMN: 
![image](https://github.com/sartography/spiff-arena/assets/18027/d931308e-3c5f-44b5-82a4-976f3579c3df)

we can totally update the code that implements that `SUPPORT` macro to avoid granting that permission if desired. that may have other affects on things they need to do, but if that's the desired direction, we can make the change and see what breaks. one example is that they will no longer be able to run the set-permissions process model (which is probably reasonable).

**Comment by madhurrya** [comment]
Let's check with @harmeet-status what he thinks.

**Comment by harmeet-status** [comment]
The permissions should be additive. If a user is part of "admin" and also "support", we would consider them an admin. Hence they should be able to update secrets through this script.

Does that answer your question @madhurrya?

**Comment by madhurrya** [comment]
@harmeet-status We have added a new script function where we can update a Secret. Here is a sample model. https://dev.app.spiff.status.im/process-models/misc:qa:update-secret
At the moment even a support (who does not have admin access and no access to the Secrets page) can run a model which contains that script and update a secret. Question is, whether we need to worry about that and whether it should be restricted. If we need to restrict then KB will have to do the update as he explained and he has said it might affect other options that Support has at the moment.

**Comment by harmeet-status** [comment]
Good to go ahead on this one, secret is safe from Support group.

**Comment by madhurrya** [comment]
Released to Prod on March 11th
