### ISSUE TITLE
No way to get all Data Store values

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1072]
On data stores, it is possible to pass the top_level_key and retrieve all the secondary_keys and their values. 
But currently, there's no way to get entire data store values without passing a top_level_key.

**Comment by calexh-sar** [comment]
@dinithihj what would be the use case for this feature enhancement?

**Comment by calexh-sar** [comment]
@dinithihj one way you could display all the Data Store values is to use Multi-Instance to pass in all the secondary keys and accumulate the result in the Output Collection.  Do you think this method would be a suitable solution to this issue or having the ability to retrieve with a script would be best?

**Comment by dinithihj** [comment]
@calexh-sar Thanks for the comment. I have tried one example with Multi-Instance and I was able to retrieve all the values from data store. 

However, I'm not sure if this will work in every situation. To get all the data, we need to know all the keys. If we don't know the keys, it's not possible to retrieve all the data store values using Multi-Instances.

Maybe we'll wait and see if there are real situations where this feature is necessary.

**Comment by calexh-sar** [comment]
@dinithihj thanks for checking the multi-instance option.  For most of the Data Stores I have created so far an enumeration list of the secondary keys was also created so the values can be easily viewed and edited.  No guarantee that will always be the practice, so waiting to "see if there are real situations where this feature is necessary" sounds like the best course of action.

**Comment by madhurrya** [comment]
@calexh-sar are we going to close this issue for now?
