### ISSUE TITLE
Task data screen disappeared when clicking on some loop iterations

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1073]
Created a process model with Loop Script task. 
Sample - https://dev.app.spiff.status.im/process-models/misc:qa:loop-script-task

When clicking on some loop iterations (when clicking on the number) task data screen disappeared. 

Below are four process instances created using the above process model. 

- https://dev.app.spiff.status.im/i/4567  - The task data screen disappeared when clicking on 3 and 4
- https://dev.app.spiff.status.im/i/4568  - The task data screen disappeared when clicking on 2 and 4
- https://dev.app.spiff.status.im/i/4569 - Did not have an issue and task data for all iterations were displayed
- https://dev.app.spiff.status.im/i/4570  - The task data screen disappeared when clicking on 4

 

Video link - https://drive.google.com/file/d/1IQEYxpUyOrQM5yDax-tR-kF1zWFXRxcx/view?usp=sharing

**Comment by madhurrya** [comment]
Couldn't recreate this issue today. It seems to be fixed now. So closing this.
