### ISSUE TITLE
JDBC remote connection from Spiff --> OpenKM to update metadata template

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#1074]
OpenKM our current DMS has metadata templates configured in the system. This allows any uploaded file to have metadata captured against it. We can do things like simple text field, to complex single or multi-picker from a dropdown.

The use-case we want to develop for is updating the metadata template to change the options in the picker. We can use currency as an example:
currency: [list of 5 currencies]

These currencies will be managed in Spiff and every time a new one is added, we want to call OpenKM and update the metadata template so that a user can use the newly created currency.

See PDF attached on how support suggests that we do this.
URL: https://docs.openkm.com/kcenter/view/okm-8.1/creating-your-own-option-select-values-plugin.html
[Update metadata picklist from external system.pdf](https://github.com/sartography/spiff-arena/files/14342985/Update.metadata.picklist.from.external.system.pdf)

**Comment by harmeet-status** [comment]
@burnettk can you have a look at this because OpenKM support takes a while to respond back so we want to be in a position that by the time we start developing this, we have all of the answers that we need from OpenKM.

I have already set up the test environment with the metadata template so that is ready.

**Comment by calexh-sar** [comment]
@jbirddog to investigate before estimating

**Comment by jbirddog** [comment]
I don't seem to have access to open the pdf, but was able to find some documentation about OpenKM rest apis which on the surface look straightforward. Not sure of the flow of the api calls we will need, or if we have a way to play around with them ahead of time.

**Comment by harmeet-status** [comment]
PDF uploaded here.
[Update.metadata.picklist.from.external.system.pdf](https://github.com/sartography/spiff-arena/files/14491556/Update.metadata.picklist.from.external.system.pdf)

**Comment by danfunk** [comment]
Harmeet is trying to get someone from the support team at OpenKM that can answer the question.

**Comment by harmeet-status** [comment]
Here is the docs from their website which talks about this very thing.
![Image](https://github.com/sartography/spiff-arena/assets/104047049/8044946e-24b8-4a02-916e-83d5966dcff2)
![Image](https://github.com/sartography/spiff-arena/assets/104047049/b6f463cc-ab28-4e6b-bf1d-84181afbd1f5)
![Image](https://github.com/sartography/spiff-arena/assets/104047049/c6c3cf43-c74b-40fc-b7e5-4ec470fe5380)
