### ISSUE TITLE
Timed events are not triggering

### ISSUE THREAD

**Issue by stefanroels** [sartography/spiff-arena#1075]
We are trying to deploy a SpiffArena server, but Timed events do not trigger at all. Neither timed start events nor timed boundary events.

I can see the scheduler running in the docker logs, but the events do not trigger.

What could be the reason for this and how can I debug the scheduling?

**Comment by stefanroels** [comment]
I think I have found the problem. I forgot to add quotes around the time string. I must say that is confuses me a lot that in text inputs you need to use quotes, although it also provides the flexibility to use task variables.

**Comment by danfunk** [comment]
@stefanroels - we have many improvements we would like to make to the BPMN modeling experience, and we are discussing it again this evening.   With a little effort, we could, as the diagram is built, amass knowledge about the variables in play, and offer validation throughout every script and text box to determine if it can be properly evaluated.  If we had such a system in place, we could have notified you immediately of the issue.   

We are also fighting everyday to find funding and support to make exactly these types of additions to the application.
