### ISSUE TITLE
allow for setting greedy mode in terms of bpmn execution

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#1083]
in this scenario, we should continue running engine steps until all engine (automatic) steps are exhausted and the entire process is blocked on human tasks or waiting tasks or similar. this is something that dylan is looking for, and is approximating by avoiding instructions on activities.

relevant PRs:
 * https://github.com/sartography/spiff-arena/pull/1161
 * https://github.com/sartography/spiff-arena/pull/1173
 * https://github.com/sartography/spiff-arena/pull/1191

**Comment by dinithihj** [comment]
@burnettk Can you please let me know how to test this ticket?

**Comment by dinithihj** [comment]
@burnettk When you get a chance can you please let me know how to test this ticket?

**Comment by burnettk** [comment]
@dinithihj sorry for the delay. first, get a token from the developer tools network tab.

make sure this request works:

`curl "https://dev.mod.spiff.status.im/api/v1.0/process-groups" -H "Authorization: Bearer [YOUR_TOKEN]`

then create an instance:

`curl -X POST "https://dev.mod.spiff.status.im/api/v1.0/process-instances/misc:test:madhu-model-1" -H "Authorization: Bearer [YOUR_TOKEN]`

the instance request will return an "id".

Run the instance, replacing 35919 with your id:

`curl -X POST "https://dev.mod.spiff.status.im/api/v1.0/process-instances/misc:test:madhu-model-1/35919/run?execution_mode=asynchronous"  -H "Authorization: Bearer [YOUR_TOKEN]`

this will return an instance with status not_started.

then create/run a new instance the same as above except replace `execution_mode=asynchronous` with `execution_mode=synchronous` when running. instead of not_started, you should see status user_input_required because it runs as much as possible during the run request, instead of a giving a message to celery to run the instance in the background.

**Comment by dinithihj** [comment]
@burnettk Thank you for the explanation. I have successfully executed the steps you mentioned. I'll do more testing around this. Just to confirm, this can only be tested on the dev.mod environment, right?

**Comment by burnettk** [comment]
I think it should actually do a similar thing on other environments, but there may be minor differences.

**Comment by burnettk** [comment]
1 and 2 sound right. I will hopefully remember to force push app-dev to mod-dev.

**Comment by burnettk** [comment]
yeah, i think it's ok for created process instances to run. i don't think there is a use case for just creating when you don't want the instance to run. i honestly can't remember why it is two different APIs. it is worth considering making a start API that combines both into one call. it will take some time for the instances to be picked up in the current implementation if run is not called, so the recommended practice would be always calling create and then run.

**Comment by dinithihj** [comment]
@burnettk Thank you for your explanation I have further tested this on dev.mod with the model https://dev.mod.spiff.status.im/process-models/misc:qa:test-execution-mode 

It worked as you explained. When running with execution_mode=synchronous it completes the process as much as possible. And if there are no user/manual tasks within the path it completes the instance.  But when you have message intermediate throw/catch events within the path it returns the waiting status.

Please see the below scenario and see whether it's correct. 

When you have message intermediate throw/catch events within the path as below 

![image](https://github.com/sartography/spiff-arena/assets/123297840/e760438e-06f7-4b22-a2cc-87f358a7e4a3)

when you create the instance and run it with below command

`curl -X POST "https://dev.mod.spiff.status.im/api/v1.0/process-instances/misc:qa:test-execution-mode/36107/run?execution_mode=synchronous"  -H [TOKEN]`

it returned the waiting status

![image](https://github.com/sartography/spiff-arena/assets/123297840/7ea411f1-729a-4df7-821a-c4c732e1a7d2)

**Comment by burnettk** [comment]
waiting sounds right when the instance is waiting for a message, yeah.

**Comment by dinithihj** [comment]
Tested on dev.mod (version 72/63) using model https://dev.mod.spiff.status.im/process-models/misc:qa:test-execution-mode and https://dev.mod.spiff.status.im/process-models/misc:qa:test-execution-mode-sub-model

When running the create instance command a new instance is created and run

`curl -X POST "https://dev.mod.spiff.status.im/api/v1.0/process-instances/misc:qa:test-execution-mode" -H "Authorization: Bearer [TOKEN]`

![image](https://github.com/sartography/spiff-arena/assets/123297840/cf1de381-59e8-432a-8cbc-92816c2c84e8)


When executing the run command with execution_mode=asynchronous it returns the instance state "not_started"

`curl -X POST "https://dev.mod.spiff.status.im/api/v1.0/process-instances/misc:qa:test-execution-mode/37142/run?execution_mode=asynchronous"  -H "Authorization: Bearer [TOKEN] `

![image](https://github.com/sartography/spiff-arena/assets/123297840/46962c2b-678f-4285-b553-9cfa94ac69fb)


When executing the run command with execution_mode=synchronous it completes the process as much as possible. And if there are no user/manual tasks within the path it completes the instance. (Tested with call activities, sub-processes, script tasks, and manual/user tasks)

`curl -X POST "https://dev.mod.spiff.status.im/api/v1.0/process-instances/misc:qa:test-execution-mode/37144/run?execution_mode=synchronous"  -H "Authorization: Bearer [TOKEN] `

![image](https://github.com/sartography/spiff-arena/assets/123297840/52b3770d-777a-419e-9420-049e4a4c1c66)

![image](https://github.com/sartography/spiff-arena/assets/123297840/b26b36af-81ea-478e-8c4d-85d36fa8b665)


When executing the run command with execution_mode=synchronous and If there are message intermediate throw/catch events within the path it returns the waiting status.

`curl -X POST "https://dev.mod.spiff.status.im/api/v1.0/process-instances/misc:qa:test-execution-mode/36107/run?execution_mode=synchronous"  -H [TOKEN]`

![image](https://github.com/sartography/spiff-arena/assets/123297840/a3a377ca-6ca2-4d0e-abd0-48d3aa53aaa6)

@burnettk above is the summary of testing I have done. Is there anything else I need to test related to this ticket or are we good to move this to resolved?

**Comment by dinithihj** [comment]
Tested and verified. Closing the ticket.
