### ISSUE TITLE
allow navigating to playground

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#1090]
Presently it is not possible to view anything within a process group unless you have access to that progress group.  So if you own a sub-group or process model, but not the containing group, you can't browse to it.   This is manifested in the SpiffDemo.org site where you can't browse to your own playground even though you have full rights to it - because you don't have rights to browse to the group that contains all playgrounds.

**Comment by danfunk** [comment]
I've hit this problem with every call this week - people can't navigate to the playground and it's causing a lot of confusion.
