### ISSUE TITLE
Process instance should display user's name instead of group when request is assigned directly to the user

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1101]
There is a situation in PP3 where one recruiter will be assigned to the request. The list of recruiters is created by the users assigned to the Talent Group in the permissions table.

When the request is assigned to a recruiter, the process instance message shows "This next task is assigned to group: Talent. There is no action for you to take at this time." However, because the recruiter is directly assigned to the request, the message should display the assigned recruiter's name instead of showing "Talent group."

@sashayar13 thinks that it could be due to the "Talent" group name which is in the DMN table and she wanted to create a ticket for this issue.

![Image](https://github.com/sartography/spiff-arena/assets/123297840/afb3e1b8-99d2-4ea2-b5c2-1e6e1267d476)

**Comment by dinithihj** [comment]
Tested on dev.app. Now, the message shows the recruiter's name correctly instead of the group name. Additionally, when the recruiter logs in, the process instance is shown under the "Waiting for me" section of the home page.

I will retest this when the latest model changes move to test.app

![image](https://github.com/sartography/spiff-arena/assets/123297840/21e0b1e5-eab2-4f8c-ae23-6cca052391ae)
![image](https://github.com/sartography/spiff-arena/assets/123297840/3ff496d1-c9d2-4f38-a8f2-84690b06de56)

**Comment by dinithihj** [comment]
Tested and verified on test.app 

![image](https://github.com/sartography/spiff-arena/assets/123297840/b70b437a-8a79-421d-bfb2-e0bd3b16df50)
![image](https://github.com/sartography/spiff-arena/assets/123297840/2725b90d-8c48-478b-8ffa-18a134bc0de9)

**Comment by madhurrya** [comment]
Released to Prod
