### ISSUE TITLE
"Cannot decode token." when logging in via google OpenId

### ISSUE THREAD

**Issue by syphar** [sartography/spiff-arena#1103]
using the `:latest` docker image I couldn't make the login work, and always saw this error: 

```json
{
  "error_code": "invalid_token",
  "message": "Cannot decode token.",
  "status_code": 401
}
```

after digging through my setup and trying to find the issue with our OpenId settings, I stumbled onto something else: 

- the backend authentication_controller has a method called [`_get_decoded_token`](https://github.com/sartography/spiff-arena/blob/ea9336e625b980287118b9ebec03d71d7a2956a6/spiffworkflow-backend/src/spiffworkflow_backend/routes/authentication_controller.py#L439-L453)
- in there, when any `Exception` happens, it returns the error I'm seeing 
- but: the method calls [`_get_authentication_identifier_from_request()`](https://github.com/sartography/spiff-arena/blob/ea9336e625b980287118b9ebec03d71d7a2956a6/spiffworkflow-backend/src/spiffworkflow_backend/routes/authentication_controller.py#L456-L462), which **always fails, since it's trying to access a `request` object, which doesn't exist here.**

I see the behaviour was introduced in https://github.com/sartography/spiff-arena/pull/897, so I reverted our service to use the image based on 2d9fb44 (the commit before the PR was merged).

**Comment by burnettk** [comment]
we replicated and fixed this issue in the following PR: https://github.com/sartography/spiff-arena/pull/1125. @syphar , if you want to check it out before it's merged, please have a go. otherwise, we'll probably get this into main tomorrow. if you're using our `:latest` docker images, let us know, and we can push a release that updates that.

**Comment by syphar** [comment]
@burnettk thank you for the fix! I'm sure I can find time today to test it before it's in the docker images, but I will definitely try it then, probably next week. 

As a sidenote, the PR title is IMO oddly named as a feature improvement, I don't see how this piece of code could have ever worked.

**Comment by burnettk** [comment]
@syphar sure thing. we will merge it. there will be a docker image tag with the word `main` in it that will have the fix after that. let us know if you want the `:latest` tag bumped.

with the sidenote, you're talking about `feature/something` and you would have called it `bug/something`? we have a script that creates branches with that `feature` prefix and don't generally bother with `feature/bug/chore/hotfix/whatever-else-people-do` differentiation. it just always uses `feature`. those different prefixes are not super helpful, are they? :) i guess i'm arguing that lots of people are wasting their time. :) i guess if i carried the argument through the whole way, we should probably not have a prefix at all, and then you wouldn't have been confused, eh?

like you say, this would have worked before the commit you mentioned, where we added more thorough checking of the jwt.
