### ISSUE TITLE
Register a New Contact - data store 

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#1147]
Please review the Register a New Contact process data store, there are errors when checking the form data vs the data store
![image](https://github.com/sartography/spiff-arena/assets/137384667/73be5ba3-4b0e-40d0-a2c3-6a479c3165e2)

**Comment by burnettk** [comment]
This means vendor_sec_info is a dictionary but it doesn’t have a key for “contact”

**Comment by MarD0607** [comment]
@calexh-sar New error is manifesting when there is a duplicate
![image](https://github.com/sartography/spiff-arena/assets/137384667/3acde0ad-72af-451e-9bf0-835bea2152bb)

**Comment by calexh-sar** [comment]
@MarD0607 please confirm that this issue has been fixed.

**Comment by MarD0607** [comment]
Bug has been fixed, thank you!
