### ISSUE TITLE
Support with extending vendor bank data checks via API

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#1150]
Expand the bank data checks, see https://dev.app.spiff.status.im/editor/process-models/misc:test:kayvon-tests:vendor-iban-test/files/request_new_role.bpmn , sample test process,  by adding:
1. the Tax Data https://apilayer.com/marketplace/tax_data-api#endpoints , GET/validate.
add tax validate after Get IBAN data
2. the Email data https://apilayer.com/marketplace/email_verification-api , add email check after Get Swift data
3. the WhoIs https://apilayer.com/marketplace/whois-api , add domain check after email check
Modify the Show all data to include all check responses.

**Comment by harmeet-status** [comment]
@MarD0607 do you need a dev assigned to this?

**Comment by MarD0607** [comment]
> @MarD0607 do you need a dev assigned to this?

I don't think so, thank you

**Comment by harmeet-status** [comment]
Chatted with @MarD0607, no longer needed. Closing ticket.
