### ISSUE TITLE
Changing message event properties doesn't make the save button enable

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1151]
Currently, the save button doesn't enable when you change the following options in the property window.

Message Start Event

- Message -> Variable Name
- Correlation -> Expression

Message Intermediate Catch event

- Message ->Variable Name
- Correlation -> Expression

Message Intermediate Throw event

- Message -> Payload 
- Correlation -> Expression

https://drive.google.com/file/d/1YgVnaUYkYBDCTEXr8KDPh-7gUBUUtH6S/view?usp=sharing

**Comment by madhurrya** [comment]
This issue is now fixed the new message updates.
