### ISSUE TITLE
NoneType' object has no attribute 'task_spec

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1152]
On dev.app some instances got suspended with the error -NoneType' object has no attribute 'task_spec
Process instances

- https://dev.app.spiff.status.im/i/3475
- https://dev.app.spiff.status.im/i/3476
- https://dev.app.spiff.status.im/i/3483
- https://dev.app.spiff.status.im/i/3540
- https://dev.app.spiff.status.im/i/3515
- https://dev.app.spiff.status.im/i/3538
- https://dev.app.spiff.status.im/i/3549

![Image](https://github.com/sartography/spiff-arena/assets/123297840/913b6051-2743-4a5d-b9a5-6d9bff1344ee)

**Comment by madhurrya** [comment]
Further discussions related to this from Slack.



![Image](https://github.com/sartography/spiff-arena/assets/110527567/eec3bae0-cf05-42bd-a6ae-8b450c326496)



![Image](https://github.com/sartography/spiff-arena/assets/110527567/51fe5bf1-ec4e-4d0e-a070-47f1c6ef4339)

**Comment by dinithihj** [comment]
Got the error - 'NoneType' object has no attribute 'task_spec', when running one of the process models I created for the unit tests. The error occurred only once.

Process Instance : https://dev.app.spiff.status.im/i/8339
Process Model : https://dev.app.spiff.status.im/process-models/misc:qa:bpmn-model-testing:loop-call-activity-with-parallel-gateway

**Comment by madhurrya** [comment]
Closing this for now and will reopen if we notice this again
