### ISSUE TITLE
Data Store Types in Create Event Model Displayed as 'Undefined'

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1153]
In the Create Event process model, the data store types are shown as "Undefined" for both data stores Events and Dynamic Enumerations. If I select it again, the data store type changes to "kkv" as expected. 
(Note - I didn't save any changes to the process model.)

![Image](https://github.com/sartography/spiff-arena/assets/123297840/1a10abe4-1f1c-45ec-9729-b45de8276d2f)

However, when I tested some other sample models which I created, I didn't see anything like this.

Link to Process Model - https://dev.app.spiff.status.im/process-models/comms-and-brand:event-management:event-execution:create-event

**Comment by madhurrya** [comment]
Closing this as it is a minor issue and happens only for this model.
