### ISSUE TITLE
Create event form edit - UI issues

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1175]
Please check this video.
When the user Edit and goes back to the first form the Breadcrumb and title is coming at the bottom of the page.

https://drive.google.com/file/d/1USAMalxQFcTLdc3nsCsZgsn88GLPMVR7/view?usp=sharing

Today I noticed a similar thing with this test model. But that is an old model and it was not created using the new form builder. Not sure whether it's the same issue.
https://dev.app.spiff.status.im/process-models/misc:test:madhu-model-1

maybe related: https://github.com/sartography/spiff-arena/pull/1180/files

**Comment by madhurrya** [comment]
Noticed a similar thing here also. https://test.app.spiff.status.im/process-models/misc:bamboo-reports
![image](https://github.com/sartography/spiff-arena/assets/110527567/3979b03d-c7ec-4936-a72c-305187215edb)

**Comment by jasquat** [comment]
this was fixed in commit https://github.com/sartography/spiff-arena/commit/5114e99f997462e6f99d010881aa120dc2799c80.

**Comment by madhurrya** [comment]
This issue seems to be fixed now.
Tested the create event in dev.app and now I don't get that issue. (can't test in test.app as we don't have those model updates there)
![image](https://github.com/sartography/spiff-arena/assets/110527567/2e48deed-ddf0-4445-9e98-790fb1548467)

Also tested with the Bamboo report in test.app and didn't notice it there also.

**Comment by madhurrya** [comment]
Released to Prod.
