### ISSUE TITLE
json schemas on data inputs and outputs

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#1179]
especially in the context of called activities, but maybe also when creating new process instances over the API.
this could allow us to display forms when starting called activities manually as discussed at #966 in order to gather the required inputs.
each data input can have a schema as its item definition, per the spec.
perhaps we recommend one variable (and one corresponding data input) for each called activity, and we recommend that variable being a dictionary/object. this would allow for ridiculous flexibility, while only needing to define one schema per called activity.
do we need json schemas on data outputs as well?

**Comment by danfunk** [comment]
Busting this up into multiple tickets
