### ISSUE TITLE
Sometimes on PP1/PP2 Old Instances "Reset Process Here" button does not reload the page

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1186]
Sometimes, on certain old PP1/PP2 instances, the "Reset process here" function doesn't work properly. When clicking on the "Reset process here" icon,  the page doesn't refresh or reload as expected, and it remains on the same page. However, if I open the instance in a different browser a few minutes later, the instance shows as it has reset to the earlier point mentioned.

Video link - https://drive.google.com/file/d/1k8ZS5K6O7eBsFNKkKeFC4E0bUnQd7ihO/view?usp=sharing
 

PP1 Instances 

- https://test.mod.spiff.status.im/i/194 - Reset to PENDING APPROVAL - Budget Owner
- https://test.mod.spiff.status.im/i/297 - Reset to PENDING APPROVAL - Budget Owner, refreshed the instance after a few minutes and completed
- https://test.mod.spiff.status.im/i/303 - Reset to PENDING APPROVAL - Security
- https://test.mod.spiff.status.im/i/189 - Reset to PENDING APPROVAL - Budget Owner 
- https://test.mod.spiff.status.im/i/286 - Reset to Submit Details

PP2 Instances 

- https://test.mod.spiff.status.im/i/318 - Reset to PENDING APPROVAL - Budget Owner
- https://test.mod.spiff.status.im/i/234 - Reset to Submit Details

This only happens in old PP1/PP2 instances. New PP1/PP2 instances don't have this problem and they are working as expected.

**Comment by madhurrya** [comment]
This doesn't seem to happen with instances created about 2 days ago, but happens with instances about a week old.
It seems the request is timing out when we click reset process here.
![image](https://github.com/sartography/spiff-arena/assets/110527567/d17d6383-c68f-4072-a4cb-8cc38372b7a5)
