### ISSUE TITLE
Dictionary changed size during iteration

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#1190]
when running certain activities (seen in mass create POs subprocess) in parallel. we may be adding to the subprocesses dictionary while running get_task_from_id.

https://sartography.sentry.io/issues/5055128964/events/3b88e11476884aaab88401a268521995/?project=4503966086529024

current investigate happening with this model: https://dev.app.spiff.status.im/process-models/misc:d:mi-test

**Comment by harmeet-status** [comment]
Had a discussion with @sashayar13, this needs to be done either in Sprint 24 or Sprint 25 as we need this for Go-Live for Implicit 1st April.

**Comment by harmeet-status** [comment]
I'm hoping that this fix: https://github.com/sartography/spiff-arena/issues/1006 will solve the original issue: https://github.com/sartography/spiff-arena/issues/1177

**Comment by harmeet-status** [comment]
@calexh-sar are there any other ticket related to Celery issues? Can we pls link them here.

**Comment by calexh-sar** [comment]
Moved above #1177 since this might be a fix for it and is needed by April 1.

**Comment by burnettk** [comment]
elizabeth says she's looking to make some library changes that may fix or at least alleviate the problem.

**Comment by essweine** [comment]
This PR may fix this issue (and will at least reduce the frequency of it occurring) https://github.com/sartography/SpiffWorkflow/pull/398

**Comment by calexh-sar** [comment]
@MarD0607 reported this error likely occurred on prod today, this was the error:
```
Event Error Details
dictionary changed size during iteration

Stacktrace:Traceback (most recent call last):
  File "/app/src/spiffworkflow_backend/services/process_instance_queue_service.py", line 132, in dequeued
    yield
  File "/app/src/spiffworkflow_backend/services/process_instance_processor.py", line 1481, in do_engine_steps
    return self._do_engine_steps(exit_at, save, execution_strategy_name, execution_strategy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/SpiffWorkflow/bpmn/workflow.py", line 211, in get_task_from_id
    for subprocess in self.subprocesses.values():
RuntimeError: dictionary changed size during iteration
```

**Comment by sashayar13** [comment]
https://dev.app.spiff.status.im/i/5804

**Comment by danfunk** [comment]
It can happen whenever you have multiple tasks operating on the task data  at the same time - so any parallel execution anywhere in the diagram.

**Comment by danfunk** [comment]
![Image](https://github.com/sartography/spiff-arena/assets/515662/721c6eb8-bfd8-44e6-b8f4-4c2800bfaea2)

Screenshot of process - in case this helps

**Comment by danfunk** [comment]
@Jon and @essweine will try to brute-force a recreation of this issue in a dev environment now that new changes to the core library make things happen a little bit faster.

**Comment by madhurrya** [comment]
Completed 900 iterations of this model https://dev.app.spiff.status.im/process-models/misc:d:mi-test and this model https://dev.app.spiff.status.im/process-models/misc:test:madhurya-testing:test-dictionary-changed-size-during-iteration-error
and didn't get any error

https://dev.app.spiff.status.im/i/4292
https://dev.app.spiff.status.im/i/4411

So I think we can close this issue as we didn't notice the 'Dictionary changed size during iteration' error.

**Comment by calexh-sar** [comment]
@madhurrya is there code that needs to be released to support your findings that you "didn't notice the 'Dictionary changed size during iteration' error" on other instances.

@harmeet-status do you agree this issue can be closed once any code as been release, if needed?

**Comment by madhurrya** [comment]
@calexh-sar this code is included in the next release.
