### ISSUE TITLE
Radio buttons not working

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1194]
It seems after this PR https://github.com/sartography/spiff-arena/pull/925 the radio buttons in existing models doesn't work.

It doesn't seem to identify the selection we did and also we can select multiple radio button items.

These are some sample models
https://dev.app.spiff.status.im/editor/process-models/misc:qa:radio-button-test-1/files/test-radio-button1.bpmn
https://dev.app.spiff.status.im/process-models/misc:test:spiff-demo-testing:examples:1-basic-concepts:1-1-content

These comments are from Sasha.
"after the change the options selected with the radio button are not captured, it writes "null" to the task data instead.
was this expected? or what are the changes should be introduced to the radio button schema config so that the radio button functionality works
As a result of the bug I mentioned above about the radio button update, we can't test the approvals in dev.app"
You can try to execute the Create Event process https://dev.app.spiff.status.im/process-models/comms-and-brand:event-management:event-execution:create-event Select an existing event and choose Edit

![Image](https://github.com/sartography/spiff-arena/assets/110527567/35a90e11-275f-4945-9cc6-49b7532d7f99)

![Image](https://github.com/sartography/spiff-arena/assets/110527567/8066ea80-834c-49e4-8e84-8bde22076481)

**Comment by jasquat** [comment]
Fixed in #1195.

**Comment by madhurrya** [comment]
Tested this in test.app and also tested with pp1/pp2 and bamboo reports and these issues are fixed now.

**Comment by madhurrya** [comment]
Released to Prod on March 18th.
