### ISSUE TITLE
Numeric range field - to not auto-populate the max value

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1197]
Make the enhancement to the field (based on users feedback) - do not auto-populate the max value when a min value is entered by a user

**Comment by dinithihj** [comment]
Tested and verified on test.app (Version 200/202) using the process model https://test.app.spiff.status.im/process-models/misc:qa:forms:test-numeric-range-field
Now, when the user types in the min value, the max value is not auto-populated.

![image](https://github.com/sartography/spiff-arena/assets/123297840/5df28395-ca3d-47cf-a50a-71ba943f2e2a)

**Comment by dinithihj** [comment]
PR https://github.com/sartography/spiff-arena/pull/925 was released to Prod on March 18th

**Comment by madhurrya** [comment]
There are other known issues related to the numeric range field and those will be addressed here. https://github.com/sartography/spiff-arena/issues/1197
