### ISSUE TITLE
Address validation

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#1198]
Need a way to validate the bounty hunter has provided a valid address.  Status has suggested "using Google address picker" in their [Spiff Bounties requirements](https://www.notion.so/Spiff-Bounties-22a7e2e23ee843c7bffd261ab15d1c9b).  Needs to work in a Guest form.

as discussed 2024-03-14, avoiding google is fine. a form to enter the address is sufficient. if we used existing typeahead components, we might avoid having to reimplement a country dropdown (the country seems to be the most important piece of information). at the same time, using existing typeahead logic requires an API, so that is more difficult for public pages like this.

**Comment by danfunk** [comment]
* This would not validate that the user was being honest about their address
* Creates a new front end dependency that we would have to take forward across all users of SpiffWorkflow.

As pointed out in the description - a form is sufficient.  So closing the ticket.

**Comment by calexh-sar** [comment]
@harmeet-status am I correct that address validation is no longer required?  We will still request their address and use the city/state/country typeahead to provide their country that we can then use to validate they are not working from a blacklisted country.
