### ISSUE TITLE
Open the form editor - Permission issue

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1199]
In dev.app when the normal user tries to open a form and in test.app any user tries to open a form it gives an error.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/0328a76b-19d0-4ec7-8866-e120d623a54a)

![Image](https://github.com/sartography/spiff-arena/assets/110527567/228cef69-5258-4437-8cb2-704d6b7b1e9c)

**Comment by danfunk** [comment]
This is a high priority issue for our Demo environment - it means no one can look at our forms if they start digging into the examples.

**Comment by burnettk** [comment]
testable on spiffdemo with a non-admin user.

**Comment by madhurrya** [comment]
Tested in spiffdemo.org and https://mysql.spiffcrm.com/ and this issue seems to be fixed now.
