### ISSUE TITLE
Vendor Onboarding - Vendor Review and Approval

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#1211]
From @MarD0607 in Discord: if you have some time, can you please take a look at https://dev.app.spiff.status.im/process-models/manage-procurement:vendor-lifecycle-management:vendor-onboarding:vendor-onboarding
I only need to know if the script tasks which communicate with the datastore are good. Do I need everytime I change the status to update the enum_list? I saw in Start Vendor Onboarding that you do that in every script task when status of the vendor is changed

**Comment by calexh-sar** [comment]
@MarD0607 yes, if the Vendor Status changes the enum list should be updated for that Vendor since the Status is used for filtering the enum list in certain situations.

**Comment by calexh-sar** [comment]
@MarD0607 pls check to confirm that the Data Store updating for "Onboarded" and "Rejected" are not working correctly.

**Comment by harmeet-status** [comment]
@MarD0607 after you chat with @calexh-sar and finalise this, can you pls close it.

**Comment by calexh-sar** [comment]
@MarD0607 is any additional work needed on this issue?

**Comment by calexh-sar** [comment]
@MarD0607 is any additional work needed on this issue?

**Comment by calexh-sar** [comment]
@MarD0607 is any additional work needed on this issue?

**Comment by MarD0607** [comment]
@calexh-sar No additional work, thank you!

**Comment by calexh-sar** [comment]
Closing per comment above
