### ISSUE TITLE
Task name not saved when saving without clicking elsewhere

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1212]
This has happened to @harmeet-status  while testing something else.

Steps to recreate

- Open a process model diagram
- Drag and drop a task onto the diagram.
- Double-click on the task and type a name.
- Without clicking elsewhere, move the cursor to the Save button and click it while the cursor is still on the task name.
- Go back to the process model and open the diagram
- Notice that the task name was not saved.

Video Link:- https://drive.google.com/file/d/1lrf7zvb7a5ZahF2zD_6cv5HigtgD-Ij1/view?usp=sharing

**Comment by madhurrya** [comment]
Since this is not a practical scenario closing this for now.
