### ISSUE TITLE
Add Criticality to Event Data Store

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#1215]
In Discord, @sashayar13 asked:  if I need to add a new field to the Event DataStore, how can I do it, the new field is "criticality"?

Clarifying discussion included:
- are you asking how you can update existing events, add that field to new event or both?
-- both - to add this field to the datastore structure - update the values, and to have this field availablt for the creation form
- Ok, and am I correct in assuming it just needs to get added to the event data and not also to the event enumeration?  The reason to maybe add it to the event enumeration would be to allow quick filter of enumeration list by criticality. 
-- you are correct - no need to add this to the enum

**Comment by calexh-sar** [comment]
@sashayar13 I had to think through this a bit and here are the general steps you would need to take to add a new field to Events:
- for yet to be added Events, the field would need to be added to the 'Submit Event Details' User Task form, the 'Review' Manual Task Instructions and the 'Format Event for Data Store' section of the 'Add Event to Data Store' Script Task.
- to update the exiting events with the new field and a value for it, I added the 'Get New Field Info` User Task and 'Add New Field Info to Data Store' MI Script Task to the process model.  These have not be fully flushed out and are not connected at this time, but I think they should be close to complete.  In addition to connecting them to the process with sequence flows, you will want to add as an option in the 'Select Event Action' User Task. 
- to be able to edit edit existing Events, you will need to add the new field info in the 'Load Field' Script Task.

I hope this helps if you need to do this while I am away.

**Comment by calexh-sar** [comment]
@sashayar13 the current option for adding field values one event at a time is not to bad for the low number of Events currently on dev, but would likely be unacceptable later when you have many on prod.  I added issue #1220 that would allow assigning multiple Events to a single field value if you want to prioritize it for the future.

**Comment by calexh-sar** [comment]
@sashayar13 is there any additional work needed for this issue?

**Comment by sashayar13** [comment]
thanks @calexh-sar I completed the items:
- for yet to be added Events, the field would need to be added to the 'Submit Event Details' User Task form, the 'Review' Manual Task Instructions and the 'Format Event for Data Store' section of the 'Add Event to Data Store' Script Task.
- to be able to edit existing Events, you will need to add the new field info in the 'Load Field' Script Task.

I also modified the existing travel process so that it includes the event criticality

No additional work is needed at the moment

**Comment by calexh-sar** [comment]
Closing per comment above.
