### ISSUE TITLE
Create shortlink for url

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1224]
Create a feature which would allow the creation of a short link for a Spiff URL provided. For example, `create_shortlink_for_url("https://dev.app.spiff.status.im/api/v1.0/process-data-file-download/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence/626/0e6187c3d3e7c3203ff4c6dcdaffe5525ace78bcf034a703e2dea005529af65a", "hot_bpmn_1.png")`
This link should be valid and clickable through Metadata view (if the variable is added as Metadata)

"blah link" added as link text in https://github.com/sartography/spiff-arena/pull/1233.

**Comment by danfunk** [comment]
Rather than createing a short link, going with:
* If a metadata value matches a url regex pattern, don't show the url show "[metadata label] link" and make that clickable.

**Comment by madhurrya** [comment]
@sashayar13 Can I close this as the link works here. 
Or is there any other place you want me to test this?

![image](https://github.com/sartography/spiff-arena/assets/110527567/48908f89-776b-42c5-9ace-81ec119cb224)

**Comment by sashayar13** [comment]
@madhurrya you can close the ticket, thanks
