### ISSUE TITLE
Required array - attachment

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1225]
@madhurrya noticed this behaviour "If I accidentally delete the supporting file option here, then when I try to submit the request it says ‘Some fields are invalid. Please correct them before submitting the form’ but user has no idea what is missing as nothing get highlighted. 
Or even if I don’t select a file while the Support file option is there it doesn’t get highlighted"

![Image](https://github.com/sartography/spiff-arena/assets/104367255/b71c96bb-c571-48a0-b9fe-03cd08c0a94a)

![Image](https://github.com/sartography/spiff-arena/assets/104367255/defe6473-34f6-4cb7-bd3e-a87c16138616)

**Comment by madhurrya** [comment]
If I just remove the file, then it shows the error message as expected.
But if I remove the full item, then it doesn't show the relevant error message

![image](https://github.com/sartography/spiff-arena/assets/110527567/49e0acdd-6891-4b80-970f-bca082ebaea0)

example model -  https://dev.app.spiff.status.im/process-models/misc:qa:forms:single-file-upload-in-items-test

**Comment by jasquat** [comment]
@madhurrya did it used to highlight something in that case or show the error message closer to the items list? I'm not sure how it would have since we'd have to add a message to the items label which we never did before.

**Comment by madhurrya** [comment]
@jasquat this didn't work earlier also.  This is part of the original issue.

**Comment by madhurrya** [comment]
Above issue is also fixed now.
![image](https://github.com/sartography/spiff-arena/assets/110527567/df9ef206-1418-4e49-bf77-58be3222ed4a)

**Comment by madhurrya** [comment]
Tested with 
https://test.app.spiff.status.im/process-models/misc:qa:forms:single-file-upload-in-items-test
and
https://test.app.spiff.status.im/process-models/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence

**Comment by kdeme** [comment]
I came across following similar issue:
- Click add new and attach  a file under an item
- Click again on add new, but for this second one, don't attach an item
- If you now try to proceed you will get the "some fields are invalid" error but it will not highlight anything to show what is invalid.

**Comment by sashayar13** [comment]
@madhurrya Can you please confirm that the fix we plan to push to production this week will address the issue described above?

**Comment by madhurrya** [comment]
@sashayar13 It is working as expected.
![image](https://github.com/sartography/spiff-arena/assets/110527567/e347631e-5a39-4863-9da4-f059b04c8a24)

![image](https://github.com/sartography/spiff-arena/assets/110527567/cf0ffea3-dff3-443b-9c77-412a75d3fc00)

**Comment by sashayar13** [comment]
thanks for checking!

**Comment by madhurrya** [comment]
Released to Prod on June 18th. Version 19/20.
