### ISSUE TITLE
Coin gecko report status

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1226]
While the coin gecko report is running like this,

![Image](https://github.com/sartography/spiff-arena/assets/110527567/54928239-3d0d-45c1-8d01-2674c189cdf7)

if I go to another tab and come back then that status displaying stops and it goes to the process instance show page and it shows data like this

![Image](https://github.com/sartography/spiff-arena/assets/110527567/6fbbf934-7e01-4464-9e14-a859cba74f8a)

(I think this is another background processor related issue)

**Comment by burnettk** [comment]
The screenshots do not show but I assume this is not on dev.mod. Yeah, this will be more likely to work as expected with celery.

**Comment by madhurrya** [comment]
Yes above screenshots are not in dev.mod.

When I try to run the coin gecko in dev.mod, it takes a long time to start the process (I think due to this issue https://github.com/sartography/spiff-arena/issues/1235) 

And even after it started it is in the first item like this for a long time. Now it has been about 5 minutes. 
![image](https://github.com/sartography/spiff-arena/assets/110527567/203efb8a-421f-40dd-8651-706f306b93bf)
