### ISSUE TITLE
Waiting state tasks

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1227]
While an instance is in 'waiting' state (before user input required state) the user assigned to the next task can complete that task. (We can notice this when we reassign a user as it is in the waiting state for some time before the state changes to user input required.)
Is that the correct behaviour or should it be available to that user only when the state is changed to user input required?

**Comment by burnettk** [comment]
The process instance status is just high level guidance. It is fine for a user to complete a task that is assigned to them regardless of pi status.

**Comment by madhurrya** [comment]
Ok. Then will close this issue.
