### ISSUE TITLE
Process start taking a long time in dev.mod

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1235]
In dev.mod when I try to start a process, even a very simple one it keeps on loading like this for several minutes. 

e.g. https://dev.mod.spiff.status.im/process-models/misc:qa:forms:simple-form-name-age

![Image](https://github.com/sartography/spiff-arena/assets/110527567/3decda5b-aac5-4586-95b7-c75a88149c01)

**Comment by burnettk** [comment]
and never completes automatically, right? like timetracking?

**Comment by madhurrya** [comment]
This is about starting a process. They get started after some time.
And yes closing is similar to time tracking, it keeps spinning.

**Comment by jasquat** [comment]
It seems that the redis queue for celery had about 2 million entries in it for some reason. We cleared it out and restarted the containers and now everything is running normally. We do not know how this happened but we will document this in spiff-arena and will watch the queue.

dev.mod should be fine to use now.

**Comment by madhurrya** [comment]
I think it's better to keep the DB as it is and test these issues when they are fixed. Because if we purge the db everything will work perfect with fewer number of instances.

**Comment by madhurrya** [comment]
This issue seems to be fixed now.

**Comment by madhurrya** [comment]
Closing this issue as it seems to be working fine now.
