### ISSUE TITLE
Messages table - view and filter

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1245]
To allow filtering of the Messages table + fix the bug - the table view actions are not working.

![Image](https://github.com/sartography/spiff-arena/assets/104367255/872d4611-defd-4efb-9072-fe82d524cfd8)

![Image](https://github.com/sartography/spiff-arena/assets/104367255/e8729b41-e576-42db-9947-24080655d39b)

**Comment by danfunk** [comment]
This is a great ticket - was thinking about it yesterday - in what ways would you think it would be good to filter?  I was thinking status - it would be nice to see the non-completed messages.  Or to view all messages by name.

**Comment by sashayar13** [comment]
@danfunk I was thinking about the following filtering criteria:
- Process
- Process Instance
- Message Name
- Type
- Correlation key? (would be good to have an option to find messages with the same correlation key)
- Status
- Created At

**Comment by harmeet-status** [comment]
@burnettk what if we introduced a new feature where you could return 10,000 rows and then we just use Ctrl-F to find things. 

Stop gap measure till the UI reskin. Thoughts?

**Comment by burnettk** [comment]
we could consider having a very large page size in the interim depending on the urgency, sure.

**Comment by harmeet-status** [comment]
Yeah lets do it @calexh-sar

**Comment by danfunk** [comment]
Re-estimated the ticket based on no backend or ui features - just the ability to select a large number for the total records to display in the pagination control.  Add options to include several reasonable limits.   500, 1000, ...

**Comment by madhurrya** [comment]
Now we have these options in pagination. 
![image](https://github.com/sartography/spiff-arena/assets/110527567/685728b8-9dbc-4f46-93c9-b379018b2f2b)

@sashayar13 is there anything else you need to get done under this ticket or shall I close this?

**Comment by sashayar13** [comment]
created a separate ticket for filters. This issue can be closed
