### ISSUE TITLE
Breadcrumb Font

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1254]
Not sure whether the font of the breadcrumb matches with the font type/size of the rest of the site. 

![Image](https://github.com/sartography/spiff-arena/assets/110527567/9cb05df4-3b5c-4ef6-b091-ba0d3a1121e2)

**Comment by burnettk** [comment]
inclined to potentially ignore this issue to save time, given the UI/UX redesign coming.

**Comment by madhurrya** [comment]
Since this is a UI issue closing this as it'll be fixed in the new UI.
