### ISSUE TITLE
Start Vendor Onboarding

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#1265]
1. There is an error when the user chooses to Edit the email message as part of the Show Email Content activity
https://dev.app.spiff.status.im/tasks/2034/1ca210af-c1d5-4206-8954-4d8ca7e947e2
2. Need to link the Cancel button of the Show Email Content to the delete scripts so that Cancel which actually cancels the entire process should then trigger the deletion of the vendor data if the user has added a new vendor instead of choosing one from the existing list.
Otherwise the vendor is saved even if the process was canceled by the user.
Example: https://dev.app.spiff.status.im/process-instances/for-me/manage-procurement:vendor-lifecycle-management:vendor-onboarding:start-vendor-onboarding/2035
![image](https://github.com/sartography/spiff-arena/assets/137384667/772fffd2-2d29-413d-9f8d-27af72a5ecbe)

**Comment by calexh-sar** [comment]
@MarD0607 this ticket should be prioritized by placing it in the priority order Status wants it worked on, not by assigning a sprint.  We will assign the sprint based on resource availability and priority order.

**Comment by calexh-sar** [comment]
@MarD0607:

- The PI link in #1 is no longer valid and I could not reproduce the error, tried for both adding new and using existing.
- I moved the adding of the new vendor after the approval of the email.  This should prevent having a new vendor added while the user is determining if the email should be sent or not and potential issues of removing the vendor from the Data Store.

**Comment by MarD0607** [comment]
Thank you
