### ISSUE TITLE
Allow setting up a min value for string value with patterns

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1268]
The "unit price" field is configured in JSON as a string value

```
"unit_price": {
"type": "string",
"title": "Unit Price",
"pattern": "^(\\d{1,3}(,?\\d{3})*)(\\.\\d{0,4})?$",
"validationErrorMessage": "Must have no commas or commas every 3 places, period for separator, 0 to 4 numbers after separator"}
```

This resulted in a user submitting the "0" value without error. The system should restrict the submission to only accepting positive numbers.

**Comment by calexh-sar** [comment]
Discussed during ticket grooming and @sashayar13 to determine next steps with this issue.

**Comment by sashayar13** [comment]
need to test the difference in behaviour:
`{
  "type": "object",
  "properties": {
    "unit_price": {
      "type": "number",
      "title": "Unit Price",
      "minimum": 0.0001,
      "exclusiveMinimum": true,
      "validationErrorMessage": {
        "minimum": "The value must be greater than 0",
        "exclusiveMinimum": "The value must not be 0"
      }
    }
  }
`

and 

`{
  "type": "object",
  "properties": {
    "unit_price": {
      "type": "string",
      "title": "Unit Price",
      "pattern": "^(0|([1-9][0-9]{0,2}(,\\d{3})*))(\\.\\d{1,4})?$",
      "validationErrorMessage": "Must be a positive number, optionally containing commas every three digits before the decimal point, and up to four decimal places."
    }
  }
`

**Comment by burnettk** [comment]
it wouldn't be the greatest long-term fix, since it seems better for the value in task data to be a number, but you could immediately change it from a number to a string in a script task or post-script to avoid affecting the rest of the model in short term (`unit_price = str(unit_price)` or similar).

**Comment by sashayar13** [comment]
tried the option with a numeric field, but getting the error 
<img width="780" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/6a9765a5-249c-4d0b-b061-a1d88bf49d23">
<img width="780" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/87be89bc-6de0-4093-9c82-df614644a324">
<img width="780" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/9fe97a4e-ee60-40ed-8476-d8d6715d4959">

**Comment by sashayar13** [comment]
the option with string type and new pattern returns the error 
<img width="780" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/fd2d21c1-8ca1-4db0-925e-c34eaf311066">
<img width="780" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/74a0ff67-291a-439b-a903-a5e817ece7d4">

**Comment by sashayar13** [comment]
the only pattern which runs without errors is 
`"unit_price": {
											"type": "string",
											"title": "Unit Price",
											"pattern": "^(\\d{1,3}(,?\\d{3})*)(\\.\\d\\d)?$",
											"validationErrorMessage": "Must have no commas or commas every 3 places, period for separator, 0 or 2 numbers after separator"
											}`

The process where I did the test is https://dev.app.spiff.status.im/process-models/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence (coworking)

**Comment by sashayar13** [comment]
@burnettk can you pls assist with this ticket? It looks like the pattern you suggested and the solution ChatGPT suggested - doesn't work. Spiff throws the validation errors

**Comment by calexh-sar** [comment]
@sashayar13 would you like me to reprioritize this issue so it gets worked on in the current sprint?

**Comment by sashayar13** [comment]
no @calexh-sar , it's fine to keep it for the next sprint

**Comment by sashayar13** [comment]
@madhurrya @dinithi-sar this ticket is ready for QA. I changed the "Unit price" field from a string with a pattern to a number, preventing users from entering "0" or negative values and resolving issues with decimal places raised by CCs.

**Comment by dinithihj** [comment]
Tested and verified on test.app
