### ISSUE TITLE
addError infinite refresh

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#1270]
we doubled the performance of the frontend with fixes to avoid full page reloads and cache permissions. unfortunately, there are a few cases where the frontend calls addError in a way that causes renders to happen in a way that never terminates. the first fix, on https://github.com/sartography/spiff-arena/pull/1269, involved watching a more specific variable in a useEffect. if we do not address these issues, we know from experience that we can take the site down due to a DOS from the frontend.

**Comment by madhurrya** [comment]
Not sure whether this Issue https://github.com/sartography/spiff-arena/issues/1289 is related to this.

**Comment by jasquat** [comment]
@madhurrya they may be related in that they may need similar fixes but I don't think it's related more than that.

**Comment by madhurrya** [comment]
Didn't notice any other issues around this so far.
