### ISSUE TITLE
Waiting time after admin actions is increased

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1273]
There is a noticeable waiting time for processing a process instance after resuming admin actions. For this example, it took 22 minutes for the process instance to change its status.
https://dev.app.spiff.status.im/i/2470
![Image](https://github.com/sartography/spiff-arena/assets/104367255/37428077-f638-41fa-93a3-771769438d4e)

Perhaps related to the https://github.com/sartography/spiff-arena/issues/1270 ?

**Comment by calexh-sar** [comment]
Check once Celery dev work is complete.

**Comment by madhurrya** [comment]
Tested with some simple models and it resumes quickly in dev.mod at the moment. But need to retest later after creating more instances when this Issue is fixed https://github.com/sartography/spiff-arena/issues/1359

**Comment by madhurrya** [comment]
Tested again in dev.mod (celery) and the resume is working fast there.
