### ISSUE TITLE
Update Request Goods and Services: create new Data Store for all Software & Licenses

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#1281]
Security wants to manage the software application catalog within spiff itself. Since we already do all software requests though Spiff (Request Goods and Services), it would be great to update this process to write to a Data Store.

See sample app catalogue attached. This catalogue has a lot of columns that we want to capture, which means that we would probably want Security to jump in and complete the fields as these can't be all populated by Request Goods and Services.

[sample application catalogue.xlsx](https://github.com/sartography/spiff-arena/files/14768213/sample.application.catalogue.xlsx)

**Comment by harmeet-status** [comment]
Related ticket needed for this functionality to be useful: https://github.com/sartography/spiff-arena/issues/1026

**Comment by burnettk** [comment]
@jbirddog i wonder if we want to handle this as a KKV json and put most of the data in json or if we want to build out a custom data store framework where custom tables with custom column definitions can be defined.

**Comment by harmeet-status** [comment]
I would prefer a table so that security finds it easier to update the data store, rather than having to deal with JSON.

**Comment by jbirddog** [comment]
I am also a big fan of the custom data store framework idea, think it would be very powerful to have and grant flexibility to lots of use cases beyond just this. Would definitely be in support of adding it. 

I do want to mention that from looking at the spreadsheet it does not seem like using the KKV would require lots of json blobs to manipulate. You could structure it such that the top level key was the short code and the secondary keys were the rest of the columns. Then each value is a single string/bool/int what have you. If we put some more work into the GUI CRUD support for data stores editing a single value for an application in the catalog would not be terrible.

With that being said, what KKV isn't great at are things like a single query to "return me all applications that are Active and cost > $10,000". It is instead geared toward "return me the cost of Juro". The custom data store framework that @burnettk is describing could make queries like this easier if they are required.

**Comment by harmeet-status** [comment]
We may also want to look at this ticket from the past: https://github.com/sartography/spiff-arena/issues/563
