### ISSUE TITLE
Some instances stuck at 'waiting' state

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1306]
In test.mod noticed a set of instances are at 'waiting' state. Noticed a similar thing in dev.app about a month ago as mentioned here. https://github.com/sartography/spiff-arena/issues/1152#issuecomment-1975810898

![Image](https://github.com/sartography/spiff-arena/assets/110527567/5e8042e5-e33f-4f92-a16d-5343fbc9f01a)

![Image](https://github.com/sartography/spiff-arena/assets/110527567/998d1b82-6f02-4dbb-ad86-96c649184ef1)

**Comment by jasquat** [comment]
I'm not sure how they get in this state, but for instance 205 it doesn't have any ready tasks:
```mysql
MySQL [spiff-workflow-backend]> select count(*) from task where process_instance_id = 205 and state = "READY";
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.012 sec)
```

but it does have future tasks:
```mysql
MySQL [spiff-workflow-backend]> select count(*) from task where process_instance_id = 205 and state = "FUTURE";
+----------+
| count(*) |
+----------+
|      130 |
+----------+
1 row in set (0.029 sec)
```

**Comment by madhurrya** [comment]
Noticed another set like that in test.mod
![image](https://github.com/sartography/spiff-arena/assets/110527567/333190e1-0d4c-4290-9531-1842d635ac17)

**Comment by madhurrya** [comment]
I'll close this for now and will reopen if I notice this again
