### ISSUE TITLE
Milestones Duplicated

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1307]
It seems after the latest deployment, the milestones of all the existing open instances has duplicated.

e.g.

https://test.mod.spiff.status.im/i/37
https://test.mod.spiff.status.im/i/48
https://test.mod.spiff.status.im/i/1277

![Image](https://github.com/sartography/spiff-arena/assets/110527567/3d787d86-f70f-4938-9e25-a81a52f2228f)

![Image](https://github.com/sartography/spiff-arena/assets/110527567/6866cfdc-1008-4dc3-b20c-047e20d21e3b)

![Image](https://github.com/sartography/spiff-arena/assets/110527567/c6260a51-69b1-4d07-8d34-faf1784e5f92)

**Comment by jasquat** [comment]
Oh so we are calling https://github.com/sartography/spiff-arena/blob/celery-docs-and-debug/spiffworkflow-backend/src/spiffworkflow_backend/services/task_service.py#L186 which adds events. We could pass in an arg to omit the event in this case since we really could not need them from the migration script.

**Comment by jasquat** [comment]
We created a hotfix for test.mod and test.app and pushed it out - hotfix/duplicate-events-on-migration-e724cc5856

spiffdemo will also get the tip of main which also has this fix.

One instance on test.mod is in a migratable state - 1078. The form on that instance can be completed and then events table can be checked to ensure no duplicate entries.

As for the other instances that have duplicate events, they can be tested as normal while ignoring the duplicate events on them. The nature of the code change is not something where we need to do a full re-test of the migration if the events table was the only issue. We have unit tests and such in place that can verify the migration worked as expected as long as no other issues have been found.

**Comment by madhurrya** [comment]
This seems to be fixed (tested in Spiffdemo site and didn't notice any duplication with the migration)

**Comment by madhurrya** [comment]
Fixed in the Prod release on April 2nd
