### ISSUE TITLE
Empty value validation - vendor field

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1345]
I need some help with fixing the data entry validation issue.

1. There is a Vendor field in the Request Goods/Services user form, where it can be populated with the "Optional - No Entry" value
2. When a new expense report is being created, this value is replaced by "" value, and when the form is submitted, the system accepts it as a "proper value", which results in the "empty" value for the Vendor field

https://dev.app.spiff.status.im/process-models/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence-procurement

![Image](https://github.com/sartography/spiff-arena/assets/104367255/ad8e6f7b-ccbf-4ba0-a4c3-8163017e5789)

**Comment by calexh-sar** [comment]
@sashayar13 i am not totally clear on what is the issue that needs addressing here.  Is it the blank display in the 'Merchant' column or is there a validation error that occurs somewhere in a User Task form?  Regardless, is updating this part of the `Set Process Start Variables` Script Task...
```
if vendor == "Optional - No Entry":
   vendor = ""
```
with something like...
```
if vendor == "Optional - No Entry":
   vendor = "Not specified"
```
work?

**Comment by sashayar13** [comment]
@calexh-sar I fixed this with the change `if vendor == "Optional - No Entry":
            vendor = None`

**Comment by madhurrya** [comment]
This is fixed now.

**Comment by madhurrya** [comment]
Released to Prod on May 9th.
