### ISSUE TITLE
Ability to prevent viewing secrets

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#1348]
As discussed on #633, some folks simply do not want secrets viewable at all. We can accomplish this for a specific secret via the `DENY:read` permission on `/secrets/[secret-identifier]`, but frontend still allows you to click on the secret and then presents an error modal. Improve this behavior, and potentially allow you to restrict access to all secrets via one permission rule (denying `/secrets/*` right now would also prevent listing them, which may or may not be what you want).

**Comment by burnettk** [comment]
i jammed this up towards the top of the backlog, @harmeet-status . please adjust as necessary.

**Comment by harmeet-status** [comment]
Can we design it in a way that we can DENY read but allow UPDATE?

UI should allow this.

**Comment by burnettk** [comment]
yeah, that makes sense, thanks.

**Comment by dinithihj** [comment]
Tested on dev.app (372/373)

When I set permissions as below 
![image](https://github.com/sartography/spiff-arena/assets/123297840/f7a7e334-95b2-44c5-96e3-b6909121fb06)

and open the Configuration tab, the entire Secret tab is not displaying now

![image](https://github.com/sartography/spiff-arena/assets/123297840/9446dfba-08a7-4421-9b3c-0a05e96461e6)


Is this correct? From the comments, I thought that users shouldn't view existing secrets but should be able to add new ones. By hiding the Secret tab, we're also hiding the "Add a secret" button.

Please correct me if I'm wrong.  @harmeet-status @burnettk @jasquat

**Comment by burnettk** [comment]
That was an interesting use case, where all secrets functionality should be hidden. I’m glad that works. To hide just the secret values, please use deny on /secrets/show-value/* instead.

**Comment by dinithihj** [comment]
Thanks KB! It is working as expected when using /secrets/show-value/*

Tested on dev.app (372/373)

When setting permissions as below 
![image](https://github.com/sartography/spiff-arena/assets/123297840/9b4c0557-1451-407e-9545-b05fd65c99db)

The secret tab displayed with data 
![image](https://github.com/sartography/spiff-arena/assets/123297840/49fdb410-6ff0-4c42-b9f9-d3855c4b9e95)

When clicking on a secret the page displayed as below - (Now "Retrieved secret value" has changed to "Edit secret value" )
![image](https://github.com/sartography/spiff-arena/assets/123297840/4271236c-5f35-408e-bb03-34b22c10d028)

When clicking on "Edit secret value" a blank textbox is displayed.
![image](https://github.com/sartography/spiff-arena/assets/123297840/7f564479-39af-46c5-9b66-996b9d6fb09d)

I was able to enter a value there and save it 
![image](https://github.com/sartography/spiff-arena/assets/123297840/6e280c27-a79a-4e46-92a1-84ced97a67ce)

Also, I can add new Secret via "Add a secret" button

**Comment by harmeet-status** [comment]
Instead of blank, can we make the value field show ***** and make it non-editable (e.g. greyed out or something)

**Comment by burnettk** [comment]
That is the same field used for updating, so I think it has to be editable? And if we put asterisks there, it would run the risk of the user overwriting the existing value with asterisks.

**Comment by harmeet-status** [comment]
Ok agreed with leaving it as editable.

What about placeholder text on the button? Is that not possible?

**Comment by dinithihj** [comment]
Tested and verified on test.app (version 207/209)

**Comment by dinithihj** [comment]
@harmeet-status do you still want the placeholder to be added here or are we good to move this ticket to ready to release?

**Comment by harmeet-status** [comment]
No that's fine, let's move to ready to release.

**Comment by madhurrya** [comment]
@harmeet-status Prod permissions will have to be updated accordingly after the code release.

**Comment by madhurrya** [comment]
Released to Prod
