### ISSUE TITLE
Coin Gecko report issue due to omitting data for completed tasks

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1351]
In dev.mod this table is coming empty. https://dev.mod.spiff.status.im/i/36046

![Image](https://github.com/sartography/spiff-arena/assets/110527567/9d50717a-f91f-4119-9993-0f926d41a104)

It should be like this https://dev.app.spiff.status.im/i/3509

![Image](https://github.com/sartography/spiff-arena/assets/110527567/508d407f-3cdc-416d-98aa-1cc16e1bd3e8)

**Comment by burnettk** [comment]
it's because there is a change on dev.mod that hasn't yet made it onto dev.app. it's unrelated to celery and dev.mod, so i renamed the issue.

**Comment by madhurrya** [comment]
This issue is fixed.
