### ISSUE TITLE
User Task JSON Schema is not properly display in property window

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1386]
On the dev.app, when I create a JSON Schema for User task, it doesn't display correctly in the property window. I have to reopen the BPMN file to see it.  

Video Link - https://drive.google.com/file/d/1g7p_elrOpl9mWN-_i4IyioR1NkZMpRTq/view?usp=drive_link

**Comment by madhurrya** [comment]
Tested in https://mysql.spiffcrm.com/ and now the Json schema file get added automatically. 

![Image](https://github.com/user-attachments/assets/ac1082db-a58a-4a4e-835b-9cb27853ab1a)
