### ISSUE TITLE
Maintain Iplicit improvements

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#1392]

**Comment by madhurrya** [comment]
1. Get -> ContactAccount -> Search contact accounts, seems to return all the contacts. Not sure why we need to enter the Contact account reference there.
e.g https://test.app.spiff.status.im/i/6010

2.  When I select different items from this list, only difference I see in the response is the "include": line. Is that the expected output?
![image](https://github.com/sartography/spiff-arena/assets/110527567/e4493276-60e9-40a4-8cb8-32c89bcdc29e)

![image](https://github.com/sartography/spiff-arena/assets/110527567/8f7cda42-ad76-4c77-9725-9b2eaf7d5922)

3.  Got this error in Get - ContactAccount - Get the customer details of the contact account - contactAccountReference

![image](https://github.com/sartography/spiff-arena/assets/110527567/25b868c9-9f4f-4a27-b57c-fdd3cb57c11f)

**Comment by madhurrya** [comment]
3. When running got this error
https://dev.app.spiff.status.im/i/6496

![image](https://github.com/sartography/spiff-arena/assets/110527567/2a93ebfd-6d7b-44f1-846e-ae932b5a6334)


And I am not sure exactly what to enter for this field
![image](https://github.com/sartography/spiff-arena/assets/110527567/b2e05b33-ab69-4379-9ed3-b16b43c2fc6a)

**Comment by madhurrya** [comment]
4. Error in PurchaseOrder - Get 
https://dev.app.spiff.status.im/i/6531

![image](https://github.com/sartography/spiff-arena/assets/110527567/553ccc55-e48f-42a5-bb42-4daf8fc97d5c)

**Comment by madhurrya** [comment]
5. When I try to  add (PUT) a catalog, after entering the Catalog, in the screen I get it says like this. Is that information correct?
![image](https://github.com/sartography/spiff-arena/assets/110527567/ee19ef42-0a46-4ef4-a182-622b3c5dbcc4)

https://dev.app.spiff.status.im/i/6535

**Comment by madhurrya** [comment]
6. When I try ContactAccount - PUT it gives this error

![image](https://github.com/sartography/spiff-arena/assets/110527567/c2342935-e3f5-40b7-9294-02027df12bb8)

**Comment by madhurrya** [comment]
7. ContactAccount - POST - Add related contacts gives this error
![image](https://github.com/sartography/spiff-arena/assets/110527567/02a41815-81c8-45ad-9ce3-a4e8f1372817)

**Comment by madhurrya** [comment]
@calexh-sar are the above mentioned issues already fixed?

**Comment by calexh-sar** [comment]
@madhurrya pls retest #1 & #2

**Comment by madhurrya** [comment]
Issues 1 to 6 are fixed.

**Comment by madhurrya** [comment]
@calexh-sar The issue number 7 is still there. https://dev.app.spiff.status.im/i/2423

**Comment by madhurrya** [comment]
8. Catalog - PUT - Add an item to a catalog gives an error

https://dev.app.spiff.status.im/i/2663

![Image](https://github.com/sartography/spiff-arena/assets/110527567/62d40b66-a979-448a-ae0a-e9b21585ce90)

**Comment by madhurrya** [comment]
10. Mentioned this in the chat also, as I am not sure where the issue is.
When I list all catalogs I see this 'ContactGroupsByCoaPurpose' which Marius shared. But when I Get by that catalog, it gives this error. But similarly when I Get by 'DepartmentsCdac' it works. Any idea about that error?
https://dev.app.spiff.status.im/i/2695

![Image](https://github.com/sartography/spiff-arena/assets/110527567/1dd6426a-9b31-4bf4-87e5-09f5c87de833)

**Comment by madhurrya** [comment]
11. Contact Account - POST - Add related contacts - gives this error


![Image](https://github.com/sartography/spiff-arena/assets/110527567/30f75301-c253-4c47-a785-15f4888c37da)

**Comment by madhurrya** [comment]
12. These GET Catalog methods also didn't work. (this might be related to the Issue no. 10)

1. Get Catalog - BankAccountPaymentMethods-Gives 400 Bad Request."message": "An insufficient number of arguments were supplied for the procedure or function generated.CatalogGet_BankAccountPaymentMethods."

2. Get Catalog - TaxBandsForTaxAuthority-Gives 400 Bad Request."message": "An insufficient number of arguments were supplied for the procedure or function generated.CatalogGet_TaxBandsForTaxAuthority."

3.  Get a Catalog - TaxCodeForTaxBand-Gives 400 Bad Request."message": "An insufficient number of arguments were supplied for the procedure or function generated.CatalogGet_TaxCodeForTaxBand."

**Comment by madhurrya** [comment]
13. It seems the API calls for the Contact are missing in Maintenance. Was it done purposely? (Only the ContactAccount and ContactGroup ones available and not the Contact related ones)

https://api.iplicit.com/api-docs/index.html#/

![Image](https://github.com/sartography/spiff-arena/assets/110527567/285e242a-3025-45ff-8db6-d1947ebba5b9)

**Comment by madhurrya** [comment]
14. Contact Account - POST - Add an existing contact to a contact account -  gives this error



![Image](https://github.com/sartography/spiff-arena/assets/110527567/cccfcd38-33f2-4fe5-a39a-efebeb749923)

**Comment by madhurrya** [comment]
15. Contact Account - POST - Create a contact account form has about 100 fields. It is better if we can know what are the mandatory fields there.
Having a hard time trying to create a contact account.

**Comment by madhurrya** [comment]
16. Get Purchase Order - Get a purchase order by id or docNo POR000008
https://dev.app.spiff.status.im/i/2929

![Image](https://github.com/sartography/spiff-arena/assets/110527567/b0e0091c-83c2-4a6e-a8bb-8f4c83b96d49)

**Comment by madhurrya** [comment]
17. Get Purchase Order - Search all purchase orders
DocNo matches exactly: POR000008
https://dev.app.spiff.status.im/i/2930

![Image](https://github.com/sartography/spiff-arena/assets/110527567/c92b7f4e-4572-42bc-8c4e-d20a9576a943)

**Comment by madhurrya** [comment]
18. Department - POST - Create a department
https://dev.app.spiff.status.im/i/2962


![Image](https://github.com/sartography/spiff-arena/assets/110527567/8070dca2-1577-43ea-9fc4-864c97d7fadd)

**Comment by madhurrya** [comment]
19. Document - POST 
https://dev.app.spiff.status.im/i/2939

![Image](https://github.com/sartography/spiff-arena/assets/110527567/8aa5cb41-a97c-43d9-aeb8-4d7867bae0b0)

**Comment by madhurrya** [comment]
20.  Department - GET - Search department
Description contains: Nim
https://dev.app.spiff.status.im/i/2955

![Image](https://github.com/sartography/spiff-arena/assets/110527567/a3d38965-e21b-41aa-a0c7-9ee6e4286f8e)

**Comment by calexh-sar** [comment]
@madhurrya pls retest #7.

**Comment by madhurrya** [comment]
Issue No 7 is fixed.

**Comment by calexh-sar** [comment]
Closed per sprint planning discussion.
