### ISSUE TITLE
File Upload > 15 MB - Error message not user friendly

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1393]
If the total size of the files uploaded is > 15 MB, the message displayed to the user is not user friendly. Please see the screenshot. (noticed this in both test and prod)

![Image](https://github.com/sartography/spiff-arena/assets/104367255/cf7e4554-56c6-49a5-9ae1-6b2c679c644c)

**Comment by harmeet-status** [comment]
This seems like general timeout error which is also experienced if you leave the process instance for too long and then try to upload a file.

Seems like the underlying error is happening because of the same timeout issue.

@burnettk should we split this error out or try and tackle it in the same issue?

**Comment by madhurrya** [comment]
Not sure whether that error message changes with the browser.
This is what I  have seen in Chrome 
![image](https://github.com/sartography/spiff-arena/assets/110527567/0ceed079-f110-45ff-adeb-03997bc7cfd7)

and this in Firefox.
![image](https://github.com/sartography/spiff-arena/assets/110527567/c12991ac-d33e-4861-ad7f-9e8ef99e50e6)

**Comment by jasquat** [comment]
This means we should be able to look for 413 response codes similar to how we look for 401's and 403's and set up default error handling for it. I assume we need to handle this in the frontend since it seems unlikely to be coming from code in backend.

**Comment by madhurrya** [comment]
Now the message is shown like this.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/52da2b9d-ace5-4284-ad56-530cc8feb203)

**Comment by madhurrya** [comment]
Released to Prod on May 9th.
