### ISSUE TITLE
JPEG files upload - Safari

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1394]
When a user wants to upload a JPEG file as an attachment to a process instance through Safari, the JPEG files are disabled for selection even though they are listed as "allowed" extensions.

![Image](https://github.com/sartography/spiff-arena/assets/104367255/8928edf1-a786-4aec-89c3-beedfd0c64af)

The process accepts different type of files including .heic and .jpeg
                 [".csv",".log",".xml",".email",".eml",".emlx",".msg",".oft",".ost",".pst",".pdf",
                                    ".bmp",".gif",".ico",".jpeg",".heic",".png",".svg",".tiff",".key",".odp",".rtf",
                                    ".pps",".ppt",".pptx",".ods",".xls",".xlsm",".xlsx",".avi",".flv",".h264",
                                    ".m4v",".mkv",".mov",".mp4",".mpg",".mpeg",".wmv",".doc",".docx",".odt",".txt"]

**Comment by sashayar13** [comment]
Added the .jpg extension to the process model - but can't do a test because of this issue in dev and test https://github.com/sartography/spiff-arena/issues/1391

**Comment by madhurrya** [comment]
This is tested and released to Prod
