### ISSUE TITLE
Update endpoint for replace bank details

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#1397]
In Maintain Iplicit process form, please add fields for  IBAN, account, Swift code, BIC, Sort Code, Beneficiary Name.
Because we can use it in prod to correct a supplier card if in Bamboo the entry was deleted and the process to synch data between Bamboo and Iplicit doesn't pick up the change since the data is cached in Bamboo.
![image](https://github.com/sartography/spiff-arena/assets/137384667/005d3728-08a8-42e3-8b51-e8f0dbe73ef1)

**Comment by calexh-sar** [comment]
@MarD0607 is this issue assigned to you because you plan on doing the work?

**Comment by MarD0607** [comment]
I'd say we can close it, since I did the bank updates in prod.

**Comment by calexh-sar** [comment]
Closing per Marius' comment above.
