### ISSUE TITLE
Allow storing process instance file data on filesystem

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#1402]
As discussed in status infra, storing a ton of file data in the db is not going to scale. Instead, let's allow storing files on the filesystem.

here's a proposal. given: 

```sh
MySQL [spiff-workflow-backend]> select digest, filename from process_instance_file_data order by id desc limit 2;
+------------------------------------------------------------------+----------------+
| digest                                                           | filename       |
+------------------------------------------------------------------+----------------+
| 0e6187c3d3e7c3203ff4c6dcdaffe5525ace78bcf034a703e2dea005529af65a | bpmn.png       |
| cab3d56a8f66d6eaa17e917adccaeb66e61eaf0f726d36f01d87c7fccac139da | sampletext.txt |
+------------------------------------------------------------------+----------------+
2 rows in set (0.001 sec)
```

 we could store files like: 
```sh
/base/directory/0e/61/0e6187c3d3e7c3203ff4c6dcdaffe5525ace78bcf034a703e2dea005529af65a
/base/directory/ca/b3/cab3d56a8f66d6eaa17e917adccaeb66e61eaf0f726d36f01d87c7fccac139da
```
 
then, if `SPIFFWORKFLOW_BACKEND_PROCESS_INSTANCE_FILE_DATA_FILESYSTEM_PATH=/base/directory` (or some name along these lines) is set, we know to stop populating the big `contents` column of the db table, and the db table is just for metadata. maybe we also have SPIFFWORKFLOW_BACKEND_PROCESS_INSTANCE_FILE_DATA_STORAGE_LOCATION=filesystem  (and it defaults to db, and supports s3compatible in future). not sure if having two vars is helpful.

**Comment by burnettk** [comment]
@jakubgs , this has been deployed to dev.app. as soon as SPIFFWORKFLOW_BACKEND_PROCESS_INSTANCE_FILE_DATA_FILESYSTEM_PATH is set to a directory, it will run the code to lift and shift the file data from the data to the filesystem and things should continue to work on dev.app.

specifically, if you ran this process before the migration, https://dev.app.spiff.status.im/process-models/misc:qa:forms:single-file-upload-in-items-test, uploaded a file, and came to the page where it gives you a link to download the file, it should work before the migration. after the migration, when the `contents` column of `process_instance_file_data` mysql table is the same for every row, going to the same task page in the browser should still allow you to successfully download the file you uploaded. for my instance, for example, i can find my assigned task with the download link from here: https://dev.app.spiff.status.im/i/5163

**Comment by harmeet-status** [comment]
@jakubgs can you pls action the above request so we can test it.

**Comment by jakubgs** [comment]
Thanks for implementing this so quickly. I will attempt to run this migration today on `dev.app` environment.

**Comment by jakubgs** [comment]
I have performed the migration by applying the env variable to backend:

- [`infra-spiff-workflow#5a0c3fcd`](https://github.com/status-im/infra-spiff-workflow/commit/5a0c3fcd) - spiff-workflow: add file location configuration

The result was the files were created:
```
jakubgs@node-01.sm-eu-zur1.spiff.app-dev:/docker/spiff-workflow % find backend/files -type f | head
backend/files/0f/91/0f9113fb807439cd37ea5c50b036edd310f2524bb51d35a7c19214a74b4da119
backend/files/0f/c8/0fc8bad615287d3b4ab28099052a8b244bcecc940fd58d97adb26f24acc9b964
backend/files/cf/ae/cfae97e3d11a60e2705e954b6fd863891926998f8ea340a596d4d153fc543b16
backend/files/d6/01/d6012d46eab66404f9c2c450942dc8874ba6fe057774a38ba19b9fa570062a2d
backend/files/97/39/973910ca615ff56e6a6e08ffd2c5c9dcb2df878f28f83607d6639805aabde641
backend/files/97/4b/974b57ac3b9f02629fd8c6d0cf4d6664394b9dc8b5738f2122e87dc27f7095ca
backend/files/97/4b/974bc1412f5a0068f8ea3fd1c3dae76994b8049fdbcbd59de75bc655c14b56da
backend/files/68/92/689293d9de3afccafb1921cfcb8cd87c3cfae5ede9cb7cbd912cff66a0ebe2d4
backend/files/f2/85/f285edeacbe36299e47b52dcecfa53477c6918cb1525f715791a5adca01785ff
backend/files/aa/ee/aaee5c00bc6c25e2bb61cdff1fc6eb5a0791c6d336bee9f81ee9585fd8819b62
```
The migration took about 1m 30s for ~900 MB of files from `process_instance_file_data` table.
Interestingly the table side did not get reduced:
```
+------------------------+----------------------------+------------+
| Database               | Table                      | Size in MB |
+------------------------+----------------------------+------------+
| spiff-workflow-backend | json_data                  |   11544.67 |
| spiff-workflow-backend | task                       |    4647.31 |
| spiff-workflow-backend | reference_cache            |    4062.64 |
| spiff-workflow-backend | process_instance_file_data |     873.70 |
+------------------------+----------------------------+------------+
4 rows in set (0.00 sec
```

**Comment by jakubgs** [comment]
It appears there's issues accessing files, and backend shows errors like this:
```
{'level': 'ERROR',
 'message': "'utf-8' codec can't decode byte 0xe2 in position 10: invalid continuation byte",
 'loggerName': 'spiffworkflow_backend',
 'processName': 'MainProcess',
 'processID': 117,
 'threadName': 'ThreadPoolExecutor-0_1',
 'threadID': 140366367942336,
 'timestamp': '2024-05-06T08:27:52.354Z',
 'exc_info': 'Traceback ...'}
```
```
Traceback (most recent call last):
  File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/connexion/decorators/decorator.py", line 68, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/connexion/decorators/uri_parsing.py", line 149, in wrapper
    response = function(request)
               ^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/connexion/decorators/validation.py", line 399, in wrapper
    return function(request)
           ^^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.12/site-packages/connexion/decorators/parameter.py", line 120, in wrapper
    return function(**kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/app/src/spiffworkflow_backend/routes/process_api_blueprint.py", line 228, in process_data_file_download
    file_contents = file_data.get_contents()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/spiffworkflow_backend/models/process_instance_file_data.py", line 33, in get_contents
    file_contents = self.get_contents_on_file_system()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/spiffworkflow_backend/models/process_instance_file_data.py", line 50, in get_contents_on_file_system
    return f.read().encode()
           ^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 10: invalid continuation byte
```

**Comment by burnettk** [comment]
stack trace resolved by #1499 . the files were written correctly, and now they are being read correctly as well on dev.app

**Comment by jakubgs** [comment]
Currently the changes are deployed to 3 out of 5 environments, remaining: `mod-test`, mod-prod`

**Comment by madhurrya** [comment]
Tested in dev.app and test.app for different models with old and new instances for different users and didn't notice any issue.

**Comment by madhurrya** [comment]
Code related to this is released to Prod on May 9th. The config changes will be done next week.

**Comment by harmeet-status** [comment]
> Currently the changes are deployed to 3 out of 5 environments, remaining: `mod-test`, mod-prod`

Can you pls do the above as well

**Comment by jakubgs** [comment]
I believe this has already been done for all environments and this issue can be closed.
