### ISSUE TITLE
reset to task within called activity

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#1415]
Brendan alerted us to the fact that resetting to a task within a called activity does not behave as expected. It gives an error, and then it appears to reset to the start event of the called activity rather than the task that you clicked to reset to.

We replicated this using a message start event on the initial process, and it had a call activity that called into the process where we were doing the resetting. i'm expecting that it repros even without the message.

UPDATE: it's not just any called activity. it happens when you are resetting to tasks inside a subprocess/called activity and there is an escalation boundary event on the wrapping subprocess, or in fact any boundary event.

UPDATE 2: Process model that repros: https://github.com/sartography/sample-process-models/tree/sample-models-1/misc/subprocess-with-boundary-event

UPDATE 3: ultimately fixed by spiff PR https://github.com/sartography/SpiffWorkflow/pull/405 and backend commit https://github.com/sartography/spiff-arena/commit/e198c8c866ca599e5223d3a4d28201505e7ef58c

**Comment by madhurrya** [comment]
Testing notes for later testing

When tested with a call activity it gives this error.
![image](https://github.com/sartography/spiff-arena/assets/110527567/46119a6b-3b23-495a-9a01-90cdd44ab736)

https://dev.app.spiff.status.im/i/5271
https://dev.app.spiff.status.im/i/5272

When tested with sub process with the given model and another model for sub process, no errors. But it resets to the start event. 
![image](https://github.com/sartography/spiff-arena/assets/110527567/b9f639ef-f140-458c-831e-51d845866258)

https://dev.app.spiff.status.im/i/5268
https://dev.app.spiff.status.im/i/5270

**Comment by burnettk** [comment]
@madhurrya it apparently wasn't deployed, apologies. i just pushed it to dev.app.

**Comment by madhurrya** [comment]
Tested with the above models and now it seems to reset to the correct task.

**Comment by madhurrya** [comment]
Tested in test.app
