### ISSUE TITLE
Reverse proxy problems

### ISSUE THREAD

**Issue by stefanroels** [sartography/spiff-arena#1419]
I have just updated my SpiffArena instance to the latest version and since then I have problems with the login.

After my OpenID provider has finished the authentication, it returns to SpiffArena. As I am running behind a reverse proxy (nginx) which provides the SSL, it should return to the `https://host.name/api/v1.0/login_return`. However, since the update, it returns to `http://host.name/v1.0/login_return` instead. So it misses the SSL part and the `/api` part of the link.

I have had a look at the code and couldn't understand why, as the code uses the `SPIFFWORKFLOW_BACKEND_URL` to generate this URL. At that moment, I realised that the code I was looking at, was an older checkout. I updated the checkout and noticed that the configuration item was no longer used. As far as I have been able to find, this is due to the change made in [commit 2b6640f](https://github.com/sartography/spiff-arena/commit/2b6640f24c710207c158f01d167c02fdbfe9182b).

**Comment by stefanroels** [comment]
If I go to the `url-info` page, it shows the non-SSL link without `/api` as the `request.host_url` and `request.url`. I will test with the WSGI prefix.

**Comment by stefanroels** [comment]
I just checked the documentation and I see that the `SPIFFWORKFLOW_BACKEND_WSGI_PATH_PREFIX=/api` is necessary when you are not rewriting the path, but I do rewrite the path. Also, all calls other than the login return are going fine. Earlier today, when I was working at the office, I had no problems, as our proxy will rewrite a http to https and I tweaked our proxy to send `/v1.0` to the backend as well. 

Now I'm working via a VPN and that does not allow a port 80 connection, so the upgrade to SSL does not work.

**Comment by burnettk** [comment]
ok, yeah, the solution is not potentially not `SPIFFWORKFLOW_BACKEND_WSGI_PATH_PREFIX ` if you are rewriting the path to remove the `/api` before it hits backend. i assume you have `SPIFFWORKFLOW_BACKEND_URL` set to `https://some.host/api` ?

**Comment by stefanroels** [comment]
Indeed, the backend URL is set to `https://some.host/api`. 

I think the code change below is causing my problem:

![image](https://github.com/sartography/spiff-arena/assets/98820493/40ad8855-feea-41aa-8783-7273996b2d59)

As you can see, the original code used the `get_backend_url()`, where the new code uses the request url (which is incorrect due to the reverse proxy).

**Comment by burnettk** [comment]
and url-info says `request.root_path` is `/` ? if so, yeah, maybe try `SPIFFWORKFLOW_BACKEND_WSGI_PATH_PREFIX=/api`

**Comment by stefanroels** [comment]
`request.root_path` is empty. I'll give the `SPIFFWORKFLOW_BACKEND_WSGI_PATH_PREFIX=/api` a try.

**Comment by stefanroels** [comment]
If I set the `SPIFFWORKFLOW_BACKEND_WSGI_PATH_PREFIX=/api`, I have to go to `https://host.name/api/api/debug/url-info` to get the info. It still reports the `host_url` without SSL, so that doesn't solve anything. I could change the NGINX to keep the `/api` to solve the double `api` in the path, but I would still be directed to the http instead of the https.

**Comment by burnettk** [comment]
I missed that you were having http vs https issues. Search for an env var that matches PROXY_FIX.

**Comment by stefanroels** [comment]
Setting that does solve the problem. Still I find it strange that you have a configuration item which specifies the URL that should be used for the API, but the code that used it is changed such that it now tries to figure out what the API URL should be (which fails if you do not set all kinds of additional variables). And still I have to have a `/v1.0/` location section in the nginx config only for the login return. All other paths leading to the API are correct (probably because they use the `SPIFFWORKFLOW_BACKEND_URL` environment setting instead of trying to guess the URL themselves.

**Comment by burnettk** [comment]
yeah, sorry that this change ended up breaking you. it was to support the non-rewritten path-based use case. we do have clients running rewritten path-based configurations using keycloak, but there could certainly be a bug in the current implementation that they are not tickling somehow.  i don't like using `SPIFFWORKFLOW_BACKEND_URL` unless we are outside the context of a request, since the request really ought to give us the information we need to generate our own url. i'd like to eventually set up a test environment that tries to mimic the issue you're seeing, but if you're in a working state with your weird extra rewrite rule, i will be inclined to close this unless there is a proposed change at this time.

**Comment by burnettk** [comment]
closing, but feel free to reopen.
