### ISSUE TITLE
Process release notes solution

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#1424]
We need a solution where we can put release notes for each process. The problem is that 1 process is usually reliant on many other processes using call activities and we don't want to have to write a release note for each process, we want this to be focused on the user facing process only.

The release notes should be somehow displayed in Spiff but should be managed in Github.

How can we achieve this?

**Comment by harmeet-status** [comment]
@burnettk @calexh-sar any ideas?

**Comment by burnettk** [comment]
how about a file called CHANGELOG in the repo with a format like this, and it could potentially be edited in the app (or via git) and then also displayed in the app via some menu or nav somewhere:

```md
# Changelog
# 2024-04-22

* autoload command conventional-changelog-menu ([d2f0b6f](https://github.com/liuyinz/emacs.d/commit/d2f0b6f4302acda4bd8405685ba307eacafc6bb9))
* conventional-changelog-transform error in md => org
* do not generate org when --dry-run is enabled ([76c4fa2](https://github.com/liuyinz/emacs.d/commit/76c4fa276a7cf877f1b3b2aa1a63fcfdc03b2edc))

# 2024-03-19

* rocked a thing. See [notes](blah).
* another thing
```

which would look something like:

# Changelog
# 2024-04-22

* autoload command conventional-changelog-menu ([d2f0b6f](https://github.com/liuyinz/emacs.d/commit/d2f0b6f4302acda4bd8405685ba307eacafc6bb9))
* conventional-changelog-transform error in md => org ([f08477e](https://github.com/liuyinz/emacs.d/commit/f08477e36f153a962380483cfeb60921670a5fcf))
* do not generate org when --dry-run is enabled ([76c4fa2](https://github.com/liuyinz/emacs.d/commit/76c4fa276a7cf877f1b3b2aa1a63fcfdc03b2edc))

# 2024-03-19

* rocked a thing. See [notes](blah).
* another thing

**Comment by harmeet-status** [comment]
Would each process have it's own changelog?

**Comment by burnettk** [comment]
We could maybe start out with one for all models?
