### ISSUE TITLE
Collapse/expand instructions for user forms

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1425]
Add a feature allowing users to collapse/expand Instructions displayed as part of their User Tasks. Similarly like we do for the End Event Instructions

![Image](https://github.com/sartography/spiff-arena/assets/104367255/49eab618-1be5-4eed-ae09-33beb4894b10)

**Comment by sashayar13** [comment]
@jasquat Is it possible to increase the character limit when instructions _are not collapsed by default_? I can provide you with the value.

**Comment by jasquat** [comment]
@sashayar13 yep, I believe we can change that fairly easily. What would be the desired length? I think right now it's doing 8 lines or 75 words.

**Comment by sashayar13** [comment]
@jasquat I've been thinking about the solution more, and now I suggest removing this feature and spending more time on the design. The toggle solution creates more confusion rather than improvement.
Can the change be reversed? We will revisit this improvement overall as part of the new Spiff design.

**Comment by jasquat** [comment]
@sashayar13 I agree. I will remove it. PR #1444

**Comment by jasquat** [comment]
Closing this ticket since this has been removed on dev now.
