### ISSUE TITLE
Disable collapsable instructions

### ISSUE THREAD

**Issue by stefanroels** [sartography/spiff-arena#1434]
I have just upgraded to the latest version of SpiffArena and I noticed that all my instructions are now collapsed away. Is there a way to prevent this from happening by default (or at all)? 

For me it is quite annoying that I have to click on "Show more" to see the instructions that the process designer has left for me. The instructions are there for a reason, they tell me what I need to do and I see no way to prevent the collapsing.

**Comment by jasquat** [comment]
This is related to #1425. Maybe we can add a configuration for this in some way.

**Comment by stefanroels** [comment]
It would be a good idea to make this configurable. I would even go as far as saying that the default should be to show the instructions without "show more" by default and have a configuration to enable the show more. For me it doesn't make sense to have "instructions" but hide them. I would expect the instructions to be something important for the user, telling them what to do. It could be useful to have collapsible areas for detailed instructions.

**Comment by jasquat** [comment]
Thanks for the feedback. We are removing this in PR #1444. We may revisit with the ui redesign in a more configurable way.
