### ISSUE TITLE
Jinja End Event instructions

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1435]
Started noticing errors in dev.app in process instances https://dev.app.spiff.status.im/i/5336

![Image](https://github.com/sartography/spiff-arena/assets/104367255/d5db1549-e6c0-4d9e-a6ce-df15cd3f9d8b)

and https://dev.app.spiff.status.im/i/5312 

![Image](https://github.com/sartography/spiff-arena/assets/104367255/13ec797d-d588-4242-9a02-051717ac8129)

I checked, and the po_details and exp_details are available in the task data - so the error message doesn't tell anything/

**Comment by madhurrya** [comment]
@jasquat so this will get fixed only in celery or is there a fix that'll work in current dev/test environments?

**Comment by dinithihj** [comment]
Received this error today while testing on test.mod (57/59)

https://test.mod.spiff.status.im/i/1863

![image](https://github.com/sartography/spiff-arena/assets/123297840/d31af0aa-4218-4136-9430-d5bcbe62b43a)

**Comment by madhurrya** [comment]
Tested in test.app/test.mod and didn't notice any issue.
