### ISSUE TITLE
UI:help is not displayed for attachments widget

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1441]
UI:help is not displayed for attachments widget

**Comment by calexh-sar** [comment]
Per discussion during Ticket Grooming meeting, parking until MUI update is completed to see if that addresses this issue.

**Comment by calexh-sar** [comment]
@madhurrya to test with Guest form.

**Comment by madhurrya** [comment]
When I checked this sample https://dev.app.spiff.status.im/editor/process-models/misc:qa:forms:pdf-file-upload/files/pdf-file-upload.bpmn in https://rjsf-team.github.io/react-jsonschema-form/ it shows the UI help with the default settings there. I am not sure why it doesn't work in Spiff.
![image](https://github.com/sartography/spiff-arena/assets/110527567/224a251a-37ca-4fb0-9560-d57e5386c34a)

It works for mui 4 and 5 also here
![image](https://github.com/sartography/spiff-arena/assets/110527567/034ccea7-7d8e-4ac3-ae46-cebb0f3d110a)

**Comment by madhurrya** [comment]
Tested with a Guest form and it works there also.

![image](https://github.com/sartography/spiff-arena/assets/110527567/6cb42625-2b0e-41eb-9d87-c645e926b337)

**Comment by madhurrya** [comment]
@sashayar13 please see whether this is ^ what you wanted.

**Comment by sashayar13** [comment]
@madhurrya yes, this is what I was referring to under the UI:help

**Comment by calexh-sar** [comment]
@sashayar13 should we close this issue and wait for the MUI update or would you like the current Carbon implementation fixed in the meantime?

**Comment by sashayar13** [comment]
considering that the MUI change coming soon - I suggest we close the issue

**Comment by calexh-sar** [comment]
Closing per Sasha's comment

**Comment by burnettk** [comment]
thanks, sasha, i love not doing throwaway work when possible. :D
