### ISSUE TITLE
Generate PDF from JSON data

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#1462]
We need JSON to PDF generation capability built within Spiff. We cannot reply on an external service since we will have private data.

We should construct a HTML CSS page and then convert that to PDF.

Example: https://codepen.io/tjoen/pen/wvgvLX

**Comment by harmeet-status** [comment]
We would want to create a generic invoice template that suits a range of scenarios. It would be great to build the template in a way that we can call it using 2 different methods:

Method 1 (Vendor invoicing) : Used for vendors, including bounties
- Vendor details
- Invoice addressed to
- Invoice summary
- Invoice details
- Payment total data
- Notes

Method 2 (CC invoicing) : Used for staff
- Vendor details (also includes contributor #)
- Invoice addressed to
- Invoice summary
- Invoice details (includes category field)
- Payment total data
- Notes

Method 2 can be thought of as a superset and contains all the fields where as method one had some less fields.

See attached PDF with markings on it.
[template-changes.pdf](https://github.com/sartography/spiff-arena/files/15247789/template-changes.pdf)

**Comment by burnettk** [comment]
We played around with a few options at https://github.com/sartography/pdfs
