### ISSUE TITLE
Add Milestone screenshot

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#1471]
Add screenshot of Milestones being displayed to the Milestones section under [How to check Milestones and Events](https://spiff-arena.readthedocs.io/en/latest/Getting_Started/quick_start.html#how-to-check-milestones-and-events).  Might also be nice to have a screenshot that ties in the the Events section screenshot, i.e., the Milestones are a sub-set of the Events.

![Image](https://github.com/sartography/spiff-arena/assets/54854669/609ff4e7-276d-4e07-bc77-496e573769b8)

**Comment by usama9500** [comment]
Updated it https://github.com/sartography/spiff-arena/pull/1489.

**Comment by usama9500** [comment]
Closing this issue as documented.
