### ISSUE TITLE
Special character related issue - open quote ` character

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1474]
If the user type something within two  open quotes (the key before the Number 1 key in the keyboard) `  or if it is typed in 2 form fields which will be displayed combined, when displaying that text it shows in a different format. And if there are &, < , > like characters inside that they show up as html entities like & amp ; etc

![Image](https://github.com/sartography/spiff-arena/assets/110527567/0199bdba-98a9-4f0f-8c79-bb3ee36db2a2)

![Image](https://github.com/sartography/spiff-arena/assets/110527567/4a1619e8-b0da-4c4b-9810-95dd8c59c1e3)

**Comment by madhurrya** [comment]
I think similar thing can happen with other characters like * etc (markdown)

**Comment by jasquat** [comment]
We have a `sanitize_for_md` method that maybe we could add to. There may also may already be something that can do this.

**Comment by jasquat** [comment]
`sanitize_for_md` doesn't handle this case now, we have to add it but it should be used for cases like this.

**Comment by madhurrya** [comment]
@jasquat I am still noticing that special highlighting thing in some places. But it doesn't happen in all the places like earlier.
![image](https://github.com/sartography/spiff-arena/assets/110527567/041fe4e7-8278-4678-80ab-3706a4607ecc)

You can try it with this simple model Dinithi created. https://dev.app.spiff.status.im/process-models/misc:qa:test-how-greater-than-and-less-than-signs-display
it happens there when you type something inside ``
![image](https://github.com/sartography/spiff-arena/assets/110527567/8075ac4d-77ab-4cff-a2fe-f2092e7b8291)

**Comment by madhurrya** [comment]
Also we noticed another issue today related to special characters, which might be result of this fix. In some places when we type > sign it comes as &gt
It works fine with the above simple model. But in PP1 it comes like this for certain fields.
![image](https://github.com/sartography/spiff-arena/assets/110527567/811e34a4-67b9-47e0-ad3c-f184cf1ec7e0)

This is how I typed
![image](https://github.com/sartography/spiff-arena/assets/110527567/29f2a50a-e3c5-4b78-a5d5-3c6095ea86be)

**Comment by jasquat** [comment]
Remember in order to escape the characters `sanitize_for_md` must be used. It can be used in a script like `escaped_md = sanitize_for_md(data)` or in markdown I believe like `{{ data | sanitize_for_md }}`. https://dev.app.spiff.status.im/process-models/misc:qa:test-how-greater-than-and-less-than-signs-display is not using this method so therefore no characters will get escaped and characters like "`" will be interpreted as code blocks.

**Comment by madhurrya** [comment]
@jasquat In the above model, I am seeing this. Did you add it or not sure whether Dinithi has already added it.
![image](https://github.com/sartography/spiff-arena/assets/110527567/038f8635-56af-4527-ac9c-d807033d659b)

**Comment by jasquat** [comment]
@madhurrya I meant to mention I just added it to test. Got caught up in fixing the `>` issue.

**Comment by madhurrya** [comment]
Greater than issue is fixed.
open quote ` character issue is also fixed when the  sanitize_for_md is used

**Comment by madhurrya** [comment]
@sashayar13 in order to fix the original issue it seems we need to update things as per Jason's comment here. https://github.com/sartography/spiff-arena/issues/1474#issuecomment-2152654709

Otherwise we'll things like this
![Image](https://github.com/sartography/spiff-arena/assets/110527567/493715e3-6ee6-40e7-9536-560938ae4f33)



![Image](https://github.com/sartography/spiff-arena/assets/110527567/454bfd44-5c20-4275-8c71-0623e48a538f)

**Comment by sashayar13** [comment]
Thanks, @madhurrya. I'm using the `sanitize_for_md` in process models, but I need to check if it's added for all text fields.

@MarD0607 FYI - this is smth you may want to incorporate for process models where you have input user forms with text fields and instructions.

**Comment by madhurrya** [comment]
@sashayar13 I think @calexh-sar will have to update the Create event model also as I am seeing that issue there also.

**Comment by madhurrya** [comment]
@sashayar13 I assume we'll do any model updates related to this in a separate ticket and shall I close this one?

**Comment by sashayar13** [comment]
correct

**Comment by madhurrya** [comment]
@sashayar13 do you already have a model ticket for this or do I need to create one in Notion?

**Comment by madhurrya** [comment]
Released to Prod on June 18th. Version 19/20.
