### ISSUE TITLE
Display message to a user when a process started by a BPMN Message

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1486]
Add a feature allowing you to configure/diplaye a message to the user while they are waiting for a process to be prepared for them. The process instance is initiated by a BPMN message

**Comment by sashayar13** [comment]
As per the discussion with the team, the following approach should be taken:
1. Add some extended Markdown (or Markdown + HTML)
2. Check the performance (why it's taking 5 mins or more)
3. Try adding a Discord notification when a user task is ready

@sashayar13 to check the Markdown and create the ticket for performance

**Comment by sashayar13** [comment]
I tried adding the html formatting, and it doesn't look good when there is a combination of Markdown text and HTML. The test margins are different - Markdown fits a column, where HTML piece not.

<img width="1781" alt="Screenshot 2024-05-28 at 4 34 58 PM" src="https://github.com/sartography/spiff-arena/assets/104367255/a4122847-5731-4565-8297-62371471e4a3">
<img width="1781" alt="Screenshot 2024-05-28 at 4 34 46 PM" src="https://github.com/sartography/spiff-arena/assets/104367255/a908c10e-b547-47f6-9201-3fc3416536f7">

**Comment by sashayar13** [comment]
Added some instructions with HTML which should visually highlight important info

**Comment by sashayar13** [comment]
Checked in dev.app - it takes an average of 1.30 minutes to reach the User task in the upload expense process (initiated by a Message Start Event).

- https://dev.app.spiff.status.im/i/3082
- https://dev.app.spiff.status.im/i/3102
- https://dev.app.spiff.status.im/i/3085
- https://dev.app.spiff.status.im/i/3122

@madhurrya, could you please check for additional instances of creating "Upload expense evidence - travel" or "Upload expense evidence - procurement" in test.app? Can you find out how many minutes it takes between the "start expense submission" task completion in the parent processes (Travel or Goods/Services) and the availability of the "Display info" human task for a user?

**Comment by madhurrya** [comment]
@sashayar13 I checked couple of Upload expense evidence - procurement and Upload expense evidence - travel instances and they take around 1.20min to 1.30min in test.app also.
https://drive.google.com/file/d/11tA5qqUXWttafAWKcEIZi0uRuyCAJz3q/view?usp=sharing

https://test.app.spiff.status.im/i/1385
https://test.app.spiff.status.im/i/1388
https://test.app.spiff.status.im/i/1391
https://test.app.spiff.status.im/i/1389

**Comment by sashayar13** [comment]
thank you @madhurrya

**Comment by sashayar13** [comment]
All the updates are captured in this ticket in Notion - https://www.notion.so/we-are-processing-check-back-in-10-minutes-message-a5611bc1f0b64386b199dccde1e3776f?pvs=4
