### ISSUE TITLE
Embedded dashboard (Expense process)

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1491]
There is a need to show the embedded Superset dashboard in the Spiff manual task, the dashboard should be pre-filtered by:
- user (the user who created the process instance = core_contributor in the dashboard)
- period

The user who starts the process in Spiff should see only the entries associated with their expenses for a selected period. (There is an existing Expense dashboard in Superset).

The prototype of the embedded report we created previously with the iframe https://dev.app.spiff.status.im/editor/process-models/misc:prototypes:embedded-superset-dashboard/files/embedded_superset_dashboard.bpmn - it doesn't send any info to the Superset.

@burnettk @jasquat can you pls advise on what needs to be configured in the process so that it can send the variables to Superset? Lalo @JoseAnaya28 will need to check from the Superset side

Sample of auth data (for Lalo @JoseAnaya28)

```
"auth_user_info": {
    "id": 2,
    "email": "sasha@status.im",
    "username": "sasha@status.im",
    "display_name": "sasha",
    "created_at_in_seconds": 1710324262,
    "updated_at_in_seconds": 1710324262,
    "tenant_specific_field_1": "112",
    "tenant_specific_field_2": null,
    "tenant_specific_field_3": null
  },
```

**Comment by calexh-sar** [comment]
Estimate based on using iFrame.  May be more if another approach is needed.

**Comment by burnettk** [comment]
@JoseAnaya28 can we pass query parameters to this sucker in the iframe?

**Comment by JoseAnaya28** [comment]
@burnettk yeah, we can pass the parameters in the url something like this:

> Pass specified parameter in query into URL such as url/?reg=North+America.

**Comment by burnettk** [comment]
@JoseAnaya28 great, thanks, can we filter by user and period with query params (please see the first comment from sasha)?

**Comment by JoseAnaya28** [comment]
@burnettk 
Yes, if we're able to pass the user or/and cc id and the period we should be good to filter the dashboards. 

I think these are the next steps:
1. Create a test dataset that incorporates the conditions to filter data using the URL parameter.
2. Create a test dashboard featuring a chart that uses the test dataset.
3. Set up the Spiff process to summon the iframe with the necessary parameters and check that works 

Is the prototype that Sasha mentioned usable for 3? It seems like it already passes a parameter in the iframe.

**Comment by sashayar13** [comment]
@JoseAnaya28 regarding the 3# - I need to update it slightly so that it has the data we need

**Comment by sashayar13** [comment]
@JoseAnaya28 I updated the prototype https://dev.app.spiff.status.im/process-models/misc:prototypes:embedded-superset-dashboard It creates filter_1, filter_2 and filter_3 which can be used for filtering

filter_1 = email of user
filter_2 = start date
filetr_3 = end date

Let me know if you need other format of variables or other data

**Comment by JoseAnaya28** [comment]
@sashayar13 

Passing filters worked well. The only thing we need to do is to pass the values in the iframe url.
`src="https://superset.bi.status.im/superset/dashboard/57/?start_date=06-01-2024`

![image](https://github.com/sartography/spiff-arena/assets/60910800/640b47d9-aadf-4567-a3d8-3366c58741d3)

The user will only see their budgets as long as their Superset user has a role that permits it, if they don't have a role with any row level security assigned they won't be able to see any budgets. 

These are currently [all the users](https://docs.google.com/spreadsheets/d/10nuHOqNlITLWjizavlBgtWxXjIUw78eurdwcFWbV1jo/edit#gid=0). Do we still match permissions and access based on the approval matrix?  in superset

**Comment by sashayar13** [comment]
@JoseAnaya28, thanks for the update.
I need to ensure that each Core Contributor (CC) has access to their respective expenses in the dashboard. 
Basically, the table should be filtered by the Core Contributor column, and the Core Contributor should not be able to see the expenses of other Core Contributors.

We won't be using the Approval matrix for permissions in this case. Is it feasible to organize this?

**Comment by JoseAnaya28** [comment]
@sashayar13 Yes, we can set up a rule to filter using the core contributor name or id. To do that we'll need to pass either the `core_contributor_display` or `core_contributor_id` in the url parameter.

**Comment by sashayar13** [comment]
@JoseAnaya28 perfect! I'll try this. And you are saying that if we do it that way - the CCs will not be able to clear the filter and view all expenses (other CCs expenses)?

**Comment by sashayar13** [comment]
Tried to filter by receipt date - but it doesn't work https://dev.app.spiff.status.im/process-models/misc:prototypes:embedded-superset-dashboard
@burnettk @JoseAnaya28 could you pls guys check the script and try to run it? Why the filter doesn't work?

**Comment by burnettk** [comment]
maybe let's just play with superset urls until it works in superset rather than involving spiff? when i ran the process model, it was generating this url for the iframe:

https://superset.bi.status.im/superset/dashboard/p/MbLrmE5orDo/?receipt_date__gte=2024-06-11&receipt_date__lt=2024-06-12

is that link correct? does it work (i assume sasha and @JoseAnaya28 can sign in to superset)?

**Comment by JoseAnaya28** [comment]
Hey @burnettk @sashayar13 sorry if I wasn't clear in the previous comments. 

There is an additional step we need to do in Superset where we modify the dataset query to include the custom url variable in the condition clauses. However I've been thinking about this and I believe it can cause issues. If we pass the filters through the iframe, nothing stops a CC from inspecting the code and changing the filter value to anything they want. 

We can do the filtering on Superset end by checking the users email and filter based on the `requestor_work_email`. 
> The {{ current_user_email() }} superset macro returns the email address of the currently logged in user.

I can setup an expense dashboard that will be use specifically for embedding and setup the rule so that any user that access this dashboard will only see the data where their superset email = requestor_work_email

**Comment by sashayar13** [comment]
thanks, @JoseAnaya28. Does this setup allow us also to apply "date" filters on top? To display expenses for this user for the selected period?

**Comment by JoseAnaya28** [comment]
Yes, we can combine both approaches. 

1. The date filter can be passed through the url parameter, we can call it receipt_date. Or if we're using a range of dates we would need to pass a start date and an end date.

2. Superset-side row level rule to filter based on current user email.

If this sounds good to you I can setup the new dashboard with the row level rule and a a dataset with the url parameters inputs.

**Comment by sashayar13** [comment]
@JoseAnaya28 yes - this sounds good. Let set this up. Thank you

**Comment by JoseAnaya28** [comment]
@sashayar13 

I created a dashboard with the same expense table breakdown but with a dataset that can receive two inputs:
- start_date
- end_date

I also set up a row level security rule where viewers of this dashboard will only be able to see the records where:
- requestor_work_email = superset viewer email

https://superset.bi.status.im/superset/dashboard/58/?start_date=01-01-2024&end_date=01-12-2024

**Comment by sashayar13** [comment]
@JoseAnaya28 can you pls grant me edit access to this dashboard? thanks 
<img width="794" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/20e7a89b-3388-45ce-a97e-0853084c4e81">

**Comment by JoseAnaya28** [comment]
@sashayar13 

dev dashboard: 
https://superset.bi.status.im/superset/dashboard/62/

**Comment by sashayar13** [comment]
@JoseAnaya28 I tested the dashboard with the process and it doesn't seem to be working. Check the video 

https://drive.google.com/file/d/1hLFOSzDmBAvZk1twHMC_ShcICJvexm9Y/view?usp=sharing

**Comment by JoseAnaya28** [comment]
@sashayar13 I gave you the wrong format for the date variable. 

It should be month-day-year:
`start_date=06-01-2024&end_date=06-30-2024`

**Comment by sashayar13** [comment]
@JoseAnaya28 I tried to run the process with this date format, but it still doesn't seem to be filtering the dashboard. It shows all entries for all users (it even doesn't filter the dashboard by my user, "sasha@status.im."). Which date column does it use to filter by the period—receipt date?

Check the video - https://drive.google.com/file/d/1M0vwPU-psNxj2ibDD6SaimBwUUs0Z1GC/view?usp=sharing

**Comment by JoseAnaya28** [comment]
@sashayar13 I see the issue, you are using the normal dashboard. I created a specific dashboard for embedding purposes

You should use this as the base link for the iframe: https://superset.bi.status.im/superset/dashboard/62/

**Comment by sashayar13** [comment]
@JoseAnaya28 oh, yeah maybe this was the reason! However, I couldn't check it - the dashboard is errored 
<img width="606" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/fdbd2a7a-1e9a-4f70-86bf-593a14716650">

**Comment by JoseAnaya28** [comment]
Make sure to pass the start_date and end_date variables in the url otherwise it'll error because it's trying to filter by date without a value.

https://superset.bi.status.im/superset/dashboard/62/?start_date=06-10-2024&end_date=06-11-2024

**Comment by sashayar13** [comment]
@JoseAnaya28 yep, I've just checked - it passes the dates, but the error is still there 
<img width="1797" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/f38a5cfe-6cc9-4d42-9aba-d1b229651414">

**Comment by JoseAnaya28** [comment]
@sashayar13 I modified the process to include the correct link, I tested and seemed to work on my end. Can you try when you have a chance?

https://dev.app.spiff.status.im/process-models/misc:prototypes:embedded-superset-dashboard

**Comment by sashayar13** [comment]
@JoseAnaya28 nope, it didn't help. There is still this error https://dev.app.spiff.status.im/i/354

![Image](https://github.com/user-attachments/assets/f027dd1a-ad29-44a6-83e8-f9342c6a6cd5)

**Comment by calexh-sar** [comment]
Closed per sprint planning discussion.
