### ISSUE TITLE
dev.mod - SystemErrorMessage failing

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1501]
SystemErrorMessages are failing in dev.mod

![Image](https://github.com/sartography/spiff-arena/assets/110527567/09277503-0f63-49bb-bd15-3da02a49c923)

**Comment by jasquat** [comment]
Oh yeah that makes sense. I guess if a process model calls the message start event of another process model then it would be handled from celery. Will look into.

**Comment by madhurrya** [comment]
It is working now.


![Image](https://github.com/sartography/spiff-arena/assets/110527567/7f0a4e50-9f7e-466b-84b3-b078401d4672)
