### ISSUE TITLE
dev.mod - PP1 noticing something odd in the interstitial page when approving

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1532]
When the reviewers approving the request, in the interstitial page background I am seeing a process recap page. It doesn't happen like that in other environments.
These videos might give an idea about the difference.
https://drive.google.com/file/d/1Aa9OnGAjBT8HphvJkKRdH_kvqtOUatx0/view?usp=sharing
https://drive.google.com/file/d/1m7SWEe6HM726su-C8_f4H0eupaX3D-EX/view?usp=sharing

**Comment by jasquat** [comment]
PR #1533 should fix this. I was not able to replicate but it avoids adding those instructions to the database so they shouldn't ever be shown to the user outside of the task show page.

**Comment by madhurrya** [comment]
This issue seems to be fixed now.
