### ISSUE TITLE
Allow sending events to a call activity or subprocess

### ISSUE THREAD

**Issue by essweine** [sartography/spiff-arena#1534]
It is possible to set a target workflow when creating BpmnEvents.
The target parameter here
https://github.com/sartography/SpiffWorkflow/blob/651ed6c31d1e972b28f7c14f468d8e4c1b8cbcaa/SpiffWorkflow/bpmn/util/event.py#L2
can be a subworkflow.

It should be possible to set this value in the backend to the subworkflow the event originates from.

It will also require some minor changes to the library to make this work in the the public method (targeting a particular workflow is currently only used internally).

**Comment by burnettk** [comment]
is there another ticket that experienced an issue that prompted this ticket to be filed? is there an example process model? is this referring to the admin feature where you manually send an event to the process instance from the site?

**Comment by essweine** [comment]
I don't think there is an existing process.  The ticket came from a question about which of these error handling scenarios we support based on this diagram:

![image002](https://github.com/sartography/spiff-arena/assets/5230851/7733e984-1b31-45e7-93cb-061adfefbfaa)

This work would make cases A and B possible (and case C, if we were to implement event subprocesses).  Case D would already work.

It's my understanding that some upcoming process model development will require using case A or B (only one instance should respond to the error).

**Comment by essweine** [comment]
This branch contains the library changes: https://github.com/sartography/SpiffWorkflow/tree/enhancement/allow-worfklow-targets-from-external-events

**Comment by jasquat** [comment]
An example process model is https://github.com/sartography/sample-process-models/tree/sample-models-1/misc/multiinstance_with_inner_error_boundary_event.

The check is after running the process model, the multi-instance task will have 3 instances on it. 3 of those instances are fine and one has an error message. This is the intended state. Before this change, they would all have the same error message.

**Comment by dinithihj** [comment]
Tested on dev.app (Version 404/405)

When I tried a sample like the one Jason provided, it worked as expected. Only the instance with an error had an error message; all other instances returned the correct values from the service task. I tested this with both parallel and sequential multi-instances, as well as with call activities, sub-processes, and expanded sub-processes. They all worked as expected.


![image](https://github.com/sartography/spiff-arena/assets/123297840/d0f46a4a-9833-4c49-932c-a2d45f3d5dae)

I tried to create a model similar to the one mentioned in the comment  https://github.com/sartography/spiff-arena/issues/1534#issuecomment-2108491166
I believe it is not working as Daniel described. All instances returned the same error message.
https://dev.app.spiff.status.im/i/3870

![image](https://github.com/sartography/spiff-arena/assets/123297840/8f8cf00a-1dff-4f01-bb16-637b38fbc3e3)

As per the Daniel's comment, Expected below output

- Error A it is caught by the boundary event and thus only 1 out of many MI instances are affected
- Error B it is caught by the boundary event of the subprocess/call activity and only 1 out of many MI instances are affected
- Error C it is caught by the event-subprocess and only 1 out of many MI instances are affected


Process Model - https://dev.app.spiff.status.im/process-models/misc:qa:test-error-handling-scenarios-within-mi

**Comment by calexh-sar** [comment]
Closed per sprint planning discussion.
