### ISSUE TITLE
dev.mod - error in pp1/pp2

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1536]
After the latest deployment there is an error when trying to run PP1/PP2 in dev.mod.
Even if the value of the last dropdown is selected, it doesn't recognize it.
Not sure why, when I tried with a sample dropdown model it works fine.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/fd417a02-9a4f-41f8-9757-001ecc1ce074)

caused by: https://github.com/sartography/spiff-arena/pull/1523

Update : noticed the same error in https://qa1.spiffcrm.com/ but not in dev.app

**Comment by burnettk** [comment]
there's a fix for this in main. we can roll it out to dev.mod when you give the ok. the fix is already on qa1.

**Comment by madhurrya** [comment]
Please deploy that to dev.mod.

**Comment by burnettk** [comment]
done

**Comment by madhurrya** [comment]
This issue is fixed now
