### ISSUE TITLE
Maintenance banner in Spiff, controlled by a process model

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#1551]
We have a requirement that when Spiff maintenance is happening, we currently post in the Spiff Discord channel telling everyone not to do anything.

Would be much more elegant to have a banner in Spiff which can be controlled by a process model.

**Comment by jakubgs** [comment]
How is this feature used @calexh-sar ?

**Comment by calexh-sar** [comment]
@jakubgs no work was done on this issue.
