### ISSUE TITLE
Entering date manually into date picker, auto assumes American format and defaults month to Dec

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#1555]
Any form, enter the date 22-05-2024 and press tab or enter, will change month to Dec.

![Image](https://github.com/sartography/spiff-arena/assets/104047049/cef15faa-3eb4-4bc1-9f88-de6246302f2d)
![Image](https://github.com/sartography/spiff-arena/assets/104047049/607a10de-0cf4-4631-a69d-b8cd84038c41)

**Comment by jasquat** [comment]
This is also due to the debounce like #1521.

**Comment by madhurrya** [comment]
This issue seems to be fixed now. Tested in dev.app

**Comment by madhurrya** [comment]
Tested using https://test.app.spiff.status.im/process-models/misc:qa:test-date-range and https://test.app.spiff.status.im/process-models/misc:qa:forms:test-date-1

**Comment by madhurrya** [comment]
Released to Prod on June 18th. Version 19/20.
