### ISSUE TITLE
dev.mod/qa1 - File upload is not working

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1564]
File upload is not currently working on dev.mod and qa1 servers. This might be due to the rjsf update.

Sample model - https://dev.mod.spiff.status.im/process-models/misc:qa:forms:pdf-file-upload

Video Link - https://drive.google.com/file/d/1OVukiP8kQxJBV159IqZJxa1oap8UcEpM/view?usp=sharing

**Comment by jasquat** [comment]
@burnettk possibly due to rjsf upgrade?

**Comment by burnettk** [comment]
agree

**Comment by dinithihj** [comment]
Tested file uploads on dev.mod and it is working now.
