### ISSUE TITLE
dev.mod/qa1 - Typing is slow in text fields and text areas after selecting a value from a dropdown menu

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1565]
Noticed a slowness when typing on text fields/text areas of PP3 on dev.mod and qa1 servers. But didn't notice the slowness on other process models. 

Further investigated this issue with the sample model which was created by referring PP3 model - https://qa1.spiffcrm.com/process-models/misc:qa:test-text-typing-slowness.

Noticed that typing becomes slow after selecting values from dropdown lists.

Video Link - https://drive.google.com/file/d/1mO6TYeCheTfMXE677MfePVcfKsfH9waQ/view?usp=sharing

related: https://github.com/rjsf-team/react-jsonschema-form/issues/3715

**Comment by jasquat** [comment]
@burnettk possibly due to rjsf upgrade?

**Comment by burnettk** [comment]
yeah, seems likely.

**Comment by dinithihj** [comment]
This seems to be fixed in the samples I created but when checking on the PP3 I can see a noticeable slowness. Here is a video where I'm typing on PP3 instances of dev.app and test.app. 

https://drive.google.com/file/d/1pqbRErvVkqkTXW7Xwuflkz6qKpw1QXr8/view?usp=sharing

Sample models, I created for testing 

- https://dev.app.spiff.status.im/process-models/misc:qa:test-text-typing-slowness
- https://dev.app.spiff.status.im/process-models/misc:qa:test-text-typing-slowness-with-more-dropdowns

**Comment by madhurrya** [comment]
It seems the other fields (specially dropdowns) are also slow in pp3 in dev.app.

Please run it in test.app and dev.app, then you'll notice the difference (Sasha also mentioned about this)
https://dev.app.spiff.status.im/process-models/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:request-new-role
https://test.app.spiff.status.im/process-models/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:request-new-role

But when I run Dinithi's sample model with a similar form, it seems to be faster in dev.app also.
https://dev.app.spiff.status.im/process-models/misc:qa:test-text-typing-slowness-with-more-dropdowns

**Comment by madhurrya** [comment]
Both Sasha and Dinithi mentioned that PP3 is considerably slow in dev.app

**Comment by madhurrya** [comment]
PP3 seems to be faster in dev.app now

**Comment by dinithihj** [comment]
Tested on test.app (Version 214/216) Issue seems to be fixed now.
