### ISSUE TITLE
dev.mod/qa1 Inclusive Gateways giving an error when only some path conditions are true

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1575]
On dev.mod and qa1 servers Inclusive gateways are causing errors when only some path conditions are true. They work fine when all path conditions are true.

Errored Instance on dev.mod - https://dev.mod.spiff.status.im/i/39004
Errored Instance on qa1 - https://qa1.spiffcrm.com/i/628

The same model with the same data selection on dev.app - https://dev.app.spiff.status.im/i/1667

**Comment by madhurrya** [comment]
@jasquat But the same model works in dev.app as Dinithi has mentioned above. So it can't be a model issue I guess?

**Comment by jasquat** [comment]
New rjsf only seems to pass in pieces that have been interacted with. So if you click on the checkbox and then uncheck it, then the value will be set to false, however if you do not click on the checkbox at all, then this field is never passed in. Currently the only way around that is to set a default value for the fields. In this case, setting the checkboxes default values to `"default": false` allows the variables to be set.

**Comment by dinithihj** [comment]
Tested again on dev.mod and qa1 servers after setting checkboxes default value to false. Now it is working as expected. 
Closing this ticket.
