### ISSUE TITLE
Spiff bounties process - Payment

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#1579]
Complete [proposed process model](https://dev.app.spiff.status.im/process-models/manage-productsprojects:develop-products-and-services:spiffworkflow-development:spiff-bounties-payment)  to allow for bounty payment.  

Bounty payment will require creation of a Iplicit PO, which involve adding the bounty supplier account in Iplicit with at least this data:
- **contact group ID:** 3P for credit suppliers, CARD for any suppliers who will be paid by debit card. I have created a group BOUNTY for bounty recipients
- **department ID:** Yes this is very important so that the supplier invoices are allocated to the correct department
- **paymentmethod ID:** DBT for all suppliers who will be paid by card, including subscriptions and adhoc payments. CRY is Crypto if the supplier will receive crypto payments and BC for BACS payments.
- **payterm ID:** We will use 30 days as standard for all 3rd party suppliers unless we specifically are told that the supplier has different terms.
- **address:** Yes, mandatory
Also...
- For bounties, the default account will be bounties.
- We will still need tax authority and tax band, but I have set them as a default tax authority of Singapore and tax band as Not applicable as a default, the same as we have for CCs

**Comment by harmeet-status** [comment]
No @sashayar13 will not be ready in time, so we can just put a manual step here for Finance to create a purchase order in Iplicit.

**Comment by sashayar13** [comment]
@calexh-sar there is a PO process in place which you can incorporate into the Bounty process. @MarD0607 is the one who will be able to assist you with this

**Comment by calexh-sar** [comment]
Thx, @sashayar13.  @MarD0607, would you please point me to a process or processes which are examples of the PO process.

**Comment by calexh-sar** [comment]
From @MarD0607 via Discord:
For the bounty data store, we will need to generate codes for suppliers just like we do with vendors. You can use https://dev.app.spiff.status.im/process-models/manage-procurement:vendor-lifecycle-management:metadata-synch:current-list-of-iplicit-codes to get the current list of codes from Iplicit, and I have a Generate supplier code script task in the MI in https://dev.app.spiff.status.im/editor/process-models/manage-procurement:vendor-lifecycle-management:metadata-synch:bbhr-man-new-cc-to-iplicit/files/bbhr-synch-with-vendor-md.bpmn, which based on the full name and the list of current codes from Iplicit, will create the new code
