### ISSUE TITLE
dev.mod - PP1/PP2 error

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1589]
When the requestor submits a PP1/PP2 form without adding any Supporting Information then it gives this error. First I thought it was a model issue, that's why I asked KB to update the models. But the same happen after that also.
It works in test.app/test.mod so it's not a model issue.

(May be it's similar to the issue Dinithi had with the inclusive gateway?)

https://dev.mod.spiff.status.im/i/39274
https://dev.mod.spiff.status.im/i/39276

![Image](https://github.com/sartography/spiff-arena/assets/110527567/40e23e67-0ab8-42fc-9625-10607b4843ae)

![Image](https://github.com/sartography/spiff-arena/assets/110527567/b01e0f1e-da9b-4c05-b3a3-0a6fd5fdd5c0)

**Comment by burnettk** [comment]
is it the same issue as https://github.com/sartography/spiff-arena/issues/1575, where some variables that were previously set to null are now absent? FYI, @calexh-sar

**Comment by burnettk** [comment]
yeah

**Comment by burnettk** [comment]
i updated three variables in PP1 on dev.app. There were del(blah) commands that were not working until i wrapped them in `try` / `except NameError` blocks, like this:

````python
# delete team_id if it exists
try:
    del(team_id)
except NameError:
    pass
````

**Comment by madhurrya** [comment]
Now it's giving this error
![image](https://github.com/sartography/spiff-arena/assets/110527567/4d366ae7-89ef-4cb3-97b1-a37c15dfda4d)

https://dev.app.spiff.status.im/i/2209

**Comment by sashayar13** [comment]
@burnettk, where exactly did you update the variables? do you remember what were the variables?

**Comment by sashayar13** [comment]
@madhurrya this error is related to the change I introduced to fix the issue you mentioned originally https://github.com/sartography/spiff-arena/issues/1589#issue-2310706791

`try:
    supporting_information
except NameError:
    supporting_information = ""`

**Comment by madhurrya** [comment]
This issue is fixed now.
