### ISSUE TITLE
Grey color loading screen - dev.app

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1615]
In dev.app when submitting a request (in many models) noticing this grey color screen for a second. Not noticing it in other environments. Seems to be due to a recent code update.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/6d8eff02-306b-4253-bc78-9b63833b240b)

Please check this video
https://drive.google.com/file/d/1t5WqxIhWTyYwzu-8arLD8eWWZ4YoCuQE/view?usp=sharing

**Comment by burnettk** [comment]
moved potential fix to dev.app

**Comment by madhurrya** [comment]
This issue seems to be fixed now.
