### ISSUE TITLE
Process instance breadcrumbs

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1616]
Add the Process model link to the breadcrumb (after the Process Group and before Process Instance).

![Image](https://github.com/sartography/spiff-arena/assets/104367255/8488fb38-d4d7-4bf8-9ce8-4b97d404f251)

**Comment by sashayar13** [comment]
should be a quick one - but helps admins a lot

**Comment by jasquat** [comment]
@sashayar13 what user are using when you see this? It's supposed to show the process model info I think. It's based on the permissions that the user has.

**Comment by madhurrya** [comment]
@sashayar13 do you remember from which model/task did you take the above screenshot?

**Comment by madhurrya** [comment]
Now I can see the full breadcrumb
![image](https://github.com/sartography/spiff-arena/assets/110527567/d00b8e26-c4cd-466c-a5c7-053433d2bb35)

![image](https://github.com/sartography/spiff-arena/assets/110527567/4cf11e93-160b-4837-ae54-44b8f7c4f32a)

![image](https://github.com/sartography/spiff-arena/assets/110527567/f78d83db-6763-4578-a407-a622eb267369)

**Comment by madhurrya** [comment]
Released to Prod on June 18th. Version 19/20.
