### ISSUE TITLE
dev.mod/dev.app - Error: Cannot find a bpmn process with guid 'None'

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1629]
I got this error when starting this process. https://dev.mod.spiff.status.im/process-models/misc:typeahead-fields-datastore:bbhr-cc-list-timer
https://dev.mod.spiff.status.im/i/39782

![Image](https://github.com/sartography/spiff-arena/assets/110527567/97490fb9-f4e0-41fb-872d-7495210145bf)

Same happened with this also. https://dev.mod.spiff.status.im/process-models/misc:typeahead-fields-datastore:cities-states-countries-list-timer
https://dev.mod.spiff.status.im/i/39784

![Image](https://github.com/sartography/spiff-arena/assets/110527567/24966ae7-58c2-4f42-a949-15d0f5a1a2c8)

This seems to happen with Cycle start timers and it happens in both dev.mod and dev.app

**Comment by madhurrya** [comment]
Now I don't get that error at the start.
But I get it when I try to terminate a new start cycle timer instance I created today. 
https://dev.app.spiff.status.im/i/3067
https://dev.mod.spiff.status.im/i/39845

![Image](https://github.com/sartography/spiff-arena/assets/110527567/47a7d465-f627-4347-95e5-352f0f02cf57)

**Comment by jasquat** [comment]
@madhurrya The new pr should full address this.

**Comment by madhurrya** [comment]
This issue seems to be fixed now.
