### ISSUE TITLE
Form Editor saving error

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1630]
I noticed error messages when I was working with Form Editor. The changes I made were not saved

![Image](https://github.com/sartography/spiff-arena/assets/104367255/03b852e3-bab4-4c0a-8533-ed3f26014515)

![Image](https://github.com/sartography/spiff-arena/assets/104367255/b2a1b36a-9683-4c87-97a5-eb83d4b3a96d)

**Comment by calexh-sar** [comment]
Work on this issue:
- Add Save button that shows up if error saving and allow user to try saving again 
- Add last saved time
- Attempt to reproduce and debug "does not have any content" error

**Comment by sashayar13** [comment]
noticed the error today 

![Image](https://github.com/sartography/spiff-arena/assets/104367255/f378656e-630c-4c79-beb9-b2b6fa99ae77)
