### ISSUE TITLE
Allow for optional Data Store connection

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#1656]
If a Data Store update is conditional, a error is throw if it is not used.

**Comment by burnettk** [comment]
@jbirddog you fixed this, maybe?

**Comment by jbirddog** [comment]
Just forgot to update the ticket. It is ready for qa

**Comment by dinithihj** [comment]
This seems to be fixed now. 
Tested on dev.app (version 412/413) with the model https://dev.app.spiff.status.im/process-models/misc:qa:data-store-tests:optional-data-store-writes

**Comment by calexh-sar** [comment]
@dinithihj what else is needed to move this issue to Ready for Release.

**Comment by dinithihj** [comment]
> @dinithihj what else is needed to move this issue to Ready for Release.

@calexh-sar just waited for PRs to be approved, to have a quick test on test.app.

**Comment by dinithihj** [comment]
Tested and verified on test.app (version 216/218) with the model https://test.app.spiff.status.im/process-models/misc:qa:data-store-tests:optional-data-store-writes
