### ISSUE TITLE
PP1/PP2 - Receiving an Error When Uploaded Files Deleted Using New "-" Icon

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#1697]
The issue was noticed on PP1 and PP2 and can be recreated with the model  https://dev.app.spiff.status.im/process-models/misc:qa:forms:test-non-required-nested-single-file-upload

On a non-required nested single file upload, I uploaded a file and deleted it using the new "-" icon. When proceeding, the script task with the below code 

`# Build Supporting File Links
file_links = [markdown_file_download_link(digest_reference["supporting_file"]) for digest_reference in supporting_files]`

gives the below error 

![Image](https://github.com/sartography/spiff-arena/assets/123297840/f6e10aa6-4c57-4901-94f1-ee6e721c8992)

The error does not occur if the file is deleted using the regular delete button instead of the new "-" icon.

**Comment by jasquat** [comment]
This also happens if the user removes the file by opening the file upload window and then hits `Cancel`.

This may be related to how rjsf works now. If a file is added and then removed, rjsf does not remove the key but instead the value gets set to undefined. Then we change these undefined values to null which results in something like:
```json
{
  "supporting_files": [
    {
      "supporting_file": null
    }
  ]
}
```
 
however if we avoid changing undefined to null then its:
```json
{
  "supporting_files": [
    {}
  ]
}
```
which results in a KeyError.

This may have to be handled in the process model where it checks if the supporting file actually has contents or not before attempting to create a link with it.

**Comment by madhurrya** [comment]
@sashayar13 could you please check the above comment. I think we'll have to update the models to fix that.

**Comment by sashayar13** [comment]
The first thing I noticed is that this icon does not look like an icon; it looks like an error or something wrong. Can it follow the same pattern as other icons/buttons? 
<img width="680" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/153e79d0-1889-45eb-8a12-d9570aae0e27">

And why was this icon added?

@harmeet-status FYI

**Comment by madhurrya** [comment]
@sashayar13 Please refer to this for more details about that icon https://github.com/sartography/spiff-arena/issues/1649
Please see the comments from Jason and KB

**Comment by madhurrya** [comment]
@burnettk @jasquat Based on Sasha's comment is there a better icon we can add for this? What are the options we have?

**Comment by burnettk** [comment]
Can someone please try it on the react json schema form demo site using the mui 5 theme and drop a screenshot on here? Our goal was to make it look like that, but I’m not sure how close we got.

**Comment by madhurrya** [comment]
This is how it looks in mui5

![image](https://github.com/sartography/spiff-arena/assets/110527567/c8022764-55cf-41af-8abb-b43671d0246f)

**Comment by burnettk** [comment]
ok, thank you, so i think the red minus button icon is pretty much the same as the one used in MUI 5. perhaps it is more visually consistent when used alongside other MUI components per the screenshot. we should really try to avoid customizing MUI form components if at all possible and let the react json schema form team maintain that theme. we can pick the icon we want for carbon, but it will just have a short term effect.

**Comment by madhurrya** [comment]
@sashayar13 do we need to change the icon for the Prod release or what do you think?

**Comment by burnettk** [comment]
https://react-jsonschema-form.readthedocs.io/en/v1.8.1/form-customization/ talks about an orderable option under array item options, so I think it is supported to make the arrays not orderable (which would remove the up/down buttons). It would possibly work with carbon and almost certainly work with mui.

**Comment by harmeet-status** [comment]
@madhurrya can we pls try with making orderable false and see how it looks. Pls post screenshot here.

<img width="750" alt="Screenshot 2024-06-13 at 5 31 50 PM" src="https://github.com/sartography/spiff-arena/assets/104047049/26c15663-57be-4bcf-ad93-79516c3f301c">

**Comment by madhurrya** [comment]
@harmeet-status in mui
![image](https://github.com/sartography/spiff-arena/assets/110527567/7ab10687-6a28-41ef-9d1f-3dcce6bf4ac3)

**Comment by madhurrya** [comment]
another one in mui

![image](https://github.com/sartography/spiff-arena/assets/110527567/49e5bec9-823c-4e1d-8d28-0056529d5ccc)

**Comment by harmeet-status** [comment]
This looks fine to me, let's go to prod.

**Comment by madhurrya** [comment]
@harmeet-status just to confirm, this is how it'll look at the moment.
![image](https://github.com/sartography/spiff-arena/assets/110527567/6fce7634-b82c-4620-ac8a-19d5938896c1)

**Comment by harmeet-status** [comment]
This is ok @madhurrya
