### ISSUE TITLE
Messages related issues (in qa5) - 2

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1716]
EDIT: @jasquat 

> This is unrelated to messages. The db was locked for some unknown reason. We plan on switching k8s environments to mysql which will help with issues like this.

1.  Got this error when completing this process instance. Not sure whether it's message related or something else.
https://qa5.spiffcrm.com/i/355

![Image](https://github.com/sartography/spiff-arena/assets/110527567/1b5a7459-e7ff-49bc-b0fa-55b9f4cc1d8c)

**Comment by madhurrya** [comment]
2. Got this error after I saved this model and tried to set the message from the drop down.


![Image](https://github.com/sartography/spiff-arena/assets/110527567/f57cc262-59d2-42e6-b5fd-e1b8ecda0749)

**Comment by madhurrya** [comment]
3. Here in this model https://qa5.spiffcrm.com/editor/process-models/manage-talents:manage-compensation-benefits-administer-payroll:business-related-meetingsevents:request-travel/files/request_travel.bpmn
It says 'Only process models within this path will have access to this message.'

![image](https://github.com/sartography/spiff-arena/assets/110527567/3b0be55d-d212-4664-b584-a1b0950e1f11)

But the model that uses that message is here https://qa5.spiffcrm.com/editor/process-models/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence-travel/files/upload-expense-evidence-travel.bpmn

Can that cause any issue? Is this something we need to worry about?
This is the case for the other upload evidence model also.

**Comment by madhurrya** [comment]
4. I have the variable name saved like this.


![Image](https://github.com/sartography/spiff-arena/assets/110527567/f57d44b9-7f27-412b-a6ff-8e12f4a79e01)

Now if I open the Message Editor and click Save and Close it then this Variable name becomes blank


![Image](https://github.com/sartography/spiff-arena/assets/110527567/5630d40f-e45f-4e13-9284-99127b4f7586)

**Comment by madhurrya** [comment]
5. I was uploading a file in qa5 (totally unrelated to message work) and got this error.


![Image](https://github.com/sartography/spiff-arena/assets/110527567/ecde4071-4745-4656-9f98-c675405df40f)

**Comment by madhurrya** [comment]
6. I am getting this error 'This process is not waiting for Madhu_message.' (I think the same error as in issue no 7 here https://github.com/sartography/spiff-arena/issues/1626)

https://qa5.spiffcrm.com/i/557
https://qa5.spiffcrm.com/i/556

![image](https://github.com/sartography/spiff-arena/assets/110527567/d47a2c45-13db-4176-8d16-4763ccc70c6e)

![image](https://github.com/sartography/spiff-arena/assets/110527567/4fff88af-4492-449d-a031-d16056229ec2)

**Comment by madhurrya** [comment]
7. When I run this model https://qa5.spiffcrm.com/process-models/misc:test:madhurya-testing:message-testing4:receive-message-3 I get this error 
(may be because I have used an apostrophe in correlation property name)
![image](https://github.com/sartography/spiff-arena/assets/110527567/d1fe6f8d-f03b-43c5-bbc7-1ee044fb73e2)

**Comment by jasquat** [comment]
Latest fixes have been deployed to qa5.

**Comment by madhurrya** [comment]
New issues will be added here https://github.com/sartography/spiff-arena/issues/1764

**Comment by madhurrya** [comment]
Issue 4 and 7 are still not fixed. I added them in the new ticket https://github.com/sartography/spiff-arena/issues/1764 and closing this ticket.
