### ISSUE TITLE
User Form Loop - Display info

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1717]
If a User Form is used to gather information in a repeated cycle (loop) and a user keeps the form opened - the fields are not cleaned up for the next cycle even if the data is not available in the task data (deleted as part of Scriot task).

Example:
- I have this process model https://dev.app.spiff.status.im/process-models/misc:prototypes:items-loop
- The "item" data is deleted as part of the Script task following the User Task
- But the data is still displayed to a user (not for all fields, though supporting files and "More" are updated - they are empty).
- However, if the user closes and opens the user form again - the fields are empty.

Check the recording attached - https://drive.google.com/file/d/111ukaQ6T1NU2kzdzKvKsn71XaU8ZhLaV/view?usp=sharing

**Comment by madhurrya** [comment]
It seems to be fixed the model Sasha has given. But still noticing it in this model. 
https://dev.app.spiff.status.im/editor/process-models/misc:qa:bpmn-model-testing:unit-test-multi-instance-loop-user-task/files/loop_user_task.bpmn

**Comment by burnettk** [comment]
Reloading the user form maintains the data, so it’s not the same issue. I don’t think the model in the last comment is doing anything unexpected, since the task data is never being deleted, so we would expect the previous entry to be populated in the form.

**Comment by sashayar13** [comment]
@madhurrya the original issue is fixed, we can close the issue
