### ISSUE TITLE
Spiff bounties Submission - process Issues

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1752]
~1. It seems 2 new fields have been added to the form
I think it's better to show the Additional notes field at the bottom and Priority before that.
What does this Priority actually means?~

![Image](https://github.com/sartography/spiff-arena/assets/110527567/378f2f49-b289-47e4-9c15-e7c26a90e331)

**Comment by harmeet-status** [comment]
> 1. It seems 2 new fields have been added to the form
>    I think it's better to show the Additional notes field at the bottom and Priority before that.
>    What does this Priority actually means?
> 
> ![Image](https://private-user-images.githubusercontent.com/110527567/340621793-378f2f49-b289-47e4-9c15-e7c26a90e331.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTA1ODAsIm5iZiI6MTcxODcxMDI4MCwicGF0aCI6Ii8xMTA1Mjc1NjcvMzQwNjIxNzkzLTM3OGYyZjQ5LWIyODktNDdlNC05YzE1LWU3YzI2YTkwZTMzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxMTMxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzNiZjY0ZmNkZGNhNzI5ZGU2NjUzMTdiMjA2MDVlMjI0NjFlN2EyMmZhZjk2MTQ1ZmU2ZWQyNmM0YTEzMTZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wX6NBWPf09T4VlMp21pk3j8Usw-_VjDarZ-ibG5hx3s)

Yeah that's just me playing around @madhurrya. FIXED.

**Comment by calexh-sar** [comment]
Closing this issue per @harmeet-status's comments above.

**Comment by calexh-sar** [comment]
Reopening

**Comment by madhurrya** [comment]
2. If we have removed the one time password then we need to update these messages also

![image](https://github.com/sartography/spiff-arena/assets/110527567/2daa965c-fd60-47a3-8398-6d2a3e18a1da)

![image](https://github.com/sartography/spiff-arena/assets/110527567/7754c312-bdc0-4c38-a80d-2171c3f5e909)

**Comment by madhurrya** [comment]
3. Spelling mistsake
![image](https://github.com/sartography/spiff-arena/assets/110527567/df063264-3ec5-4b9c-a99e-fa6bc7cd14c6)

**Comment by madhurrya** [comment]
4. When I submit my details then it just says 'Thank You'. It's better explain there what happens next.

![image](https://github.com/sartography/spiff-arena/assets/110527567/d7eb1b9a-3f38-4b99-a666-53819af2154a)

**Comment by madhurrya** [comment]
5. Suggestion - Since the user can request for more than one bounty, it might be better to show the Issue number also here.
![image](https://github.com/sartography/spiff-arena/assets/110527567/a626ad93-c21d-46f4-bcb1-367e84212174)

**Comment by madhurrya** [comment]
6. I have set the label as Bounty compete. But it says it's not a Bounty issue.

![image](https://github.com/sartography/spiff-arena/assets/110527567/02d20533-10b9-4f05-83cd-ded3e7eaf9d1)

![image](https://github.com/sartography/spiff-arena/assets/110527567/8d92c108-641c-4382-99ec-80f017be19d8)

**Comment by madhurrya** [comment]
7. If the user accidently closes the the bounty form, when he tries to open the link again it gives this error.
![image](https://github.com/sartography/spiff-arena/assets/110527567/2eda9b53-3b65-4bac-b438-5ea81d005d0c)

Shouldn't the user be able to open it again?
If we are blocking it on purpose I think we should show a proper message (UI/UX).
If we are not blocking it then the user should be able to open the completed form and complete it.

**Comment by madhurrya** [comment]
8. We need to show 2 decimal places (Harmeet asked to add this)

![image](https://github.com/sartography/spiff-arena/assets/110527567/07c97849-c340-48dc-aadd-3264a7499bd3)

**Comment by madhurrya** [comment]
9. Is this value three hardcoded? Currently this issue is not assigned to anyone but it says it assigned to three.
![image](https://github.com/sartography/spiff-arena/assets/110527567/3c0a540b-9b96-4024-be9e-31daa376fa21)

**Comment by madhurrya** [comment]
10. It seems the font type/size in these 3 are different. Better to use the same font and format
![image](https://github.com/sartography/spiff-arena/assets/110527567/629530f7-984c-4d45-b2d5-f035822e6c4d)

**Comment by madhurrya** [comment]
11. For this also it is saying 'Issue is not a bounty issue.'
https://github.com/sartography/SpiffWorkflow/issues/420



![Image](https://github.com/sartography/spiff-arena/assets/110527567/3cabdc55-8059-40ba-9362-173a7c476def)




![Image](https://github.com/sartography/spiff-arena/assets/110527567/e4479dcb-562e-40b9-9076-14316d3cdfee)




![Image](https://github.com/sartography/spiff-arena/assets/110527567/7d61e66a-e81f-4209-8fb5-10bdaaab7bc7)

**Comment by calexh-sar** [comment]
@madhurrya pls retest #6.  Labels are case sensitive and I updated the labels in the `bpmn-js-spiffworkflow` repository to all lowercase.

**Comment by harmeet-status** [comment]
#2 fixed: Discord message updated.

**Comment by harmeet-status** [comment]
**Improvements**

#12 @calexh-sar can you pls add a URL to the XML, in the below screenshot.
![Image](https://github.com/sartography/spiff-arena/assets/104047049/97631873-d5f2-49d0-9297-20eaa0b39470)


#13 Add bounty name and URL here 
![Image](https://github.com/sartography/spiff-arena/assets/104047049/a4de422f-60de-458f-bcf8-c397db30e908)
![Image](https://github.com/sartography/spiff-arena/assets/104047049/96f45664-0533-4268-8173-39d672c8ba0f)


#14 Remove the OTP rule from the dmn table, we no longer use this

**Comment by harmeet-status** [comment]
#16 Update the process flow to this
https://app.diagrams.net/?border=0&tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Page-1%22%20id%3D%22iAVFmr82_K5mgpOtPOTw%22%3E1Vpbd6M2EP41Pts%2BJAeQwfgxttPNnibntM1puvsogwA1ArlCxPb%2B%2BkogbhZ2SHwheUnQMEJi5puZT4NHYB5vvjK4ih6oj8jIMvzNCCxGljW1HfFXCraFwHScaSEJGfaVrBY84p9ICQ0lzbCP0pYip5RwvGoLPZokyOMtGWSMrttqASXtVVcwRJrg0YNEl%2F6DfR4VUtc2avkdwmFUrmwa6k4MS2UlSCPo03VDBG5HYM4o5cVVvJkjIo1X2qWY99ueu9XGGEp4nwk8uPPQ7wv%2B59P0wSJPT5GR3FwBtTe%2BLV8Y%2BeL91ZAyHtGQJpDc1tIZo1niI%2FlUQ4xqnXtKV0JoCuG%2FiPOtcibMOBWiiMdE3S3WlAvtfRUlSmnGPHRg%2FyUkIAsRP6BnVQYXSEU0RpxtxTyGCOT4pb0PqCATVnq1VcWFMuwbjKye%2BwJJplb6lqbiUjpMOMCBsbDbLFmmq9w4DhFvMktXMGl5xvkvk1CZLaH3HOY%2BuPIooWwEbuQGEswxJMUDlKa4CuV%2FmPhCYytsKSMRcYhJWi4jXqhYqVDV4NB29jrCHD2uYO6TtYj4Lse%2BIMbR5rBrdVeoCa6Klm17uK5jzywDKmrEnWOcyXf2KxZ5B%2FyFJdj2u5qfD37IwbVdDheb5s3FVo1OGDZWz7AZDxk27ifPTX2NPBnSyJaWm3TARzReZulFwt8at%2BN%2Fose%2F2xH%2B7rnCH%2BjmuAAI35sh0Abz77WmGP1o3KknyUE5x4dplO%2F1xOgf963MzpDwH2vwn9MkwEywN0yTvLQWdXLJyhK5wKlHmayoMUpTSR%2BFNaR5jiqdMmqwoJ03BIdi3QWnq9NEFHDaEWX3rKiV8OQ2n2g2%2F4p5lC2FLEsRS2AsTYoEeWcf1KYVpy9PNX1pink2nmICzaqzjHOFYeObZH7YT77wPLQ8JCNLbKOJ4oGZH5jYbaOaulGnHTa1z2ZS55MTENPumYP3OOZCpyP7IHIf5E66EgRO82OPyMVMHvyHhq8F2vCtcsRg8J0MSl2qQUFdJn25i9lkLtdWSWS6ycspgwX0DRZwZLTkU28Yg9uGworihKeNJ%2F8hBTW8xs5udnSbCNH07Z2y%2F2b98WF9bT9tfXFRvGGN38pUR0Da1VKFYF45FUvDkqn5%2BKVqfIQQJ41OR%2BNWZ2zcwyUibTxDxR08ASjEOkhFjH2%2FCB2U4p9wmT9PYlN5VDzcno3sxaEso5qXavKoSh1NHB%2BI8b05ybg2TAu0%2FFR2%2FN6GVs39JYkr2zTt%2BTQIUsS1DHYCBFTh%2FGlr8rRnmmn0iIcoytPXi3K4ryh%2F2JLcQdMvWpLBIOj9CP1GoyfqwaCoL7fZQP2N7yuEy%2B3TJhdlaEX19sAvMUwySPKXTZ%2FzXaayUqjZd5DFCPEvMk4YJejXwaNkt0HQ1XO7bM%2Fd0s%2Byc5pwnOTfTBLK4ty%2BAaFrzXrCDvy9FbzL1m1vBGIbZbSa5biIO8FNTuIOx2i7o29rYXw2bziaN6oW2F7omq9DN8CEzIsPWGIu8CFyA09%2B%2BOKMPqPGHcdz0TLQrH96U191tRwuDP1hD22NolB1ji9UIZy%2BvOjY49dx%2FtFPIB7Bnszzf%2F913%2Bm7T3eosA4fKq6Ma9N02vxfLfneQ8X5zw1gkB867GuGvMa8zvVNBvSlYUd%2FlHlXj8PdycfA2PlFyyv6V66xg50z9CCAzhEfix5E%2FWEIep6ADi%2FiEgcisvOvSd054tJ8z7Yux%2FfEsP6BU%2BGB%2Bmdi4PZ%2F%3C%2Fdiagram%3E%3C%2Fmxfile%3E

**Comment by harmeet-status** [comment]
#17 We don't need this screen anymore, since we no longer use OTP. Jump straight to the next form.
![Image](https://github.com/sartography/spiff-arena/assets/104047049/7ca876a0-5345-417e-aebf-f35c8e35d2c3)

**Comment by harmeet-status** [comment]
#18 I can't see where the text above the title comes from, it's not in the JSON
![Image](https://github.com/sartography/spiff-arena/assets/104047049/9120d22b-0000-4eee-8ad1-669c99e085f7)
![Image](https://github.com/sartography/spiff-arena/assets/104047049/4d6ad8dc-3fe8-4aee-9aea-8d2f2ff3107e)

**Comment by harmeet-status** [comment]
19. When clicking a URL which has expired, we need to show a nicer error message:
Oops! Looks like this URL has expired. Please start from scratch and resubmit the form.

![Image](https://github.com/sartography/spiff-arena/assets/104047049/4074ab09-1014-4a65-a4fd-1382f9b5ca1c)

**Comment by harmeet-status** [comment]
20. Update this page as follows:

Title: Bounty application complete
Body: Thank you for applying to work on this bounty. We will review your application and get back to you ASAP. We may get in touch with you over Discord to discuss any further details that we need.

![Image](https://github.com/sartography/spiff-arena/assets/104047049/49a2f72e-0ff8-4faf-9708-c11c539277e6)

**Comment by harmeet-status** [comment]
21. Upon form load, dont auto pick a radio button, this could lead to accidental error
![Image](https://github.com/sartography/spiff-arena/assets/104047049/011ebf39-1a01-4056-a179-4bc2f11cb1e3)

**Comment by harmeet-status** [comment]
22. What is this suppose to show?

![Image](https://github.com/sartography/spiff-arena/assets/104047049/ca46b2bf-214e-4085-94a8-270ed72e868f)

**Comment by harmeet-status** [comment]
23. Add line breaks here and some spacing

![Image](https://github.com/sartography/spiff-arena/assets/104047049/fbe6754e-1f57-4713-bc06-ba0f052ab3f2)

**Comment by harmeet-status** [comment]
24. This page needs the following content:

Title: Bounty already assigned
Body: You are already assigned to this bounty. If you meant to apply for another bounty, please start a new form.

Button: Start new form

![Image](https://github.com/sartography/spiff-arena/assets/104047049/7500e391-1441-4014-971a-547942905133)

**Comment by harmeet-status** [comment]
25. We don't need this page anymore. Look at 24. and we can just send them back to the main form - start from scratch

![Image](https://github.com/sartography/spiff-arena/assets/104047049/19391f44-4cbd-4ab4-8068-0541b5720f0e)

**Comment by harmeet-status** [comment]
26. Entering the wrong bounty number, doesn't do a validation check, it just let's it though as if it's correct

**Comment by calexh-sar** [comment]
@harmeet-status - 
#12, #13 and #15 are ready for your review.  The url for #12 needs to be updated with the desired link.
Regarding #14, which DMN table are you referring to?

**Comment by calexh-sar** [comment]
@harmeet-status regarding #17, I had to add that Manual Task when the OTP was removed since Guest Link sent needs a single Human Task destination and the flow beyond it can either go to the "Show Not Bounty Issue" Manual Task or the "Show Bounty - Compete Confirmation" User Task or the "Complete Bounty Request" User Task next.

**Comment by calexh-sar** [comment]
@harmeet-status regarding #18, the text can be found in the Instructions of that User Task.

**Comment by calexh-sar** [comment]
@harmeet-status -
Regarding #21, this is an older format and no longer valid.
Regarding #22, this shows additional bounties to which the requestor has been assigned.

**Comment by calexh-sar** [comment]
> 16. Update the process flow to [this](https://app.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Page-1%22%20id%3D%22iAVFmr82_K5mgpOtPOTw%22%3E1Vpbd6M2EP41Pts%2BJAeQwfgxttPNnibntM1puvsogwA1ArlCxPb%2B%2BkogbhZ2SHwheUnQMEJi5puZT4NHYB5vvjK4ih6oj8jIMvzNCCxGljW1HfFXCraFwHScaSEJGfaVrBY84p9ICQ0lzbCP0pYip5RwvGoLPZokyOMtGWSMrttqASXtVVcwRJrg0YNEl%2F6DfR4VUtc2avkdwmFUrmwa6k4MS2UlSCPo03VDBG5HYM4o5cVVvJkjIo1X2qWY99ueu9XGGEp4nwk8uPPQ7wv%2B59P0wSJPT5GR3FwBtTe%2BLV8Y%2BeL91ZAyHtGQJpDc1tIZo1niI%2FlUQ4xqnXtKV0JoCuG%2FiPOtcibMOBWiiMdE3S3WlAvtfRUlSmnGPHRg%2FyUkIAsRP6BnVQYXSEU0RpxtxTyGCOT4pb0PqCATVnq1VcWFMuwbjKye%2BwJJplb6lqbiUjpMOMCBsbDbLFmmq9w4DhFvMktXMGl5xvkvk1CZLaH3HOY%2BuPIooWwEbuQGEswxJMUDlKa4CuV%2FmPhCYytsKSMRcYhJWi4jXqhYqVDV4NB29jrCHD2uYO6TtYj4Lse%2BIMbR5rBrdVeoCa6Klm17uK5jzywDKmrEnWOcyXf2KxZ5B%2FyFJdj2u5qfD37IwbVdDheb5s3FVo1OGDZWz7AZDxk27ifPTX2NPBnSyJaWm3TARzReZulFwt8at%2BN%2Fose%2F2xH%2B7rnCH%2BjmuAAI35sh0Abz77WmGP1o3KknyUE5x4dplO%2F1xOgf963MzpDwH2vwn9MkwEywN0yTvLQWdXLJyhK5wKlHmayoMUpTSR%2BFNaR5jiqdMmqwoJ03BIdi3QWnq9NEFHDaEWX3rKiV8OQ2n2g2%2F4p5lC2FLEsRS2AsTYoEeWcf1KYVpy9PNX1pink2nmICzaqzjHOFYeObZH7YT77wPLQ8JCNLbKOJ4oGZH5jYbaOaulGnHTa1z2ZS55MTENPumYP3OOZCpyP7IHIf5E66EgRO82OPyMVMHvyHhq8F2vCtcsRg8J0MSl2qQUFdJn25i9lkLtdWSWS6ycspgwX0DRZwZLTkU28Yg9uGworihKeNJ%2F8hBTW8xs5udnSbCNH07Z2y%2F2b98WF9bT9tfXFRvGGN38pUR0Da1VKFYF45FUvDkqn5%2BKVqfIQQJ41OR%2BNWZ2zcwyUibTxDxR08ASjEOkhFjH2%2FCB2U4p9wmT9PYlN5VDzcno3sxaEso5qXavKoSh1NHB%2BI8b05ybg2TAu0%2FFR2%2FN6GVs39JYkr2zTt%2BTQIUsS1DHYCBFTh%2FGlr8rRnmmn0iIcoytPXi3K4ryh%2F2JLcQdMvWpLBIOj9CP1GoyfqwaCoL7fZQP2N7yuEy%2B3TJhdlaEX19sAvMUwySPKXTZ%2FzXaayUqjZd5DFCPEvMk4YJejXwaNkt0HQ1XO7bM%2Fd0s%2Byc5pwnOTfTBLK4ty%2BAaFrzXrCDvy9FbzL1m1vBGIbZbSa5biIO8FNTuIOx2i7o29rYXw2bziaN6oW2F7omq9DN8CEzIsPWGIu8CFyA09%2B%2BOKMPqPGHcdz0TLQrH96U191tRwuDP1hD22NolB1ji9UIZy%2BvOjY49dx%2FtFPIB7Bnszzf%2F913%2Bm7T3eosA4fKq6Ma9N02vxfLfneQ8X5zw1gkB867GuGvMa8zvVNBvSlYUd%2FlHlXj8PdycfA2PlFyyv6V66xg50z9CCAzhEfix5E%2FWEIep6ADi%2FiEgcisvOvSd054tJ8z7Yux%2FfEsP6BU%2BGB%2Bmdi4PZ%2F%3C%2Fdiagram%3E%3C%2Fmxfile%3E)

Created #1860 for this update.

**Comment by calexh-sar** [comment]
@harmeet-status regarding #24, we should discuss further once #1727 is completed.

**Comment by calexh-sar** [comment]
@harmeet-status regarding #25, we cannot take them back to the "main form: since that is only accessible during the initial unauth Message Start Event flow.  By this time the bounty hunter is in the Guest Link flow.

**Comment by calexh-sar** [comment]
@harmeet-status regarding #27, this exchange can be found in #979:

![Image](https://github.com/sartography/spiff-arena/assets/54854669/e1d8c5fe-c9e5-4d3f-bf01-dffd524cb28d)

Are you saying now you want to reverse that decision?

**Comment by calexh-sar** [comment]
@harmeet-status regarding #26, I am seeing that a wrong number is getting a validation, both if a valid issue number that does not have a bounty label or if an invalid issue number are entered.

![Image](https://github.com/sartography/spiff-arena/assets/54854669/1a1e4096-ddaf-43ed-9090-4ca85a68b0da)


![Image](https://github.com/sartography/spiff-arena/assets/54854669/3761338b-f540-4723-8ee2-0fd45affa490)

Do you have a specific number you tried that the process "just let's it though as if it's correct"?

**Comment by harmeet-status** [comment]
> [@harmeet-status](https://github.com/harmeet-status) regarding [#17](https://github.com/sartography/spiff-arena/pull/17), I had to add that Manual Task when the OTP was removed since Guest Link sent needs a single Human Task destination and the flow beyond it can either go to the "Show Not Bounty Issue" Manual Task or the "Show Bounty - Compete Confirmation" User Task or the "Complete Bounty Request" User Task next.

If you need that step, let's put the OTP back in.

**Comment by harmeet-status** [comment]
> [@harmeet-status](https://github.com/harmeet-status) regarding [#27](https://github.com/sartography/spiff-arena/pull/27), this exchange can be found in [#979](https://github.com/sartography/spiff-arena/issues/979):
> 
> ![Image](https://private-user-images.githubusercontent.com/54854669/345265690-e1d8c5fe-c9e5-4d3f-bf01-dffd524cb28d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODAyNjEsIm5iZiI6MTcxOTk3OTk2MSwicGF0aCI6Ii81NDg1NDY2OS8zNDUyNjU2OTAtZTFkOGM1ZmUtYzllNS00ZDNmLWJmMDEtZGZmZDUyNGNiMjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA0MTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMWRjZjgyMjRjZDc1Mjk2ZjE0YTlmNzYzZTU5MTA5ZjhlZDNlYzcyNzE2MjVkZTc0ZTM4ODBhMGFlNjMzNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SPsbSsgXx2fiFnJLUo0zJ7RY6ysQGXX3U-aDl7deinw)
> 
> Are you saying now you want to reverse that decision?

Yes reverse decision. Let's check for valid address.

**Comment by harmeet-status** [comment]
> [@harmeet-status](https://github.com/harmeet-status) regarding [#25](https://github.com/sartography/spiff-arena/pull/25), we cannot take them back to the "main form: since that is only accessible during the initial unauth Message Start Event flow. By this time the bounty hunter is in the Guest Link flow.

Ok then, leave as-is. Text change as follows:

Title: Make same as first page of form
Body: Please specify the bounty information below and check the data before entering.

**Comment by harmeet-status** [comment]
> [@harmeet-status](https://github.com/harmeet-status) - Regarding [#21](https://github.com/sartography/spiff-arena/pull/21), this is an older format and no longer valid. Regarding [#22](https://github.com/sartography/spiff-arena/pull/22), this shows additional bounties to which the requestor has been assigned.

For 22. please change heading to: Bounties currently assigned to you

**Comment by calexh-sar** [comment]
@burnettk and/or @jasquat would you please look at #7 and #19 above and let me know if there is anything from a process POV that can be done to address either/both of these concerns.  And if not, should this be written up as one or two issues so they can be addressed elsewhere.

**Comment by calexh-sar** [comment]
@harmeet-status added #1867 to account for time to add the OTP back.

**Comment by harmeet-status** [comment]
> 7. If the user accidently closes the the bounty form, when he tries to open the link again it gives this error.
>    ![image](https://private-user-images.githubusercontent.com/110527567/341312769-2eda9b53-3b65-4bac-b438-5ea81d005d0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzU4MzIsIm5iZiI6MTcyMDA3NTUzMiwicGF0aCI6Ii8xMTA1Mjc1NjcvMzQxMzEyNzY5LTJlZGE5YjUzLTNiNjUtNGJhYy1iNDM4LTVlYTgxZDAwNWQwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQwNjQ1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWM5ODMyYjI0MzY3NzAzOTM0NTg3MjMyYTMxZTkyOTBhMGRiMzY4ZDg5OWMwNDQ5NWE5MmRmMWQ4ZDAyNWQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aAps4aLFReQy25ai0-6QB-2z1XYHKYt2nh94cvqLeBk)
> 
> Shouldn't the user be able to open it again? If we are blocking it on purpose I think we should show a proper message (UI/UX). If we are not blocking it then the user should be able to open the completed form and complete it.

The link should only work 1 time. Otherwise we could have edge case where a user has multiple discord message links which all work - cause the form wasn't submitted for any of them. This is a worse outcome, so let's leave the expiration of link 1 time use, like it is right now - no change.

The error message should be updated to this: https://github.com/sartography/spiff-arena/issues/1752#issuecomment-2201996431

**Comment by harmeet-status** [comment]
Change to following:

Title: Discord account verified
Body: Thank you for verifying the Discord account belongs to you.

Button: Next

![Image](https://github.com/sartography/spiff-arena/assets/104047049/bd3fbd27-6377-4402-95b2-3979ddd0be9c)

**Comment by harmeet-status** [comment]
Change this to:

Title: We hope to see you soon
Body: Feel free to browse and apply for other Spiff Bounties [add link to Github board here].

![Image](https://github.com/sartography/spiff-arena/assets/104047049/66aa01ae-043b-4be4-9f59-f14ca40edf4e)
