### ISSUE TITLE
Custom widgets adjustments for MUI #1842

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#1765]
NOTE: some of our customizations for forms are documented at https://spiff-arena.readthedocs.io/en/latest/Building_Diagrams/Forms.html#spiffarena-react-jsonschema-form-enhancements

NOTE: duplicate help text is being handled in #1726 .

See also related ticket #1727

After the initial run of tests with the MUI theme for user forms, I found that several changes will be required for custom widgets we use in processes to fit the new UI theme.

1. **Typeahead** The widget does not display the field "title", instead it duplicates the "UI:help". Also the design of the element should be updated to the MUI dropdown style

![Image](https://github.com/sartography/spiff-arena/assets/104367255/e0ffe5db-b390-4874-89be-3486fa4c554a)

![Image](https://github.com/sartography/spiff-arena/assets/104367255/4826d11a-a5ad-400d-970c-033fe7300f36)

2. **Date range** The widget does not display the field "title", instead it duplicates the "UI:help". Also the design of the element should be updated to the MUI date style

![Image](https://github.com/sartography/spiff-arena/assets/104367255/f45bbe9f-7d33-4b9f-a30b-137e005fa65f)

3. **Numeric range** The widget does not format the field "UI:description", and it duplicates the "UI:help". Also the design of the element should be updated to the MUI style

![Image](https://github.com/sartography/spiff-arena/assets/104367255/0bcbc10f-fff6-4f15-a652-6916017f2c91)

**Comment by harmeet-status** [comment]
Link to PIA backlog ticket in Notion https://www.notion.so/Try-ui-theme-mui-with-user-forms-5429dc1454154a1cb9abae43ebe3b72e

**Comment by calexh-sar** [comment]
Estimate is for #1 typeahead only.  Remainder will be moved to separate issues and estimated later.
