### ISSUE TITLE
Messages - Deleted correlation properties

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1808]
To test the things from the start I deleted the Correlation properties from these 2 models. Then when I run the models still it shows the correlation keys in the message info like below. 

[unit-test-receive-task-new (1).bpmn.txt](https://github.com/user-attachments/files/15964659/unit-test-receive-task-new.1.bpmn.txt)
[unit-test-send-task-new (1).bpmn.txt](https://github.com/user-attachments/files/15964658/unit-test-send-task-new.1.bpmn.txt)

Please see this video.
https://drive.google.com/file/d/1IhfKgZkGd0YfssP9Xyska1QC2jr6gWd4/view?usp=sharing

And when I check the xml this is still there.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/b7842df3-be7b-48d6-813f-c0ac2eae0b1d)

**Comment by theaubmov** [comment]
Yes, this is also ok, when you create a message and then you add properties, an auto-generated main correlation key will be created. This key will contain all properties present in the process. Next: If you remove the properties, the correlation key will still be there, but it will be empty. I tested this locally, and it shouldn't cause any issues in terms of matching.

The correlation key will not be displayed in the message editor, as it should not be managed by the user.

**Comment by madhurrya** [comment]
But the user will not expect to see something he already deleted. Please check that video. He wouldn't expected to see the Receive data correlation info there as he already delete it.

**Comment by burnettk** [comment]
Very similar to #1810 . Also closing this one for the same reason. We agree that there is a UX issue, but it is behaving as designed.
