### ISSUE TITLE
Messages - Deleting correlation properties in one places doesn't update the other

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1810]
I deleted the correlation property from the send task. But it doesn't get deleted from the Receive task (same message).
But when adding them when I add to the send task, it get automatically added to the receive task which uses the same message. So I expect the same to happen when deleting also.

Please check this video. https://drive.google.com/file/d/1TkNtwGTn_E3w5NSjajZ5kFxH0B6TPJoT/view?usp=sharing

**Comment by madhurrya** [comment]
Also noticed that after deleting the property in the Send task, when I go to the Receive task there's that warning to save it, so I save it. But the properties are not deleted and later when I go back to the Send task I see the property there also again.
Please see this video https://drive.google.com/file/d/1_6tGuxRvO5l7hcRidVzWh97B61cB4zDv/view?usp=drive_link

**Comment by theaubmov** [comment]
the same point: 
https://github.com/sartography/spiff-arena/issues/1812#issuecomment-2188395611

**Comment by burnettk** [comment]
It's expected behavior that if you delete a correlation property in model A, and then you save model B that also uses it, it will come back. We will deal with this UX issue later.
