### ISSUE TITLE
Using Message Start Event Triggers Error

### ISSUE THREAD

**Issue by fharmusial** [sartography/spiff-arena#1836]
If I use a Message Start Event in my BPMN diagram it triggers the following error upon saving:

Error: Could not find messageRef from message event definition: {message_event_definition}.

Reproduction:

- Go to current spiffdemo.org playground
- Add Process
- Change None Start Event to Message Start Event
- Save

**Comment by burnettk** [comment]
thanks for the clear reproduction steps. the UX is not amazing on this feature yet, but it did just improve a little bit.

if you click on a newly-minted message start event, there will be a dropdown in the properties panel on the right, "Which message is this associated with?" There probably won't be anything in the list to select, so you can use the "Open message editor" button to create a message. For a message start event, you just need to enter "Message Name" and hit "Save." Then you can hopefully select that message where it says "Which message is this associated with?" and successfully save your bpmn file.

Thanks for reporting this, and if you're not in discord yet, feel free to pop in over there, https://discord.com/invite/F6Kb7HNK7B. 🙇

**Comment by fharmusial** [comment]
Thanks for the quick reply: I can now indeed save my model! I posted a
follow-up question on Discord!
