### ISSUE TITLE
Messages - Message payload in Pre script

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1842]
Adding this issue https://github.com/sartography/spiff-arena/issues/1626#issuecomment-2160046500 as a separate issue so I can close the above ticket.

If I define the payload in the Prescript of the Send task, it doesn't recognize it. But if I define it in a script task before that then it works. Is that the expected behaviour?

![Image](https://github.com/sartography/spiff-arena/assets/110527567/75047314-18d5-4f07-afdd-c36b81dc1a77)

![Image](https://github.com/sartography/spiff-arena/assets/110527567/7ee6b8cd-df4f-4081-bb79-0897506fdca9)

**Comment by jasquat** [comment]
I'm guessing the pre-script doesn't execute until the task is completed however the message payload needs to be available before the task can complete. I'm not sure what we can do about that.

@essweine does that sound right to you?

**Comment by essweine** [comment]
Fixed in library in https://github.com/sartography/SpiffWorkflow/commit/7e15a0b68f926161bfa88e1306f3145ee028fad4

**Comment by calexh-sar** [comment]
@madhurrya would you pls test this and close if working.

**Comment by calexh-sar** [comment]
Closed per sprint planning discussion.

**Comment by madhurrya** [comment]
Yes, this is fixed now.
Test model : https://mysql.spiffcrm.com/editor/process-models/misc:qa:bpmn-model-testing:unit-test-send-task-new/files/unit-test-send-task-new.bpmn
