### ISSUE TITLE
Spiff bounties process flow update

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#1860]
Update the process flow to [this](https://app.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#R%3Cmxfile%3E%3Cdiagram%20name%3D%22Page-1%22%20id%3D%22iAVFmr82_K5mgpOtPOTw%22%3E1Vpbd6M2EP41Pts%2BJAeQwfgxttPNnibntM1puvsogwA1ArlCxPb%2B%2BkogbhZ2SHwheUnQMEJi5puZT4NHYB5vvjK4ih6oj8jIMvzNCCxGljW1HfFXCraFwHScaSEJGfaVrBY84p9ICQ0lzbCP0pYip5RwvGoLPZokyOMtGWSMrttqASXtVVcwRJrg0YNEl%2F6DfR4VUtc2avkdwmFUrmwa6k4MS2UlSCPo03VDBG5HYM4o5cVVvJkjIo1X2qWY99ueu9XGGEp4nwk8uPPQ7wv%2B59P0wSJPT5GR3FwBtTe%2BLV8Y%2BeL91ZAyHtGQJpDc1tIZo1niI%2FlUQ4xqnXtKV0JoCuG%2FiPOtcibMOBWiiMdE3S3WlAvtfRUlSmnGPHRg%2FyUkIAsRP6BnVQYXSEU0RpxtxTyGCOT4pb0PqCATVnq1VcWFMuwbjKye%2BwJJplb6lqbiUjpMOMCBsbDbLFmmq9w4DhFvMktXMGl5xvkvk1CZLaH3HOY%2BuPIooWwEbuQGEswxJMUDlKa4CuV%2FmPhCYytsKSMRcYhJWi4jXqhYqVDV4NB29jrCHD2uYO6TtYj4Lse%2BIMbR5rBrdVeoCa6Klm17uK5jzywDKmrEnWOcyXf2KxZ5B%2FyFJdj2u5qfD37IwbVdDheb5s3FVo1OGDZWz7AZDxk27ifPTX2NPBnSyJaWm3TARzReZulFwt8at%2BN%2Fose%2F2xH%2B7rnCH%2BjmuAAI35sh0Abz77WmGP1o3KknyUE5x4dplO%2F1xOgf963MzpDwH2vwn9MkwEywN0yTvLQWdXLJyhK5wKlHmayoMUpTSR%2BFNaR5jiqdMmqwoJ03BIdi3QWnq9NEFHDaEWX3rKiV8OQ2n2g2%2F4p5lC2FLEsRS2AsTYoEeWcf1KYVpy9PNX1pink2nmICzaqzjHOFYeObZH7YT77wPLQ8JCNLbKOJ4oGZH5jYbaOaulGnHTa1z2ZS55MTENPumYP3OOZCpyP7IHIf5E66EgRO82OPyMVMHvyHhq8F2vCtcsRg8J0MSl2qQUFdJn25i9lkLtdWSWS6ycspgwX0DRZwZLTkU28Yg9uGworihKeNJ%2F8hBTW8xs5udnSbCNH07Z2y%2F2b98WF9bT9tfXFRvGGN38pUR0Da1VKFYF45FUvDkqn5%2BKVqfIQQJ41OR%2BNWZ2zcwyUibTxDxR08ASjEOkhFjH2%2FCB2U4p9wmT9PYlN5VDzcno3sxaEso5qXavKoSh1NHB%2BI8b05ybg2TAu0%2FFR2%2FN6GVs39JYkr2zTt%2BTQIUsS1DHYCBFTh%2FGlr8rRnmmn0iIcoytPXi3K4ryh%2F2JLcQdMvWpLBIOj9CP1GoyfqwaCoL7fZQP2N7yuEy%2B3TJhdlaEX19sAvMUwySPKXTZ%2FzXaayUqjZd5DFCPEvMk4YJejXwaNkt0HQ1XO7bM%2Fd0s%2Byc5pwnOTfTBLK4ty%2BAaFrzXrCDvy9FbzL1m1vBGIbZbSa5biIO8FNTuIOx2i7o29rYXw2bziaN6oW2F7omq9DN8CEzIsPWGIu8CFyA09%2B%2BOKMPqPGHcdz0TLQrH96U191tRwuDP1hD22NolB1ji9UIZy%2BvOjY49dx%2FtFPIB7Bnszzf%2F913%2Bm7T3eosA4fKq6Ma9N02vxfLfneQ8X5zw1gkB867GuGvMa8zvVNBvSlYUd%2FlHlXj8PdycfA2PlFyyv6V66xg50z9CCAzhEfix5E%2FWEIep6ADi%2FiEgcisvOvSd054tJ8z7Yux%2FfEsP6BU%2BGB%2Bmdi4PZ%2F%3C%2Fdiagram%3E%3C%2Fmxfile%3E)

Updates include:

- Add GitHub Rest API User Resource
- Update workflow as shown in the linked diagram

**Comment by calexh-sar** [comment]
@harmeet-status is this step in your diagram

![Image](https://github.com/sartography/spiff-arena/assets/54854669/16bbff9c-0745-4919-9bdf-cbc039619531)

to be completed by the same users who approve/reject the bounty request or should this be a new lane?

**Comment by harmeet-status** [comment]
> @harmeet-status is this step in your diagram
> 
> ![Image](https://private-user-images.githubusercontent.com/54854669/345264132-16bbff9c-0745-4919-9bdf-cbc039619531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5ODA1NjAsIm5iZiI6MTcxOTk4MDI2MCwicGF0aCI6Ii81NDg1NDY2OS8zNDUyNjQxMzItMTZiYmZmOWMtMDc0NS00OTE5LTliZGYtY2JjMDM5NjE5NTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA0MTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1Yzk4ZTZlZTI1ODE1YWRkNzllOWMxYmUxYzZjNDczZDdhMTIzZDc2M2MxNmQxMTM1M2UxYjFhMDNjMmZhZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FIFn3AkPmXhcvNX7svOEAvDLRv3Q6Jk99Q_neW_rOLw)
> 
> to be completed by the same users who approve/reject the bounty request or should this be a new lane?

Correct.
