### ISSUE TITLE
dev.mod - Error when terminating an instance

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1861]
Getting this error when trying to terminate instances.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/bda2b1f4-7bf0-4db4-92d2-4ee01dc8ec1c)

I don't get that error for this simple model
https://dev.mod.spiff.status.im/process-models/misc:qa:forms:simple-form-name-age

But it happens for Status models like PP1, PP2, Expense report

Update : This seems to happen in dev.app also

**Comment by jasquat** [comment]
From slack conversation:
```
[07:49]
Elizabeth Esswein
 I can't see the diagrams in 1530 butin 1861, you can fix this error by putting an exclusive gateway before the two inputs to 'Get Name'.

07:53
Madhurya
 In 1861 there's no issue with the models. That error happens when terminating the instances. I think something introduced with the latest code.
07:55
Elizabeth 1530 and 1861 are not related to the BPMN things I mentioned above :slightly_smiling_face:

[07:56]
Elizabeth Esswein
 Often models with direct inputs to tasks get this recursion error (I guess it doesn't happen in this case because of the boundary event.
07:58
"Maximum recursion depth" errors are frequently caused by having two inputs to a task without an intervening gateway.
```

**Comment by madhurrya** [comment]
@jasquat Terminate was working fine earlier. This started happening after the latest code update. So it can't be related to a model issue I guess?
It works fine this model https://dev.mod.spiff.status.im/process-models/misc:qa:forms:simple-form-name-age
Issue is with Status models. It was working fine for them earlier. This happens in dev.app also. So not a celery related thing I guess.
