### ISSUE TITLE
Please document restrictions in python usage in SpiffArena

### ISSUE THREAD

**Issue by fharmusial** [sartography/spiff-arena#1882]
Spiffarena targets citizens developers amongst others through possibility to use easy-to-learn python in script tasks, pre-post scripts etc.

The documentation mentions restrictions on python usage in spiffarena, but does not specify these restrictions themselves.

In my humble opinion, both starting and seasoned developers will be less confused when restrictions in python usage are documented (could even be just a faq entry).

This is what i learned so far:

* Keywords and operands can be used without restrictions

* SpiffArena uses RestrictedPython under the hood that whitelist 'safe names' for builtins

https://github.com/zopefoundation/RestrictedPython/blob/master/src/RestrictedPython/Guards.py#L27C5-L28C7 

* SpiffArena extends this whitelist with additional 'global names' (builtins and even modules)

https://github.com/sartography/spiff-arena/blob/main/spiffworkflow-backend/src/spiffworkflow_backend/services/process_instance_processor.py

* Despite the above the 'not JSON serializable' error sometimes kicks in (not only with sets) with no reference to this in faq

I know scripts etc. are intended for things for simple tasks, but nonetheless it would help (citizen) developers to know what the limits are before they are discouraged by unexplainable errors during proces model implementation. If documentation does become available then the related error messages perhaps even could refer to it directly.

**Comment by burnettk** [comment]
good idea, and thanks for helping with the research!

https://spiff-arena.readthedocs.io/en/latest/Building_Diagrams/Script_Tasks.html#what-can-you-do-and-not-do-in-script-tasks
https://spiff-arena.readthedocs.io/en/latest/Support/FAQ.html#not-json-serializable-error-in-script-task
