### ISSUE TITLE
PI Migration - Data input/output deletion

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1910]
In this model https://timetracking.spiffworkflow.org/process-models/misc:qa:madhu-testing:data-input-output I had 2 data inputs and outputs like below.

![Image](https://github.com/user-attachments/assets/4345f9e8-05e3-4034-a9dd-735791335258)

I deleted the 'DataObject1' data input and migrated the instance.

This is the instance after migration https://timetracking.spiffworkflow.org/i/6241

Even though that Data input is not here, in the task data (inside the call activity) it is still there.

![Image](https://github.com/user-attachments/assets/a03af340-a8f7-4f76-8e50-473a75e1e3b5)

![Image](https://github.com/user-attachments/assets/302a7bf7-62da-4b1e-b0eb-7c4a2a1eeff6)

But when I run another process instance without any migration (after the above deletion) it doesn't have the deleted data input in the task data e.g. https://timetracking.spiffworkflow.org/i/6242

![Image](https://github.com/user-attachments/assets/c66de3ef-3689-450b-80ea-8abd4e1271c5)

**Comment by madhurrya** [comment]
@jasquat I deleted the Datainput before the Call activity got called. When it was in this manual task. So the variable shouldn't be inside the call activity. 
![image](https://github.com/user-attachments/assets/8b7afa17-4d41-483b-918f-b7c1af371248)

**Comment by jasquat** [comment]
thanks for the clarification @madhurrya. that does seem wrong then.

**Comment by jasquat** [comment]
@madhurrya  are you sure? I'm not replicating and according to the events, the StartEvent in the call activity was completed before the migration happened: https://timetracking.spiffworkflow.org/process-instances/misc:qa:madhu-testing:data-input-output/6241?tab=2

**Comment by madhurrya** [comment]
@jasquat I couldn't recreate it today. So I might have changed it after the call activity was started.
So I'll close this issue.
