### ISSUE TITLE
PI Migration - revert

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1919]
When I try to revert this instance it gives this error/warning.
I am not sure why.

https://timetracking.spiffworkflow.org/i/6277

![Image](https://github.com/user-attachments/assets/64c3669f-577b-4ab7-b8f1-575771c85cd2)

**Comment by jasquat** [comment]
@madhurrya this happens if you completed tasks after the initial migration and then attempt to revert. It's just like trying to migrate an instance where the model has updated a previously completed task.

**Comment by madhurrya** [comment]
@jasquat do you mean if any tasks get completed we can't revert? I thought we should be able to revert to any point at any time if we didn't change anything in those tasks after the migration.

**Comment by jasquat** [comment]
Yes. If any tasks are completed AFTER the point of the migration then you cannot revert. To the system, it's the same thing as modifying a task in the process model before the current task and then trying to migrate the instance.

**Comment by madhurrya** [comment]
@jasquat so if any of the completed tasks have been updated (migrated) then we'll not be able to revert it. 
But if none of the completed tasks have been updated (only some tasks that are not yet completed have been updated/migrated), in that case we can revert until a migrated task get completed.
Is that correct?

**Comment by madhurrya** [comment]
As mentioned in the above PR, now the Revert button is hidden, if that cannot be reverted.


![Image](https://github.com/user-attachments/assets/df50bfce-3ac2-4b40-a7e7-e906355c285e)

**Comment by madhurrya** [comment]
In this instance - https://sample.spiffcrm.com/i/1029 I have added some Instructions to the 'Get Data' task and migrated it while in that task. Then when I moved to the next task 'Show Data', I can still revert it. But I guess I shouldn't be able to revert it since I completed a task which had migration.

If I move to the next task 'Review' and if I try to revert, the Revert button is hidden.
If I just changed the name of the 'Get Data' task instead of instructions and migrated then in the 'Show Data' task I can't revert it. But not sure why when instructions are changed that I am able to revert it there.


![Image](https://github.com/user-attachments/assets/07e645b1-1d5b-4fd2-8ca8-c0a2eb70e24d)

**Comment by jasquat** [comment]
@essweine since instructions are in extension properties are they omitted from the migration check?

**Comment by essweine** [comment]
This should work -- the raw text is stored on the task.  The problem seems to be that the extensions don't get added in `to_dict`.  The serializer adds them later.  This is because they aren't arguments to the task spec's constructor, due to the fact that the parser creates the task before it can parse the extensions.  So fixing this will involve a serializer change.

**Comment by essweine** [comment]
This commit should ensure the extensions are available when the task is serialized: https://github.com/sartography/SpiffWorkflow/commit/c45ab5ec322081d0a6e3d785213260a03af9c820

**Comment by madhurrya** [comment]
Above issue is fixed now.
