### ISSUE TITLE
PI Migration - Multi Instance

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1920]
While in this manual task Multi instance I changed some MI properties and tried to migrate.
Then got this error.

https://timetracking.spiffworkflow.org/i/6284

![Image](https://github.com/user-attachments/assets/bb2548b2-8429-42b1-adae-31320630d821)

![Image](https://github.com/user-attachments/assets/b432fd28-5630-4bcd-93c0-60b5256821de)

**Comment by madhurrya** [comment]
Same happens with a user task also 



![Image](https://github.com/user-attachments/assets/d07c1537-ffe3-41e3-8eac-887d5171c803)



![Image](https://github.com/user-attachments/assets/90edf0d0-ec38-47a8-be4a-1bf32e0643b8)

**Comment by madhurrya** [comment]
Same happens with loop also



![Image](https://github.com/user-attachments/assets/b8134671-4742-4f07-b1ec-4dc42880af3c)

**Comment by jasquat** [comment]
@essweine I think it's trying to look up the child task but can't find it in the alignments: https://github.com/sartography/SpiffWorkflow/blob/main/SpiffWorkflow/bpmn/util/diff.py#L133

This is happening when calling `diff_workflow` from https://github.com/sartography/spiff-arena/blob/main/spiffworkflow-backend/src/spiffworkflow_backend/services/process_instance_service.py#L196.

**Comment by jasquat** [comment]
This should be fixed in main with update to https://github.com/sartography/SpiffWorkflow/commit/3c7da30f3ee5283fd557d9e73c5f1e6652bb87aa

**Comment by madhurrya** [comment]
Above error seems to be fixed now. But If I change something in the Multi instance properties while in that task, it doesn't allow me to migrate. I am not sure why. Is that the expected behaviour?
E.g https://sample.spiffcrm.com/i/1035



![Image](https://github.com/user-attachments/assets/5190fd38-1d98-4108-828d-65e4c57a770c)

**Comment by essweine** [comment]
This is expected -- once a task starts, it can't be migrated, and MI task has been started.

**Comment by madhurrya** [comment]
@jasquat @essweine @burnettk  for all the other tasks the migration works when that task is started. It doesn't work only for MI tasks. Even the loop task also works. 
So we'll document it won't work for MI tasks when it's started?

**Comment by essweine** [comment]
User, manual, etc tasks -- they're ready or waiting.  The loop task actually should not work either.  If it is in fact letting you migrate it, that is a bug.

**Comment by madhurrya** [comment]
@essweine Ok. I guess that status you mentioned is something we can't see from the UI? Because when I check a MI task and a User task, in both what I see is 'user_input_required' state.
![image](https://github.com/user-attachments/assets/880e46cf-e401-4317-84cf-b6a817c06a4f)
![image](https://github.com/user-attachments/assets/fcb1d5c4-b365-4d29-a3ea-ffbb187c0928)

On the loop task, if I add/change something in the pre/post scripts of the loop task, I can migrate it. But if I change the Loop Maximum value then it doesn't allow me to migrate. For the MI even if I change the pre/post scripts it doesn't allow to migrate.
So do you think for the loop task also it should be the same?

**Comment by essweine** [comment]
Yes, it should be the same.  There is probably some inconsistency how they're serialized (the migration tool uses serialized versions to compare).  I'll see if I can figure out why.

**Comment by madhurrya** [comment]
@essweine Ok Thanks. May be pre scripts/post scripts are not working for loop tasks? Eventhough I have set pre/post scripts like this those values doesn't seem to change. 
![image](https://github.com/user-attachments/assets/4e95c698-0931-4067-bdb0-16a83e125352)

**Comment by essweine** [comment]
Thanks.  That's very useful.  Might actually be a parser issue (maybe they're never even parsed at all).

**Comment by essweine** [comment]
Turned out to be a serializer issue.  This should be fixed by https://github.com/sartography/SpiffWorkflow/commit/c62a76d121567e6265e2bf3ae1b817be78f4f397

**Comment by madhurrya** [comment]
Now the loops also can't be updated and migrated when active.
