### ISSUE TITLE
PI Migration - Milestones duplicated

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1928]
It seems when we migrate an instance the  milestones get duplicated.

https://sample.spiffcrm.com/i/42

![Image](https://github.com/user-attachments/assets/4604b7ef-4352-44c6-83dc-29667018ff43)

**Comment by jasquat** [comment]
Oh yeah, we are apparently duplicating all events on migration it seems. We probably shouldn't do that. It looks like we are calling `did_complete_task` although that is a little unexpected. We will need to look into why that is getting called.

**Comment by madhurrya** [comment]
This is fixed now
