### ISSUE TITLE
PI Migration - when current activity's name is updated

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1945]
This currently active task's name was 'Manual Task 2222'. I changed it to 'Manual Task 2' and migrated it. In the diagram and when I go to the task it shows the updated name. But under 'Tasks I can complete' it shows the old name.

https://sample.spiffcrm.com/i/1058

![Image](https://github.com/user-attachments/assets/78acffc3-fb82-492a-98b7-64a9420c6114)

**Comment by jasquat** [comment]
"Tasks I can complete" is probably using the cached task info on the human task. We haven't been updating human tasks at all. I'm thinking this would affect all task list tables.

**Comment by madhurrya** [comment]
If you were referring to tables like process instance table, yes there also it shows the old one. 
![image](https://github.com/user-attachments/assets/75c685d7-e0af-46a7-884e-4ae81a15dd3a)

**Comment by madhurrya** [comment]
This is fixed now.
