### ISSUE TITLE
Call activity from another call activity - Error

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1951]
When I call another call activity from a Call activity when I run that model, it gives this error.
Model : https://sample.spiffcrm.com/process-models/misc:qa:madhu-testing:call-activity-test-1

![Image](https://github.com/user-attachments/assets/63b3ccd9-cd41-4527-99ce-0bbc24ab8dcc)

**Comment by jasquat** [comment]
If I add a manual task before the second call activity then it works. I guess the issue is that if a call activity calls a process that immediately calls another call activity, then it fails. We must be not saving something at the right time.

**Comment by madhurrya** [comment]
This issue seems to be fixed now.
