### ISSUE TITLE
Inclusive Gate way - 'maximum recursion depth exceeded' error

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1955]
It gives this  'maximum recursion depth exceeded' error in this inclusive gateway. 

[inclusive-gateway-error.bpmn.txt](https://github.com/user-attachments/files/16313675/inclusive-gateway-error.bpmn.txt)

This looping back seems to cause that error. 

![Image](https://github.com/user-attachments/assets/b5af7beb-0e09-4db7-b79c-53fca457004e)

**Comment by essweine** [comment]
Fixed in https://github.com/sartography/SpiffWorkflow/commit/8e000c0f52433a868742482da97abcd395d27dfc

**Comment by burnettk** [comment]
arena PR at https://github.com/sartography/spiff-arena/pull/1958

**Comment by calexh-sar** [comment]
Closed per sprint planning discussion.
