### ISSUE TITLE
PI Migration - New Activity skipped

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1961]
Please check this instance. https://sample.spiffcrm.com/i/1204

Model : https://sample.spiffcrm.com/process-models/misc:qa:madhu-testing:call-activity-test-1

Here I updated the MMM task and added DDD task and migrated.  The MMM task updates were shown when running but the DDD was not executed.

![Image](https://github.com/user-attachments/assets/d7902eef-92d0-41ae-b157-6007f4252b35)

**Comment by madhurrya** [comment]
@jasquat the fix you have added mentions about sub processes. Does that apply to call activities also? Because the above model didn't have any sub processes. Only call activities.

**Comment by burnettk** [comment]
yeah, when we were digging into it, we realized that subprocesses replicated just like call activities, so we simplified it down to a minimal repro with subprocesses, but the fix should equally apply to call activities.
