### ISSUE TITLE
PI Migration - Revert missing

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1962]
These are the steps I followed.

1. Model had just one manual task like this and I started it.

![Image](https://github.com/user-attachments/assets/8b061c4a-e98a-4892-9f95-b81c692223c1)

2.  Then added Manual Task 2 and migrated

![Image](https://github.com/user-attachments/assets/f8195d7d-aaa7-4037-8ef1-d168d77b62dc)

3.  Then Reverted it

4. Then Updated Manual Task 2 and Added Manual Task 3 and migrated.

![Image](https://github.com/user-attachments/assets/f3aa6dbd-8292-4bcd-ab45-11c50620f982)

5.  Then completed the first task 

![Image](https://github.com/user-attachments/assets/026b6cc2-4e96-49d5-89a5-f710aa9cb7db)

now it's here

![Image](https://github.com/user-attachments/assets/4b68c71e-5ef3-401c-b3b4-d0fc4f323c8b)

6.  Now when I check the Migrate page the Revert button is not visible for the last migrate entry. Why is that?

![Image](https://github.com/user-attachments/assets/196c5044-478b-47d7-a78f-b24bdae47510)

Instance : https://sample.spiffcrm.com/i/1233
Model :  https://sample.spiffcrm.com/process-models/misc:qa:madhu-testing:test-revert-2

**Comment by jasquat** [comment]
I think this is correct. At git revision `ff607e88` `Manual Task 222` was not in the xml so you cannot revert back to it since that task is now `READY`.

**Comment by madhurrya** [comment]
@jasquat yeah that's correct. I'll close this.
