### ISSUE TITLE
Call Activity Instance diagram related error

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#1963]
In the Process instance diagram, when I click on a Call activity which has not completed/started yet and click on 'View Call Activity Diagram' , it gives an error like below saying 'Cannot find a bpmn process with guid '060396db-d2e3-4ac7-81bd-944546f80ac4' for process instance '1238''. Is it because that instance has not started yet so there's no diagram to show yet? If so is that error message meaningful to the user?

![Image](https://github.com/user-attachments/assets/763cbe6c-dbfe-4c94-a0a2-fdfb50e2db92)

![Image](https://github.com/user-attachments/assets/5d9ab90a-8517-4aba-a961-b3362e571322)

**Comment by jasquat** [comment]
Yeah that makes sense. So the CallActivity Task exists so it has a guid, but that guid isn't linked to a bpmn process yet so we get that error. We probably shouldn't even show that link if the bpmn process doesn't exist yet. As a shortcut we could check status like `FUTURE`, `LIKELY`, `MAYBE`.

**Comment by madhurrya** [comment]
Now the ' 'View Call Activity Diagram' option is hidden if the Call activity is not active/completed yet.

**Comment by burnettk** [comment]
Yeah, this was the fix we put in.
