### ISSUE TITLE
Errors during model implementation are displayed differently for different properties

### ISSUE THREAD

**Issue by fharmusial** [sartography/spiff-arena#1965]
**Description:**

Errors during model implementation are displayed differently for different properties.

e.g. 
- an undefined variable in a pre/post script displays an immediately visible error once executed
- the same undefined variable in a pre/post script does not display anything and the evidence for an error can only be found by examining process instances events for this specific model.

Why can't both errors be apparent immediately after starting the flawed model implementation?

**Reproduction steps**

error in pre-script:
- create a new model 
- put 'print(non_defined.data)' in the pre-script property of the manual task
- start the model: see undefined error immediately

error in instruction:
- create a new model
- put '{{ non_defined.data }}' in the instruction property of the manual task
- start the model: no indication of any error, but jumps back to home screen 
- processes -> model -> my process instances -> click on the lates process instance id reveals an error 
- events -> click on 'event type' of event id with error reveals the the cause (undefined error)

**Comment by burnettk** [comment]
hi, @fharmusial , i think there might be something else going on with the "error in instruction" model.

can you try this BPMN? the process instance completes successfully for me and there is no error in events. for instructions, when you have an error in jinja (`{{ }}`), it simply doesn't print anything. maybe attach your model if you are seeing something different and want us to try it? i'm going to close this for now, but feel free to respond and/or re-open.

````xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:spiffworkflow="http://spiffworkflow.org/bpmn/schema/1.0/core" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_96f6665" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="3.0.0-dev">
  <bpmn:process id="Process_err_instructions_idhuy3b" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1">
      <bpmn:outgoing>Flow_17db3yp</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:sequenceFlow id="Flow_17db3yp" sourceRef="StartEvent_1" targetRef="Activity_0qpzdpu" />
    <bpmn:endEvent id="EndEvent_1">
      <bpmn:incoming>Flow_12pkbxb</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="Flow_12pkbxb" sourceRef="Activity_0qpzdpu" targetRef="EndEvent_1" />
    <bpmn:manualTask id="Activity_0qpzdpu" name="Example manual task">
      <bpmn:extensionElements>
        <spiffworkflow:instructionsForEndUser>look at this before
{{ non_defined }}
look at this after</spiffworkflow:instructionsForEndUser>
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_17db3yp</bpmn:incoming>
      <bpmn:outgoing>Flow_12pkbxb</bpmn:outgoing>
    </bpmn:manualTask>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_err_instructions_idhuy3b">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1">
        <dc:Bounds x="179" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Event_14za570_di" bpmnElement="EndEvent_1">
        <dc:Bounds x="432" y="159" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Activity_0zqotmb_di" bpmnElement="Activity_0qpzdpu">
        <dc:Bounds x="270" y="137" width="100" height="80" />
        <bpmndi:BPMNLabel />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="Flow_17db3yp_di" bpmnElement="Flow_17db3yp">
        <di:waypoint x="215" y="177" />
        <di:waypoint x="270" y="177" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNEdge id="Flow_12pkbxb_di" bpmnElement="Flow_12pkbxb">
        <di:waypoint x="370" y="177" />
        <di:waypoint x="432" y="177" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
````
