### ISSUE TITLE
Set Permissions / Multi-Instance Support

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#1980]
From Slack post:
For development, it makes a lot of sense for process model changes to be stored on the file system, so that they can easily be pushed into a repo. In a non-dev deployment where you have replication, FS-based solutions are significantly less awesome. This comes up primarily in the "Set Permissions" flow. It would be great if there was an option to store DMN content in the database (or S3?) so that we could make a change to group membership without needing to do a new release. Or perhaps there is (or should be) a different way to manage users and groups?

**Comment by burnettk** [comment]
proposing to consider this work unnecessary given the implementation of #1983 and using user group information from keycloak/openid.
