### ISSUE TITLE
Adding new users to in-flight instances

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#1981]
From Slack post:
Thinking along similar lines as instance upgrades, how difficult would it be to recreate the list of users that can perform tasks on an in-flight workflow? Our current understanding is that updates to group permissions don't propagate to in-flight process instances. It would be useful if the list of eligible users could be refreshed/rebuilt when group membership changes.

**Comment by madhurrya** [comment]
There's a slash in front of the group name. Is it added purposely? 

![Image](https://github.com/user-attachments/assets/04f32939-ac9d-4a4d-ac8e-debf77b5297b)

**Comment by madhurrya** [comment]
I have added 3 users to the security group like this. But when I login from admin, I don't see the Security group for him. And when I call the get_group_members() it returns only the Madhu user.
You can check with this. https://keycloak-open-id.spiffcrm.com/process-models/misc:madhu-testing:get-current-approvers


![Image](https://github.com/user-attachments/assets/3739ed16-9f0c-4e04-abb5-08b13c608ca7)

**Comment by jasquat** [comment]
admin seems to be in the `/Security` group now. I also logged in as jon and he is now appearing in the group as well.

I guess keycloak is returning a slash in the group names. We store the group exactly as keycloak gives it so this is correct.

**Comment by madhurrya** [comment]
I removed admin from the security group. But when I login to admin I still see the /Security group in the home page. Does the keycloak updates take time? Is that the reason for the above issue I mentioned and this one?
![image](https://github.com/user-attachments/assets/826e9db3-3f8a-4943-89cb-00ddd2163f86)

![image](https://github.com/user-attachments/assets/b2af6c7a-6c68-4fd3-a45f-5ffcdc2b9699)

**Comment by madhurrya** [comment]
madhu3 user had 3 instances assigned for Infra like this.
![image](https://github.com/user-attachments/assets/39946746-062b-4759-a4c9-d33051327b70)

Instance 25 was created after the madhu3 user was created assigned to the Infra group. Other 2 instances were created before that.

When the user competed the 'Show Data' task in instance 25 the 'Review' task get assigned as expected.
But when the user completed  'Show Data' task in instance 24 the 'Review' task doesn't get assigned to that user.

![image](https://github.com/user-attachments/assets/3024f25f-0baf-45eb-9a75-0e600fed765f)

But if I login from another user who was there before these instances were created, that user can see the 'Review' task for both instances as expected under the Infra group.
![image](https://github.com/user-attachments/assets/d98fa7e1-d3ce-4334-99a8-90d2e373c970)

This is the model I used for testing - https://keycloak-open-id.spiffcrm.com/process-models/misc:qa:madhu-testing:lane-test-2

**Comment by jasquat** [comment]
The proceeding tasks should get assigned if the user is still in the group. will look into this.

**Comment by jasquat** [comment]
Repro'd both issues - removing a group from a user and the next task not getting assigned to the user. Will fix.

**Comment by jasquat** [comment]
Fixes are in #2025 

Removing a user from a group when they have no groups left should be fixed now.

The other fix however is a little different. The bug was actually that the process model was using the `lane_owners` variable. When this happens, a user added to a group should NOT be added to tasks within a lane defined in the variable. We fixed that so the user new user will not be able to complete any of the tasks now.

**Comment by madhurrya** [comment]
- Adding/Removing users work as explained above (user get added/removed from the group after he logout and login again)

- When users are assigned to a group (without using lane_owners) it works as expected. Tested with this model https://keycloak-open-id.spiffcrm.com/process-models/misc:qa:madhu-testing:lane-test-3
![image](https://github.com/user-attachments/assets/ac10ad35-658e-4b14-aa1d-721e00e2518f)
![image](https://github.com/user-attachments/assets/cc34f099-6fbe-4470-a9d5-c8a7d65e9af3)


- When users are assigned using lane_owners (without using groups) it works as expected. Tested with this model  https://keycloak-open-id.spiffcrm.com/process-models/misc:madhu-testing:lane-test-1
![image](https://github.com/user-attachments/assets/3e4af491-de19-4357-b764-399bd1bc7f8e)
![image](https://github.com/user-attachments/assets/b33bba88-ab2c-4360-ad04-5c736d72fd12)

**Comment by madhurrya** [comment]
But if the  `lane_owners` are set the keycloack group I am not sure how it should work and whether it works correctly currently.
![image](https://github.com/user-attachments/assets/cfb04962-a97e-4be8-b2a9-49dfba8a34e9)
When it is set like above, the users already in /Infra group see the instance under /Infra
![image](https://github.com/user-attachments/assets/b9b534e1-e6ce-4f78-ab6c-6be768c16086)

But if I assign a new user to /Infra and login from that user, that instance doesn't show for that user.

And if an existing /Infra user who had an instance assigned to him under /Infra, go removed from Infra group. Then when he logout and login he sees that instance under 'waiting for me'
![image](https://github.com/user-attachments/assets/267dc1a7-773a-4faa-be23-258bb87a8ed7)

Model used for testing these scenarios - https://keycloak-open-id.spiffcrm.com/process-models/misc:qa:madhu-testing:lane-test-2

**Comment by jasquat** [comment]
@madhurrya this would be expected. When `lane_owners` is used then it wins with whatever list it had at the time it was set. Changing user groups will not affect who is assigned those tasks.

**Comment by madhurrya** [comment]
@jasquat OK. But as I mentioned in the second part, when I remove a user from the group and when he logs back in, why does he see that instance under 'waiting for me'? Is that also expected?

**Comment by jasquat** [comment]
@madhurrya if you look in task data, is the user in the `lane_owners` list? If so then this user will always be assigned to the task no matter what changes in groups.

**Comment by madhurrya** [comment]
@jasquat Yes I see that user under lane_owners. But as I mentioned in the description above, initially the user had the instance under /Infra. Only when he was removed from the group it came under 'waiting for me'.
https://keycloak-open-id.spiffcrm.com/i/56

For example all the users in the /infra group see this instance 56 under /infra (all these users are set as lane_owners too).
![image](https://github.com/user-attachments/assets/9a8c7e5d-66a5-418e-ba7f-8d37df841255)

This user (madhu3) also had it under /infra until that user got removed from /infra.
Now it is under 'waiting for me' for that user.
![image](https://github.com/user-attachments/assets/528169a4-8fa5-40d4-ae0f-450902df8326)

Is that the correct behavior or should all the users see it under 'waiting for me' from the beginning instead of seeing it under /Infra?
Test model : https://keycloak-open-id.spiffcrm.com/process-models/misc:qa:madhu-testing:lane-test-2

**Comment by jasquat** [comment]
Ah thank you. I see what you mean. The instance moved from appearing under the group table to appearing under waiting for me. Yeah this is probably how it would work. Those queries are complicated and a little unintuitive but this is probably how it would work. As long as the instance appears in one of those tables then it should be good.

**Comment by madhurrya** [comment]
Ok, then I think everything works as expected.

Attaching the 3 models used for testing in case if needed later.
[lane-test-3.bpmn.txt](https://github.com/user-attachments/files/16499450/lane-test-3.bpmn.txt)
[lane-test-2.bpmn.txt](https://github.com/user-attachments/files/16499451/lane-test-2.bpmn.txt)
[lane-test-1.bpmn.txt](https://github.com/user-attachments/files/16499453/lane-test-1.bpmn.txt)
[review-form-schema.json](https://github.com/user-attachments/files/16499462/review-form-schema.json)
[get-item-info-schema.json](https://github.com/user-attachments/files/16499464/get-item-info-schema.json)
[review-form-uischema.json](https://github.com/user-attachments/files/16499465/review-form-uischema.json)
[get-item-info-uischema.json](https://github.com/user-attachments/files/16499466/get-item-info-uischema.json)
