### ISSUE TITLE
Some other RBAC

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#1983]
From Slack post:
Alternately to #1980 and #1981, how possible might it be to not manage group membership in Spiff and instead rely on group memberships established by JWT scopes/claims? If this isn't super-difficult, it could be pretty valuable.

See SPIFFWORKFLOW_BACKEND_OPEN_ID_IS_AUTHORITY_FOR_USER_GROUPS and the original PR, #457

**Comment by madhurrya** [comment]
If I run set permission, it seems the keycloak user groups goes missing from the users' home page.
For example this user's home page was like this.


![Image](https://github.com/user-attachments/assets/3a3a4486-4638-46e5-aa5d-9f6d8411e1fb)

Then I ran set permissions. Now it looks like this.


![Image](https://github.com/user-attachments/assets/133c7496-f9c6-4a21-905e-84b401a1edee)


If I logout and login again, then I see the groups again.

**Comment by madhurrya** [comment]
If I set some groups to a user in the users to group dmn file, should those groups appear in that user's home page? Or are we overwriting it and we are only showing the groups from keycloak?


![Image](https://github.com/user-attachments/assets/92f9ce4f-0593-40d6-99be-ec2b80b38b1a)

**Comment by jasquat** [comment]
@madhurrya yeah, we need to update set-permissions to pass in some certain args so the groups assignments are not removed.

And yes, if groups are coming from keycloak then the user to group dmn file will not work. It should be omitted on envs where keycloak is handling groups.

**Comment by jasquat** [comment]
@madhurrya I added this process model to demonstrate how set-permissions should be when using open id server for groups: https://keycloak-open-id.spiffcrm.com/process-models/site-administration:set-permissions-groups-only. Use this one for testing this feature.

**Comment by madhurrya** [comment]
When the https://keycloak-open-id.spiffcrm.com/process-models/site-administration:set-permissions-groups-only permission is run the above mentioned issue doesn't happen.

**Comment by madhurrya** [comment]
Might not be related to this but thought of mentioning. Even when we delete a user from keycloak, that user can continue to work on spiff until he logs out from the system. Is that going to cause any issue or is that how it works?

**Comment by jasquat** [comment]
This is unrelated but interesting. Same thing happens if you manually kill a user's session. When the token expires it would also figure itself out the same way logout does. This is because the token is valid until it expires which I think is standard practice for jwt's.
