### ISSUE TITLE
Authorized Party Check does not make sense

### ISSUE THREAD

**Issue by pitwegner** [sartography/spiff-arena#2077]
In the spiff backend authentication service, the "azp" of the jwt is checked to match the client id of spiff itself. See [authentication_service.py#L377](https://github.com/sartography/spiff-arena/blob/ca88178700ed96a28f29eecb1726c2c6ec58d665/spiffworkflow-backend/src/spiffworkflow_backend/services/authentication_service.py#L377)
However, this check does not make sense in case of an exchanged token. My user logs in via a different service and then my backend performs a token exchange for the spiff client in order to talk to the API. The audience check should suffice, as the authorized party may legitimately be another client.

**Comment by burnettk** [comment]
@pitwegner i think you're right, but since this is security-related, i'm wondering how you feel about specifying a `SPIFFWORKFLOW_BACKEND_OPEN_ID_ADDITIONAL_VALID_CLIENT_IDS=whateveryourazpendsupbeing` instead.

i think this might fix your issue and it potentially feels like a good solution, but since you submitted the issue, what do you think? just kill the check? thanks.

**Comment by pitwegner** [comment]
I did think about using that option. However, SPIFF is deployed in a highly dynamic micro service architecture for us. So new services (and hence new Keycloak clients) might be able to exchange tokens for SPIFF. The rules, whether the exchange is allowed or not is handled in Keycloak policies, so security should be fine when disabling the check. At least in our case...

**Comment by pitwegner** [comment]
As a workaround, I could write an api wrapper to simply exchange the token once more for itself and then forward the API call to the actual API.

**Comment by burnettk** [comment]
Thanks for that context. I’m inclined to remove the conditional and rely on the audience. If you’d like to PR it, feel free, and otherwise I’ll knock it out probably early next week. Thank you.
