### ISSUE TITLE
Missing documentation on process creation

### ISSUE THREAD

**Issue by ManuelLevi** [sartography/spiff-arena#289]
When creating a new process there are two undocumented fields, or at least, I couldn't find anything related to them.

One is "notification addresses" and the other "metadata extractions".

**Comment by burnettk** [comment]
There is now documentation for each of these at https://spiff-arena.readthedocs.io/en/latest/DevOps_installation_integration/admin_and_permissions.html#step-2-add-process-model. Please be aware that the way "Notification Addresses" work may change a bit in the near future. Right now you specify recipients in each process model and they are used in another process model. We may centralize all of the logic instead so the configuration is not split between two places.

Thank you very much for reading the documentation and raising this issue! With everyone's input, the documentation (and system) continues to evolve in a good direction.
