### ISSUE TITLE
Allow downloading a process model, and then re-uploading it

### ISSUE THREAD

**Issue by danfunk** [sartography/spiff-arena#394]
Currently we require that all process ids are unique across the whole system.  This is required because call activities need to be able to unique reference another process in the system.  

I suggest that we modify the process id when you are uploading the file, and just do this transparently, or perhaps with an alert message to let folks know that the process id was modified.

**Comment by vkuehn** [comment]
Every process model should be unique as the execution of it, thought 

Still imports with different id's would be great.E.G loading models as templates  or from examples would only be possible with that.

If you implement a solution can you kindly also give a hint how to do it scripted and / or with a process?

**Comment by vkuehn** [comment]
changing the ID manually did work

related to the [command line question](https://github.com/espruino/BangleApps/issues/2870) 

probably one can be closed and a future version could ease life for template usage

**Comment by burnettk** [comment]
thanks for the update, @vkuehn . i think for the command line question a wrong link ended up in the comment. i'm guessing it should have been https://github.com/sartography/spiff-example-cli/issues/24.

**Comment by vkuehn** [comment]
ups you are right, excuse me please.

corrected the comment for the sake of quality

**Comment by danfunk** [comment]
This is fixed.
