### ISSUE TITLE
Missing Element and Collection fields in Parallel multi-instance task

### ISSUE THREAD

**Issue by vtexier** [sartography/spiff-arena#404]
Arena is installed and running following this documentation :
https://www.spiffworkflow.org/posts/articles/get_started_docker/

Playing with spiff-arena, I am editing Parallel Multi-instance tasks.

But the task tab is missing Input/Output Element/Collection fields.

![Capture du 2023-07-20 12-20-37](https://github.com/sartography/spiff-arena/assets/2174016/04261933-113d-4907-abff-314e911db4fc)

But they should appear like in the documentation here : 
https://spiffworkflow.readthedocs.io/en/latest/_images/multiinstance_task_configuration1.png

Thanks for this great project.

**Comment by burnettk** [comment]
@vtexier thank you very much for the kind words. i replicated your issue by following the getting started guide, and we have tagged a new release, which updates the docker images used by the getting started docker compose file. this fixed it for me, from the directory with the compose file:

````
docker-compose down # kill containesr
docker-compose pull # update images
docker-compose up -d
````

please drop a note if you would be willing to about some of the problems you are trying to solve with spiffworkflow. we will be very grateful. 🙇
