### ISSUE TITLE
sample-process-models

### ISSUE THREAD

**Issue by sofiane27** [sartography/spiff-arena#440]
Hello,

I've been trying to set up the `spiffworkflow-backend` project locally, following the instructions provided in the repository. However, I've encountered an issue related to the `sample-process-models` directory. The script `./bin/run_server_locally` seems to expect this directory to be present, but I couldn't find it in the repository.

Could you please provide guidance on where I can find the `sample-process-models` directory or if there are any additional steps I need to follow to set up the project correctly? Your assistance would be greatly appreciated.

Thank you in advance for your help.

Best regards,
Sofiane 

---

**Comment by burnettk** [comment]
Hi Sofiane,

Yes, the repo that is referring to is
https://github.com/sartography/sample-process-models. You can clone it
right next to spiff-arena and that would make the script work. Instead, if
you want, you can use any git repo or start from scratch with an empty
repo. If you wanted to do that, you could locate or create a git repo and
then run:


SPIFFWORKFLOW_BACKEND_BPMN_SPEC_ABSOLUTE_DIR=/path/to/any/git/repo
./bin/run_server_locally

Two other options, in case you're interested, which are potentially faster:
 * https://www.spiffworkflow.org/posts/articles/get_started_docker -
there's a three liner to run with docker compose
 * https://www.spiffworkflow.org/posts/articles/get_started - no install,
access a version of spiff hosted on the internet

Thanks for the feedback. Will try to think how we can improve this.

**Comment by cluck** [comment]
Any reason this instructions shouldn't be reflected on the main README at https://github.com/sartography/spiff-arena#frontend-setup?

**Comment by burnettk** [comment]
good point, @cluck . for the next person, I went ahead and just made it work by cloning a process model repo if one isn't available: https://github.com/sartography/spiff-arena/commit/c2c2a2f07a44302c89f42039660842928075c71e. hopefully this is one less thing to worry about during the first 60 seconds of using SpiffWorkfllow.
