### ISSUE TITLE
Workflows with "Start Timer Event" are not re-scheduled after completion if they contain a Manual Task object

### ISSUE THREAD

**Issue by chrda81** [sartography/spiff-arena#463]
I tried to use the internal scheduler to run workflows in defined intervals. The simple workflow named _Cycle Test_ with a "normal" task is re-scheduled as expected until its termination. But when I use a Manual Task object in the workflow named _Simple Example_, it runs only once and is not started with a new interval, when the Manual Task was completed.

Please see the discussion in the discord "general" channel.

![image](https://github.com/sartography/spiff-arena/assets/36750848/a5af63fd-8b02-46bc-8737-81e9e58d2f80)
![image](https://github.com/sartography/spiff-arena/assets/36750848/6796ff55-5604-4276-b2da-a4a3921c9cf8)

**Comment by chrda81** [comment]
The code changes are working! The workflow is scheduled again, after the manual task action has completed. Thank you sooo much 🥳

**Comment by danfunk** [comment]
@chrda81  - would be very kind of you if you could write a short two sentence endorsement for SpiffWorkflow that we could use on the website along with your name and company.  Star our projects on GitHub, post a message on Twitter or Linked In.  These would be great ways to show your appreciation, and help us grow the community and assure we can continue to support this open source project in the future.

**Comment by chrda81** [comment]
@danfunk - I gave the project one star, but unfortunately I can't write a review of the project itself because I've only been busy setting it up so far. But I'll be happy to come back to it when I have a little more experience.
