### ISSUE TITLE
SpiffWorkflow Service Properties command parameters alphabetically sorted

### ISSUE THREAD

**Issue by vtexier** [sartography/spiff-arena#476]
SpiffWorkflow Service Properties tab presents Parameters sorted by alphabetic order not by the real command signature order specified in the connector.

This is very confusing when optional parameters come before mandatory ones.

**Comment by danfunk** [comment]
Flask's jsonify was doing a deep sort, this is turned off.  Unfortunatel the python introspection that we do to determine the  parameters for a service connector is not offering any promises on order - so it won't alphabetize them anymore, but they are still somewhat random and are not in the exact order defined.  I guess that technically it does resolve this issue - but perhaps we need a new feature request:

SpiffWorkflow Connectors should provide additional information about accepted parameters including which fields are required.  I suspect this would best be handled by having all the connectors provide a Json Schema that describes the parameters, type, etc... It could even let people select from a drop down list of options for certain fields.  Connectors could provide two schemas - the first describes expected parameters, the second describes the successful response.

**Comment by vtexier** [comment]
Thanks for the quick response !

To respect the command signature is a key feature for me.

First, I understand that the connector proxy can be in any language so the respect of the signature should not be compromise by the connector proxy REST API. We should trust the API to not mess with parameters order.

Then if the connector proxy is in Python and use the SPiff Connector Proxy blue print lib, it should not mess with the parameter order as well.

I have coded a connector for my project, with nine commands. I do not really want to have more work to do writing json schema. Signature is here and param order should be introspected correctly.

Some ideas : may be `Python Static Typing` annotations might be useful to achieve a good introspection or the command could be a `dataclass` object with a good description of fields. If it is not sufficient, may be the `attrs` could help...

I can do research on the subject and come back with (may be) simple solution to avoid to much work for Python coders.

**Comment by vtexier** [comment]
`spiffworkflow-proxy` code seems fine, as it returns an ordered list and know about required arguments.

Didn't find anything in Arena backend code...

I found a sorting operation in `bpmn-js-spiffworkflow`.
The line to blame seems to be here (correct me if I am wrong):

https://github.com/sartography/spiff-arena/blob/d2dea0b85a4a49ed0f5f5a2b716d0d7626a9c614/bpmn-js-spiffworkflow/app/spiffworkflow/extensions/propertiesPanel/SpiffExtensionServiceProperties.js#L70C40-L70C40

**Comment by dinithihj** [comment]
Tested and verified with process model https://dev.app.spiff.status.im/process-models/misc:test:dinithi-testing:sartography-issues:service-task-476
![image](https://github.com/sartography/spiff-arena/assets/123297840/9a3e6db0-7256-4d67-a573-b02674c44b7d)

**Comment by madhurrya** [comment]
Released to Prod on November 27th
