### ISSUE TITLE
Task on parallel branch not executed

### ISSUE THREAD

**Issue by vtexier** [sartography/spiff-arena#487]
The following diagram fails on "FFmpeg video + audio muxer" task requiring the `audio_destination` variable set in the previous task "Fmpeg audio encode".

```
Error Details
Event Error Details
Error evaluating expression 'f"-y -i {video_destination} -i {audio_destination} -map 0:0 -map 1:0 -f mp4 {destination}"', name 'audio_destination' is not defined. Did you mean one of '['video_destination', 'destination', 'destinations']'?

Task Name:FFmpeg video + audio muxer
Task ID:ffmpeg_muxer
Call Activity Trace:Split Subprocess (ffmpeg_fixed_chunks.bpmn) -> FFmpeg video + audio muxer (ffmpeg_fixed_chunks.bpmn)
```

Two bugs here:
* A task on a parallel branch is not executed (so  `audio_destination` variable is not set).
* The states of tasks in the diagram are not set correctly as they are in the event list.

In this diagram, the task "Fmpeg audio encode" is not executed before the final task "FFmpeg video + audio muxer":

![Capture du 2023-09-14 13-49-08](https://github.com/sartography/spiff-arena/assets/2174016/103e9e27-4403-427f-b97b-b4d7ea0ef4c8)

It is quite hard to debug reading the diagram because the tasks in the diagram are not in their final state at the time of the error.

The list of events is quite explicit about it:

![Capture du 2023-09-14 13-41-49](https://github.com/sartography/spiff-arena/assets/2174016/4fb60d13-0f79-4db2-93b1-36891afe4f06)

**Comment by danfunk** [comment]
@vtexier - please try using a parallel gateway if you want to execute the tasks in parallel.  I would do both an opening and closing parallel, like this:
![image](https://github.com/sartography/spiff-arena/assets/515662/94e59272-18b3-4bcc-9c2c-3def92ec37ed)

**Comment by vtexier** [comment]
Thanks!  **This solution is working with only one parallel gateway at the end of parallel paths.**

But I consider it as a workaround, because even if using gateways is better as it is explicit, simple parallel paths should at least respect the visible order of tasks. Imho.

**Comment by danfunk** [comment]
According the specification: 

> "Gateways are used to control how the Process flows (how Tokens flow) through Sequence Flows as they converge
> and diverge within a Process. If the flow does not need to be controlled, then a Gateway is not needed. The term
> “gateway” implies that there is a gating mechanism that either allows or disallows passage through the Gateway--that is,
> as tokens arrive at a Gateway, they can be merged together on input and/or split apart on output as the Gateway
> mechanisms are invoked."

So it is true, that according to the specification, if all paths are valid, then they should be executed, even if no gateway is provided - though that would not guarantee that these tasks are executed in parallel, simply that both paths are valid and should be executed when possible.  So yes we should look into making this work.   If you would like to create a ticket specific to this bug, I would honor it.
