### ISSUE TITLE
Logout failure when already logged out

### ISSUE THREAD

**Issue by jakubgs** [sartography/spiff-arena#488]
If one has already logged out from Spiff, but has another tab open and attempts to log out they see this:

![image](https://github.com/sartography/spiff-arena/assets/2212681/dc397cbe-40dc-4920-9b13-905253780323)

Which is a result of `id_token_hint` being set to `null`:

![image](https://github.com/sartography/spiff-arena/assets/2212681/5159ee69-5f35-4b4d-b457-a7ae3b24b334)

Which happens here:
https://github.com/sartography/spiff-arena/blob/9db12d0c1efba39fb260f0ef3f379f245c2b1419/spiffworkflow-backend/src/spiffworkflow_backend/services/authentication_service.py#L92-L101

I think this could be pretty easily avoided by checking if `id_token` is `None`, and if it is simply redirect to the main page.

**Comment by jakubgs** [comment]
Maybe a better place for redirect to the main page is here:
https://github.com/sartography/spiff-arena/blob/9db12d0c1efba39fb260f0ef3f379f245c2b1419/spiffworkflow-backend/src/spiffworkflow_backend/routes/user.py#L310-L315
But not sure.

**Comment by madhurrya** [comment]
This seems to be fixed now. Now when the user logout from the other tabs also it goes to the login screen instead of showing that error.

**Comment by jakubgs** [comment]
Thanks.
