### ISSUE TITLE
When a Diagram fails, node states are wrong and different from event states

### ISSUE THREAD

**Issue by vtexier** [sartography/spiff-arena#492]
After an error on this diagram, the diagram is displayed. When clicking on node to see the content data, I can not because most node are in FUTURE state or WAITING state. **(I have written states under each node in this image).**

![Capture du 2023-09-14 13-49-08](https://github.com/sartography/spiff-arena/assets/2174016/02a3d1e5-76ba-4270-9eb4-f5caf00f946e)

Fortunately, the list of events is good and reflect the real state of the nodes:

![Capture du 2023-09-14 13-41-49](https://github.com/sartography/spiff-arena/assets/2174016/6acc322d-9d97-4043-b9fc-7d227afde84a)

and the `task failed` link display a meaningful error message. But I can not debug by consulting the data content of completed nodes in the diagram, cause there are in a false FUTURE state...

**Comment by calexh-sar** [comment]
Does adding Parallel Gateways as @danfunk suggested in #487 resolve this issues as well?

**Comment by calexh-sar** [comment]
Thanks for the update.  We have opened another ticket, #645, to catch this in the future.
