### ISSUE TITLE
Simple blank task Go button does not work

### ISSUE THREAD

**Issue by vtexier** [sartography/spiff-arena#493]
When executing a diagram with a simple blank task, the user is required to click on a **Go button** (like a manual task).

But clicking on this **Go button** redirect to the **"Something went wrong"** page.
And the diagram execution is stuck on this simple task node...

This **Go button** should work as expected and pass the task, or the task should be executed without user manual action (but executing pre-post script).

**Comment by jasquat** [comment]
Fixed in https://github.com/sartography/spiff-arena/pull/598.

**Comment by dinithihj** [comment]
Tested Environment: dev.app
Frontend Version: 289
Backend Version: 292
Process Model: https://dev.app.spiff.status.im/process-models/misc:test:dinithi-testing:sartography-issues:493-blank-task-go-button-issue
Comment: The blank task is showing up as a manual task in the UI and the process continues without any error. 

![image](https://github.com/sartography/spiff-arena/assets/123297840/c35367e5-f2a0-4331-a6bf-0c51e1e90cfb)

**Comment by madhurrya** [comment]
Released to Prod on November 27th

**Comment by usama9500** [comment]
Removing documentation label since its a bug and I feel it doesn't need to be documented.
