### ISSUE TITLE
Markdown editor widget is not opened when adding new markdown file to process model

### ISSUE THREAD

**Issue by chrda81** [sartography/spiff-arena#496]
![image](https://github.com/sartography/spiff-arena/assets/36750848/b7c81437-0daf-4a05-a4a6-1c7046aac762)

Only the text editor is opened, but there is no widget for the markdown styling options:
![image](https://github.com/sartography/spiff-arena/assets/36750848/d6dfe9c6-baf9-457a-ae6d-d50f132ba127)

**Comment by jasquat** [comment]
This will be fixed with https://github.com/sartography/spiff-arena/pull/495.

**Comment by burnettk** [comment]
Fixed on main, let us know if you have more feedback!
