### ISSUE TITLE
Web Forms - Workflow engine doesn't find task data for dropdown list field

### ISSUE THREAD

**Issue by chrda81** [sartography/spiff-arena#497]
Today I wanted to try the Web Forms and found this great youtube introduction (https://www.youtube.com/watch?v=1IaiaquQ0y0) from Dan. I loaded the example for the dropdown list, save everything (3 files were created) and ran the workflow. But sadly this error is happening.

![image](https://github.com/sartography/spiff-arena/assets/36750848/205bbb2a-b6e9-43ea-8c6e-1db5a6a4747e)

I look in the file exampledata.json and see the correct json data:
![image](https://github.com/sartography/spiff-arena/assets/36750848/bd58a9db-9c13-4548-aed2-6c7e5d869e48)

Side note: Is the styling via ui:options supported? I tried the example from the referenced documentation, but it wasn't rendered:

```
  "firstName": {
    "ui:options": {
      "chakra": {
        "p": "1rem",
        "color": "blue.200",
        "sx": {
          "margin": "0 auto"
        }
      }
    }
  }
```

**Comment by danfunk** [comment]
We have a bug with the form data that might be causing the problem.  Should
have a dix rolled out Monday. Will get back to you

**Comment by chrda81** [comment]
Hi @danfunk,
do you have any news for me?

**Comment by danfunk** [comment]
Hi Sky,

The data you see in the form builder (the Fruits) is an example of what you
need to have set up in the task data of your running workflow.  It's just
there to help design the form.

To make the form work during execution, you could create a script task
immediately prior to the form that contains the data you need.

fruits = [
{
"value": "apples",
"label": "Apples"
},
{
"value": "oranges",
"label": "Oranges"
},
{
"value": "bananas",
"label": "Bananas"
}
]

[image: image.png]
[image: image.png]

**Comment by chrda81** [comment]
@danfunk thanks for your answer, but it is confusing me. In the forms builder I see this hint for the **Data View**

![image](https://github.com/sartography/spiff-arena/assets/36750848/4ffbcb82-df69-409c-ba9f-c55e583cbd4b)

So I assumed that the content of the JSON file was available for the **Task Data**. So do I have to load this JSON file myself, or as you say, provide all the content as its own variables? That seems a little inconsistent, doesn't it? ;)

**Comment by danfunk** [comment]
I'll think about better wording.  It's a little complicated as it is
working in two different ways:

1) The data you enter into the form is ADDED TO the "Data View" so you can
see how the form data will add information to the task data.
2) In this special case that you are working on, the form is READING FROM
the "Data View" so you can see how task data can be used to effect a form -
in this case by adding options to a drop down.

That it works this way is very powerful, in that you can build up very long
lists in code - or make calls to 3rd party applications and then use this
information to populate your forms.  But I agree that the wording here is
confusing and would lead you in the wrong direction for this case.

**Comment by chrda81** [comment]
Ok @danfunk, with your hint I have now managed it. Many thanks. In a script task called **Task Data** I created the variable for the dropdown field.

![image](https://github.com/sartography/spiff-arena/assets/36750848/eb123720-e249-4145-b572-90dbdaed832a)

But what about the UI settings? Will this JSON be automatically evaluated by the Web Forms, or do I have to do this separately? I would like to tune the appearance of the input fields with Chakra UI Settings, as described in the react-jsonschema-form documentation (https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference /themes/chakra-ui/uiSchema)

**Comment by danfunk** [comment]
Good to hear - if you think of words that might get this across better, I
will happily introduce them into the editor.

I am completely under water at the moment, trying to secure some additional
contracts to keep the lights on here.  But I will put the UI Settings on my
todo list, and will see if I can pull something together.  We are, for
historical reasons, tightly coupled to the IBM Carbon UI framework which is
used throughout the site.  So making the forms adopt an alternate rendering
library could prove to be very difficult.  Is is Chakra-ui itself that you
are after, or if we provided some options for controlling the *style*
attribute of the form element, would that be sufficient?

**Comment by chrda81** [comment]
Here is my suggestion: "Data entered in the form on the right is provided as shown below. In order to initialize a form in the Workflow with default or list values, this data must be made available to the Task Data as variables."

Oh, I hope your light will stay on a very long time! My intention is to change the size of fields or group them together on a single row, e.g. for first_name and last_name. So I'm not after Charka-UI at the moment.

**Comment by burnettk** [comment]
updated the language in the Data View to incorporate some of the feedback and hopefully make it clearer: https://github.com/sartography/spiff-arena/commit/5800f95ea20ba473d9dd3a381e5a96b2b07a051d

i think the side by side UX for the form fields would be some work. i filed https://github.com/sartography/spiff-arena/issues/521 so we can remember it and forget about the other stuff on this ticket which i think is resolved. :)
