### ISSUE TITLE
Allow styling form fields next to each other

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#521]
From Status Notion ticket:
Implement a solution which would allow handling the compensation amount range:
Position 2 input fields side by side, where one of them represents the minvalue and another one - maxvalue

Original description:
To allow for things like:

first_name last_name

instead of:

first_name
last_name

Idea originally from https://github.com/sartography/spiff-arena/issues/497.

https://github.com/audibene-labs/react-jsonschema-form-layout

related to #647

**Comment by jasquat** [comment]
Implemented by #858

**Comment by dinithihj** [comment]
Tested and verified on dev.app (version 325/327)
Fields are displayed side by side when setting up the UI schema as below.

![image](https://github.com/sartography/spiff-arena/assets/123297840/74fdb61a-ce1c-4d5c-b8f6-6261dda4e9c2)
![image](https://github.com/sartography/spiff-arena/assets/123297840/d1332b4e-b6a3-41ec-b6e7-d16d0abbfa17)

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12

**Comment by usama9500** [comment]
Documented here: https://github.com/sartography/spiff-arena/pull/1047

**Comment by madhurrya** [comment]
This is already completed.
