### ISSUE TITLE
System to customize homepage ecosystem

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#537]
Create a system to customize the homepage for a given deployment of spiff.

We could extend the extensions functionality to allow for rendering components that the homepage currently renders and remove the status column from all tables for a given deployment.

Initial example json:

````
page: /tasks/completed {
    api: /tasks/blah,
    components: [{
      header: "Started by me",
      type: "ProcessInstanceShow",
      "columns": "id,process,task,waiting_for,started,last_updated,last_milestone,action"
    }, {
      header: "Waiting by me",
      type: "ProcessInstanceShow",
      columns: "default"
    }, {
      type: markdown
      existing_extensions_stuff_could_go_here
    }]
  }
````

The system should also support doing similar customizations on the process model show page, even if this is not fully implemented right now.

https://docs.google.com/document/d/1lJsmlCLtXgAjXZAaiIlBTe5QO1IV2lIgSxv-qTARFI0/edit?usp=sharing

**Comment by dinithihj** [comment]
@burnettk @jasquat Can you please let me how I should test this ticket?

Also can you please grant me read access to the document that linked in the ticket?

**Comment by burnettk** [comment]
we're using the new homepage stuff on the timetracking site (we added a fourth tab on the "homepage"). maybe that's good enough to prove the point. granted.

**Comment by dinithihj** [comment]
Moving this to Resolved

**Comment by dinithihj** [comment]
Closing the ticket
