### ISSUE TITLE
Add support for a KKV data store

### ISSUE THREAD

**Issue by jbirddog** [sartography/spiff-arena#538]
Due to the nature of reading/writing from data stores it would be advantageous to have a `KKV` data store which deferred the actual read/write until a top level key is specified. This could be achieved with low effort if functions were returned from the data store read/write operations. Another option is to add extensions to the arrows from data stores to/from tasks which would specify the top level key.

**Comment by dinithihj** [comment]
Tested Environment: dev.app
Frontend Version: 289
Backend Version: 292
Comment: New kkv items are visible under the "Select Data Store" dropdown list.

![image](https://github.com/sartography/spiff-arena/assets/123297840/7d3d4566-9deb-4b66-a5f6-763788318992)

**Comment by madhurrya** [comment]
Released to Prod on November 27th

**Comment by usama9500** [comment]
Closing this issues as  documented KKV data store at https://github.com/sartography/spiff-arena/pull/1360
