### ISSUE TITLE
Improved Messages:  UI For Managing Messages

### ISSUE THREAD

**Issue by danfunk** [sartography/spiff-arena#544]
Rather than define Correlation Keys, Correlation Properties, and Message Names within the BPMN.io editor - and having to replicate these exact settings in each process model that needs to send or receive a message,  provide a way to define these things with the Messages Tab on the top level UI, similar to Data Stores.

# Frontend Tasks
- [ ] Messages UI - add to the Messages Tab the ability to list and edit Message Types.  A Message Type is made up of a name and an optional description.  It should be possible to view all process models that send or receive a message with this name.
- [ ] Messages UI - Messages can, optionally, have one or more correlation properties.  A correlation property is a name and a retrieval expression.  The retrieval expression will be executed against the body of a sending message to extract a value.  
- [ ] Message API - pull list of messages from the backend and present them to the BPMN IO Editor.

# Backend Tasks
- [ ] Message API - Crud on messages and correlation properties

# BPMN IO Changes
- [ ] Remove the message and correlation properties from the Collaboration Properties Panel
- [ ] Add ability to get a list of messages and their correlation properties from an external source.

**Comment by calexh-sar** [comment]
Closed since current work is documented on #1511
