### ISSUE TITLE
Document react-jsonschema-form enhancements

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#550]
We have enhanced, and will continue to enhance the [react-jsonschema-form](react-jsonschema-form) capabilities.  We need to document these enhancements and explain how they can be used when building forms in SpiffArena.   Enhancements include:

1. Dynamic enumerations
2. Checkbox validation
3. Regex validation
4. Date range selector
5. Date validation when compared to another date

**Comment by burnettk** [comment]
@calexh-sar https://spiff-arena.readthedocs.io/en/latest/Building_Diagrams/Forms.html#spiffarena-react-jsonschema-form-enhancements
