### ISSUE TITLE
Error Boundary Event Development Work for Service Tasks

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#551]
There is some development work we need to complete for Error Boundary Events to behave consistently for Service Tasks.  We spoke in detail about this today and I wanted to capture some of the thoughts:

1) We need to standardize all connectors to error out on failure. Currently Service calls to Connector Proxies do not raise errors - the HTTP Connector never errors out - if the call fails, the information will be in the response variable, and would need to be parsed out in a post-script or script task. Probably return an exception name or error name with each response. BambooUserNotFound, XeroAccessDenied, S3BucketNotFound, and that sort of thing.
2) Errors should be codified and reported as a part of a service signature. A call to an external service may fail in many ways, some of which may be recoverable, some may not.  For example, a call to Bamboo HR might error out with a “404 - User not found” which may not be recoverable, vs a “500 - Internal Error” which may mean we should just wait for 30 minutes and try again.  Every service is different, with different errors that a BPMN architect has no way of knowing.   So we suggest that the Connector Proxy be able to report which errors are possible when making a service call, so you can catch each one and handle it as needed. 
3) Catch all errors in the backend, and allow the BPMN workflow to handle them if it chooses.  When executing any “engine” task (Service Task, Script Task, etc…) BEFORE you raise the error, check to see if there is an error boundary event, and if so, execute that instead.  This will allow BPMN authors the chance to catch errors, but will allow them to display in the pink error box if they are not caught.  Query all active service tasks and add these to the xml. This will cause them to appear as options when configuring error boundary events. Talk to elizabeth about this.
4) Allow for raising errors.  It should be possible to raise an error, causing the workflow to properly fail and log the issue.  This would allow the BPMN Author to force a process to fail out rather than just complete. 
5) Allow for generic exception catching.  It should be possible to catch ANY task execution error - so you can put an error event on a task with no specific error code assigned (or perhaps you select ‘all’ as an option), and if a failure happens during the execution of that task it will definitely follow the path.

**Comment by jasquat** [comment]
https://github.com/sartography/spiff-arena/pull/552

**Comment by madhurrya** [comment]
Tested in dev.app using https://dev.app.spiff.status.im/process-models/misc:test:madhurya-testing:madhu-error-boundary-event-test and https://dev.app.spiff.status.im/editor/process-models/misc:test:madhurya-testing:madhu-service-task-error-boundary-event-with-error-code/files/service-task-error-boundary-with-code.bpmn

**Comment by madhurrya** [comment]
Closing as it is complete

**Comment by madhurrya** [comment]
@usama9500 I think you have already documented about this. So I closed it.
