### ISSUE TITLE
Display UI-help (Specific to adding help text to a web form field)

### ISSUE THREAD

**Issue by usama9500** [sartography/spiff-arena#556]
Merged PR here: https://github.com/sartography/spiff-arena/pull/555

Screenshot: 

![Image](https://github.com/sartography/spiff-arena/assets/96994784/ac1ea82f-e237-44a0-a4b7-46476313c122)

**Comment by burnettk** [comment]
this is about when you configure a form in a specific way (is there an example set of json files somewhere), it should display something it's not currently displaying?

**Comment by calexh-sar** [comment]
@usama9500 would you please add details and if available a screenshot in the description.

**Comment by usama9500** [comment]
Sure @calexh-sar  Let me add details and create a PR here.

**Comment by usama9500** [comment]
@calexh-sar Added in description.

**Comment by usama9500** [comment]
Closing the issue. It is documented here: https://github.com/sartography/spiff-arena/pull/555
