### ISSUE TITLE
Design CRUD support for data stores

### ISSUE THREAD

**Issue by jbirddog** [sartography/spiff-arena#563]
Need to decide how we are going to support CRUD operations across multiple data store types, ideally in some common interface. One approach could be an interface beyond that exposed by SpiffWorkflow that allows each data store to describe how to add/update/delete etc records with its realm. Once this is designed out separate tickets will likely be required for the implementation for the various data stores.

**Comment by dinithihj** [comment]
@jbirddog Can you please let me know whether is there anything to test related to this ticket?

**Comment by jbirddog** [comment]
This was more of an internal code change in the backend, no new functionality was added. Everything should work as before with regards to the data store tab and interaction with data stores in the diagrams.

**Comment by dinithihj** [comment]
Executed all tests and everything looks ok.

**Comment by dinithihj** [comment]
Released to Prod on December 21st
