### ISSUE TITLE
Signal boundary event on human task cancelling task repeatedly

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#567]
https://spiffdemo.org/process-instances/for-me/examples:0-2-basic-example/3122?tab=2&log-list-events_page=1&log-list-events_per_page=50

That signal boundary event doesn't have a signal although it does have a button label
https://spiffdemo.org/editor/process-models/examples:0-2-basic-example/files/user-guide-basics.bpmn

(https://sartography.slack.com/archives/G013HT01VUY/p1698156186088019)
i wonder if that makes it constantly execute every time the background processor checks it since it's user input required

evidently it doesn't replicate unless you loop back around at least once by hammering the signal button.

**Comment by jasquat** [comment]
Fixed with https://github.com/sartography/spiff-arena/pull/596.

**Comment by dinithihj** [comment]
Tested Environment: dev.app
Frontend Version: 289
Backend Version: 292
Process Instance: https://dev.app.spiff.status.im/process-instances/for-me/misc:test:dinithi-testing:sartography-issues:boundary-event-task-cancelling-567/13029?tab=2
Comment: Now there are no repeated tasks canceling events.

![image](https://github.com/sartography/spiff-arena/assets/123297840/ecaeb525-7cbc-4164-b389-be4b962a8661)

**Comment by madhurrya** [comment]
Released to Prod on November 27th
