### ISSUE TITLE
Check CC field when defining the BO

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#568]
Add a check where CC field need to be checked before selecting a BO. If CC = L1 BO → L2 BO should be assigned

**Comment by calexh-sar** [comment]
@madhurrya will be ready for testing when PRs #769 and #770 are approved and merged.

**Comment by sashayar13** [comment]
@madhurrya the PRs are approved. For your testing, these are the scenarios which need to be checked:

- requestor = cc = L1 BO -> L2 BO should approve
- requestor <> cc but requestor = L1 BO -> L2 BO should approve
- requestor <> cc but cc = L1 BO -> L2 BO should approve
- requestor <> cc and none is L1 BO -> L1 BO should approve

**Comment by madhurrya** [comment]
Tested all the above scenarios for PP1 and PP2 and everything is working as expected.

**Comment by madhusarto** [comment]
This was released to Prod on Nov 6th

**Comment by madhurrya** [comment]
This was released to Prod on Nov 6th
