### ISSUE TITLE
Allow resuming a task from a previously lazy loaded call activity

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#571]

**Comment by jbirddog** [comment]
Noting the change to disable and adding failing test - https://github.com/sartography/spiff-arena/commit/d2dea0b85

**Comment by madhurrya** [comment]
@jbirddog Is there anything that I can test related to this?

**Comment by jbirddog** [comment]
> @jbirddog Is there anything that I can test related to this?

Directly, no. There is a unit test in the backend that was failing at the time this is disabled, which is now working. All in all if the existing process models are still working then all is good.

**Comment by madhurrya** [comment]
Didn't notice any issues in dev.app.
