### ISSUE TITLE
Use Data Stores for Enum Lists

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#572]
This is to replace service tasks with datastores. And create a seperate BPMN with a scheduled trigger to refresh datastores.

**Comment by madhurrya** [comment]
@calexh-sar Please let me know what I need to test in this.

**Comment by madhurrya** [comment]
1. Currency Types - Crypto, Fiat - Working
2. Event Type - All Hands, Conference, Meetup, Team Event - Couldn't find
3. Payment Method - Crypto Transfer, Debit Card, Reimbursement, Bank Transfer, "" -Working
4. Category - Consulting Fees, Equipment, Events, Learning & Development, Other Fees, Software & Licenses, Travel - Working
5. Consulting Fees - Ambassadors, Consultants, Freelancers - Working
6. Equipment Sub Category - Laptops, Ledgers, Mic and headphones, Phones, Yubikay - Working
7. Events Subcategory - Rent, Insurance, Logistics, Meals, Sponsorship, Entertainment, Equipment rental, Promotion, People, Other - Working
8. Learning and Dev Sub Category - Books, Courses, Online Conferences - Working
9. Other Fees Sub Category - Bounties, Coworking, Other - Working
10. Software Licenses Sub Category - Licenses & Subscriptions, Open Source - Working
11. Travel Sub Category - Accommodation, Meals, Flights, Transportation, Tickets, Visas, Other - Working
12. Software Deployment - SaaS, Self-hosted - Working

**Comment by madhurrya** [comment]
@calexh-sar I couldn't find this in the dropdowns. Everything else is there.
**Event Type - All Hands, Conference, Meetup, Team Event**

**Comment by calexh-sar** [comment]
@madhurrya just added, please test again.

**Comment by madhurrya** [comment]
Now Event Type drop down is also visible.  


![Image](https://github.com/sartography/spiff-arena/assets/110527567/6901f4f0-df83-41b9-bf47-690d90c3c1c5)

**Comment by madhurrya** [comment]
Released to Prod on November 27th
