### ISSUE TITLE
3rd parties are process participants (login to separate realm)

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#573]
Establish a 3rd party (external) user Spiff onboarding process.

As per discussion with @jakubgs, it was decided that we would not be comfortable holding both internal and external users in the same realm of Keycloak. There are 2 primary reasons:
1. We would like logical separation between internal and external users
2. We may like setup different custom scripts. We may not want to share these across both types of users.

Hence we need to look into Spiff supporting 2 SSO providers.  

New login screen Figma: https://www.figma.com/file/pn0SGCkPROlGyD0hKxmF9O/MVP-UI?type=design&node-id=1320-20832&mode=design&t=C2e9x3WZ7cqSQVGy-0

**Comment by jasquat** [comment]
PR #602

**Comment by madhurrya** [comment]
I guess we have not enabled the multi login UI (as shown in the Figma) in the version we are testing and we'll have to test it when the UI is available later. Until that is available can we move this ticket to somewhere else?

**Comment by harmeet-status** [comment]
We should enable multi-login as @MarD0607 will need this capability soon when he's done the vendor invoicing process.

**Comment by burnettk** [comment]
@jakubgs were you going to create a keycloak realm that could be used for people who are not core contributors? i think the idea was that people didn't want those folks in the standard realm. after that, we'll need to create an infra PR so that spiff knows about both of these openid providers and provides a way to select which one you want to use to sign in.

**Comment by jakubgs** [comment]
I can create it when needed, I simply need information on what env variables I need to configure for this realm.

**Comment by calexh-sar** [comment]
@harmeet-status closing this issue until the need to sign in 3rd parties arises that Guest User Tasks and unAuth Start Event does not handle.  At that time we will test the code written for this issue.
