### ISSUE TITLE
Change submit button to next on form pages

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#583]
On all pages, submit button change to next except for the last page which remain as submit.

From comment Dan left on Notion ticket:
Add support for the “SubmitText” setting in the React Json Form Schema so you can customize the text on the button when needed.  Because “Next” has connotations that may not work (it takes you back) we suggest we keep “Submit” as the default.   Attempting to guess when the text of the button should change based on it’s location in the BPMN diagram is extremely difficult and will not be estimated. 

https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/uiSchema

fixed by https://github.com/sartography/spiff-arena/pull/662

**Comment by calexh-sar** [comment]
Investigate a way to specify the button label in the json file.

**Comment by madhurrya** [comment]
Tested with https://test.app.spiff.status.im/process-models/misc:qa:forms:test-submit-button-text-1


![Image](https://github.com/sartography/spiff-arena/assets/110527567/7258a8f5-d05b-4b71-8bc9-2496517bdbc0)
