### ISSUE TITLE
Refactor Background Processor - Fast Background Processing

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#584]
* Prob. a new **queuing system** - an intelligent queue system that orders and prioritizes new processes and set dates. 
* Assure reliable execution of timers (if it says 2 minutes, it takes 2 minutes, regardless of other processes that are running - under NORMAL operation)***
* Maybe move interstitial to the background processor (will depend if we need to implement a second locking mechanism)

Original:
The Timer value is set to PT2M (2 mins) - https://dev.app.spiff.status.im/editor/process-models/misc:approval-strategy-main:reminders/files/approver_reminder_timer_value.dmn

But the timer is triggered in the process only after 11 mins

Process instance in [dev.app](http://dev.app/) - https://dev.app.spiff.status.im/admin/process-instances/manage-procurement:procurement:requisition-order-management:request-goods-services/7415?log-list-events_page=2&log-list-events_per_page=50

The two issues sasha would love to see fixed are:
 * you don't cause the instance to stop progressing when you leave the interstitial page
 * timer events fire a bit closer to when they are supposed to (a timer shouldn't fire in 11 minutes, when it's supposed to fire in 2 minutes)

perhaps switch SSE to polling to make the system simpler now that we don't need to process things in a loop in the controller. this would allow us to see results more easily in the dev tools network tab as well.

**Comment by danfunk** [comment]
Related to these other tickets in Notion:
https://www.notion.so/Interstitial-Performance-55ce7787c4ce422cb3c27aae8443575f
https://www.notion.so/The-interstitial-page-should-work-on-the-background-230828dbd5404b8299103a5e8acbd302

**Comment by jasquat** [comment]
Implemented with #788.

**Comment by jasquat** [comment]
This is ready for QA on dev.mod.

**Comment by dinithihj** [comment]
Tested on dev.mod (Version 60/51) environment. Need to retest on test.app/test.mod environments when the background processor is added to those environments. 

1. If you leave the interstitial page now the instance does NOT pause. It is continuing in the background and moving to the next task
Video link - https://drive.google.com/file/d/1s9L3SfGuZIjizvDsn_rgFhtTCbqRzQ_t/view?usp=sharing

2. Set reminder timer value to PT2M (2 mins) and the timer triggered accurately (closer to 2 mins)
![image](https://github.com/sartography/spiff-arena/assets/123297840/139ef839-e79b-4701-8d94-56ec333b021e)

**Comment by madhurrya** [comment]
Tested with a 2M timer https://dev.mod.spiff.status.im/i/36229

Interstitial page instructions continue to run when switched to other tabs and when the browser is minimized.
Tested with https://dev.mod.spiff.status.im/process-models/misc:test:madhurya-testing:interstitial-instructions-test

**Comment by calexh-sar** [comment]
Closed per sprint planning discussion.
