### ISSUE TITLE
Web3 login to Spiff using Wallet Connect SDK

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#586]
Our goal is to allow Status App to be used to Login to Spiff. Technically we are using the Status wallet to authorise login. We will be using Wallet Connect SDK to achieve this, which will allow us to login using any Web3 wallet.

Status app is currently working on integrating wallet connect amongst many other options. We've been advised by John that it's best to stick to the basic Sign-in with Ethereum EIP-4361.
Here is the standard docs: https://docs.login.xyz/general-information/siwe-overview/eip-4361
Additional resources: https://wagmi.sh/examples/sign-in-with-ethereum

**Solution overview:**
https://www.notion.so/Phase-3-Experiment-with-decentralised-governance-and-build-Web3-capabilities-in-SpiffWorkflow-fa6b90118302467f90ca0f35fa255023#5d400d250dbd4dbf9569850030c55591

**Comment by madhurrya** [comment]
@calexh-sar please check this
