### ISSUE TITLE
View who completed user tasks in a process instance

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#588]
Milestones are great for general idea of where you are at in a process.

We need to way to quickly see which user tasks were completed by which user. This is currently available in the process recap, however there are 2 things wrong with this:
1. Process recap is available at the completion of a process (not during)
2. Process recap is not the neatest way to seeing this, as there is not a standardised template (it will vary depending on the process)

An idea is to put a default filter in the events section which would show you just the user tasks and who completed them. Other ideas welcome.

Comment added to Notion ticket during Ticket Grooming meeting:

## Proposal

Change My Completed Tasks to Tasks and add sub-selection for Mine and All. Don’t include show form button on All (user should only be able to see data they entered).

Maybe use this for sub-sub-nav: https://react.carbondesignsystem.com/?path=/story/components-contentswitcher--default&globals=theme:white

**Comment by madhurrya** [comment]
Tested from different users and everything looks fine.


![Image](https://github.com/sartography/spiff-arena/assets/110527567/f468b278-ef31-4423-9cee-b1927ce05921)



![Image](https://github.com/sartography/spiff-arena/assets/110527567/ac19aaaa-996c-470e-9dd2-d1718150592f)

**Comment by calexh-sar** [comment]
@dinithihj has this been released and just waiting on documentation?

**Comment by burnettk** [comment]
@calexh-sar yes, it has been shipped to prod. here's a screenshot from test.mod:

![image](https://github.com/sartography/spiff-arena/assets/18027/33ad229f-646c-452b-8f25-5ca92d7d21a0)

**Comment by calexh-sar** [comment]
Setting status to Resolved.  Documentation team will still see this ticket in their view.

**Comment by usama9500** [comment]
Removing Documentation Label. Its done in the last PR : https://github.com/sartography/spiff-arena/pull/786
