### ISSUE TITLE
Web3 login to Spiff using Sign-in with Ethereum

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#589]
Our goal is to allow Status App to be used to Login to Spiff. Technically we are using the Status wallet to authorise login. We will be using the base implementation of Sign-in with Ethereum.

Here is the standard docs: https://docs.login.xyz/general-information/siwe-overview/eip-4361
Additional resources: https://wagmi.sh/examples/sign-in-with-ethereum

**Solution overview**:
https://www.notion.so/Phase-3-Experiment-with-decentralised-governance-and-build-Web3-capabilities-in-SpiffWorkflow-fa6b90118302467f90ca0f35fa255023#5d400d250dbd4dbf9569850030c55591

**Comment by burnettk** [comment]
@harmeet-status We were just about to start on this ticket, we went to https://docs.walletconnect.com/api/auth/overview , and it is saying that "Auth API is in the process of being greatly simplified, and will involve breaking changes. Please stand by." I don't think this note was there the last time I visited this page. This is giving us cold feet. Would it make sense to defer this ticket until the Wallet Connect API is more stable?

**Comment by harmeet-status** [comment]
@burnettk good pickup, yes pls wait. Let's come back to this in December.

**Comment by burnettk** [comment]
started working in https://github.com/sartography/sign-in-with-ethereum

**Comment by jasquat** [comment]
Here are some thoughts and questions KB and I had that we should discuss in the demo meeting:

We did some looking into this and prototyping.
There are a couple questions here, related to the fact that this is a major change to the system, frontend and backend, requiring the implementation of an auth system.
How soon do we want to use this?
If Status wanted to use this in June, it would potentially make sense to defer this work.
Implementing this and then never using it would be a real shame.
Can we avoid installing library dependencies in frontend?
It seems like this would require a direct frontend dependency for wallet integration and auth.
    * Installing wagmi will require upgrading react and potentially removing create-react-app/react-scripts due to dependencies
Can we avoid implementing a session store (and nonce store) in backend for this purpose?

**Comment by burnettk** [comment]
we discussed this. status wallet sign in functionality is planned for march of 2024, so it probably makes sense to hold off on this until we are slightly closer to rolling out this change in the status context. ideally there is a way to make this is a pluggable feature that is not prominent unless you want it to be, but we will have to think about how to implement this. it's possible status might even use wallet sign in to get into keycloak, in which case spiff might not need to change, but status is not excited about keycloak in terms of a long-term direction, so this is not incredibly likely.

**Comment by harmeet-status** [comment]
@burnettk I have confirmed with the Status App team and they will strictly be using the sign-in with Ethereum standard. So this means we are good to go ahead on implementing this.

For all of Feb, could you pls start thinking about how to best design this with things like adding this as a plugin/toggle feature in Spiff and we can re-discuss this in March.

**Comment by burnettk** [comment]
sounds good.

**Comment by harmeet-status** [comment]
This is what I'm envisioning for Spiff.
![Image](https://github.com/sartography/spiff-arena/assets/104047049/6da6dfb8-fb18-4f1b-91db-e48bacfa2e6a)

**Comment by harmeet-status** [comment]
This is what I was envisioning for Spiff.
![Image](https://github.com/sartography/spiff-arena/assets/104047049/de6c4fe6-c7e1-4855-9c20-216ee3a23cab)

**Comment by madhurrya** [comment]
@calexh-sar please check this
