### ISSUE TITLE
First 5 Minutes

### ISSUE THREAD

**Issue by danfunk** [sartography/spiff-arena#594]
The first 5 minutes someone uses SpiffWorkflow Application can be very daunting.  Here are issues I've worked through with several new users, or suggested by team members, that should be addressed:

**General Features:**
1. We should display directions when viewing an empty Progress Group that you can edit  ("This is an empty process Group.  To get started you should create a new Process Model using the button below") ✔️ 
1. If you can't start a process model because it doesn't have a BPMN file, don't show a start button. ✔️ 
1. If you are viewing a process model and it doesn't have any files in it - Ask the user if they would like to create a new BPMN file. ✔️
1.  #797 ✔️ 

Use cases to capture imagination of users:
 * integrate with openai (respond to prompt, generate image)
 * read and write to database
 * send discord message
 * fire http request to example data endpoint
 * generate "if statement"

Figma ideas [here](https://www.figma.com/file/uLnj6IoyGxBY68hd8Kpu8X/First-five-minutes-palette-ideas?type=whiteboard&node-id=0%3A1&t=lDHKGELgWqeKVaz5-1). Ayoub is sketching out a [proposal](https://ayoub98.notion.site/BPMN-New-Fresh-UX-UI-fa104d6e0345431ca565bcf4db5cf693).

**Comment by jasquat** [comment]
Draft PR at https://github.com/sartography/spiff-arena/pull/601

**Comment by dinithihj** [comment]
Tested Environment: dev.app
Frontend Version: 296
Backend Version: 299

1. Directions displayed for empty process models, However directions are still available even if the user does not have permission to add process models/groups, which is not correct.
![image](https://github.com/sartography/spiff-arena/assets/123297840/46a1fb27-13ca-4e31-9d4e-d170bd446c52)
![image](https://github.com/sartography/spiff-arena/assets/123297840/f6bf2371-fb6b-4bd0-810a-58aff5ce625c)

2. & 3. The start button is not visible when there's no BPMN file associated with it. And directions given on how to create BPMN file

![image](https://github.com/sartography/spiff-arena/assets/123297840/dca3507a-2f3f-484e-803c-07b4177044b9)
![image](https://github.com/sartography/spiff-arena/assets/123297840/a7328ff6-c73d-43b7-9872-6057715c3be4)

**Comment by jasquat** [comment]
Removed instructions to add a process model / group if a user does not have access. It now just says there aren't any to display.

**Comment by dinithihj** [comment]
Tested Environment: dev.app
Frontend Version: 299
Backend Version: 302

1. Working as expected. On empty process groups, when the user has permission to add process models/groups directions are displayed. When the user does not have permission to add process models/groups  just displays a message "There are no models/groups to display"


![image](https://github.com/sartography/spiff-arena/assets/123297840/a8db4592-c8c1-4ae4-a7dc-fad39ec73f1f)

**Comment by dinithihj** [comment]
Released to prod on 2023 November 27
