### ISSUE TITLE
Redesign how we handle the diagram on pi show page

### ISSUE THREAD

**Issue by jasquat** [sartography/spiff-arena#621]
Currently the diagram does not handle displaying looped tasks or parallel gateway information very well. This is because we only grab the most recent tasks associated with any given element on the diagram. This causes issues like a cancelled gateway being displayed instead of the completed one since we insert the cancelled gateway task into the db AFTER the completed one even though the completed one is correct.

Some options would be:
1. make the task-info api endpoint smarter and return the "correct" task in all cases
2. redesign the diagram completely to allow displaying all tasks that were iterated through from the diagram
3. have spiff tell us which tasks were cancelled as a result of another task completing. use this information to potentially store things in a way that would be advantageous.

Time Box:  2 days - attempt option 1 above, and if it doesn't work, provide a better ticket description for a followup effort.

**Comment by burnettk** [comment]
can anyone remember what the diagram looked like that caused the issue here?

**Comment by essweine** [comment]
I think it was one of the issues opened for cancelled tasks which are written to the db after other tasks, making the "most recent" attribute less meaningful, as it isn't representative of what's happening in the workflow.

IMO, a view that has the number of instances and allows viewing any task associated with a spec would go a long way to alleviating  "wrong color" issues and would be beneficial in its own right (it would also make it obvious at first glance how many times a loop was iterated over, for example).  And if the spiff update timestamp was used for ordering, I think it be less ambiguous than db update time what was actually done most recently.

**Comment by jasquat** [comment]
Implemented with #816

**Comment by dinithihj** [comment]
@burnettk @jasquat Can you please let me know how to test this ticket? Is it related to https://github.com/sartography/spiff-arena/issues/648?

**Comment by burnettk** [comment]
No, I don’t think it’s super related to that ticket. Please confirm that if you have a process instance where the same activity on the diagram occurred more than once (because of looping back), that you can view the dates/times those “task instances” occurred and what the task data was when they completed.

**Comment by dinithihj** [comment]
@burnettk I created a small process model to test this ticket. https://dev.app.spiff.status.im/i/4738

Created a user task to display 3 times. When I checked the task data all seemed good except for having a task instance entry as MAYBE. Is there any reason why it shows a record as MAYBE?

![image](https://github.com/sartography/spiff-arena/assets/123297840/dc9948d6-d598-4e47-927b-91774a9cd797)

And just a thought - assume that displaying task instances in descending order is purposely done - starting with number 1. I'm just wondering if it could confuse users as the first task instance is numbered as the highest number.

**Comment by jasquat** [comment]
MAYBE displays because it still exists in spiff. We could omit them but not sure if that's the right thing to do since it hides information.

Yeah that numbering could be confusing. Maybe we number in other order as well. So the newest one is number 4.

**Comment by dinithihj** [comment]
@jasquat shall I close this ticket and create a new ticket if we are changing the order of numbering?

**Comment by usama9500** [comment]
Documented (View task instance history) https://github.com/sartography/spiff-arena/pull/899

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12
