### ISSUE TITLE
Data Object Categories

### ISSUE THREAD

**Issue by danfunk** [sartography/spiff-arena#622]
We want to manage access to Data Objects in an easier to maintain way.

Imagine creating a Data Object Category called "Super Admin Only" and allow setting a permission in our main permissions file that restricts access to all data objects in the system that are given this category. 

This would require altering our BPMN-JS so it we can specify a category and altering the category api endpoint so that category is included in the url.  At this point it will be possible to set permissions across a category of data objects.

We might consider extending this to Data Stores as well.

**Comment by danfunk** [comment]
Since this was marked as a Sartogprahy ticket, I'm deleting it.  We created this to resolve an issue for Status, if they don't want it, it does not need to exist.

**Comment by jasquat** [comment]
I believe categories were added for #574.
