### ISSUE TITLE
Auto-Create the primary BPMN File when you create a new Process Model

### ISSUE THREAD

**Issue by danfunk** [sartography/spiff-arena#624]
Right now when you create a new process model - it builds the directory but you don't have any files - it can't do anything.  Why not generate a base BPMN file with the same name as the process model - put a start event, maybe a manual task, and an end event in it - so you have something that is runnable and it gives people a good starting point.

**Comment by calexh-sar** [comment]
@burnettk has this work be done?  released?

**Comment by burnettk** [comment]
yes, it has been done, but i guess we didn't realize there was a ticket. it is not released, so i marked it ready for qa (it is on dev and test, in the current release candidate, but not yet on test.mod or prod.mod.

**Comment by dinithihj** [comment]
Tested and verified on dev.app (version 325/327)
Now automatically creates the primary BPMN file with start event, manual task, and end event, When creating a new process model

![image](https://github.com/sartography/spiff-arena/assets/123297840/469ae5e9-f8f2-4aaf-a9f3-aa0ed8d865a8)
![image](https://github.com/sartography/spiff-arena/assets/123297840/ef1f8015-8c83-41d2-bab6-768df1f3924d)

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12
