### ISSUE TITLE
Documentation: Timer Events

### ISSUE THREAD

**Issue by Phillana26** [sartography/spiff-arena#625]

**Comment by madhurrya** [comment]
@usama9500 @calexh-sar is the documentation of this completed? Shall I close this?

**Comment by calexh-sar** [comment]
I defer to @usama9500 if the documentation has been completed.

**Comment by usama9500** [comment]
Timer Events documentation was done by @Phillana26 however I added enhancements to timer events with this PR: https://github.com/sartography/spiff-arena/pull/1524.

You can close this one!
