### ISSUE TITLE
Allow Spiff manual task to load iFrame and send parameters through the URL

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#632]
As part of PP1 and PP2, Budget Owners will need to approve costs, and in order to do this, they need to check the Superset report which shows their available budget.

We can currently embed an iFrame into the markdown file for a manual task (proven [here](https://www.notion.so/Superset-dashboard-embedded-in-Spiff-test-if-the-capability-exists-f4647f1b9b4c4011ba6c25605f42591e?pvs=4)), however we need to be able to send URL parameters in the iframe, which will load the correct budget for that particular user. The iframe has access to the cookie on the browser, so if a user is already logged in, the iFrame will load Superset.

See https://dev.app.spiff.status.im/process-models/misc:prototypes:embedded-superset-dashboard for current state of the art from sasha. It should be possible to use jinja syntax in this way to access task data and include these variables in the url.

Speak to Lalo Anaya for reports to test this functionality.

**Comment by harmeet-status** [comment]
@mrtrosen could you pls estimate this ticket, before I pull it into the backlog. Perhaps @burnettk and @jasquat can help.

**Comment by madhurrya** [comment]
@calexh-sar please check this
