### ISSUE TITLE
Encrypt the storing of API secrets

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#633]
API secrets are stored in Spiff DB, unencrypted. The host is encrypted though.

**Comment by harmeet-status** [comment]
Comment from @burnettk:

There is code in backend to encrypt them, so we could turn that on via configuration and re-install secrets on the four relevant envs. https://github.com/sartography/spiff-arena/blob/main/spiffworkflow-backend/src/spiffworkflow_backend/__init__.py#L164.

**Comment by burnettk** [comment]
@jakubgs would you possibly be able to update the `FLASK_SESSION_SECRET_KEY` on each env to make it 32 characters long. `spiff_backend_session_secret_key: '{{lookup("passwordstore", "services/spiff-workflow/"+stage+"/session-key")}}'`.

`uuidgen | sed 's/-//g'` sort of thing.

we are currently using FLASK_SESSION_SECRET_KEY to encrypt the secrets, and if we use the cryptography lib, it wants a decryption key of length 32. we could truncate FLASK_SESSION_SECRET_KEY for this purpose, but that feels confusing. we could also use the simple crypt lib, which doesn't appear to have requirement. lots of options, but if it's easy/reasonable to change the `FLASK_SESSION_SECRET_KEY` values (i don't think we're really using them for anything at the moment, so changing them should have no effect), that would make this simpler.

**Comment by jakubgs** [comment]
Our secrets currently have 64 characters:
```
 > pass services/spiff-workflow/app-test/session-key | tr -d '[:space:]' | wc -c
64
```
I don't know if I buy making them shorter. What kind of library are you trying to use exactly?

**Comment by jakubgs** [comment]
If these secrets will be used for encryption and current ones are unused then the variable names should be changed to reflect their actual function.

Also, if they are not used, then how exactly are we handling cookies?

**Comment by jasquat** [comment]
We updated the configs needed to set to turn on encryption in PR #673.

**Comment by burnettk** [comment]
oh yeah, you're right, we're using the FLASK_SESSION_SECRET_KEY for cookies. it's the `cryptography` lib. we're adding a new environment variable to specify the encryption key for this new "secrets encryption" purpose: SPIFFWORKFLOW_BACKEND_ENCRYPTION_KEY_FOR_SECRETS

**Comment by jakubgs** [comment]
You could avoid 4 characters in that variable name by calling it `SPIFFWORKFLOW_BACKEND_SECRETS_ENCRYPTION_KEY`.

But ah well.

**Comment by jakubgs** [comment]
Done:

- [`infra-spiff-workflow#ac8d5987`](https://github.com/status-im/infra-spiff-workflow/commit/ac8d5987) - spiff-workflow: env variable for secrets encryption

All environments have it.

**Comment by jasquat** [comment]
Reopening since we still need to merge PR #673 and release it.

**Comment by jakubgs** [comment]
The PR has been merged.

**Comment by burnettk** [comment]
I think we're releasing the code that makes use of this new env var to status prod on monday, and then we'll need to have a little party where we actually enable encryption and re-encrypt the values on each env (it will be a party because we don't have access to merge to infra--to change the env var to enable encryption--or to edit secrets on prod).

**Comment by harmeet-status** [comment]
@madhurrya moving this back to Ready for Release, as we need to enable this on our infrastructure. Once that is done, we can close this ticket.

**Comment by harmeet-status** [comment]
Changing to Resolved.

**Comment by burnettk** [comment]
this ticket has multiple parts. the code changes to support it are live, but the env var to actually enable encryption (SPIFFWORKFLOW_BACKEND_ENCRYPTION_LIB) has not been set, and we have not manually re-encrypted secrets on all envs. @harmeet-status , do you want to set up a meeting with us and @jakubgs or a delegate who can update infra and we can knock out these two pieces?

**Comment by jakubgs** [comment]
I don't know if we need a meeting for this. If you need me to run some kind of script/commands to encrypt stuff in the database I'm happy to do that manually if it's just a on-off(per stage) operation.

**Comment by burnettk** [comment]
the environment variable to enable encryption is `SPIFFWORKFLOW_BACKEND_ENCRYPTION_LIB=cryptography`,  but we have to delete all secrets before changing that environment variable.

**Comment by jakubgs** [comment]
Approved and merged the PR:

* https://github.com/status-im/infra-spiff-workflow/pull/34

Backed up secrets from the `secret` table and then re-added the secrets on `app-dev`:
```
admin@node-01.sm-eu-zur1.spiff.app-dev:~ % /docker/spiff-workflow/backend-db-admin.sh -D spiff-workflow-backend -e 'SELECT count(*) FROM secret;'
+----------+
| count(*) |
+----------+
|        7 |
+----------+
```

**Comment by jakubgs** [comment]
Is there anything left to do here?

**Comment by jakubgs** [comment]
I see on production the secrets are still not encrypted.
https://github.com/status-im/infra-spiff-workflow/blob/955e605502ac5318bb2077c2719cdf30944db375/ansible/group_vars/spiff.yml#L30-L31

**Comment by jakubgs** [comment]
BTW, this issue should have been created in `infra-spiff`, not here. This should be closed favor of:

* https://github.com/status-im/infra-spiff-workflow/issues/40

**Comment by harmeet-status** [comment]
@burnettk I'm thinking that we dont let the user retrieve a secret, only save it. This is just an additional level of security.

What do you think?

**Comment by burnettk** [comment]
turning retrieval off seems like a reasonable configuration option. we stole the existing UX from the way aws handles secrets, so I suspect some people will want one way and others will want the other way. it is undeniably handy to be able to fetch them from the UI. i would personally still fetch them, but i would need to go onto the server and run a script to be able to do so. we could remove the feature from the UI, kill the API, or both, potentially based on configuration settings. maybe we should just use permissions to implement this on status envs, since that would be simpler and already mostly built?

**Comment by harmeet-status** [comment]
Opening this ticket to allow us to action my last comment.

Comment:
> Secrets should not be able to be retrieved, they can only be saved

**Comment by burnettk** [comment]
Opened https://github.com/sartography/spiff-arena/issues/1348 for this.

**Comment by calexh-sar** [comment]
@harmeet-status closing this ticket and will accomplish this additional work in #1348.
