### ISSUE TITLE
MySQL deadlock error

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#634]
Got the below error when submitting a request.

![Image](https://github.com/sartography/spiff-arena/assets/104047049/c04ebf9e-74c4-4e90-b6d9-e3751ccbbcc2)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/5b2aa714-a5e6-4ccd-9b4a-24f613d688b8)

**Comment by harmeet-status** [comment]
Comment from @madhurrya:

Noticed similar deadlock errors in two instances in test.mod. (instance Ids 2310, 871)


![Image](https://github.com/sartography/spiff-arena/assets/104047049/1920f4bc-f595-4f29-9eec-a2441e3cd405)

**Comment by harmeet-status** [comment]
Comment from @madhurrya:

Did some testing with Dinithi today by both of us creating instances parallelly and continuously. We created about 50 instances altogether and got that error in 6 instances. Yesterday I created hundreds of instances but never got that error as I was not running multiple instances same time.

**Comment by harmeet-status** [comment]
Comment from @burnettk:

We decided on 30 oct with @Harmeet Singh  that a couple hour maintenance window is acceptable in order to perform the database migration to drop the id columns on the two tables in question. Once the release occurs tomorrow tuesday, we can begin discussions about the thing that is most important to release next and can get an idea about when to plan this window.

**Comment by madhurrya** [comment]
Didn't notice this after the fix.

**Comment by madhurrya** [comment]
Released to Prod on November 27th
