### ISSUE TITLE
Info icon for fields

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#636]
Allow adding info with help text written in Markdown
Should be configurable by a process architect. Potentially through the Form builder

**Comment by harmeet-status** [comment]
Comment from @sashayar13:

We should consider the following:

1. add “i” icon, pop-up messages, static help text, configured as part of the form (json)
2. being able to use Markdown to format the text - use md files?
3. test the current config for “key” “value”
4. DMN - test if we add additional column “Description”

**Comment by danfunk** [comment]
Duplicate
