### ISSUE TITLE
A character counter for text fields

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#640]
Add a widget/functionality allowing displaying to an end-user a count of chars entered to a text field vs the limit of chars set for the field

UPDATE: docs are [here](https://spiff-arena.readthedocs.io/en/latest/Building_Diagrams/Forms.html#character-counter).

**Comment by Kayvon-Martinez** [comment]
I have added a character counter field in https://github.com/sartography/spiff-arena/pull/1113

**Comment by Kayvon-Martinez** [comment]
I am going to get rid of the feature/character_counter_field branch as I accidentally made it track the numeric_range_field branch. I have made some fixes to the character counter field and pushed the changes to the numeric_range_field branch. The changes and example schema for this field are in https://github.com/sartography/spiff-arena/pull/925.

**Comment by dinithihj** [comment]
Tested on dev.app (Version 350/352) using the model https://dev.app.spiff.status.im/process-models/misc:qa:forms:test-character-counter and found below issues

1. When the "ui:field": "character-counter" is added to a text field, the help text appears larger than usual.
![Screenshot 2024-03-14 163147](https://github.com/sartography/spiff-arena/assets/123297840/970f3e32-a6e3-4a1a-9c99-51af89dc2c98)

2. When the "ui:field": "character-counter" is added place holder text is not displayed
![Screenshot 2024-03-14 163147](https://github.com/sartography/spiff-arena/assets/123297840/7a08c5af-0e19-4fc6-b0da-475c1f745eb9)

3. After adding "ui:field": "character-counter", it's not possible to submit the data after filling it out; it's showing the following error.
![image](https://github.com/sartography/spiff-arena/assets/123297840/644cae74-e22f-4503-ba58-8c7eaf5e03aa)

**Comment by dinithihj** [comment]
@harmeet-status Do you want this feature to be available in text area as well? Right now, if I add "ui:field": "character-counter" to a text area, it ends up looking the same as a text field.
![Screenshot 2024-03-14 163147](https://github.com/sartography/spiff-arena/assets/123297840/fb8e0cc8-5c2a-4b01-81d5-25126f249b32)

**Comment by dinithihj** [comment]
@Kayvon-Martinez I had a chat with @harmeet-status about the text area (about the above comment) he said it is a bug and needs to be fixed.

And also he suggested it's good to show the character counter on the top right corner of the control. 
![image](https://github.com/sartography/spiff-arena/assets/123297840/298a6b43-9111-41ba-9408-eb10fa6b2bdb)

**Comment by burnettk** [comment]
The character counter is a feature that is built in to the carbon components, so moving where it is displayed involves hacking on carbon.The direction is to move off of carbon with the new UI/UX. Perhaps we don’t spend too much time tweaking this now?

**Comment by tcoz** [comment]
The feature is very easy to implement without using the component (onKeyHandler, you just count 'em up and display them wherever you want). It might be useful to create this as a component that can be used for any text field flexibly.

**Comment by Kayvon-Martinez** [comment]
@dinithihj I will fix these errors.

**Comment by jasquat** [comment]
This is fixed in #1432. It should resolve the bugs however carbon only displays the counter field on the left it seems. Since this will have to get implemented differently with mui we recommend that we accept that constraint at this time.

**Comment by dinithihj** [comment]
Tested and verified on dev.app (version 383/384) All the above-mentioned bugs are fixed now and the character counter is working on text fields and text areas. The counter is still positioned on the left side, which is agreed to keep as it is.

![image](https://github.com/sartography/spiff-arena/assets/123297840/6ae83ea7-9aa3-4f2e-b4da-e83889a0543f)

**Comment by dinithihj** [comment]
Tested and verified on test.app

**Comment by madhurrya** [comment]
Released to Prod on May 9th.
