### ISSUE TITLE
maximumDate json validation option

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#642]
Similar to the json minimumDate validation option, add a maximumDate option.  When applied to a date-range field, it should be the maximum date of the date-range end date.

**Comment by jasquat** [comment]
Implemented with #851

**Comment by dinithihj** [comment]
@jasquat Maximum date is working as expected for Date Fields. But for Date Ranges it's not seem to be working correctly. 

Can you please have a look at it, whether I'm missing something or whether it's an issue?

Tested using Process model - https://dev.app.spiff.status.im/process-models/misc:qa:test-maximum-date
Added an End date field and used it to check the maximum date.

1. Date range did not validate against the end date

- End Date - 31-01-2024
- Date Range 19-01-2024 to 10-02-2024
- Date Range did not give an error message similar to date field
![image](https://github.com/sartography/spiff-arena/assets/123297840/dc60016c-ee81-4bd5-bcc6-e4a7866e4c13)


2. Start date on date range validates against end data
- End Date - 31-01-2024
- Date Range 10-02-2024 to 10-02-2024
- This time it's giving an error, I think it's the start date of the date range validated against end date?
![image](https://github.com/sartography/spiff-arena/assets/123297840/30e2bf98-de80-448f-a06c-af049e369b68)


This is my json file
![image](https://github.com/sartography/spiff-arena/assets/123297840/4d263636-885f-436b-9689-e08c46474e5a)

**Comment by jasquat** [comment]
@dinithihj Yeah it's working as expected. We use the first date in a date range for all validations. It seemed more intuitive to me to use first date in a range for all validations rather than change to the end date for maximum date. We can change this if people disagree with that assumption though.

**Comment by dinithihj** [comment]
@jasquat Thanks

@harmeet-status Can you please have a look at the above comments? Would you please let me know if you're ok with this change or if you want any modifications?

**Comment by dinithihj** [comment]
Had a discussion with @harmeet-status @burnettk @jasquat on this. Agreed to leave this as it is for now.

Therefore changing this to Ready for Release.

**Comment by burnettk** [comment]
we discussed how we might consider making the json more general in the future (like would it really need to be specific to dates...), and we could possibly support exclusiveMinimum and so on from the json schema standard and the relative field stuff from ajv, https://stackoverflow.com/a/36865790/6090676

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12
