### ISSUE TITLE
How cancelled task events are shown

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#648]
Input from @burnettk: “There are now canceled events for tasks that could have been completed, but were not completed because of the path that the process instance took. For example, a timer boundary event would be canceled if someone completed the associated user task before the time period elapsed.”

1. Can we do and display in the Log the task_cancelled right after the activity which was taken? For example, a timer boundary event would be canceled right after someone completed the associated user task before the time period elapsed. So the task_cancelled should be displayed in the Event log after the completed user task instead of after the end event.

2. Please check why the duplicated entries for task_cancelled are logged in the Event log (see the screenshot attached). The process instance id in the test app is 13672

**Comment by harmeet-status** [comment]
Comment from @sashayar13:

![Image](https://github.com/sartography/spiff-arena/assets/104047049/dc222ecc-c168-48a6-831c-a693d129b269)

**Comment by dinithihj** [comment]
Tested a few requests and now duplicate task_cancelled events are not logged. 
https://test.app.spiff.status.im/i/16470
https://test.app.spiff.status.im/i/16856
https://test.app.spiff.status.im/i/16734
https://test.app.spiff.status.im/i/16653
https://test.app.spiff.status.im/i/16659

![image](https://github.com/sartography/spiff-arena/assets/123297840/e74e1f89-3d9e-4208-a65b-825660f3f138)
![image](https://github.com/sartography/spiff-arena/assets/123297840/68fd7f15-4d53-4203-8ba2-32cbeb6a46e3)
![image](https://github.com/sartography/spiff-arena/assets/123297840/2d549b47-8051-4ae0-9909-06f07fdb83dd)
![image](https://github.com/sartography/spiff-arena/assets/123297840/56b09a8e-bf83-4374-98d7-eb0b9592273c)
![image](https://github.com/sartography/spiff-arena/assets/123297840/ee44deec-a9c2-4557-b887-993cb0d3495d)

@sashayar13 Shall I move this to resolved?

**Comment by sashayar13** [comment]
@dinithihj yes, I think we can close this ticket
