### ISSUE TITLE
Radio button styling

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#649]
Allow process architect to control the positioning of the element - vertical or horizontal.
Previously the default positioning was - vertical, recently it’s been changed to horizontal. But not for all cases horizontal works well, for instance if the label text is too big

If the positioning is horizontal, add space between the Title and Values:

![Image](https://github.com/sartography/spiff-arena/assets/104367255/9fe99f84-18c2-4206-9ffd-3e15dbbe314a)

PR: https://github.com/sartography/spiff-arena/pull/925

**Comment by harmeet-status** [comment]
Comment from @sashayar13:

comment from @Kevin Burnett in the channel: “I’m estimating it would probably take a half day to force all radio buttons to lay out vertically, and another day to make it configurable.”

**Comment by harmeet-status** [comment]
@sashayar13 can we pls update the option to: Approved, skip Infra and Security

**Comment by Kayvon-Martinez** [comment]
@sashayar13 Hey where should we be putting the configuration to change the style of the radio buttons? Is this something you figured out or  do you want to talk about it together?

**Comment by burnettk** [comment]
I vote in the ui schema json and using whatever property makes sense to you.

**Comment by sashayar13** [comment]
@burnettk suggestion looks good to me. @Kayvon-Martinez

**Comment by harmeet-status** [comment]
@Kayvon-Martinez can you post a screenshot of what the UI look like here.

**Comment by Kayvon-Martinez** [comment]
Hi @sashayar13 . I understand. I will get on that. Thank you @burnettk . Also I will make sure to post screenshots here @harmeet-status .

**Comment by Kayvon-Martinez** [comment]
Is there a test process I can use for this @harmeet-status and @sashayar13 ? I have tried it on my own and could not get the horizontal layout.

**Comment by burnettk** [comment]
https://dev.app.spiff.status.im/process-models/misc:qa:forms:test-radio-button-1 could work.

**Comment by harmeet-status** [comment]
@Kayvon-Martinez what's the latest on this ticket, the last comment is from 2023?

**Comment by Kayvon-Martinez** [comment]
I have made changes in https://github.com/sartography/spiff-arena/pull/925 that should resolve this issue.

**Comment by calexh-sar** [comment]
@Kayvon-Martinez do you have an example of this working or how this is specified in the uischema?

**Comment by Kayvon-Martinez** [comment]
Here is an example of how it should be in the ui schema:
![Image](https://github.com/sartography/spiff-arena/assets/142514475/ac99510e-f00d-404f-b220-6154f31c926b)

The field now takes a "ui:layout" that can be set to either "column" or "row". When it is set to column the field's radio buttons will be vertical. When "ui:layout" is not specified or is set to row the radio buttons will be horizontal.

**Comment by burnettk** [comment]
@calexh-sar note that the PR isn't merged yet, so hold for that before testing.

**Comment by dinithihj** [comment]
Tested on dev.app (version 350/352) using the model https://dev.app.spiff.status.im/process-models/misc:qa:forms:test-radio-button-styling 

When positioning is Horizontal no space is added between the Title and Values
![image](https://github.com/sartography/spiff-arena/assets/123297840/919cb9c1-ff31-4d56-aa4c-4c9a4d0e9125)

**Comment by dinithihj** [comment]
Additional Note on this ticket. As per the Slack discussion, @jasquat has removed the ui:layout and now the inline option is used to control the positioning.

Below is an example 
![image](https://github.com/sartography/spiff-arena/assets/123297840/4a701ba3-5c95-4a14-b3f5-8d73df33e008)

The inline : true will position values horizontally and inline : false will position values vertically.
By default values will be positioned vertically. On the discord @sashayar13 @calexh-sar and @madhurrya agreed to it.

**Comment by madhurrya** [comment]
I think it'll be good to add spacing for both horizontal and vertical.
![image](https://github.com/sartography/spiff-arena/assets/110527567/2865f5e3-a406-4bed-bfbf-eea7baf1d65e)

**Comment by Kayvon-Martinez** [comment]
Thank you @madhurrya for bringing this up. I will try to make this change happen.

**Comment by harmeet-status** [comment]
@calexh-sar Kayvon is off atm, is it possible to assign this to one of the devs for next sprint?

**Comment by dinithihj** [comment]
Tested and verified on dev.app (Version 383/384) with the process model https://dev.app.spiff.status.im/process-models/misc:qa:forms:test-radio-button-styling

Now with the inline option user can set positioning as vertical or horizontal. The inline : true will position values horizontally and inline : false will position values vertically. By default values will be positioned vertically.
Space was added between the title and values for both vertical and horizontal positions.

![image](https://github.com/sartography/spiff-arena/assets/123297840/2980dfff-b8e0-46a9-bba9-3ad2c6d5040c)
