### ISSUE TITLE
When admin is reviewing task on behalf of another user - instance is not under ‘For Me’ tab in Process Instances

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#653]
When the Admin review on behalf of another user, that instance doesn’t get listed under Admin’s ‘For Me’ in Process Instances list page.

But it comes under ‘Instances with tasks completed by me’ for Admin in the Home page.

Steps for Admin approving on behalf of Budget owner:
1. Suspend the Process Instance
2. Open the Call Activity: "Get Approver(s) Review Outcome"  -> "Do Approval Review"
3. Click on "Review the Request" (which is the current activity in Yellow) and select "Edit" in the pop up screen 
4. Change "review_outcome": "" to "review_outcome": "app"
5. If you want to add a comment, add a new line after the above line with the following variable name and comment.
"reviewer_comment": "Admin approved on behalf of Budget owner",
6. Click "Save" and then click "Execute Task"
7. "Resume" process instance.
8. Refresh the page after a few seconds (now it takes about a minute) and make sure it has moved to the next activity as the current activity.
9 Now the rest of the process can flow.

Steps will be similar for the SME also.

Note: This might be the case for other users also when they approve on behalf of others. Need to test that, after that other bug related to this is fixed.

**Comment by madhurrya** [comment]
@calexh-sar are we going to close this?
