### ISSUE TITLE
Update BambooHR connector to provide write capabilities

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#654]
Need these capabilities to be able to write data to BambooHR, e.g. contract PDF etc.

Considering the near future CC onboarding processes, we will need to be able using the connector to:

- Add new employee data
- Update employee data
- Delete/archive employee data

Also since there was a discussion surrounding time off and how we can identify a backup for an approver based on availability we might also need:

- Get a list of Who’s out

Additionally there are more endpoints for adding/retrieving/updating Bamboo data

**Comment by danfunk** [comment]
It would help estimation if we could have specific items that we want to do with Bamboo HR - implementing and testing every possible edit / update / delete of user data may lead to very high estimate.   @harmeet-status

**Comment by calexh-sar** [comment]
@harmeet-status is this a Bamboo API permissions issue and no additional work for us since we are using the http connector?

**Comment by calexh-sar** [comment]
Using http, just need Bamboo permissions set.
