### ISSUE TITLE
'Reset Process Here’ to a User task

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#657]
If an Admin resets a process instance to a User Task, the user who needs to complete the task cannot do it - the User form cannot be open (see the attached screen recording)

the example I had - reset PP1 from PPG BA approval step back to the Budget Owner

**Video**:
https://www.notion.so/Reset-Process-Here-to-a-User-task-657e68957b524c52ab32a368976ce75a?pvs=4#1b6d268e2d784ec3b9932cac3a00d946

**Comment by danfunk** [comment]
Please retest - we suspect this is not valid.

**Comment by dinithihj** [comment]
@harmeet-status / @sashayar13 I have tested this and it looks fine for me. 
Reset PP1 from PPG BA approval to Budget Owner approval and the Budget Owner was assigned to perform the next task. 

Video link - https://drive.google.com/file/d/1BMedtE7HN-xYjr91AkuzusFcDS7Gp06h/view?usp=sharing

Please let me know if you referred to something else and want me to test more.

**Comment by sashayar13** [comment]
hey @dinithihj could you pls confirm that if you open the review task as BO - fluffy project lead, you can see the user form and you can complete the task, after the completion of the task the request proceeds to the next tasks?

**Comment by dinithihj** [comment]
@sashayar13 I have tested both new instance and old instance for the above scenario. In both scenarios, BO - fluffy project lead could see the user form and complete the task. After completing the request it proceeded to the next task. Furthermore I have completed full flow till Legal approves the requests.

Process instances

- https://dev.app.spiff.status.im/i/4485
- https://dev.app.spiff.status.im/i/3914

Video Links 

- https://drive.google.com/file/d/1bX3lRAaKW8svlqHJOL2Pq3GA2PkgxS-K/view?usp=sharing
- https://drive.google.com/file/d/1ncGqhCGwsr7CX2wVHVZ5plgOn3pjY3oE/view?usp=sharing

**Comment by sashayar13** [comment]
thanks for checking @dinithihj

**Comment by dinithihj** [comment]
@sashayar13 Shall I move this ticket to resolve or do we need further testing on this?

**Comment by sashayar13** [comment]
@dinithihj yes please
