### ISSUE TITLE
When rehydrating workflows for spiff, do not add data to completed tasks

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#658]
originally implemented in #661 
bug #705 was raised
PR #706 reverted PR #661
implemented again with PR #828, where we accounted for the reset task bug
hoping this helps with #773

**Comment by jasquat** [comment]
PR #661

**Comment by burnettk** [comment]
yep, marked ready for qa.

**Comment by dinithihj** [comment]
Tested and verified on test.app (190/192). 
Task data does not disappear when performing the "Reset Here" functionality. 

![image](https://github.com/sartography/spiff-arena/assets/123297840/7cd528ee-aa9d-4265-86a3-b2f511715283)
![image](https://github.com/sartography/spiff-arena/assets/123297840/7540393c-1dd9-4cd3-8489-decde287258b)

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12
