### ISSUE TITLE
Git deployment process models issue

### ISSUE THREAD

**Issue by danfunk** [sartography/spiff-arena#664]
I'm trying to create a PR for Request Travel process (Test -> prod), but instead it creates a PR to merge changes across all process models. See the recording attached.

We could be running into a problem where we are pushing changes between dev and test AND test and prod so may need to protect against this. 

To do:
-----
* Add a check to see if the commit already exists when doing a publish -- provide an alert message if the branch already exists.
* Could provide some additional information and append it to the name of the branch we create so it will always be unique.

**Comment by danfunk** [comment]
KB Writes: this was occurring because there was an old branch of the travel process model and it wasn’t being updated as a part of the promotion process. we have deleted the branch as a temporary fix and will investigate why it wasn’t being updated

Sasha Responds: the issue is back, for request goods/services process model (test.app → prod.mod). But this time under branches it shows the correct number of diffs

KB: please delete the branch from GitHub and then republish from the app.

**Comment by burnettk** [comment]
we updated the branch name to to include the target branch, rather than just the process model identifier. this will resolve this issue, we believe: https://github.com/sartography/spiff-arena/commit/07f2cbc8af9d8154e23eff0f2d3965210dceb043
