### ISSUE TITLE
Front-end behaviour_"read" permission applied to a specific process group/model

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#667]
There is a need to fix the front-end behaviour for the Processes tab.
If a user group doesn't have permission to "read" to "PG: all" but instead has "read" permission to a specific PG or PM, they still should be able to navigate to the process group/model through the Processes tab and folders.

Currently, the user from such a user group would not see any process groups/folders displayed under the Processes tab, and they can only open the process group/model through a direct link.

**Comment by jasquat** [comment]
Implemented with #832

**Comment by dinithihj** [comment]
Tested and verified on dev.app (Version 316/318)
Now users can navigate to process groups/models through the process tab and folder even when they have read permission to a specific process group or model.

- When the user has read permission to Process Group : Requisition Order Management
![image](https://github.com/sartography/spiff-arena/assets/123297840/06c8c661-a018-406a-829f-fe932bc5f5ed)
![image](https://github.com/sartography/spiff-arena/assets/123297840/e0bc13fc-2e50-4e6d-af19-508be25539a6)

- When the user has read permission to Process Model : Request Goods or Services 
![image](https://github.com/sartography/spiff-arena/assets/123297840/26f3e060-62db-4093-a071-bb28b41e6f60)
![image](https://github.com/sartography/spiff-arena/assets/123297840/587948d0-8708-4ddb-b1ca-8252ebd821d7)
