### ISSUE TITLE
Delete files from MySQL automatically on storing in DMS

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#669]
Any files uploaded in a process are stored by default in MySQL. Implementation of a DMS will mean that we want to store the files, on completion of process in the DMS and at this point, to automatically remove them from MySQL and store the link to the file in the task data.

related to #580

**Comment by harmeet-status** [comment]
@mrtrosen this is the second part of the DMS work I was talking about, where we would want to clear the DB of files and store them only in the DMS.

**Comment by madhurrya** [comment]
@calexh-sar please check this
