### ISSUE TITLE
Support 2 process model repo's in Spiff to allow different permissions on each repo

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#676]
We would like the ability to have multiple process repo's in Spiff so that we can have different permission on each repo. E.g. process-repo-1 can be public and process-repo-2 can be private.

The business use-case behind this is that as part of Status, we would like to start making some of our process models public so that other Web3 organisations can fork and use our process models within their own organisation, meanwhile there will be other process models which are Legal/Finance specific which we would like to keep private.

It would be ideal to have 1 directory structure visible in Spiff, with 2 repos in Git. We can then use permissions in the system to give/deny permissions to users within Spiff. At the repo level, we would set the permissions on the repo itself.

**Comment by harmeet-status** [comment]
@mrtrosen @burnettk @jasquat Let's start discussions on how we would achieve this.

**Comment by danfunk** [comment]
Sub-trees are maybe an option but it feels very dangerous. 
requires some discussion and a bit of trial and error to see how well certain git operations will work.
Maybe consider publishing a more public repository based on a portion of the full private repository using some sort of script.  So the repository remains simple, but you have some transparency when you are ready to share.

**Comment by calexh-sar** [comment]
@harmeet-status waiting to see if you want to discuss further.

**Comment by madhurrya** [comment]
@calexh-sar please check this
