### ISSUE TITLE
Reassign SME/BO issue for old instances

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#678]
When I reassign a SME/BO task of an old instance (it seems any instance created before a day ago or older, I am not exactly sure about it) that new assignee sees it in the home page and he can continue and finish without any issue. 
But after reassigning, without completing it immediately if I check that instance after about 30 mins or so I don't see it in the home page and I can't get it by searching for that new assignee. It seems it is available for that user only while that instance is in 'waiting' state (in test.app it is in this state for about 10-15 mins) and when it turns to 'user input required' it's no longer available for that user.
e.g https://test.app.spiff.status.im/i/13737  (PeopleOps task was assigned to ppg ba sme)
https://test.app.spiff.status.im/i/14986 (Infrastructure task was assigned to ppg ba sme)
https://test.app.spiff.status.im/i/14990 (Legal task assigned to ppg ba sme)

Video : https://drive.google.com/file/d/1Ol_ZcUTA72TDvUbPWJwRLwUNdXDQJ9gO/view?usp=sharing

But that issue is not there for an instance I create and reassign at this point of time. For that even after the state change that new assignee can see it in the home page.
e.g https://test.app.spiff.status.im/i/15254 (PeopleOps task was assigned to ppg ba sme)

**Comment by madhurrya** [comment]
This seems to happen with PP1 only. Didn't notice with the few instances I checked with PP2

**Comment by madhurrya** [comment]
As I mentioned in the slack, 
I am not clear how it worked for some PP2 instances 
for example this one https://test.mod.spiff.status.im/i/3608 (People ops activity assigned to Service lead and he can still see it in the home page)
and this one https://test.mod.spiff.status.im/i/3607 (BO activity assigned to service lead) and he can still see it.

And I am not clear how the timer triggered immediately (most of the time) when we do a reassignment in PP1.
May be this is all related to the long delays we have been having in timers/resume etc.. I'll do some testing in dev.app today and see how it behaves there as we have a clean db and things are fast now.

**Comment by burnettk** [comment]
One hypothesis for why timers triggered shortly after a reassignment is because there are two background threads, one for user input required and one for waiting, and perhaps the user input required thread is more backlogged/slower. After reassignment , it goes into waiting status.

**Comment by sashayar13** [comment]
@calexh-sar, it looks reasonable if the assignment returns to the L1 BO after the reminder. But I need to know if the timers triggered as they were scheduled or somehow triggered because of the assignment change.

@madhurrya, have you noticed the same behaviour for the new instances (created after the latest code release)?

**Comment by madhurrya** [comment]
@sashayar13 Yes this is an instance created on Nov 23rd after the latest code deployment on Nov 22nd in test.mod.
https://test.mod.spiff.status.im/i/5555
Please see the 3 screenshots
1. Before the assignment
2. After assignment while waiting.
3. After the resume is completed.

![5555_1](https://github.com/sartography/spiff-arena/assets/110527567/0f049340-c8d5-48e1-ad20-a2bd47e97f05)
![5555_2](https://github.com/sartography/spiff-arena/assets/110527567/a96de3cd-125b-456b-970c-dff288273b2c)
![5555_3](https://github.com/sartography/spiff-arena/assets/110527567/e91d64c4-6c90-4548-8036-ac058dd97066)

**Comment by madhurrya** [comment]
I tested a set of instances in dev.app today and it works as Alex has explained above. It is there for the new user until the waku timer triggers next time. After that it is no longer available for that user.

So I guess the issues we are seeing in test.app and test.mod are due to the 4,5 days of delay in timers and something related to that causes it to behave like what I have explained in the above comment. So due to some reason when we reassign at that point it triggers the timer and then the reassignment get cleared.
In dev.app after the database reset yesterday since the timers and resume etc are working more accurately, I think we can assume that the reassign feature works as Alex has explained.

**Comment by sashayar13** [comment]
@madhurrya I see, thanks for confirming this. You are saying that I can go ahead and try to re-assign users in prod?
Do we have the ticket to fix the issue with timers in GitHub? I can't find it @harmeet-status

**Comment by madhurrya** [comment]
@sashayar13 Yes, based on how it works in dev.app I think it should work the same way in Prod.
But the new assignee will have to do the approval within a day before the next timer triggers. Otherwise it'll reset.
Do we need to add a ticket to fix that or is that behavior OK for now?

**Comment by calexh-sar** [comment]
@madhurrya are we good to close this issue?

**Comment by calexh-sar** [comment]
Closing
