### ISSUE TITLE
Process model errors

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#679]
@calexh-sar I'd really appreciate it if you could help me with the process model I'm working on. https://dev.app.spiff.status.im/process-models/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:request-new-role

Currently I'm having 2 issues:
1. If "Hiring manager" = "Requestor", the system throws an error that it can't find a usergroup "Project Lead", however if I select another user for Hiring manager, it works fine
2. It keeps assigning a Requestor to the "Approve" task (instead of a program lead). The Approve task is part of the process file https://dev.app.spiff.status.im/editor/process-models/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:request-new-role/files/role_approval_program.bpmn

**Comment by calexh-sar** [comment]
Fix for #1: The Proeject Lead lane_owner assignment was being made on the Post Script of the "Send notification to a PL" Sub-Process, so it was only being set if the "Requestor = Project Lead?" Exclusive Gateway 'No' path was taken.  I added a Script Task after the Merging Gateway and put the land_owner expression in there.

**Comment by calexh-sar** [comment]
Fix for #2: The role_approval_program.bpmn process called by the "Get Program manager approval" Call Activity contained a Pool only, no lanes. This was new to me as well, but once I added an additional lane, there were two lanes and I made the bottom one the "Program Lead" lane and moved the Tasks that were used to determine who is the Program Lead and the lane_owner assignment into the top lane.

**Comment by calexh-sar** [comment]
@madhurrya per our scrum discussion today, this issue does not require QA testing.

**Comment by calexh-sar** [comment]
@Phillana26 and/or @usama9500 per our weekly meeting discussion, please update our [Pools and Lanes](https://spiff-arena.readthedocs.io/en/latest/Building_Diagrams/pools_and_lanes.html) documentation to clarify that a pool by itself does not have any lanes and lane_owner can only be set for a lane in a pool with two or more lanes.

**Comment by sashayar13** [comment]
Thanks for your prompt assistance @calexh-sar !

**Comment by usama9500** [comment]
Added small note in my last PR: https://github.com/sartography/spiff-arena/pull/1677
