### ISSUE TITLE
Task_cancelled - loop, every second

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#684]
Noticed a bug in prod. If there is an open instance, waiting for a requestor to action (first user task, after the merging parallel gateway), the system keeps cancelling tasks every second until a user actions (I assume). 

It increases the size of DB and potentially impacts the system performance. There are a few recordings from Event logs available (3 different process instances, Request Travel process)

**Comment by sashayar13** [comment]
I couldn't attach recordings to the issue as their size was above the limit. Let me know if you want to see them, I can share.
<img width="1240" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/c11bf03b-f6de-4d02-b91d-0f5315f28779">
<img width="1240" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/88cc3bc2-1bb7-47ea-a6d6-b0822074d983">

**Comment by sashayar13** [comment]
<img width="1240" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/40e18d4d-529c-4d58-84a6-015de6334319">

**Comment by burnettk** [comment]
nice find, yeah, the fix for #567 is in the current release candidate and seems likely to resolve this.

**Comment by madhurrya** [comment]
Checked with these instance in test.app
https://test.app.spiff.status.im/i/15734 - 11/21 - Only 2 Pages of event data
https://test.app.spiff.status.im/i/15733 - 11/21 - Only 2 Pages of event data
https://test.app.spiff.status.im/i/15221 - 11/16 - Only 2 Pages of event data
https://test.app.spiff.status.im/i/14800 - 11/11 - Only 2 Pages of event data

Will check some more instances in test.mod in few days.

**Comment by calexh-sar** [comment]
@dinithihj do you know if you need to check any more instances in test.mod?

**Comment by dinithihj** [comment]
Checked a few instances from test.mod 

https://test.mod.spiff.status.im/i/5900 - 11/27 - Only 2 Pages of event data - only 2 task_cancelled events
https://test.mod.spiff.status.im/i/5910 -  11/27 - Only 2 Pages of event data - only 2 task_cancelled events
https://test.mod.spiff.status.im/i/6057 -  11/27 - Only 2 Pages of event data - only 2 task_cancelled events

**Comment by dinithihj** [comment]
Released to Prod on November 27th
