### ISSUE TITLE
PP1/PP2 error when resuming after some admin features

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#686]
QA noticed an error when resuming the instance after performing the scenarios mentioned below. Please see the screenshots for details.

1. Admin approving on behalf of Budget owner
2. Admin approving on behalf of a SME
3. Skip Manual Task (Role - Infra, Manual Task - Update Application Landscape/Catalogue)

**Steps for Admin approving on behalf of Budget owner PP1**
1. Suspend the Process Instance
2. Open the Call Activity: "Get Approver(s) Review Outcome" ->"Get Budget Owner Review" -> "Do Approval Review"
3. Click on "Review the Request" (which is the current activity in Yellow) and select "Edit" in the pop up screen 
4. Change "review_outcome": "" to "review_outcome": "app"
5. If you want to add a comment, add a new line after the above line with the following variable name and comment.
"reviewer_comment": "Admin approved on behalf of Budget owner",
6. Click "Save" and then click "Execute Task"
8. "Resume" process instance.
9. Refresh the page after a few seconds (now it takes about a minute) and make sure it has moved to the next activity as the current activity.
10. Now the rest of the process can flow.

**Steps for Admin approving on behalf of a SME  PP1**
1. Suspend the Process Instance
2. Open the relevant SME "Review the Request" activity (which is the current activity in yellow)
3. Click on "Review the Request" and select "Edit" in the pop up screen
4. Change "review_outcome": "" to "review_outcome": "app"
5. If you want to add a comment, add a new line after the above line with the following variable name and comment.
"reviewer_comment": "Admin approved on behalf of PPG",
6. Click "Save" and then click "Execute Task"
7. "Resume" process instance.
8. Refresh the page after a few seconds (now it takes about a minute) and make sure it has moved to the next activity as the current activity.
9. Now the rest of the process can flow.

Screenshots added below.

(Created from https://www.notion.so/PP1-PP2-error-when-resuming-after-some-admin-features-d192e94a1cc84da99c3979746da2e484)

**Comment by calexh-sar** [comment]
- 
![Image](https://github.com/sartography/spiff-arena/assets/54854669/ef30778d-9efd-4cc5-ae49-9e5949ab43e9)

![Image](https://github.com/sartography/spiff-arena/assets/54854669/17c69640-cc3a-4894-8ee0-1b926bc3a9d5)

![Image](https://github.com/sartography/spiff-arena/assets/54854669/39db1453-176a-43ef-9d66-25eab223abd8)

**Comment by burnettk** [comment]
resume not working on test.app was because the container had been manually shut down. it was subsequently started.

**Comment by calexh-sar** [comment]
@burnettk or @jasquat  am I remembering correctly that this tickets should be put on hold until the current work on updating the background processor is complete?

**Comment by burnettk** [comment]
this should be testable now on dev.mod, where the new background processor work has been deployed.

**Comment by calexh-sar** [comment]
@dinithihj Would you please retest this an let us know if the issue is still active or not.

**Comment by calexh-sar** [comment]
@dinithihj have you had a chance to retest this?

**Comment by dinithihj** [comment]
Tested on dev.mod environment and the issue still exists there. 

![image](https://github.com/sartography/spiff-arena/assets/123297840/ceb33639-a1bd-45f0-8142-b02833d17897)
![image](https://github.com/sartography/spiff-arena/assets/123297840/b4685d4a-2605-4260-a4d1-bc7da20b4cc9)

**Comment by madhurrya** [comment]
@calexh-sar This issue is still there. Are we going to close this since this is pp1/pp2 related.
