### ISSUE TITLE
Investigate Avalanche and similar platforms

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#687]
From Dan's Slack posting:
D mentioned that we should look at [Avalanche](https://www.avax.network/) as another possible starting point for distributed version of SpiffWorkflow.  

If this concept looks interesting, might be worth investigating other similar possibilities.

michael was suggesting that our use case might fit well with an avalanche subnet: https://docs.avax.network/learn/avalanche/subnets-overview

**Comment by danfunk** [comment]
Going to close this for now, and we can pick up this effort at a later date with more thought.
