### ISSUE TITLE
Improve error message when no form exists

### ISSUE THREAD

**Issue by danfunk** [sartography/spiff-arena#691]

**Comment by danfunk** [comment]
If you create a User Task and add an empty form to it you get an error that simply states "invalid schema: null".   Would be better to say "Please create a valid form for this user task."  or something nice like that.   This was encountered by a prospective client when evaluating the platform.  


![Image](https://github.com/sartography/spiff-arena/assets/515662/fec058b5-5340-4a59-8d4c-026acbb93df3)

**Comment by jasquat** [comment]
Implemented with 812.

**Comment by dinithihj** [comment]
@danfunk @jasquat The message "Invalid schema: null" no longer shows up. However, there isn't a more helpful message in its place. Instead, the form loads as shown in the screenshot. When the user clicks on Submit button, the process instance gets completed. Is this okay, or should we show a clear message asking the user to create a valid form?

![image](https://github.com/sartography/spiff-arena/assets/123297840/8659c373-fae3-4758-a7ac-a2154c543f7f)
![image](https://github.com/sartography/spiff-arena/assets/123297840/b18e987a-b282-4da3-9ec9-b0514c57e299)

**Comment by burnettk** [comment]
I think this (treating it like a manual task) is as good as an error message.

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12
