### ISSUE TITLE
Configure frontend logic for manually entered Job Title

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#692]
Need to allow users to provide their value if none of the options fit their need. Process - Request New Role
Process - https://dev.app.spiff.status.im/process-models/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:request-new-role

The fields where this will be used:
1. Program (label = new program)
2. Project (label = new project)
3. Job title (label = None from the listed options - add option)

If a user selects these options - a new text field should appear - which allows to enter free text.

(copied from https://www.notion.so/Configure-If-then-else-frontend-logic-for-a-few-fields-956f108f720e4e23bb414331c5838968)

**Comment by calexh-sar** [comment]
@sashayar13 this work is ready for your review.  I ended up using the `oneOf` option instead of the `if-then-else`.  If there was a particular reason for wanting to using `if-then-else`, please let me know.  If all looks good to you, please update the Status to  either `Ready for QA` if you would like QA to test or `Ready for Release` if you feel QA testing is not needed.

**Comment by calexh-sar** [comment]
@sasha, I did not do any of the work that will be needed to add displaying this field in later User elements that display the Job Title.  Just let me know if you wanted me to do that work as well.

**Comment by sashayar13** [comment]
thanks @calexh-sar. I noticed that you did it only for Job titles, I'll apply the same logic to the Project field.
No need for further work from your side at this moment

**Comment by sashayar13** [comment]
@calexh-sar After the implementation of these changes I started getting the following errors when I'm doing the submission of the form: 

![Image](https://github.com/sartography/spiff-arena/assets/104367255/69c1a173-c90b-431a-b476-3761477da080)

**Comment by calexh-sar** [comment]
@sashayar13 we got the validation errors taken care of for all three fields with basically the same fix of specifying a new enum list that did not include the one set of values that made the hidden text field appear.  I had to consult with @jasquat to get this figured out.  If you would like more insight into the fix, perhaps we can discuss the next time we are all in a meeting.

**Comment by sashayar13** [comment]
@calexh-sar yep, I found the scripts you added to the process model to fix the issue. But would appreciate hearing more insights about the nature of the error

**Comment by calexh-sar** [comment]
Sasha moved Notion ticket to Ready for QA.
