### ISSUE TITLE
Approval process - BO holiday check

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#694]
Introduce a process on how tasks are assigned to the back-ups.
The additional logic for assigning L2 BO approvers:
1. every time when a request is sent for a BO approval, check timeoff data
2. if there is a Time off entry for the BO, send the request to the L2 BO
3. If the L2 BO is a Requestor or also AFK (need to check their time-off data as well), assign the request to the CFO.

How to get TimeOff data:
https://documentation.bamboohr.com/reference/get-a-list-of-whos-out-1

the test - https://dev.app.spiff.status.im/process-models/misc:service-tests:bbhr-service-tasks:bbhr-time-off

the response sample:
```
<?xml version="1.0"?>
<calendar>
<item type="timeOff">
<request id="1650"/>
<employee id="109">Harmeet Singh</employee>
<start>2023-10-30</start>
<end>2023-11-11</end>
</item>
</calendar>
```
   
(Copied from https://www.notion.so/Approval-process-backups-DoA-9d032b9fb84043a89591fc4e12be761a)

**Comment by calexh-sar** [comment]
@sashayar13 do you want the time off check to be for the date of the approval request only, or also include the day after (or more) as well?

**Comment by sashayar13** [comment]
> @sashayar13 do you want the time off check to be for the date of the approval request only, or also include the day after (or more) as well?

@calexh-sar let's check the date of the approval request only

**Comment by sashayar13** [comment]
> @sashayar13 this is now a Bamboo Reports option on dev. Had to get that working before moving on to getting it incorporated in existing process models. Let me know if you want me to created an PR for just the Bamboo updates so you can confirm how it will run on prod.

@calexh-sar yes, I think it's a good idea. Could you pls create the PR?

**Comment by calexh-sar** [comment]
PRs #819 and #820 created so Bamboo Who's out report can be move to test and then prod for review there.

**Comment by calexh-sar** [comment]
@sashayar13 can you pls confirm from the prod report that the employeeId number returned is the Bamboo API Id for the employee found in the URL and not the Employee # that is entered in the Personal Basic Information section:


![Image](https://github.com/sartography/spiff-arena/assets/54854669/4dfb6dd0-1471-4b9d-8856-be78544971c4)

**Comment by calexh-sar** [comment]
@sashayar13 thoughts on how the CFO should be identified?  Add that information as a L3 in the Budget Owner DMN table?

**Comment by sashayar13** [comment]
@calexh-sar let's not do the part about the CFO for now, let's do only L1 and L2 BOs.
There are some internal discussions happening about this topic right now.

**Comment by calexh-sar** [comment]
@sashayar13 very well, will set the CFO/L3 aside.  How do you want to handle if the L2 is the person who should be approving and is not available due to the holiday check?  Leave them assigned and alert support?

**Comment by sashayar13** [comment]
@calexh-sar Let's check only L1 Time Off and keep the assignment on L2

**Comment by calexh-sar** [comment]
@dinithihj please let me know if you need assistance with setting up Bamboo to test this issue.

**Comment by dinithihj** [comment]
@calexh-sar I used Bamboo to set up some user accounts earlier. So it should be fine. I will let you know if I need further help.

**Comment by calexh-sar** [comment]
@dinithihj this should be ready to test once PR #875 is merged.

**Comment by dinithihj** [comment]
Tested and verified. Version test.app 187/189
When L1 BO has a time off entry request assigned to the L2 BO.

**Comment by dinithihj** [comment]
Released to Prod on December 21st
