### ISSUE TITLE
Software & Licenses change approval logic

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#695]
1. Add the new field to the User Form, make it “required” for Software&Licenses path

2. Based on the value selected for “Deployment model”, Infra SME step can be included or excluded from the process
- If “Self-hosted” is selected, Infra needs to be included into the approval process
- If “SaaS” is selected, by default Infra team is excluded from the approval process, but Security SME can decide to request “Infra”s review (same way we did for Equipment and PeopleOps partner review step)

3. move the “Application Landscape” task from Infra to Security, customise it

(Created from https://www.notion.so/Software-Licenses-change-approval-logic-df6a17a84f774b8a9afc3b41707f6489)

**Comment by calexh-sar** [comment]
@dinithihj this should be ready to test once PR #875 is merged.

**Comment by dinithihj** [comment]
Tested and verified. Version test.app 187/189

**Comment by dinithihj** [comment]
Released to Prod on December 21st
