### ISSUE TITLE
Requestor and Core Contributor display format should match

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#696]
Update PP1 and PP2 so that the Requestor and Core Contributor fields display format matches

(Created from https://www.notion.so/Requestor-and-Core-Contributor-display-format-should-match-8861f71424f14c96bb75f7e709d966a8)

**Comment by calexh-sar** [comment]
@sashayar13 PP1 and PP2 formats now match.  Will be included in next PR for each when you are ready.

**Comment by sashayar13** [comment]
@calexh-sar For some reason, I can still see the difference between "Requestor" and "Core Contributor" fields
<img width="902" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/0f233ce9-9253-4fca-9fdd-17f36e01bb9f">

It also looks different at the User Form stage:
<img width="902" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/2b83ecf0-b64d-4b02-a4f1-26cbe3f36470">
<img width="902" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/ee8ecd93-adbd-46f8-8688-92a5a2c189ae">

**Comment by calexh-sar** [comment]
@sashayar13 this is ready for your review again.

**Comment by sashayar13** [comment]
@calexh-sar I still see the different formats in PP1 (first user task)


![Image](https://github.com/sartography/spiff-arena/assets/104367255/22aafdd1-05c2-4219-8a20-6b0c15f8a685)

and same in PP2 (first user task) - Requestor and Traveller

**Comment by calexh-sar** [comment]
@sashayar13 , I updated the cc typeahead to display `preferred last` names if preferred is available.  Please be aware that the result makes searching for your first and not preferred name appear like this.


![Image](https://github.com/sartography/spiff-arena/assets/54854669/2a20cd12-884f-4eb9-9d7b-e023ebf2b30a)

**Comment by calexh-sar** [comment]
@sashayar13 I am seeing what I posted below.  Were you on dev for your post above?  If so, which process model?


![Image](https://github.com/sartography/spiff-arena/assets/54854669/7de2ea2b-0727-49d8-8da5-21364f98a00c)

**Comment by sashayar13** [comment]
@calexh-sar yep, it was the Request Goods/Services process model in dev.app

**Comment by calexh-sar** [comment]
@sashayar13 are you still seeing the wrong format with a new instance there now?

**Comment by madhurrya** [comment]
@calexh-sar 
![image](https://github.com/sartography/spiff-arena/assets/110527567/647f8839-4aa3-4f61-84c5-d2e583c4c673)

**Comment by calexh-sar** [comment]
@sashayar13 would you pleasae click on the link above, do a hard browser refresh, and let me know what you see then.

**Comment by sashayar13** [comment]
@calexh-sar yes, the fix helped! Now I can see the matching display formats in PP1. Could you pls apply the same change to PP2?

**Comment by calexh-sar** [comment]
@dinithihj this should be ready to test on test once PRs #878, #879 and #880 are merged.

**Comment by dinithihj** [comment]
Tested and verified on test.app (version 187/189)
Both Requestor and Core contributor/Traveller have the same name format.

**PP1**
![image](https://github.com/sartography/spiff-arena/assets/123297840/29446abf-c86c-4d6f-b606-cc4330b42ecb)
![image](https://github.com/sartography/spiff-arena/assets/123297840/df3d9beb-5573-4787-8a92-722f14b8e623)


**PP2**
![image](https://github.com/sartography/spiff-arena/assets/123297840/8da92bdf-3758-411a-98e4-59dc759d4ab9)
![image](https://github.com/sartography/spiff-arena/assets/123297840/088079b5-bc44-4402-960a-fcc45d471688)

**Comment by dinithihj** [comment]
Released to Prod on December 21st
