### ISSUE TITLE
Bamboo reports - Divisions

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#697]
To update the Active Departments and Divisions report so that it shows active (only) Divisions

(Created from https://www.notion.so/Bamboo-reports-Divisions-cedcfde9ba37426dbbc62a48f0ad5bf7)

**Comment by calexh-sar** [comment]
@sashayar13 would you please provide additional details on how this report is not showing active Divisions only. When I run the dev version for active only this list is returned:


![Image](https://github.com/sartography/spiff-arena/assets/54854669/13ea14cf-e0a6-4937-84e4-b781103a8a75)

And when run for all Divisions this list is returned:


![Image](https://github.com/sartography/spiff-arena/assets/54854669/7f51fa93-616d-4eca-8e87-21ad86c96ebe)

**Comment by sashayar13** [comment]
hey @calexh-sar I think it was an issue in prod, but it could be the case when source data was not up-to-date, and it created confusion.
If the report uses the active divisions only, there is no need to update the report. Thank you

**Comment by calexh-sar** [comment]
@sashayar13 the PRs I just created for the Who's out report should have the latest for the Dept and Div report as well if you want to check it again after moving that to prod.  If it is still a problem, we can check into other reasons why it is working on dev and not on prod.  Might be something like it still has employees assigned to it but flagged as inactive.
