### ISSUE TITLE
[PROD bug] Something went wrong on submission of additional info - Request Travel process

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#699]
Travel request was submitted, additional info was requested, additional info was added and on clicking submit, received this error.

![Image](https://github.com/sartography/spiff-arena/assets/104047049/2235d8d1-0fbc-4dbd-813c-b700ee1be33e)

Work on this ticket will be a serialization download so the Json can be analyzed.

**Comment by harmeet-status** [comment]
@burnettk @jasquat any debugging info that you need, I can send directly to you as can't post prod logs here on Github.

**Comment by burnettk** [comment]
We could potentially make this issue about being able to import/export a process instance from one environment to another. i'm trying to think of other ways to debug, but if we had this instance locally, we could probably figure out what is going on fairly efficiently.

**Comment by harmeet-status** [comment]
@burnettk yeah thats a good idea, can you estimate how much work this is?

**Comment by harmeet-status** [comment]
@burnettk I got this error again today in prod, when trying to submit a fresh instance with the same data. Seems like a recurring issue.

@dinithi I will send you details on how to replicate.

**Comment by burnettk** [comment]
@harmeet-status / @dinithihj : any update on this?

**Comment by harmeet-status** [comment]
Here is the same notion ticket you linked above @burnettk, in Github Projects
https://github.com/sartography/spiff-arena/issues/773

**Comment by harmeet-status** [comment]
@dinithihj you can replicate this:

1. Create a request for Travel, with the following things added:
Flight to Melbourne, Flight back to Sydney, Ticket, Accomodation, check the per diem checkbox, dates 5 days in Nov 2023, amount equal to approx 1000 usd.
2. Submit request, the BO for Insights should send back for more info
3. As soon as the CC re-submits the info, error should be thrown

**Comment by dinithihj** [comment]
@harmeet-status I have tried a travel request with the above data and steps. But could not replicate the error. 
Below is the process instance. https://dev.app.spiff.status.im/i/3705

Please take a look at the screenshot below and let me know if I need to change the data input.

![image](https://github.com/sartography/spiff-arena/assets/123297840/a38d3e35-c702-4195-91b2-33a0fa1963a6)




Since the error is related to encoding/decoding, I'm wondering if it's connected to the text you put in the request. If you can, please share all the details you entered in the request. (If they are not sensitive information)

**Comment by dinithihj** [comment]
@harmeet-status I have tested a few instances on dev.app, test.app, and test.mod environments with the task data you shared. But I was not able to recreate the issue in this ticket.

Process Instances
https://dev.app.spiff.status.im/i/5331
https://dev.app.spiff.status.im/i/5332
https://dev.app.spiff.status.im/i/5333

https://test.app.spiff.status.im/i/17581
https://test.app.spiff.status.im/i/17582
https://test.app.spiff.status.im/i/17583
 
https://test.mod.spiff.status.im/i/7401
https://test.mod.spiff.status.im/i/7402
https://test.mod.spiff.status.im/i/7403

**Comment by harmeet-status** [comment]
Ok I have created a new ticket which allows us to dump a process instances from 1 env. to another https://github.com/orgs/sartography/projects/3/views/8?pane=issue&itemId=50118958

**Comment by madhurrya** [comment]
Closing this as this was a one time issue and couldn't recreate it.
