### ISSUE TITLE
Form buttons need to be responsive on mobile

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#700]
The buttons should stack on top of each other on smaller screens. Right now they spill to the right of the screen, forcing the user to scroll. See screenshot.

![Image](https://github.com/sartography/spiff-arena/assets/104047049/339bfca9-284e-49bf-a097-6cf3b2e3e03a)

**Comment by madhurrya** [comment]
Closing this issue as these will be handled in the new UI
