### ISSUE TITLE
When 'Reset here' to a task the task data goes missing

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#705]
When I do a 'reset process here', after that the task data seems to be empty in test.app and dev.app

![Image](https://github.com/sartography/spiff-arena/assets/110527567/16d68f60-a416-418f-b51f-5731db66775a)

I reset to this activity. Noticed the same happening when resetting to another activity also.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/1cb30b79-524c-43b4-9662-df1237f9a224)

This is when the same thing tried in test.mod where the above issue not there. There you can see the task data when you reset to the same task as in the above scenario.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/4e3a8574-e5d4-4343-a271-efdad8d565cb)

**Comment by madhurrya** [comment]
It happens for any model. You can check this sample. 
https://dev.app.spiff.status.im/i/16088

**Comment by jasquat** [comment]
@burnettk @essweine this may be why we need task data on completed tasks. Possibly a result of #658.

**Comment by jasquat** [comment]
Possibly fixed with PR #706.

**Comment by madhurrya** [comment]
This is fixed now

**Comment by madhurrya** [comment]
Released to Prod on November 27th

**Comment by madhurrya** [comment]
This issue is already fixed.
