### ISSUE TITLE
Timer start events set <60s take longer to start

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#711]
For a timer start event when the time is set for less than one minute, it takes more than a minute to start the timer, the time specified in seconds does not seem to apply.
Sasha mentioned that it needs to be accurate, (This seems to happen after the background process related changes)
For timers greater than 1 minute also I am not sure whether it triggers exactly at that time. Sometimes it seems to take long.

**Comment by harmeet-status** [comment]
Comment from @madhurrya:

I have been noticing the same with waku message timers when set for 1 minute, 2 minute
When I have set the timer for 1 minute, it was triggering after about 10 mins and now I have set it to 2mins and it has taken more than 30 mins

![Image](https://github.com/sartography/spiff-arena/assets/104047049/b957d7e1-bdf2-451a-89ae-df2b0bc40aab)

**Comment by harmeet-status** [comment]
Comment from @madhurrya:

This got more than 5 hours to trigger. Timer is set for 20 seconds https://dev.app.spiff.status.im/admin/process-instances/misc:qa:bpmn-model-testing:unit-test-timer-boundary-event/1147

![Image](https://github.com/sartography/spiff-arena/assets/104047049/980cde9d-6886-4449-a945-cb45e6aefa9e)

**Comment by burnettk** [comment]
related to #584

**Comment by dinithihj** [comment]
Tested on dev.mod environment. The timer set to 20 seconds, triggered at 21st second.
Need to retest this again in test.app/ test.mod environments once the background processor is added to those environments.

![image](https://github.com/sartography/spiff-arena/assets/123297840/1cda36ef-5152-4a24-9416-dfd289fc3cd7)
![image](https://github.com/sartography/spiff-arena/assets/123297840/6cefedf3-6c38-46f1-aae7-4a30579284e8)

**Comment by madhurrya** [comment]
Now we have many instances in dev.mod and noticing that the timers are not working properly there now.

Below is a list of timers I tested.

=============Not Working=========================
Boundary Cycle timer - 1 hour - Not triggered even after a day
https://dev.mod.spiff.status.im/i/35865

Boundary timer - 1 hour - Not triggered even after a day
https://dev.mod.spiff.status.im/i/35868

Duration timer - 1 hour - Not triggered even after a day
https://dev.mod.spiff.status.im/i/35871

Start timer - 12 hours - Completes immediately (in other environments it doesn't happen like that)
https://dev.mod.spiff.status.im/i/35890

PP1/PP2 timers - 5 mins  - Not triggered even after a day
https://dev.mod.spiff.status.im/i/35855

=============Working=========================

Cycle Start timer - 6 hours - Works as expected
https://dev.mod.spiff.status.im/i/35884

Cycle Start timer  -30 secs - Works as expected
https://dev.mod.spiff.status.im/i/35892

Timer intermediate catch event - Duration timer - 15 sec  - Works as expected
https://dev.mod.spiff.status.im/i/35889

**Comment by jasquat** [comment]
For 35865, the task with a timer is ef6db7d5-4a7b-4897-aeac-b96233927c2d and that is in the future_task table:

```
[spiff-workflow-backend]> select guid, from_unixtime(run_at_in_seconds) from future_task where guid = 'ef6db7d5-4a7b-4897-aeac-b96233927c2d';
+--------------------------------------+----------------------------------+
| guid                                 | from_unixtime(run_at_in_seconds) |
+--------------------------------------+----------------------------------+
| ef6db7d5-4a7b-4897-aeac-b96233927c2d | 2024-03-02 12:15:29              |
+--------------------------------------+----------------------------------+
1 row in set (0.001 sec)
```

I'm not sure why that isn't running. It probably needs to be queued again for celery but I'm not sure yet where that is breaking down.

**Comment by burnettk** [comment]
we have new instrumentation available on dev.mod. please retest a few of the cases that were not working before. perhaps we can catch one of the issues in the act and see what is going on.

**Comment by madhurrya** [comment]
Test instances. Will check these later whether they work or not.

Boundary Cycle timer - 1 hour
https://dev.mod.spiff.status.im/i/35923

Boundary timer - 1 hour 
https://dev.mod.spiff.status.im/i/35924

Duration timer - 1 hour 
https://dev.mod.spiff.status.im/i/35925

Start timer - 12 hours - Completes immediately (in other environments it doesn't happen like that)
https://dev.mod.spiff.status.im/i/35890

**Comment by madhurrya** [comment]
It'll be good to fix this issue first as it takes a long time to start a process in dev.mod. https://github.com/sartography/spiff-arena/issues/1235

**Comment by madhurrya** [comment]
@burnettk you can use the above instances to see what's happening as none of them are working as expected.

**Comment by madhurrya** [comment]
Will check these instances later

Boundary Cycle timer - 1 hour
https://dev.mod.spiff.status.im/i/35975

Boundary timer - 1 hour
https://dev.mod.spiff.status.im/i/35976

Duration timer - 1 hour
https://dev.mod.spiff.status.im/i/35977

Start timer - 12 hours - Completes immediately (in other environments it doesn't happen like that)
https://dev.mod.spiff.status.im/i/35978

Cycle Start timer - 12 hours (In other environments it creates an instance after 12 hours. But here it seems to create an instance immediately also.)
https://dev.mod.spiff.status.im/i/35989

Timer intermediate catch event - Cycle timer - 2 mins/100 times
https://dev.mod.spiff.status.im/i/35990

**Comment by madhurrya** [comment]
@jasquat These are not working as expected

Boundary Cycle timer - 1 hour (only the first cycle has worked)
https://dev.mod.spiff.status.im/i/35975
https://dev.mod.spiff.status.im/i/35995
https://dev.mod.spiff.status.im/i/35998

Start timer - 12 hours - Completes immediately
https://dev.mod.spiff.status.im/i/35978

Cycle Start timer - 12 hours (In other environments it creates an instance after 12 hours. But here it seems to create an instance immediately also. Not sure it's an issue or not. It's just behaves differently)
https://dev.mod.spiff.status.im/i/35989

**Comment by jasquat** [comment]
@madhurrya we updated dev.mod with timer fixes. It should be ready to test.

**Comment by madhurrya** [comment]
Will check these instances later

Boundary Cycle timer - 1 hour
https://dev.mod.spiff.status.im/i/36003
https://dev.mod.spiff.status.im/i/36004

Start timer - 12 hours
https://dev.mod.spiff.status.im/i/36005

Cycle Start timer - 12 hours
https://dev.mod.spiff.status.im/i/36006

Boundary timer - 1 hour 
https://dev.mod.spiff.status.im/i/36007

Duration timer - 1 hour
https://dev.mod.spiff.status.im/i/36008

Timer intermediate catch event - Cycle timer - 2 mins/100 times
https://dev.mod.spiff.status.im/i/36009

**Comment by madhurrya** [comment]
@jasquat It seems the Issue mentioned in the ticket originally is still there.
"For a timer start event when the time is set for less than one minute, it takes more than a minute to start the timer, the time specified in seconds does not seem to apply."

Start timer - 50sec (seems to take longer to start)
https://dev.mod.spiff.status.im/i/36005

Cycle Timer Start 30s  (seems to take longer to start)
https://dev.mod.spiff.status.im/i/36058

**Comment by burnettk** [comment]
probably not a blocker for shipping celery you think?

**Comment by jasquat** [comment]
Yeah that makes sense. Start events are still processed by the "not_started" background processor. It would be nice to move that over to celery AFTER the initial celery release. It'll take a bit more work to figure out how to do it in celery.

**Comment by madhurrya** [comment]
@jasquat I'll move this to In progress. When the original issue mentioned in the ticket is fixed, please move this to Ready for QA. There's nothing else to be tested in this ticket at the moment.

**Comment by jasquat** [comment]
@madhurrya what's the original issue? timer start events specifically? This ticket has just blown up since then so we need to get a handle on what this ticket is actually about then. I don't think we should keep it as a general timer issue ticket.

**Comment by madhurrya** [comment]
@jasquat The issue explained in the Issue description. 
![image](https://github.com/sartography/spiff-arena/assets/110527567/b897b8e3-1dac-4c61-b435-fd8b9ebaf397)

**Comment by sashayar13** [comment]
@madhurrya, is the issue with Start Timers only there if the timer is set for less than one minute? Have you tried to set the timer to minutes/days? Does it work as expected?

**Comment by madhurrya** [comment]
Sasha, Start timers with 5 mins, 12 hours etc are about 20-30secs off. I think this increases a bit as the number of instances increase. I assume that's OK, compared what we had earlier where things were off my 10-20mins sometimes.
30 sec timer is also about 30sec off (seems to take about 1 mins or so to start).

**Comment by madhurrya** [comment]
Sasha, is it OK to close this ticket or do you feel we need more improvements?

**Comment by sashayar13** [comment]
I assume it is okay to expect some 20-30 secs delay for 5 mins, 12 hours etc. We can close the dev ticket

@calexh-sar I suggest documenting the expected delay under Spiff documentation for process architects to be aware of.

**Comment by calexh-sar** [comment]
@sashayar13 agree with your recommendation to document the expected delay.  I updated the Status to Documentation so it is now in @usama9500's queue.

**Comment by burnettk** [comment]
Yeah, that makes sense. dev.app won’t have the important fixes until celery is shoved out there.
