### ISSUE TITLE
Admin function “Add internal user” - Task Data

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#713]
When Admin adds a user for a task, and the user completes the task, the data about the user should be captured in the task data as well

(example - Request Access → User Task → requestor name)
Before assigning for dev, need more analysis

**Comment by harmeet-status** [comment]
Comment from @sashayar13:

this is delivered for PP1 and PP2, need to updated other process models same way - to use “current user”

**Comment by danfunk** [comment]
@sashayar13 - process related?

**Comment by calexh-sar** [comment]
After discussion, it was determined that this will be handled by process model as is currently being done.
