### ISSUE TITLE
Juro connector

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#714]
Needs to be built so that we can automate the manual copy and paste of various PDF files into BambooHR.

Use-case: Contracts are created in Juro and are currently manually copied into BambooHR. We should automate this. 

It would be nice to use web hooks, when a contract is created, call Spiff and then Spiff can fetch and store that in the DMS and do some other maintenance things. 

https://api-docs.juro.com/?_ga=2.242441986.1453371653.1690360870-2091347451.1690360870#setting-up-webhooks

---
### Complete this bounty ticket
If you think this ticket is something that you are interested in completing, then please follow the steps below:

1. Join our discord server and introduce yourself
2. Do a search for the ticket to see if any discussion on this topic has already happened, if not then feel free to start a new chat
3. Once you understand the work in more detail, come back to this ticket and fill in [this form](https://dev.app.spiff.status.im/)

We are very excited to work with you! Feel free to reach out on Discord

**Comment by harmeet-status** [comment]
@mrtrosen this is the Juro connector that we talked about today.

**Comment by madhurrya** [comment]
@calexh-sar please check this
