### ISSUE TITLE
Add filter by Git version

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#716]
To add the ability to filter Process Instances list by Process model revision for Admins only.  Possibly in Advance Search section.

**Comment by harmeet-status** [comment]
Comment from @sashayar13:

@danfunk the use case would be that Admin user needs to find all running process instances not using the latest process model version and apply some admin actions to process instances with a specific version.

**Comment by madhurrya** [comment]
@calexh-sar please check this
