### ISSUE TITLE
After deleting a instance → Process instance list page shows breadcrumbs

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#720]
After deleting a process instance it takes you to the process instance list page. There it shows a bread crumb. Please see the screenshot.  Return to originating Process Instance page (For Me or All).

![Image](https://github.com/sartography/spiff-arena/assets/104047049/60ee7f59-800e-4642-9256-cc9e89f6a4bb)

**Comment by madhurrya** [comment]
Closing this for now as these will be handled in the new UI
