### ISSUE TITLE
On process error, allow notifications to roles (e.g. support)

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#722]
The requirement was to allow selecting a group of users as recipients of the notification i.e. Support group

**Comment by harmeet-status** [comment]
I wonder where we would get the mapping for group name to BambooID so that we can fetch the Status Chat Keys and notify these users. Perhaps it makes sense to use a Data Store to save multiple calls?

**Comment by harmeet-status** [comment]
Comment from @sashayar13:

We have BBHRids in KeyCloak, assigned to each user.

**Comment by danfunk** [comment]
Errors are handled in a two part process.   Part of the errors are handling in an ["Error Process Model"](https://dev.app.spiff.status.im/editor/process-models/misc:system-message-notification/files/system_message_notification.bpmn) The other is setting "emails", waku handles in the Process Model Edit page.

We have a ticket that would remove all of the configuration of errors from the Process Model Edit page, and move all the logic to this error handling process model.  This would centralize where this logic occurs, could change what kind of message goes where.

**Comment by calexh-sar** [comment]
After discussion during ticket grooming, decided to use DMN tables similar to permissions.

**Comment by madhurrya** [comment]
@calexh-sar please check this
