### ISSUE TITLE
BPMN editor collaboration mode

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#725]
So multiple people can draw simultaneously - like Figma

Allow editing permissions on certain parts of the file, so that changes don't conflict with each other, which multiple people are working on it.

people are saying words over at https://forum.bpmn.io/t/is-it-possible-to-use-bpmn-from-multiple-devices-using-sockets/5893/5

**Comment by madhurrya** [comment]
@calexh-sar please check this
