### ISSUE TITLE
Save as for BPMN Files

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#727]
Failed test scenario E2E-13 "Upload BPMN process file". When trying to upload downloaded bpmn file, getting error "Process id (...) has already been used for..."System should somehow generate a new process id, otherwise Download function is useless

**Comment by harmeet-status** [comment]
Comment from @danfunk:

We need to discuss this, but we suggest we add a Save as button as described below —  In discussions we became unsure of the exact desire of this ticket.
SAVE AS - add the ability to save a bpmn file under a different name and in a different process model path (which will automatically change it’s process id)

**Comment by harmeet-status** [comment]
Comment form @danfunk:

Automatically change the process_id when uploaded - but only if it Exists already?  And show some sort of alert message like “Hey, we changed the process id to be xxxxxx, because yyyyy already existed in the system.”

**Comment by harmeet-status** [comment]
Can we design this in a way where the SAVE AS button will create the BPMN file in a Spiff process model or download it to your computer. You have the choice of both.

@danfunk is there a way that we can design a feature, where we can select part of a process model, through the editor and be able to paste this in another process model.

**Comment by madhurrya** [comment]
@calexh-sar please check this
