### ISSUE TITLE
Download, upload, share perspectives

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#728]
1. Download perspective to your computer
2. Upload a downloaded perspective into Spiff
3. Share a perspective with another user (via sharing a URL)

**Comment by harmeet-status** [comment]
Comment from @danfunk:

Add a button to grab a link to share the prospective, when followed, it will apply all the filter parameters - and these can then be saved by the user if desired.

**Comment by burnettk** [comment]
When you open up the filter thing on the process instance list page, it gives you a little icon that let's you "copy shareable link" and i think that probably satisfies this. Feel free to reopen if not.
