### ISSUE TITLE
PLUGIN: Rename technical IDs

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#729]
[https://github.com/camunda-community-hub/camunda-modeler-plugin-rename-technical-ids#:~:text=First click on the "Generate,the documentation and this example](https://github.com/camunda-community-hub/camunda-modeler-plugin-rename-technical-ids#:~:text=First%20click%20on%20the%20%22Generate,the%20documentation%20and%20this%20example)

**Comment by madhurrya** [comment]
@calexh-sar please check this
