### ISSUE TITLE
Automated testing for BPMN models

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#733]
Incorporate an end-to-end testing system that will allow you to quickly assure that a bpmn model is working as expected. Imagine Cypress tests that you could define and execute in the modeler.

**Comment by harmeet-status** [comment]
https://spiff-arena.readthedocs.io/en/latest/wish_list/wish_list.html#automated-testing

**Comment by burnettk** [comment]
bpmn unit test framework has been implemented. marked this item off on the wish list.
