### ISSUE TITLE
Go to call activity from process model task

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#740]
There should be a hyperlink to go to the Call Activity from the Model. Just like jumping into a sub-process, but still will open in a new tab.

**Comment by madhurrya** [comment]
@harmeet-status in a sub process, when we open the diagram it shows the arrow 
![image](https://github.com/sartography/spiff-arena/assets/110527567/cfa46369-1e7d-4c7a-a0ad-c5cb551683ea)

But for the call activity we see the arrow only if we click on the call activity. 

When we open the diagram no arrow. 
![image](https://github.com/sartography/spiff-arena/assets/110527567/31244c7d-e59a-4906-abcb-df9866e34c67)

If I click the call activity it comes
![image](https://github.com/sartography/spiff-arena/assets/110527567/1cf672dd-5bb3-41e0-aa58-ddd06e9a9b24)

@harmeet-status is that OK?

**Comment by harmeet-status** [comment]
Looks good.

**Comment by madhurrya** [comment]
@harmeet-status This works for a model. But not for a process instance.
If I go to a process instance, I can click the arrow for sub processes and go inside. But not for a call activity. 
Should that be handled under this ticket or a new ticket?

![Image](https://github.com/sartography/spiff-arena/assets/110527567/8caa5117-ed02-4071-87d1-2fd924de8271)

**Comment by harmeet-status** [comment]
Yes we should handle it in this ticket

**Comment by madhurrya** [comment]
Now it works for process instances also
![image](https://github.com/user-attachments/assets/fb3f434b-54a1-45bb-91e8-5b30272797ac)
