### ISSUE TITLE
Message field uplift

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#741]
Per our 09/22 weekly meeting, Daniel's email suggested the following for the Message list page: - Process Id, Message Name, Message Receive ID (Message Catch Event or Receive Task), Correlation Data, Process Model Name, Participant/Pool name (if any)

**Comment by harmeet-status** [comment]
Comment from @sashayar13:

We use them for the system notifications and will use for Notification center (Discord, Status, Email)

**Comment by burnettk** [comment]
we've messed with these columns recently and this ticket is quite old. closing. feel free to reopen.
