### ISSUE TITLE
Process Instance List - columns and filters (proper solution)

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#743]
To review and update the “Filter” and “Clear” behavior for all fields

------------
1. **“Add a column”**. When a user adds a column, the new column is displayed together with the available values (without a need for pressing the “Filter” button). “Condition Value” is empty.
2. **“Remove column”**. When a user removes a column, the column disappears from the screen, and all conditions previously applied to this column are cleared out.
3. **“Add Condition Value” and “Filter”.** If a user wants to add a condition to the column (custom metadata), he needs to enter the value into the “Condition”  → Save → “Filter.”
4. **“Clear”**. The custom metadata columns are kept when the user presses the "Clear" button. 
    1. If a user previously added the "Category" process metadata column and set the Condition Value to "Consulting Fees" , and later they press the "Clear" button, the "Category" column will stay, but the Condition Value will be empty again.
    2. This should work the same way as it is configured for other filters like Status, Process model, etc.

**Comment by harmeet-status** [comment]
Comment from @sashayar13:

a temporary solution was introduced for the UAT (with “Apply”) button, but a proper solution still needs to be delivered. @calexh-sar Is the “Ready for QA” status for the filtering without “Apply”?

**Comment by harmeet-status** [comment]
Comment from @danfunk:

What looks like a simple form here is VERY complicated - with the abiltiy to construct and save custom perspectives, add and remove columns, share URLs — this ticket is really looking to auto-update the list as you make selections, which is large refactoring effort.

**Comment by harmeet-status** [comment]
Comment from @sashayar13:

Smth to think here about as well is to how to filter process instances by “empty” fields. Use case - A user wants to find all process instances where the “Project” (process-defined metadata) value is empty.

**Comment by burnettk** [comment]
note that we did end up implementing "is empty" in the context of another ticket.

**Comment by dinithihj** [comment]
Tested and verified on test.app (Version 190/192)
The "Apply" button is not available anymore, and the filter starts working as soon as the values are set.

1. When a user adds a column, a new column appears with data.
2. When the user removes a column column is removed and any conditions created are also removed.
3. When a user clicks the Save button after setting the condition, the data is filtered accordingly.
4. When a user clicks the clear button, any conditions set on metadata columns are also cleared.

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12
