### ISSUE TITLE
[Editor] Sub process - Blue arrow missing

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#745]
From @madhurrya:

I imported a simple model with a sub process (Download from another model and uploaded) and when I opened it I don’t see the blue arrow icon to go inside.
It came back only after editing the model and adding another activity to that.

![Image](https://github.com/sartography/spiff-arena/assets/104047049/7a579bc6-6028-4816-b9c8-3b8cafb84e86)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/2a5427b4-c8d5-4b1f-a6c8-9cfa423dda02)

**Comment by madhurrya** [comment]
I couldn't recreate this. So closing this issue
