### ISSUE TITLE
User Form validations and dependencies

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#748]
1. “PP3” Program and Projects: To display only Projects values (Enum) which are under the selected Program (same way like we did for Categories and Sub-Categories)
2. “PP3” Project and Hiring Manager? (TBC): To display Hiring manager values (CC list, Enum) who are part of the Project selected (CC - Department)
3. “PP3” “Preferred Start date” value > Today (same in PP1 has been already implemented)

**Comment by calexh-sar** [comment]
No longer valid
