### ISSUE TITLE
Link to keycloak account page from Spiff

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#754]
from #status-client discord channel:

1. jakubgs@August 21, 2023 8:24 AM (EDT)@August 21, 2023 8:24 AM (EDT)@kb could we have a link to Keycloak account console in Spiff UI? it's available under https://${REALM_DOMAIN}/realms/${REALM_NAME}/account/ and allows users to add/remove/update credentials or manage their sessions
2. @August 21, 2023 8:24 AM (EDT)@August 21, 2023 8:24 AM (EDT)@August 21, 2023 8:24 AM (EDT)maybe we could make the email a link? Or a separate link under it called Account or something
3. kb@August 21, 2023 8:25 AM (EDT)@August 21, 2023 8:25 AM (EDT)ya, that should be possible
4. jakubgs@August 21, 2023 8:27 AM (EDT)@August 21, 2023 8:27 AM (EDT)thanks, not super high priority, but would be nice to have
5. @August 21, 2023 8:27 AM (EDT)@August 21, 2023 8:27 AM (EDT)@August 21, 2023 8:27 AM (EDT)since currently people have no idea how to get there if they wanted to

implementation notes:
 * this probably needs to be two different links, and to differ based on environment, since there are two keycloak instances.
 * this might be a good use case for extensions, since we could add arbitrary links in the user profile area, (we could consider replacing the implementation of the documentation link). we would need to link to an extension (that could be accessed via http GET, like the download report extension, and it would need to redirect to the account page).

**Comment by harmeet-status** [comment]
@burnettk feel free to cleanup the description of this issue.

**Comment by burnettk** [comment]
seems fine.

**Comment by burnettk** [comment]
oh, sorry, i was thinking you had edited the issue i filed. let's call this a dup of #708
