### ISSUE TITLE
Parallel gateway and user tasks

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#762]
If we use parallel gateway for “edit request” task + escalation, the “edit request” task is displayed to the requestor immediately.
If I add a timer (to wait for 1 min), the task is not getting assigned to the requestor. The only user task is waiting for an approver
See the example here https://dev.app.spiff.status.im/editor/process-models/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:request-new-role/files/request_new_role_submission.bpmn

process instance - https://dev.app.spiff.status.im/i/16364

UPD: It assigns the task to the requestor when the user gets another task assigned to them

(Created from https://www.notion.so/Parallel-gateway-and-user-tasks-3babf35974f845bda863f06403624d67)

**Comment by calexh-sar** [comment]
@sashayar13, I am a bit confused about this process, so might be missing something about it's intent in my comments.  The first observation I have is there is no merging Parallel Gateway.  This may be causing some of the unwanted behavior you are seeing.

Part of my confusion though is the intent of that Parallel Gateway.  It is not clear to me what is the reasoning behind having the Project Lead determine if edits are required by the Requestor and the Program Lead approve at the same time?  If the Project Lead determines edits are needed, won't any approval done by the Program Lead be nullified?  If so, would it be preferable to request the Program Lead approval after the Project Lead determines no additional edits are required?

(Response added to Notion ticket as well).

**Comment by calexh-sar** [comment]
@sashayar13 the issue with the Edit request User Task not being available after the timer is due to an issue with the background processor taking excessive time to recognize the timer.  This issue should be addressed by the background processor work Jason and KB are working on presently.

When the timer does fire, as you can see in [PI 364](https://dev.app.spiff.status.im/process-instances/for-me/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:request-new-role/364?tab=0), the Edit request User Task does not show up in the Requestor's Waiting for me list:


![Image](https://github.com/sartography/spiff-arena/assets/54854669/8ae86a4e-f5c3-4327-954b-3da1b6d96738)

But if the Requestor clicks on the instance in the Started by me list, they are able to access the Edit request User Task on the Process Instance page:


![Image](https://github.com/sartography/spiff-arena/assets/54854669/9dfb6411-f5e2-466e-898f-c523629d3edc)

I think this is a reasonable scenario, since the Edit request User Task is not technically waiting for Requestor input, but is available if they want to update the process information.

Please let me know if there is any additional investigation you wish for me to do for this issue at this time.  Otherwise, we can revisit again after the background processor updates are available.

**Comment by calexh-sar** [comment]
@sashayar13 I just checked this out with the updated background processor on dev and it appears to be working as designed to me.  Do you agree that no further work is needed on this ticket?

**Comment by sashayar13** [comment]
@calexh-sar It requires more testing (at least the use case I have - Request new role process model), but it works fine from what I see. We can close this ticket and open a new one when/if needed.

**Comment by sashayar13** [comment]
@calexh-sar, actually, I've just checked the process model, and it doesn't look to me like the background processor is fixed. I have 1 min timer which is not fired after 5+ mins, https://dev.app.spiff.status.im/i/3429 And I don't see the timestamp column under the Events anymore

**Comment by burnettk** [comment]
new background processor is currently only on the dev.mod status environment.

**Comment by calexh-sar** [comment]
@dinithihj would you please check this on dev.mod.

**Comment by dinithihj** [comment]
@sashayar13 @calexh-sar I have tested this on dev.mod environment. https://dev.mod.spiff.status.im/i/148

After BO approves the request it showed in requestors Home -> Started by me tab
![image](https://github.com/sartography/spiff-arena/assets/123297840/69e796a1-1638-4c27-8ed4-08e6e9b2f98c)

This is how it looks when the requestor view the process instance immediately after the BO approval
![image](https://github.com/sartography/spiff-arena/assets/123297840/f3a2cad2-722a-41c2-98df-092738c95b4a)

This is the event tab at that moment
![image](https://github.com/sartography/spiff-arena/assets/123297840/771cde31-4479-4cdf-b121-8eab0f3a5d24)

After about `1-2 minutes this is how the process instance displayed to the requestor (with events tab)
![image](https://github.com/sartography/spiff-arena/assets/123297840/c745dac7-241f-4ade-972a-5a61a84e8c77)

This is how it showed on the requestor's Home page after 2 minutes
![image](https://github.com/sartography/spiff-arena/assets/123297840/f6ad9547-cbcb-4eec-8413-61d9cb001615)

When Program-lead opens the request after 2 minutes this is how it looks like.
![image](https://github.com/sartography/spiff-arena/assets/123297840/a3a87948-2b71-4174-bc0f-a12f3f4f8bd6)


I was wondering whether the last screenshot is correct - when the program lead opens it. It says next task is assign to requestor, There's no action for you, but the same time it's giving program lead to review the request- which is confusing.

Please let me know if you want me to do further testing on this.

**Comment by sashayar13** [comment]
thanks for checking this @dinithihj 
I agree with you that the last screenshot it's confusing for a user, but not sure if/how we can eliminate this @calexh-sar

**Comment by burnettk** [comment]
closing as a dup of #1062. feel free to undo this if you disagree.
