### ISSUE TITLE
ui:help and ui:placeholder are not working when creating the form using json form builder

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#764]
- Create a simple text field using json form builder (Click on Add new json file and use Form Builder). 
- Add ui:help and ui:placeholder to the -uischema.json 
- ui:help and ui:placeholder  did not show up as expected
- Sample model - https://dev.app.spiff.status.im/process-models/misc:qa:forms:form-with-text-field-created-manually

They are working as expected when creating the form by loading an example from User Task 

- Create a simple text field by loading a text field example from User Task -> Launch Editor. 
- Add ui:help and ui:placeholder to the -uischema.json 
- They worked as expected. 
- Sample model - https://dev.app.spiff.status.im/process-models/misc:qa:forms:form-with-text-field-loaded-by-examples

**Comment by jasquat** [comment]
@dinithihj https://dev.app.spiff.status.im/process-models/misc:qa:forms:form-with-text-field-created-manually/form/created-manually-schema.json has the field id set to "firstname" while the uischema uses "firstName". These fields are case sensitive and need to match.

**Comment by dinithihj** [comment]
@jasquat Thank you for the comment. I have changed the field ids to match each other but still ui:help and ui:placeholder do not show up as expected. Please see the screenshot.

![764_ui_help_and_ui_placeholder](https://github.com/sartography/spiff-arena/assets/123297840/895bf925-e5b3-4bbe-b559-a0c39076a05c)

**Comment by calexh-sar** [comment]
@dinithihj is this still an issue?

**Comment by harmeet-status** [comment]
@dinithihj any update on this ticket?

**Comment by dinithihj** [comment]
@calexh-sar @harmeet-status This is not an issue now, as per @burnettk 's comment on https://github.com/sartography/spiff-arena/issues/804#issuecomment-1932332128 we do not have the old form builder anymore. 

Therefore moving this ticket to Resolved.

**Comment by dinithihj** [comment]
Closing the ticket
