### ISSUE TITLE
Bug in process instances filter

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#765]
When moving to the next pages and applying a new filter with a reduced number of results, no results will be visible in the results section.

For instance, consider a scenario where the user is in the "My Process Instances" tab. Upon clicking the "Next page" button, the user moves to page 4. While on page 4, the user applies another filter that returns only 14 records. Consequently, no data is presented in the "My Process Instance" tab, leading to confusion. This issue arises because the user was previously on page 4, and presently, there is insufficient data to populate page 4.

![Image](https://github.com/sartography/spiff-arena/assets/123297840/2acbc2f0-bf97-48b8-8656-bf0b929bea77)

Note that if the user returns to page 1 by clicking the "Previous Page" option or selecting 1 from the page number list, the results of the new filter become visible.

Link to the Video - https://drive.google.com/file/d/1J8YUdIfwbnx4Hm4PPKCFwHmhMK3cKvo1/view?usp=sharing

**Comment by burnettk** [comment]
fixed with PR #769

**Comment by burnettk** [comment]
fixed by https://github.com/sartography/spiff-arena/pull/769

**Comment by dinithihj** [comment]
Tested Environment: dev.app
Frontend Version: 307
Backend Version: 309
Comment: Working as expected. Resetting to page 1 when applying a new filter.

**Comment by dinithihj** [comment]
Released to Prod on December 21st

**Comment by madhurrya** [comment]
This issue is already fixed
