### ISSUE TITLE
Git deployment process models issue

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#766]
I'm trying to create a PR for Request Travel process (Test -> prod), but instead it creates a PR to merge changes across all process models. See the recording attached.

We will allow the text box to search using a username or a group name.

**Comment by harmeet-status** [comment]
Video uploaded by @sashayar13:

https://file.notion.so/f/f/1518abd9-c08f-4989-93c1-96525e62bce5/92259964-c88d-4528-b9d9-14f7485f49de/Screen_Recording_2023-10-31_at_3.31.47_PM.mov?id=f43bd1b7-7e4f-49c1-bef1-62e594b474c8&table=block&spaceId=1518abd9-c08f-4989-93c1-96525e62bce5&expirationTimestamp=1701302400000&signature=z3tRqo641cV-JgPOyyKDqbSRVXVkRXfTe9iMeib5LBI&downloadName=Screen+Recording+2023-10-31+at+3.31.47+PM.mov

**Comment by harmeet-status** [comment]
Comment by @burnettk:

this was occurring because there was an old branch of the travel process model and it wasn’t being updated as a part of the promotion process. we have deleted the branch as a temporary fix and will investigate why it wasn’t being updated.

**Comment by harmeet-status** [comment]
Comment by @sashayar13:

@burnettk the issue is back, for request goods/services process model (test.app → prod.mod). But this time under branches it shows the correct number of diffs

![Image](https://github.com/sartography/spiff-arena/assets/104047049/211df115-d76c-4051-b299-62842d219172)
![Image](https://github.com/sartography/spiff-arena/assets/104047049/9a8ca28f-38d3-4c8c-b4bd-480edaa8f86f)

**Comment by harmeet-status** [comment]
Comment by @burnettk 

please delete the branch from GitHub and then republish from the app.

**Comment by harmeet-status** [comment]
This issue is not fixed, we are monitoring to see if it comes back.

**Comment by danfunk** [comment]
Reducing to medium during our monday ticket grooming discussion

**Comment by harmeet-status** [comment]
@burnettk I think that we have a duplicate, can you close on of these?
https://github.com/sartography/spiff-arena/issues/664

**Comment by burnettk** [comment]
we ahead and closed #664. we updated the branch name to to include the target branch, rather than just the process model identifier. this will resolve this issue, we believe: https://github.com/sartography/spiff-arena/commit/07f2cbc8af9d8154e23eff0f2d3965210dceb043

**Comment by dinithihj** [comment]
@sashayar13 Can you please let me know if there's anything I should do related to this ticket?

**Comment by sashayar13** [comment]
@dinithihj no, I don't think so. We can close the issue

**Comment by dinithihj** [comment]
Closing ticket as per Sasha's comment.
