### ISSUE TITLE
AttributeError:user. Error occurred in the Pre-Script (Random)

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#771]
Noticed "AttributeError:user. Error occurred in the Pre-Script" error 2 times in the Get BBHR SME Approver Info Task when checking System Message Notifications

Process instances

- https://dev.app.spiff.status.im/i/730
- https://dev.app.spiff.status.im/i/163

![Image](https://github.com/sartography/spiff-arena/assets/123297840/0e09dfc3-3e2e-4f29-8655-86c0d0b8e4a6)

![Image](https://github.com/sartography/spiff-arena/assets/123297840/1664b052-2e72-491f-81c6-9b86105ef48e)

**Comment by danfunk** [comment]
Random issue that we haven't run into recently.
We recommend not using the get_current_user function if you are not currently on a user task.   As it is otherwise possible that the task is running in the background (disconnected from user interaction) and there is no current user at that time.
