### ISSUE TITLE
Form builder related issues/improvements

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#772]
1. When I try to create files in "Edit JSON Schema" nothing happens. When I close that window and go to the Process Model page I can see the files created. This does not happen always, out of about 10 times this happened about 3 times.

2. When loading multiple components from the "Examples" the created form title and description changes to the last added component related description. If the user has already modified them, those get replaced.

3.1 Dropdown list example has an issue. When added, it shows an error building form.
3.2 When running the process get the error: “Error building form. Attempting to create a selection list with options from variable 'fruits' but it doesn't exist in the Task Data.”
3.3 When set fruits = ["apple", "banana", "pineapple"] in the prescript and try to run it again get the error “Something Went Wrong.”
Process Model: https://dev.app.spiff.status.im/process-models/misc:qa:forms:test-dropdown-list-1

![Image](https://github.com/sartography/spiff-arena/assets/104047049/f547367c-2cb3-4f57-a87c-8b57ec14b6f6)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/f634401d-0ed3-48d2-82cd-363e58fc3b6e)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/cf2f2278-f4fc-4043-a97a-73d8808df989)

4. When launching the editor to edit the Nested form, see this error.
Process Model: https://dev.app.spiff.status.im/process-models/misc:qa:forms:test-nested-form-1

Update : it happens for other items also, when loading the form editor again.
https://dev.app.spiff.status.im/process-models/misc:qa:forms:test-text-area-1
https://dev.app.spiff.status.im/process-models/misc:qa:forms:test-checkbox-1

![Image](https://github.com/sartography/spiff-arena/assets/104047049/b6122c2b-ac79-416a-904b-af5ea61337a4)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/d786f500-cec4-4358-abd3-17aa78fdbc5b)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/e137e4db-1c0d-4570-be38-477a52fd16a6)

5. When you add the Auto Complete example, it looks like it is adding a city field with a date type. So a validation error occurs when running.
Process Model: https://dev.app.spiff.status.im/process-models/misc:qa:forms:test-auto-complete-1

![Image](https://github.com/sartography/spiff-arena/assets/104047049/aa870a8e-6652-43bc-b201-ab2d3a3ad223)

6. When the “No” option is selected in a “Required” Radio button, it gives an error saying “Some fields are invalid” (Same issue Dinithi mentioned in demo site) **-- This is fixed now**
Process Model: https://dev.app.spiff.status.im/process-models/misc:qa:radio-button-test-1

7. This is not a bug, just mentioning the user experience about this and we might not need to do anything related to this.
When building a form by loading components from examples, If I make a mistake, I can't reset or cancel. Since we have the auto save feature, closing and opening the editor doesn't help either.

8. I think it’ll be good to add an example for radio buttons also under ‘Examples’

9. In this form, I have set default values to all the fields. https://dev.app.spiff.status.im/process-models/misc:qa:send-discord-message
I see them in the form builder preview.
But when run the form I don’t see the default values.

![Image](https://github.com/sartography/spiff-arena/assets/104047049/0650231f-f5d3-4a0b-9c87-b7b05552e16a)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/3d7a47f9-2013-457d-a31c-0331df5c3956)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/73108156-f875-4d95-84bc-27dbb32b92f7)

10. Inform the user if there is a field in the Ui Settings that is not also in the Json Schema file (this is often due to a typo that can be hard to find).

**Comment by burnettk** [comment]
hopefully the flakiness issue where nothing happens sometimes is fixed by https://github.com/sartography/spiff-arena/pull/915

**Comment by burnettk** [comment]
closing as dup of #618
