### ISSUE TITLE
Old instances BO/SME approve - time out error/slowness

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#773]
UPDATE 20240312: proposal: avoid handing completed subprocesses to spiff to improve performance.

Noticed that instances create about 10 day or ago (in [test.app](http://test.app/) and [test.mo](http://test.mo/)d both) when BO/SME approves it waits in that page for a long time and shows an error message. Please see the screenshot.
For the instances not that old, didn’t notice the error, but some of them also take a long time to complete in the above step(may be the older ones get more time??)
Here are some videos https://drive.google.com/drive/folders/1bBliE4uYO3a2CjGam3ecdmyUls0bsp8v?usp=sharing

Even if we get these errors, it seems it gets assigned to the next reviewer correctly and they can continue the process.

![Image](https://github.com/sartography/spiff-arena/assets/104047049/4b5a389e-994f-4533-afcd-83265a5f28e5)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/3e77814f-5f68-4b8d-80e3-4829f7e1c70e)

**Comment by harmeet-status** [comment]
Comment from @madhurrya:

Update : when testing old instances for the current release in test.mod I am still noticing this behaviour. I didn’t get any errors this time, but it seems when the instance is older it take more time when submitting the form after BO/SME reviewing. (noticing this with about 20-30 days old instances)

**Comment by madhurrya** [comment]
I am still noticing the delay as the instance get older.

For example please check this video. It shows 2 instances, old one created about 12 days ago and the new one created 1 day ago.
https://drive.google.com/file/d/1Eaw9yJhpLIM4jGMcRMHnklOvCYlCG5Nb/view?usp=sharing

The older it gets, the time increases.
@harmeet-status do we need to fix this?

**Comment by harmeet-status** [comment]
Yes we need to fix performance issues. Back before we went Live, we spent a fair amount of effort focusing on performance and I think that we should be thinking now that we need to scale, so everything that we build has to also be performant!

**Comment by harmeet-status** [comment]
What work is remaining on this?

**Comment by burnettk** [comment]
we think we should add an optimization to avoid considering completed subprocesses. we'll try that and see if it is implementable.

**Comment by jasquat** [comment]
Note we will wait for https://github.com/sartography/SpiffWorkflow/issues/395 before attempting anything with this ticket.

**Comment by jasquat** [comment]
This is ready for qa on dev.mod.

**Comment by madhurrya** [comment]
Don't have a way to test this properly in dev.mod at the moment, since the instances we have are erroring.
Will create new instances when this issue is fixed https://github.com/sartography/spiff-arena/issues/1359

But noticed that loading the PI show page for old instances still takes time. Please watch this video.
https://drive.google.com/file/d/1Sva4avDIDJQPYcx-tQXU5czUEQhpi2ra/view?usp=sharing

I tried to review these 2 instance and both of them got suspended. Not sure whether we need to worry about them.
https://dev.mod.spiff.status.im/i/139
https://dev.mod.spiff.status.im/i/35333

**Comment by jasquat** [comment]
The slowness for 35346 seems that task-info is taking 9 seconds to load. We maybe could clean up that page so that it doesn't need to load everything before displaying items and we maybe could load less in the original task-info call.

**Comment by jasquat** [comment]
I don't think we should worry about pi 139 and 35333 since they seem to be using the get_current_user script from a call activity post script. This cannot work with celery and I believe most of the process models have been updated to move this call to a relevant human task instead.

**Comment by calexh-sar** [comment]
Write script to determine which current instances will be impacted.

**Comment by danfunk** [comment]
This ticket is now dependent on the celery release - and we need to test it once that is completed. There is no additional development work here.  We should move this to "ready for qa" once we deploy celery.

**Comment by calexh-sar** [comment]
Closed per sprint planning discussion.
