### ISSUE TITLE
Waku message timer not accurate

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#774]
It seems the waku message timers for PP1/PP2 are not triggering accurately in 24 hours as it used to do earlier.
Please check these instances for example in [test.app](http://test.app/) - 3825, 9197, 10754, 11453

![Image](https://github.com/sartography/spiff-arena/assets/104047049/122f1b29-e523-485f-8fb4-001e626fe629)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/c63f22b2-2154-4270-9ebe-b3f8d39ae4cf)

**Comment by harmeet-status** [comment]
Comment from @madhurrya:

It seems the delay is increasing now. 

![Image](https://github.com/sartography/spiff-arena/assets/104047049/d94489d2-3748-4305-82aa-f74874b7183a)

**Comment by harmeet-status** [comment]
Comment from @madhurrya:

This ticket could be related to this issue https://www.notion.so/Boundary-timer-taking-long-time-to-trigger-acb30aea1e474406bb9f23f152ee9ed7?pvs=4

**Comment by burnettk** [comment]
related to #584

**Comment by dinithihj** [comment]
Tested on dev.mod environment and the timers look accurate there. Need to retest on test.app/test.mod once the background processor is added to those environments.

![image](https://github.com/sartography/spiff-arena/assets/123297840/e09d3450-1292-479b-9e9a-286a910c05c5)
![image](https://github.com/sartography/spiff-arena/assets/123297840/6dbc9955-085d-4fd4-8fc5-ed2889a543e2)
![image](https://github.com/sartography/spiff-arena/assets/123297840/8e6ab6d0-2cb2-4388-aacd-5d4757b30bfe)

**Comment by madhurrya** [comment]
It seems it has started working accurately again with the recent changes. Need to monitor again some time later to see whether it continues like that. 
https://dev.mod.spiff.status.im/i/35372

![image](https://github.com/sartography/spiff-arena/assets/110527567/a194fdf5-6b71-43e3-b50f-e6d9877966b2)

**Comment by calexh-sar** [comment]
Closed per sprint planning discussion.
