### ISSUE TITLE
Normal user  - Read me file - Edit file option

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#776]
A normal user can click on the edit icon for the readme file and see the file in the editor. But he can't save it. It is better to remove the edit icon, same logic as for all other files should be applied.

![Image](https://github.com/sartography/spiff-arena/assets/104047049/425caddc-94b9-4f68-9b39-019dbbf2bba7)

**Comment by jasquat** [comment]
Fixed with https://github.com/sartography/spiff-arena/commit/a7ab3e21eb06dc3c6d79ff555897329f02b8f674.

**Comment by dinithihj** [comment]
Tested and Verified.
On test.app, the edit button is not visible for admin/normal users
![image](https://github.com/sartography/spiff-arena/assets/123297840/1341a717-4395-4ce6-ae91-6037e976b7d3)
![image](https://github.com/sartography/spiff-arena/assets/123297840/4464c72c-fc5e-4513-8fbb-6c4c7a368e69)


On dev.app, the edit button is not visible for normal users and it is visible for admin users.

**For admin users** 
![image](https://github.com/sartography/spiff-arena/assets/123297840/f3bcc0f8-296b-40d2-a9da-069aba4d84c1)
![image](https://github.com/sartography/spiff-arena/assets/123297840/67d3eaf5-00ca-4dca-b6ee-c15100484b40)

**For normal users**
![image](https://github.com/sartography/spiff-arena/assets/123297840/e1e9e2a8-e609-4041-8349-38d1318704eb)
![image](https://github.com/sartography/spiff-arena/assets/123297840/247a8d14-0446-474a-ab3d-bcd902985eab)

**Comment by dinithihj** [comment]
Released to Prod on December 21st
