### ISSUE TITLE
Requestor chat key update

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#780]
1. When requestor initiated the request he didn’t have a chat key, by the time budget owner approved, requestor had the chat key set. But when it approved, requestor didn’t get the Approved status message, support got a message saying the requestor did not have a chat key.
Instance Id in dev: 8392
2. When the status key of the requestor changed after the request is initiated and before the approval, the Approved status message comes to the user with the status key which requestor had at the initiation of the process.
Instance Id in dev: 8393

**Comment by harmeet-status** [comment]
@dinithi can you pls test.

**Comment by dinithihj** [comment]
@harmeet-status Sorry, I just noticed your comment now. I didn't receive the notifications as it was tagged to an incorrect account. 

I have tested the above 2 scenarios. Both of them are still working as described in the comment. 

1. When requestor initiated the request he didn’t have a chat key, by the time budget owner approved, requestor had the chat key set. -  The requestor did not receive the approved message and support got a message saying the requestor did not have a chat key. Instance: https://test.app.spiff.status.im/i/16678
![image](https://github.com/sartography/spiff-arena/assets/123297840/fa3be834-c334-4f62-ad87-d2d93885e8c8)

3. When the status key of the requestor changed after the request is initiated and before the approval - The approved status message received by the user with the status key which requestor had at the initiation of the process. Instance: https://test.app.spiff.status.im/i/16679

Shall I move the ticket back to the backlog?

**Comment by harmeet-status** [comment]
Looks like the problem here is that the Status Key is probably fetched at the start of the process instance and all further references to this key are from the task data, hence the change in the key value is not registered.

Perhaps we can fix this problem by structuring the process models separately, where sending of Waku messages is a seperate call activity and it's a non-blocking call activity. I think that we wanted to do something like this anyways, do you remember @sashayar13?

@dinithihj let's move back to backlog.

**Comment by calexh-sar** [comment]
@dinithihj this will be ready for testing once PR #913 is merged.

**Comment by calexh-sar** [comment]
@dinithihj this will be ready for testing on PP2 once PR #914 is merged

**Comment by dinithihj** [comment]
Tested and verified both PP1 and PP2 on test.app.  
Now, the messages are sent to the right requestor whose chat key was set at the point of request review. 

1. When requestor initiated the request he didn’t have a chat key, by the time budget owner approved, requestor had the chat key set. - The requestor received the approved message 
2. When the status key of the requestor changed after the request is initiated and before the approval - The approved status message received by the user with the changed status key.

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12
