### ISSUE TITLE
Error with an old instance in prod

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#781]
I tried to terminate an old instance which was suspended before, but got the error (check the screenshot attached)

![Image](https://github.com/sartography/spiff-arena/assets/104047049/487db733-f008-49e4-8c31-bc3e6271f286)

**Comment by jasquat** [comment]
I think this is due to us not storing PREDICTED tasks  in the database. We are now storing them to avoid issues like this so this issue should be resolved going forward.

Looks like we are also trying to suppress KeyError on terminate. We may want to add in ValueError as well.

**Comment by danfunk** [comment]
Closing this - as we now store predicted tasks.
