### ISSUE TITLE
DetachedInstanceError: Instance <ProcessInstanceQueueModel at XX> is not bound to a Session (Random)

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#794]
Received the below error 2 times. 

Process instances

- https://dev.app.spiff.status.im/i/372
- https://dev.app.spiff.status.im/i/1961

There were no errors displayed under the events tab. 

- 372 - After a couple of minutes I refreshed the page and completed the flow without any issues. I was trying to complete the flow for an old instance here.
- 1961 - After a couple of minutes when I refreshed the page, the status was updated to user_input_required. (I did not try to complete the flow). This is a new instance created today and got the error while creating it.

![Image](https://github.com/sartography/spiff-arena/assets/123297840/e030169d-e6d3-4298-bef7-2c4bb664bac8)

![Image](https://github.com/sartography/spiff-arena/assets/123297840/653feab5-ee74-4bc5-816e-ac2c0a3ac5fc)

**Comment by dinithihj** [comment]
Received one more time when creating a new instance. 
![image](https://github.com/sartography/spiff-arena/assets/123297840/4a8e89df-f546-4b4a-9131-08f221d9da8e)

**Comment by dinithihj** [comment]
Received same error again when creating new instance


![Image](https://github.com/sartography/spiff-arena/assets/123297840/161470a0-4775-42c1-bab4-a005fb998ebd)

**Comment by dinithihj** [comment]
Received same error on test.app (2023/12/23) when creating a  new instance. 


![Image](https://github.com/sartography/spiff-arena/assets/123297840/b5f965d0-f1b5-4609-811e-73940731d3bf)

**Comment by dinithihj** [comment]
Received same error on test.mod (2023/12/21) when creating a new instance.


![Image](https://github.com/sartography/spiff-arena/assets/123297840/3da49838-2766-4bc4-976a-5c5498db61aa)

**Comment by dinithihj** [comment]
I keep seeing this error. Today (2023/12/27) got this about 5-6 times when creating new instances in test.app
![image](https://github.com/sartography/spiff-arena/assets/123297840/79fc25b5-03b3-4474-a850-d859dfde7c31)

**Comment by dinithihj** [comment]
Got this when clicked on the start button. 
Video link - https://drive.google.com/file/d/1f02VtA0o15UjPi7fTO_lxALdaSyDtYe6/view?usp=drive_link

**Comment by dinithihj** [comment]
Video link to error when creating new instance - https://drive.google.com/file/d/1kJi4pWKGhn3xAPy8gZtWRw-om7H9njRv/view?usp=sharing

**Comment by dinithihj** [comment]
This error did not occur on dev.app (Version 319/321). I will do further testing on test.app and test.mod environments once we push code there.

**Comment by dinithihj** [comment]
This error did not occur during testing on test.app(version 190/192) and test.mod (version 45/47).

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12

**Comment by madhurrya** [comment]
This issue is already fixed.
