### ISSUE TITLE
Instructions to handle multiple URLs

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#795]
I need assistance to fix an issue I faced when adding a URL array to be displayed in Instructions in a table format.
The current instructions can handle one URL, but adding more urls displays the error (check the body of the task)
the process model - https://dev.app.spiff.status.im/process-models/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:request-new-role

Notion [PIA-267](https://www.notion.so/Instructions-to-handle-multiple-URLs-f43788cd4c0848fdb47e8bbff7082e12)

**Comment by burnettk** [comment]
i mean:

````
{% for icnt in range(url_list | length) %}
````

**Comment by sashayar13** [comment]
thanks, @calexh-sar . The new solution does look simpler

**Comment by calexh-sar** [comment]
Closing since QA will occur later when Sasha is done with PP3
