### ISSUE TITLE
Validation errors (edit request)

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#798]
Validation errors are displayed for the non-required fields when a user goes back and edits the user form.
The screen recording is attached.

[PIA-268](https://www.notion.so/Validation-errors-edit-request-d70e8eff7c0845618f9bdb9218a16838) (Screen recording can be found here)

**Comment by calexh-sar** [comment]
@sashayar13 this appears to be working correctly/. Jason and KB pointed me in the right direction that the Get Labels for Instructions Script Task the each field was set to " " instead of "".  The space was not a valid enum option on the Edit loop.  I also added a blank option to the compensation enum list, since it was not a required field.

**Comment by sashayar13** [comment]
good catch, guys, thanks @calexh-sar
@Kayvon-Martinez, this is what we did for Instructions and Jinja. Let's catch up today, and I'll share the insights

**Comment by dinithihj** [comment]
Tested and verified on dev.app. (Version 316/318)

Now, non-required fields are not displaying as mandatory fields when a user goes back and edits the user form.

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12
