### ISSUE TITLE
extract react json schema form carbon theme

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#803]
There are two open source libraries in the frontend that are related:
 * https://github.com/rjsf-team/react-jsonschema-form - library for rendering forms
 * https://github.com/carbon-design-system/carbon - UI framework

Since we decided to use carbon for our look and feel, we wanted our forms to also fit with this aesthetic. As such, we implemented a react json schema form "theme" to make our forms use carbon components and blend in with the rest of the site. We placed that theme in our codebase. However, react json schema form has themes inside of [their codebase](https://github.com/rjsf-team/react-jsonschema-form/tree/main/packages) for various UI frameworks. It seems like this would be a more appropriate place for this code, and we might benefit from community-maintained upgrades to a greater extent. I asked if they would be willing to accept a pull request to add a theme for carbon, https://github.com/rjsf-team/react-jsonschema-form/issues/3857. It seems like they might be willing to, but we should take them up on their offer to join their meeting and discuss it to make sure we don't waste a bunch of time. I thought of this since @Kayvon-Martinez 's first ticket was related to this area, and he did a good job on it.

It looks like the react json schema form community has been running with this to some extent:
 * https://github.com/rjsf-team/react-jsonschema-form/pull/3883
 * https://carbon.react-jsonschema-form.jianghao.dev/

**Comment by jasquat** [comment]
NOTE: there are still a couple references to material-ui in the carbon theme. These would also have to be updated to use carbon.

They are the "RangeWidget" and "CheckboxesWidget". I'm not entirely sure how those get in used in rjsf.
