### ISSUE TITLE
PP3 Reviewer Comments History

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#817]

**Comment by sashayar13** [comment]
@calexh-sar, thanks for adding the reviewer's comments history. I've checked the updates, and here are a few things that need to be fixed:
1. The current solution doesn't include the Head of PeopleOps comment, but it should.
2. The current solution shows the "Project Lead" role for all reviewers. 

![Image](https://github.com/sartography/spiff-arena/assets/104367255/19c45f59-c84e-4428-a829-2eafe8701313)


3. Also, I couldn't find the place where the Program's Lead comments are added to the Comments history (but I believe it should be done after the Call Activity "Get Program Lead approval")
4. Need to include the Recruiter's comments on the history. (I've added the Comments field for the Recruiter's User Task "Update the request."

let me know if you have any questions

**Comment by calexh-sar** [comment]
@sashayar13 here is the latest reviewer comments stored in Task Data:
  "review_comment_list": [
    {
      "Reviewer": "Project Lead (Infra1)",
      "Reviewer Comment": "Project Lead budget comments by Infra1 Project Lead",
      "Reviewer Comment Date": "28-12-2023",
      "Reviewer Comment Time": "19:00:24"
    },
    {
      "Reviewer": "Program Lead (Peopleops Lead)",
      "Reviewer Comment": "Program Lead reviewer comments by PeopleOps Project Lead",
      "Reviewer Comment Date": "28-12-2023",
      "Reviewer Comment Time": "19:03:26"
    },
    {
      "Reviewer": "Head of PeopleOps (Peopleops Lead)",
      "Reviewer Comment": "Head of PeopleOps comments by PeopleOps Project Lead",
      "Reviewer Comment Date": "28-12-2023",
      "Reviewer Comment Time": "19:04:44"
    },
    {
      "Reviewer": "Recruiter (Ppg.ba)",
      "Reviewer Comment": "Recruiter comments by PPG BA Project Lead",
      "Reviewer Comment Date": "28-12-2023",
      "Reviewer Comment Time": "19:10:03"
    }
  ]

I am not clear if the right lane assignments are getting made since PeopleOps Project Lead is active for the Program Lead and Head of PeopleOps comments.  If you would please clarify this for me, I will be able to better understand the intended process and make the additional comments you requested.

**Comment by sashayar13** [comment]
thanks, @calexh-sar . It looks correct

PeopleOps Project Lead can be a Program Lead if the "New Program" option is selected

**Comment by calexh-sar** [comment]
Marking this ticket as resolved per @sashayar13 last comment.  QA will be done on complete process.
