### ISSUE TITLE
Add spacing between the fields (type: "object")

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#836]
Add spacing between the fields

![Image](https://github.com/sartography/spiff-arena/assets/104367255/6ad35c73-a82a-41d0-827b-e84b69c0b8eb)

**Comment by jasquat** [comment]
Example of the issue https://github.com/status-im/process-models/blob/deploy-app-dev/manage-finance/accounts-payable/process-expense-reports/upload-expense-evidence/upload-expense-without-request-schema.json#L103-L145

**Comment by jasquat** [comment]
Fixed by #850

**Comment by dinithihj** [comment]
Tested and verified. dev.app (Version 317/319) 
Space added between fields.

![image](https://github.com/sartography/spiff-arena/assets/123297840/88172079-084a-4e44-b692-260ed1f1b67a)
![image](https://github.com/sartography/spiff-arena/assets/123297840/798cd938-f6a9-40bc-ae8c-453bdc595508)
![image](https://github.com/sartography/spiff-arena/assets/123297840/bc1a441a-0f7d-47da-9023-222d3c45396c)

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12
