### ISSUE TITLE
Error message in test env while trying to launch JSON schema editor

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#837]
In Test env while trying to launch the JSON schema editor from the bpmn file the user gets this error message
![image](https://github.com/sartography/spiff-arena/assets/137384667/e58060a0-139e-461d-9299-ed173e56293f)

**Comment by calexh-sar** [comment]
From Slack discussion with @danfunk: It is trying to auto-save as soon as you open the editor.  We could change that behavior.

**Comment by madhurrya** [comment]
I think this is the same issue as this https://github.com/sartography/spiff-arena/issues/1199
This was recently fixed (but no deployed in test.app yet)
