### ISSUE TITLE
File links not working

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#838]
Cannot open file links created on PP1 task data. 

![Image](https://github.com/sartography/spiff-arena/assets/123297840/7259b6ea-0bdd-4436-9a25-c18dd6c4184c)

**Comment by jasquat** [comment]
This is probably caused by https://github.com/sartography/spiff-arena/blob/main/spiffworkflow-backend/src/spiffworkflow_backend/routes/process_api_blueprint.py#L186 which was added when we were initially trying to add categories to data objects. I don't think it's needed for file download though.

**Comment by jbirddog** [comment]
> This is probably caused by https://github.com/sartography/spiff-arena/blob/main/spiffworkflow-backend/src/spiffworkflow_backend/routes/process_api_blueprint.py#L186 which was added when we were initially trying to add categories to data objects. I don't think it's needed for file download though.

Removing this param fixes the file download issue.

**Comment by jasquat** [comment]
Fixed in #848

**Comment by dinithihj** [comment]
Tested and verified on dev.app (Version - 319/321)
Now, files can be downloaded by clicking on the file link.

![image](https://github.com/sartography/spiff-arena/assets/123297840/1242120b-c54f-4639-b415-618e99f9c567)
![image](https://github.com/sartography/spiff-arena/assets/123297840/3fd2e89b-1492-443b-800f-7108a862072b)

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12

**Comment by madhurrya** [comment]
This issue is already fixed.
