### ISSUE TITLE
Json `accept` not filtering some files

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#839]
Users can type the file names of not accepted file types on choose file pop-up and upload them. ex- .py is not an accepted file type in the above process model. But users can type the file name "sample.py" and upload the file.  This was seen when using [this process model](https://dev.app.spiff.status.im/editor/process-models/misc:qa:single-file-upload-in-items-test/files/single-file-upload-in-items-test.bpmn) which had the following `accept` list:
```
"accept": [
	".csv",".log",".xml",".email",".eml",".emlx",".msg",".oft",".ost",".pst",".pdf",
	".bmp",".gif",".ico",".jpeg",".heic",".png",".svg",".tiff",".key",".odp",".rtf",
	".pps",".ppt",".pptx",".ods",".xls",".xlsm",".xlsx",".avi",".flv",".h264",
	".m4v",".mkv",".mov",".mp4",".mpg",".mpeg",".wmv",".doc",".docx",".odt",".txt"
]
```
![Image](https://github.com/sartography/spiff-arena/assets/123297840/9ac6f0ba-25d2-48fb-b57a-ea0796bdee9a)

**Comment by jasquat** [comment]
This is default browser behavior. The `accept` option tells the browser to filter to these file types but does not validate that the file is of that type. We could workaround this but it would be messy, potentially a lot of work, and could cause performance issues in the browser as we parse the whole file.

**Comment by burnettk** [comment]
in jason's browser, it didn't show python files by default when .py wasn't in the accept list, but you could still select python files if really wanted to. how this is implemented seems to be highly browser-specific.

**Comment by calexh-sar** [comment]
The previous screenshot I posted was my Chrome browser.  My. FF seems to behave as expected, cannot select or upload a .py file.

![Image](https://github.com/sartography/spiff-arena/assets/54854669/78cb635d-f643-4001-80df-587ba556fb9b)

Are we saying we do not have the ability to control this for specific browsers, or that the LOE may be significantly different than originally anticipated.

**Comment by burnettk** [comment]
yeah, specifically the way browsers deal with `<input type="file" accept="blah" />` is not something we can control. The [mozilla docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept
) put it in this way:

> The accept attribute doesn't validate the types of the selected files; it provides hints for browsers to guide users towards selecting the correct file types. It is still possible (in most cases) for users to toggle an option in the file chooser that makes it possible to override this and select any file they wish, and then choose incorrect file types.

**Comment by burnettk** [comment]
so basically, this json schema feature translates directly to a browser feature. if you specify an "accept" list in the json schema, it will get propagated to the browser. what the browser does with it after that is not something the app can control. closing, but feel free to keep the discussion going or reopen.
