### ISSUE TITLE
Bug in Date Picker

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#853]
1. When you select a date it's resetting to some other date.
2. Cannot type a value on the date picker. It's changing to a different format.

Video Link - https://drive.google.com/file/d/1ePQdS7xfE5a4N1t1S_Xy6baamSWAZ3T-/view?usp=sharing

I have initially noticed this on PP1. For further testing create this process model - https://dev.app.spiff.status.im/process-models/misc:qa:check-date

**Comment by dinithihj** [comment]
@jasquat I still cannot type a value on date picker. When I try to type 05-01-2024 on it below is what happened.
![image](https://github.com/sartography/spiff-arena/assets/123297840/361367f1-1a83-434f-afd3-2af019d01d07)
![image](https://github.com/sartography/spiff-arena/assets/123297840/e4150459-1c1e-4c05-be02-f0450076d81d)

**Comment by jasquat** [comment]
The typing issue should be fixed on dev now.

**Comment by dinithihj** [comment]
Tested and verified on dev.app (version 319/321)

**Comment by jasquat** [comment]
Newest bug fixed with #869.
