### ISSUE TITLE
Breadcrumb navigation disappeared when click on any link

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#860]
hopefully fixed by #862

Steps to recreate

1. Open any process model ex- Request Goods or Services, Then click on any link on the breadcrumb navigation 

![Image](https://github.com/sartography/spiff-arena/assets/123297840/85bd8880-5e9b-43bc-a9ee-e0bd3ab10b66)

2. The breadcrumb navigation is not displaying on the new page loaded

![Image](https://github.com/sartography/spiff-arena/assets/123297840/72149e71-6195-4b0c-a427-d0a0ef62f909)

**Comment by dinithihj** [comment]
Another scenario is, that when you click on the Processes tab and click on any Process group/model, it will not display the breadcrumb navigation

**Comment by dinithihj** [comment]
Note - When you are on the process instance page and click on the process model link then the breadcrumb is NOT disappearing. It shows as expected.

Sample - Click on the Process model name - Check Date
![image](https://github.com/sartography/spiff-arena/assets/123297840/a7000228-b8d4-4616-9f06-563182561d33)
Then Breadcrumb navigation is displaying on the newly loaded page 
![image](https://github.com/sartography/spiff-arena/assets/123297840/3a691463-82ad-4c80-90e0-aee0ef4a450b)

**Comment by burnettk** [comment]
deploying to dev.app

**Comment by dinithihj** [comment]
Tested and verified on dev.app (Version 320/322)
Now the breadcrumb navigation does not disappear when clicking on links.
![image](https://github.com/sartography/spiff-arena/assets/123297840/557d0dad-56fa-4524-a6ba-c421bf8db7ea)

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12

**Comment by madhurrya** [comment]
This is fixed.
