### ISSUE TITLE
Archiving a process model

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#861]
Process models will be deprecated at some point, due to various reasons. We need the ability to signal process models as archived, while keeping the completed process instances. It makes sense to move the process models into some type of archived folder and marked as such in the interface as well.

Do not allow process models with active instances to be archived.

This ticket is related to: https://github.com/sartography/spiff-arena/issues/749

**Comment by calexh-sar** [comment]
Won't fix, handle with #749
