### ISSUE TITLE
UI tweaks (Part 2)

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#863]
1. Title spacing is inconsistent
![Image](https://github.com/sartography/spiff-arena/assets/104047049/a6c755df-dc31-4070-8dce-44a1d12c23e2)

2. All buttons should follow convention, only first letter is capital, all else small. I.e. Cancel request, Edit request
![Image](https://github.com/sartography/spiff-arena/assets/104047049/d67ccdbb-5fd2-4d26-97e3-480fa389d85a)

3. Buttons need to be responsive
![Image](https://github.com/sartography/spiff-arena/assets/104047049/62c1b031-5cdf-4885-a935-eff67ec31ea0)

4. Make this grey lighter color. Also the spacing between top and bottom in inconsistent.
![Image](https://github.com/sartography/spiff-arena/assets/104047049/b5425fcf-e67d-4577-b4eb-e5dc89931f70)

5. The description text should be closer to the title, rather than the fields below
![Image](https://github.com/sartography/spiff-arena/assets/104047049/f396f507-eb40-4dce-81ae-30b48ca83852)

6. Is there a better color that we can use here, perhaps grey and white to make it look more interesting?
![Image](https://github.com/sartography/spiff-arena/assets/104047049/1afcc053-13f3-42f7-aafc-7599eaaa739b)

7. This is too close to the title, needs a bit of spacing in between. Make this consistent for all forms.
![Image](https://github.com/sartography/spiff-arena/assets/104047049/59974953-82fa-4fa3-97ae-b33b3c89bf9d)

8. Remove the spacing between the title and description. Abide by the spacing listed in 7.
![Image](https://github.com/sartography/spiff-arena/assets/104047049/dde758cd-5f7d-4b0c-b556-146c635ae852)

9. Choose file button needs to be left aligned. The delete button is also inconsistently spaced.
![Image](https://github.com/sartography/spiff-arena/assets/104047049/c7391192-ca31-4c03-9514-d038da466224)

10. Tables headers (Home page, Process Instances) - add a tooltip (help text displayed when a user hovers over the name of the column)

11. Make the metadata column wider
![Image](https://github.com/sartography/spiff-arena/assets/104047049/18cf5bbb-e069-4b04-a4a9-bd753cf916e2)

12. Last milestone - full text is not displayed, and the tooltip is displayed with a delay.
https://www.notion.so/UI-tweaks-take-two-de344efb65be47ed9e5bb4543aa746d2?pvs=4#252768a250254de8a19dd05e3671dc65

**Comment by calexh-sar** [comment]
Closing, new UI effort will address elsewhere.
