### ISSUE TITLE
Add filter by “Waiting For”

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#865]
Add filtering functionality by “Waiting For” an individual or a group to Process Instances list.

**Comment by calexh-sar** [comment]
Consider using a typeahead that has both individuals and groups.

**Comment by burnettk** [comment]
branch https://github.com/sartography/spiff-arena/tree/feature/waiting-for-filter started. we were thinking we'd probably have a new API that returned something like:

````json
[
  {
    "type": "User",
    "entity": {
      "name": "Jon",
      "etc": true
    }
  },
  {
    "type": "Group",
    "entity": {
      "name": "Joint Chiefs of Staff",
      "etc": true
    }
  }
]
````

then the frontend could formulate the appropriate filters.

**Comment by burnettk** [comment]
deferring
