### ISSUE TITLE
Radio button (UI tweaks)

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#879]
Improve the latest changes introduced to the radio component:
1. add space after the name of the field
2. ensure that it wraps on mobile

![Image](https://github.com/sartography/spiff-arena/assets/104047049/13e12133-7f0c-44c7-a634-6a4e384ff9ec)

**Comment by calexh-sar** [comment]
Include in UI Style Guide project

**Comment by calexh-sar** [comment]
Closing per Ticket Grooming meeting discussion.
