### ISSUE TITLE
Missing process groups

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#880]
Noticed that in dev.app we have a set of folders and files for Extensions and Api Keys https://dev.app.spiff.status.im/process-groups/misc:extensions 
While in test.app we have only 2 process models which are not even part of a process group. See the screenshots attached for "Create" process model in dev.app vs test.app.
Why lack of the process group file in test.app didn't cause any error? Previously if there is no process group json file, the spiff displayed the error to a user

![Image](https://github.com/sartography/spiff-arena/assets/104047049/93765fa3-3813-4571-9afe-4efae31f3bd6)
![Image](https://github.com/sartography/spiff-arena/assets/104047049/537750a8-3dd6-439c-89c3-2dff71c4820e)
![Image](https://github.com/sartography/spiff-arena/assets/104047049/3f01fe2b-eec3-4137-9c11-399fb98f20be)

**Comment by jasquat** [comment]
I think this is a dup of #860. Closing this in favor of that one. The fix is on dev.app but not test.app yet. Closing this.
