### ISSUE TITLE
New Form Builder bugs

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#882]
1.  word duplicated
![Image](https://github.com/sartography/spiff-arena/assets/104047049/41684ee1-15aa-4cdd-a02d-5990e6c62263)

2. After entering a name in the text box, when I click Create files, nothing happens.  It seems it creates the schema files, but user has no clue. May be we can close the popup or show a message to the user.
![Image](https://github.com/sartography/spiff-arena/assets/104047049/0b990aa8-89ae-4912-9399-b0fa5311370d)

**Comment by harmeet-status** [comment]
@burnettk yeah I will do that from now on. This one I couldn't find, sometimes I change the title from Notion to Github. This particular one is probably @madhurrya

**Comment by burnettk** [comment]
Nice, thanks, @harmeet-status

**Comment by dinithihj** [comment]
Tested and verified on dev.app (Version 325/327)
1. Dupicated word is no longer available 
![image](https://github.com/sartography/spiff-arena/assets/123297840/bebecea0-53f3-4b59-bed7-66113f69efe2)

2. After entering a name and clicking on the "Create Files" button, the next screen opens "Edit JSON Schema."
![image](https://github.com/sartography/spiff-arena/assets/123297840/a488bd8c-411d-4b83-9036-549fe3da556f)

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12
