### ISSUE TITLE
[Editor]Expanded sub process looking weird

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#883]
When I add a task and set it as expanded sub process, it looks bit weird. But if I add a expanded sub process directly from the menu items then it looks Ok. Please see the video. https://drive.google.com/file/d/1f0KjpPTuHHkvIWaENMialfPx8x_8wndt/view?usp=sharing

**Comment by jasquat** [comment]
@harmeet-status this is how bpmn-js displays it. The Start event is actually outside of the subprocess hence the lines although it does display "inside" the box. You have to move it out of the box for a better visual representation. I'm not sure if we can address this or not without rewriting core bpmn-js code.

**Comment by harmeet-status** [comment]
Closing this ticket, as is default behavior.
