### ISSUE TITLE
Existing diagrams - User tasks not showing the form attached to it

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#884]
When I go to a User Task in an existing diagram, I can’t see the Json schema file name. But the when I run the diagram the form that was already there works. May be this happens after the new Form related changes. But not noticing it in every User task.
E.g. https://dev.app.spiff.status.im/editor/process-models/misc:test:madhu-model-1/files/MadhuModel1.bpmn
https://dev.app.spiff.status.im/editor/process-models/misc:test:process-model-with-form-and-lane/files/form_and_lane.bpmn
![Image](https://github.com/sartography/spiff-arena/assets/104047049/0fd5c324-6b9f-4090-9cc3-c74c450ea3b7)

**Comment by madhurrya** [comment]
I think this happened with couple of old models I had. Since no one else complained about it I'll close this issue.
