### ISSUE TITLE
[UI/UX Minor] Save button and Zoom icons tooltip overlap

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#886]
Process Model Editor: Tool tips of Zoom buttons overlap on the "Save" button, when the mouse moves from below to save button, so the user can't click it. 
Please see the screenshot

![Image](https://github.com/sartography/spiff-arena/assets/104047049/c4144e44-b121-49bb-93d1-e571265949c6)

**Comment by jasquat** [comment]
@harmeet-status where was this screen shot taken? I can't reference to that button in the code and I didn't see it on dev.app or test.mod. Only the icon "Zoom fit" exists.

**Comment by burnettk** [comment]
there is a proposal to change the UX related to this fairly substantially, fwiw. we should have it available to look at somewhere soon.

**Comment by harmeet-status** [comment]
@madhurrya do you remember which environment this pic was taken in?

**Comment by madhurrya** [comment]
@harmeet-status This was in dev.app but not sure which browser it was. I just checked in Chrome, FF and Edge now but didn't notice it today.

**Comment by harmeet-status** [comment]
@madhurrya ok lets close this, will open a new one when it becomes an issue again.

**Comment by calexh-sar** [comment]
Closed per comment above.
