### ISSUE TITLE
API Keys - UI/UX minor issues

### ISSUE THREAD

**Issue by harmeet-status** [sartography/spiff-arena#889]
1. When I add a new key, it doesn’t come in the table. We have to refresh the page to see it.
![Image](https://github.com/sartography/spiff-arena/assets/104047049/3e0785f0-de19-456f-ba4c-8f8a17d56b6c)

2. Keys with spaces doesn’t work.
![Image](https://github.com/sartography/spiff-arena/assets/104047049/d2b84e78-c47b-421a-aa39-8596c5e27d7c)

**Comment by madhurrya** [comment]
Closing this minor UI issue for now as these will be handled in the new UI
