### ISSUE TITLE
Id-generator

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#892]
We need to have a function/field type that allows us to auto-generate a unique id for input based on a certain logic.

Use case:
1. A user needs to create an Event as a dimension
2. They start a process and provide their input through a User Form
3. At the moment when the form is being submitted, a unique ID is being created by Spiff
4. This ID belongs only to this Event/process instance
5. This ID will be written to an external system and will be used across other processes/documents/reports

Is this smth we can use https://www.npmjs.com/package/react-id-generator ?

**Comment by burnettk** [comment]
so the user should not know this is happening? could it be like a hidden field that has an autogenerated value (possibly generated in a pre-script)? could it be generated in a script task and then subsequently used in a service task?

**Comment by sashayar13** [comment]
@burnettk I'd expect that the field will be displayed but disabled or displayed as part of Instructions. The user needs to know the ID before it will be used in a service task

**Comment by sashayar13** [comment]
Just checked the API docs of the external system https://api.iplicit.com/api-docs/index.html#/ (Catalogs -> PUT request). The request expects us to provide the "code".
It seems that we need to generate unique consequent codes on Spiff's side. 

max length: 50
no symbols or spaces, no leading zeros

@burnettk @danfunk @jbirddog 
What are the options we have, and what would be the effort associated?

FYI, @MarD0607 @harmeet-status

**Comment by sashayar13** [comment]
@MarD0607, what if we really use the process instance ID but with a prefix?
For example:
1. INV123 - for invoices
2. PO123 - for POs
3. EV123 - for events
4. PJ123 - for projects
5. PG123 - for programs

**Comment by sashayar13** [comment]
got an ok from a process owner to process with this pattern for Events

**Comment by burnettk** [comment]
Cool, I labeled this “process” then, as I believe the process instance id script is available.

**Comment by MarD0607** [comment]
As far as Vendors or Suppliers are concerned, the matter is a bit more difficult.
For suppliers related to CCs we can use any ID logic as long as we link it to the BBHR ID of the CC.
For third party Vendors, the best approach would be to generate the ID on Postgress side and use the same logic as the one implemented in the external finance system.

**Comment by sashayar13** [comment]
@MarD0607 is there any dev work needed for CCs/Vendors? or it can be all handled as part of process models design?

**Comment by MarD0607** [comment]
@sashayar13 I don't think we will need any dev work for CCs/Vendors. We can generate IDs in Postgress and use foreign keys in Iplicit to uniquely identify any Iplicit IDs to BBHR IDs or Postgres generated IDs.

**Comment by harmeet-status** [comment]
@MarD0607 we should avoid building any new functionality in Postgres as our long term strategy is to decommission it. We should be slowly trying to get rid of it.

See this page here that @sashayar13 put together.
https://www.notion.so/PostgresDB-one-pager-f1654c2780334df3b493c3a2c5b16f1d

**Comment by calexh-sar** [comment]
Unless otherwise indicated later, will assume the process architect will use the process id concatenated with something else to achieve this and no dev work is needed.  @harmeet-status @sashayar13 @MarD0607

**Comment by calexh-sar** [comment]
Not needed at this time per discussion with team.
