### ISSUE TITLE
Move BO Holiday Check in PP1 & PP2

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#896]
In Slack discussion, @dinithihj identified that the BO Holiday Check should be done at the time the BO check is needed and not as part of the Requestor submission as it currently is done.  @sashayar13  requested that the check be moved to the budget_owner_approval process to improve its effectiveness.

**Comment by calexh-sar** [comment]
@dinithihj would you please test this in PP1 on dev.

**Comment by dinithihj** [comment]
@calexh-sar getting the below error when trying to create a PP1 on dev. 
Process Instance - https://dev.app.spiff.status.im/i/5844


![image](https://github.com/sartography/spiff-arena/assets/123297840/c4e52ced-5bf0-4681-9a0c-30d38cdb7052)

**Comment by calexh-sar** [comment]
@dinithihj please retest.

**Comment by dinithihj** [comment]
@calexh-sar getting below error when submitting the request.
Process Instance - https://dev.app.spiff.status.im/i/5897

![image](https://github.com/sartography/spiff-arena/assets/123297840/b5c8f348-25bf-43bc-918b-d0543e51b85c)

**Comment by calexh-sar** [comment]
@dinithihj please retest.

**Comment by calexh-sar** [comment]
@dinithihj please retest.

**Comment by dinithihj** [comment]
@calexh-sar This is still not assigned to L2 BO, still assigned to BO. Checked both PP1 and PP2.
https://dev.app.spiff.status.im/i/6325
https://dev.app.spiff.status.im/i/6326

To double check- tested on the test.mod (current prod version) with the same holiday entry on bamboohr. There both PP1 and PP2 were assigned to L2 BO as expected.
https://test.mod.spiff.status.im/i/7713
https://test.mod.spiff.status.im/i/7714

**Comment by calexh-sar** [comment]
@dinithihj please retest.

**Comment by dinithihj** [comment]
@calexh-sar Now when the L1 BO is off request is assigned to L2 BO, When the L2 BO reviews and submits the outcome, an error message is shown.

PP1 : https://dev.app.spiff.status.im/i/6572
PP2 : https://dev.app.spiff.status.im/i/6565

![image](https://github.com/sartography/spiff-arena/assets/123297840/e8769446-454b-46f6-bfa2-873077017099)

**Comment by calexh-sar** [comment]
@dinithihj please retest.

**Comment by dinithihj** [comment]
Tested and verified on dev.app and test.mod environments.

**Comment by dinithihj** [comment]
Model changes released to prod on 2024/01/29
