### ISSUE TITLE
All the PP1/PP2 old pending instances got suspended on test.app

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#900]
With the new code deployment on test.app (version 188/190) all the PP1/PP2 old pending instances got suspended. Events tab contained error - DataObject.__init__() missing 1 required positional argument: 'category'

![Image](https://github.com/sartography/spiff-arena/assets/123297840/03904b9d-8c2d-46bf-b83a-7625a869de2a)

![Image](https://github.com/sartography/spiff-arena/assets/123297840/30770511-a869-4c63-8872-3a30e1a52828)

![Image](https://github.com/sartography/spiff-arena/assets/123297840/a91c30f2-1fc3-4ff4-9ec1-6b6b27cd9ebc)

**Comment by dinithihj** [comment]
Noticed this error on dev.app on a couple of instances earlier but I thought it was due to a process model change. Since we didn't have many old instances on dev.app did not notice that the issue affected to all old instances.

However, done further investigation today on dev.app and noticed that this happened on dev.app environment on the 13th of December. 

![Screenshot 2024-01-16 162803](https://github.com/sartography/spiff-arena/assets/123297840/336064b5-ece9-4304-b2d1-b7b12d7838c4)

**Comment by dinithihj** [comment]
Checked this issue on dev.mod environment it also had the same issue after the version released on January 13th (Version 59/50)
On the events tab the error was repeated 

https://dev.mod.spiff.status.im/i/158
![image](https://github.com/sartography/spiff-arena/assets/123297840/36bd395c-1dd2-4b60-bd5a-f1b1f2ea8cee)

https://dev.mod.spiff.status.im/i/161
![image](https://github.com/sartography/spiff-arena/assets/123297840/9bfa46fd-b24e-4613-a828-3efabb445dd6)

**Comment by dinithihj** [comment]
Asked the team to deploy test.mod code to dev.spiff environment, created instances on dev.spiff, and asked the team to push data object category fix on top of that. 

Old instances were not suspended with the fix. Tested a few old instances and they were able to go through the flow without any problems.

**Comment by dinithihj** [comment]
Tested on test.mod. (version 45/47) 
The version release did not suspend old instances.

**Comment by madhurrya** [comment]
Closing this issue.
