### ISSUE TITLE
Events Data Store

### ISSUE THREAD

**Issue by calexh-sar** [sartography/spiff-arena#906]
Per discussion with @sashayar13 in Discord, create an Events Data Store that is updated in the [Create Event Process Model](https://dev.app.spiff.status.im/process-models/comms-and-brand:event-management:event-execution:create-event) to be used in other processes to display information about the event.

**Comment by calexh-sar** [comment]
@sashayar13 this is ready for your review and comments.

**Comment by madhurrya** [comment]
@calexh-sar please see my comments below. 
1. When user select an existing event, go to edit page and click "Next", an error displayed in "Purpose" field, saying "Purpose must be string".
![Image](https://github.com/sartography/spiff-arena/assets/110527567/abb700ff-5e31-45d3-ae54-318efc5731c3)


2. First select an existing event, go to edit page, change the event name and complete the process. Then start the process again go to even selection dropdown, you will still see the initial event name in the dropdown. But when you go to edit page again you will see the modified name.
![Image](https://github.com/sartography/spiff-arena/assets/110527567/48c67bb4-9ee1-4de4-a228-e59f73f04224)

![Image](https://github.com/sartography/spiff-arena/assets/110527567/25644049-fa19-4125-b899-dd33a9f68368)

3. What is the purpose of the Review page?
![Image](https://github.com/sartography/spiff-arena/assets/110527567/8a87c576-ca24-4a09-ba65-2ef38f75b1bc)

4. When you go to edit page the title still shows as "Create a new event", isn't it better to change this?
![Image](https://github.com/sartography/spiff-arena/assets/110527567/15e79348-58d7-46b4-823d-daa07599c1e2)

**Comment by calexh-sar** [comment]
@madhurrya please confirm your four comments have been addressed.

**Comment by calexh-sar** [comment]
@madhurrya the issue when adding a new event has been fixed.

**Comment by madhurrya** [comment]
Tested in dev.app

**Comment by madhurrya** [comment]
@calexh-sar 
When I click Edit in Review page, in the first form noticing this at the bottom of the page.
![image](https://github.com/sartography/spiff-arena/assets/110527567/3bf460fb-72be-49a1-b7e6-904114693b05)

![image](https://github.com/sartography/spiff-arena/assets/110527567/67f49d11-f3d6-43ff-8b78-ba71ad0ed1fd)

**Comment by calexh-sar** [comment]
@madhurrya I just tried to edit an existing event and the header information seemed to be in the correct location.  If you are still seeing this, there is nothing I know to do from a process model configuration perspective that would fix this and another ticket should be made for the devs.

![Image](https://github.com/sartography/spiff-arena/assets/54854669/53566df6-5b40-491e-b921-cd8669d90207)

**Comment by madhurrya** [comment]
@calexh-sar This is the issue, please let me know whether I should create a new ticket. https://drive.google.com/file/d/1USAMalxQFcTLdc3nsCsZgsn88GLPMVR7/view?usp=sharing

**Comment by madhurrya** [comment]
Created a new ticket for the above issue. https://github.com/sartography/spiff-arena/issues/1175

**Comment by madhurrya** [comment]
@calexh-sar 
When I edited some info in the Event, I got this error. 
https://test.app.spiff.status.im/i/3100
![image](https://github.com/sartography/spiff-arena/assets/110527567/fe4085fc-8624-4037-b9cd-c1cb640618a2)

**Comment by madhurrya** [comment]
@sashayar13 should we allow adding multiple events with the same name or should the event name be unique?

**Comment by madhurrya** [comment]
Noticed that if we use the open quote (the key before the Number 1 key in the keyboard) in both Event name and Purpose, the Review information get messed up. Not sure whether this is something that needs to get fixed.
 
![image](https://github.com/sartography/spiff-arena/assets/110527567/aeff610a-3101-4f0b-a06a-f50dbf6f82bf)
![image](https://github.com/sartography/spiff-arena/assets/110527567/c16b5b06-3d46-477b-bed8-99758fd9d931)

**Comment by calexh-sar** [comment]
@sashayar13 is ^ an issue or will the ` character not be used in these cases?

**Comment by madhurrya** [comment]
Added an Issue for the special character issue, since it is a common issue for all the forms. https://github.com/sartography/spiff-arena/issues/1474

**Comment by sashayar13** [comment]
@madhurrya Event id should be unique, no restriction for the Event Name yet

**Comment by sashayar13** [comment]
@calexh-sar @madhurrya I don't expect users will enter ^ into the Name or Purpose.
However, I can imagine when a user enters the character ` or uses the breakdown in the Purpose. Suggest the adjustments for this case should be implemented

**Comment by madhurrya** [comment]
I have already created a new ticket for the special character issue as it is common for other models also. https://github.com/sartography/spiff-arena/issues/1474
I think Sasha can prioritize it accordingly and better to close this.

**Comment by sashayar13** [comment]
let's close this one
