### ISSUE TITLE
JSON Schema files can be saved without a name

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#911]
Click on Web Form -> Launch Editor on the User Task Property window

![Image](https://github.com/sartography/spiff-arena/assets/123297840/6fa68232-a38d-4d41-8a81-9d7f4779af78)

Click on the Create button without entering a name

![Image](https://github.com/sartography/spiff-arena/assets/123297840/def970ed-9c97-470e-bd9f-7d69e17c70a1)

JSON schema files were created without a name

![Image](https://github.com/sartography/spiff-arena/assets/123297840/06d81228-8b5e-46a8-ad0a-73219661e153)

![Image](https://github.com/sartography/spiff-arena/assets/123297840/8cc6c3e2-d627-4482-b291-e474496ce283)

**Comment by burnettk** [comment]
addressed by https://github.com/sartography/spiff-arena/pull/915

**Comment by dinithihj** [comment]
Tested and verified on dev.app (325/327)
Now, cannot save JSON schema files without a name.

![image](https://github.com/sartography/spiff-arena/assets/123297840/183c40f4-d07a-46f8-aaef-c7a09e973aee)

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12

**Comment by madhurrya** [comment]
This is fixed.
