### ISSUE TITLE
Vendor Onboarding - Register a New Contact

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#912]
Please review and fix the Pre-Script and Post-Script in the Call Check Vendor Stored Procedure step.
The Pre-Script currently does not include "fetch_results": True, which results in the input_json data to be saved in the Postgres tables.
Otherwise if the fetch code line is enabled than the input_json data is not saved in the DB tables.

The Post-Script requires refactoring as the result from the stored procedure has changed.

In the Show the Vendor Data Notification step, please refactor the Instructions so that the  = false option displays also the status returned by the stored procedure in the text:
"The contact details you have just added correspond to an existing entry in the Vendor Master Data. The status of the vendor contact is .(status)......"

**Comment by calexh-sar** [comment]
@MarD0607 is the intent of this process to update the Postgres database with the vendor info if the vendor is not found?  Right now it appears to only check the database if the vendor exists already or not, but regardless of what I enter it seems to always return `"true, New"`.

**Comment by MarD0607** [comment]
@calexh-sar Yes, the intent is to add the vendor information if it does not already exist. When I tested it would return also false, new but the problem was that the vendor data was not actually been added in the database. Then Lalo suggested to exclude from the script in the call activity the line fetch : true. That way the data was being added to the database but the normalizing script and instructions in the manual step need to be changed now.

**Comment by MarD0607** [comment]
@calexh-sar 
The last step of the process which should show the user a notification as a result of the process, is not generating any of the 2 possible responses.
The instructions were set for a response of the the type is_new, but in the process data I can see now the response from the stored procedure is again "resp_check": {"body": "{\"result\": \"1 rows affected\"}"
I believe now the stored procedure is returning a table again and not a string.
Is there a way to normalize the response and get a value such as true or false , so that the instructions in the last step may work?

**Comment by MarD0607** [comment]
Confirm all working ok now.
We can close the ticket.

**Comment by calexh-sar** [comment]
Closing per Marius' comment above.
