### ISSUE TITLE
Vendor Onboarding - Start Vendor Onboarding

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#913]
https://dev.app.spiff.status.im/editor/process-models/manage-procurement:vendor-lifecycle-management:vendor-onboarding:start-vendor-onboarding/files/Start%20Vendor%20Onboarding.bpmn

In the user activity Enter Vendor Data, the form is not showing properly all the required fields even if they are specified as such in the JSON schema.

**Comment by calexh-sar** [comment]
@MarD0607 the `required` is now working as designed.  There were two problems I found:

1. The entries in the required section were not the same as the field names.  Usually there was a missing `_`.
2. The indentation level of the `required` section was incorrect.  It was at the field name level and not the `properties` level.

There were a few fields that were not in the `required` lists.  I did not add these, just in case they were not required.

Please let me know if you need any additional assistance on this issue or not.

**Comment by MarD0607** [comment]
@calexh-sar
I am experiencing several issues now:
1. when the user opens the first form, the dropdown for selecting an existing contact will show only 1 entry and there are several available
2. after completing the form as a guest and submitting the form the process shows this error message
![image](https://github.com/sartography/spiff-arena/assets/137384667/d5d9c46f-9bc1-4a85-81c6-4c45da6396d6)

**Comment by calexh-sar** [comment]
@MarD0607 regarding #1 above, there are currently three vendors in the dropdown list.  Is this working correctly now?

**Comment by MarD0607** [comment]
No, there should be more

**Comment by calexh-sar** [comment]
@MarD0607 I believe that #2 is now addressed.  You should review the data that is being stored in the Postgres table to confirm that it is in the format you are expecting.  Back to #1.

**Comment by calexh-sar** [comment]
@MarD0607 based on the Discord chat with Lalo, am I assuming correct that this ticket is complete?

**Comment by MarD0607** [comment]
@calexh-sar Yes we can for the moment close this ticket, I will run conjugated tests of Register a New Contact with Vendor Onboarding and see how data is stored and changed as well.

**Comment by calexh-sar** [comment]
Closing per Marius' comment above.
