### ISSUE TITLE
PP3 - process automation assistance

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#916]
@calexh-sar could you pls assist with the following things (https://dev.app.spiff.status.im/process-models/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:request-new-role) :
1. Need info path
- check why the process instance creates 2 user tasks when the Program Lead requests More Info (Boundary Events are used)
- Display Review History to Requestor
- add Comments cleanup, so that when a user wants to add a new comment, the field is empty (Requestor, Budget Owner, Program Lead, Head of PeopleOps)

**Comment by calexh-sar** [comment]
@sashayar13 for "check why the process instance creates 2 user tasks...", we determined the reason was Escalation Events need a value in the Escalation Code field to be unique.  With no value in there, both Escalation Boundary events were fired and each called for the creation of that User Task.  @essweine checked the [BPMN 2.0 spec](https://www.omg.org/spec/BPMN/2.0.2/PDF#G11.93832) and SpiffWorkflow was executing this correctly, so no code changes needed, just additional diagram configuration.  I updated the process and this is no longer an issue. 

![Image](https://github.com/sartography/spiff-arena/assets/54854669/6bcee893-3d70-4bcf-b8b1-a00acac97a32)

**Comment by sashayar13** [comment]
thank you both @calexh-sar @essweine for checking this! I'm glad that no code changes are needed :)

**Comment by calexh-sar** [comment]
@sashayar13, @dinithihj just did an initial round of testing and so far Review History and Comment cleanup appear to be taken care of.  Will check back and see if Dinithi or yourself find anything that needs addressing after further testing and review.

**Comment by calexh-sar** [comment]
@sashayar13 is there any additional work needed for this issue?

**Comment by calexh-sar** [comment]
@sashayar13 is there any additional work needed for this issue?

**Comment by calexh-sar** [comment]
@sashayar13 is there any additional work needed for this issue?

**Comment by calexh-sar** [comment]
@sashayar13 is there any additional work needed for this issue?

**Comment by sashayar13** [comment]
@calexh-sar sorry for keeping you waiting with my response. These are the items where I'd like to get some help from you:
- DataStores are not working (I guess there should be some changes done - same way like you did previously for RGS and Travel) This is the error I get 
<img width="1183" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/01a89c65-6480-489c-a57d-232b470f3cee">

**Comment by sashayar13** [comment]
@calexh-sar Also, can you please help me to switch the Job titles data store from kkv to typeahead? So that the job_title field is with the typeahead type

**Comment by calexh-sar** [comment]
@sashayar13 the reason you were getting that error is that the Professional Levels and Job Titles Data Stores we empty.  I assume both got cleared out during the last dev purge.

I created the `job_titles (typeahead)` Data Store and you can see how that was done, how to use it in a User Task form and how to extract the label from the resulting data [here](https://dev.app.spiff.status.im/process-models/manage-talents:talent-acquisition-from-job-requisition-to-hiring:job-requisition:job-titles).

**Comment by sashayar13** [comment]
now I'm getting this error when trying to run the process 
<img width="1557" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/ea7b7bbd-2df1-41fb-bfbc-1800462fa5f2">

**Comment by sashayar13** [comment]
UPD - the issue was caused by the numeric_range field updates

**Comment by calexh-sar** [comment]
@sashayar13  is any additional work needed from me on this issue?

**Comment by sashayar13** [comment]
No, thanks. The issue can be closed
