### ISSUE TITLE
Catch (receive) message event is not being created for a second time (loop)

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#920]
As per the process logic, sent/received messages are generated for every iteration (loop). (check the process model - https://dev.app.spiff.status.im/editor/process-models/manage-talents:manage-compensation-benefits-administer-payroll:business-related-meetingsevents:request-travel/files/request_travel.bpmn)

When it's executed for the second time, the Throw message event is logged under the Messages table, but not the Catch Event.
Please check what the reason is and fix this ASAP. The process model will be deployed to prod on 29/01/2024, so the fix should be in place very quickly.

**Comment by sashayar13** [comment]
I tried a number of process model solutions, but they didn't help:
- created a number of catch events with conditions
- tried to use Receive task instead of event
- clean task data every loop

Still, the process creates a new task instance but not a new message.

**Comment by burnettk** [comment]
hopefully will be resolved by #924

**Comment by dinithihj** [comment]
Tested on dev.app (version 325/327). Now in the loop, the message catch event is recorded under the messages tab. 

Tested Process model - https://dev.app.spiff.status.im/process-models/misc:message-example:process-1b-looping-messages
https://dev.app.spiff.status.im/i/366

![image](https://github.com/sartography/spiff-arena/assets/123297840/b664e391-dff5-40da-8dbb-7a881a00605d)


Tested PP2 - https://dev.app.spiff.status.im/i/380
![image](https://github.com/sartography/spiff-arena/assets/123297840/28e0f76c-f4c1-4b63-9dc1-a168e3f9e202)

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12
