### ISSUE TITLE
Create and use a datastore for Vendor Onboarding processes

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#932]
We want to create and use a datastore in Spiff for the Vendor Onboarding processes.
The datastore should support the following processes and actions:
- for Register a New Contact process, the user intention is to create a new contact entry that will contain a vendor name, a contact name, a vendor url and a contact email. This set of data should be verified if it is already registered in the data store and if not it should be stored with the specific status New added together with the vendor ID, contact ID and the CoreContributor ID 
- for Start Vendor Onboarding process, the user intention is to start the vendor onboarding process for a contact that was registered through Register a New Contact or by entering the initial data from scratch. From the datastore we will need to generate a enumeration list containing all the vendor entries with status New so that the user can choose if he wishes.
After the user has selected or entered the vendor data to start the onboarding, the vendor will be invited through a guest form to submit a set of full identification data, and this full set of data will be registered in the datastore with status Pending.
In the case the user selected the vendor from the New list, than the Vendor should be able to see the existing data (vendor name, contact name, vendor url and contact email) but he may choose to change them so in this case the data will be overwritten in the datastore.
_As part of a separate synch process the vendor data with status Pending will need to be uploaded via API to the new finance system._
 - for Vendor Review and Approval process, the datastore returns a list of all vendor entries with status Pending and users from Legal and Finance can review the data (editing is not allowed) and can decide to onboard or reject. The decision will of course change the status of the Vendor to Onboarded or Rejected. During this process specific Vendor data from the datastore will be used in validation checks with specific financial APIs but the returned validation responses will not be saved in the datastore, however we do want to add the validation date.
_As part of a separate synch process the vendor data with status Onboarded will need to be uploaded via API to the new finance system._
 - for Update Vendor Data process, only onboarded vendors with keycloak credentials will have access to the process and they will be able through an user form to change data regarding url, contact details, address details, bank details and account details. Changes to url or contact will not trigger a status change BUT changes to address, bank or account details will trigger the change of the status from Onboarded to Pending.
 - for Archive Vendor process, the datastore returns the list of all vendor entries with status Onboarded and users from Finance can decide to archive the vendor, therefore the status will be changed from Onboarded to Archived.
 _As part of a separate synch process the vendor data with status Archived will need to be uploaded via API to the new finance system._
 

 Please see the table structure below for reference
 
![Vendor DB Structure - Copy of Vendor DB Structure](https://github.com/sartography/spiff-arena/assets/137384667/7615c614-c963-4a8e-9d6b-0533d3373d94)

**Comment by burnettk** [comment]
it's cool having this slightly higher-level description of the plan. why is there both "Register a New Contact" and "Start Vendor Onboarding"? could they potentially be combined into one thing?

**Comment by MarD0607** [comment]
> it's cool having this slightly higher-level description of the plan. why is there both "Register a New Contact" and "Start Vendor Onboarding"? could they potentially be combined into one thing?

Is there any additional details that would be useful? Sorry for the short description

**Comment by burnettk** [comment]
thanks for the clarification.
nah, i don't need any other details. what you wrote was very helpful.

**Comment by calexh-sar** [comment]
@MarD0607 please let me know if there is anything else you need for this issue or if I missed anything.

**Comment by MarD0607** [comment]
The datastore has been created and it is according to the requirements. For further datastore updates we will open a new issue.
