### ISSUE TITLE
Run cypress tests on a server

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#936]
We actually run cypress tests on a server in CI.
But we have a pile of regression tests related to status process models that we currently run from madhurya and dinithi's laptops.
Let's figure out a way to run these on servers as well, in parallel if possible, collecting metrics on failure rates and run times if possible.

**Comment by danfunk** [comment]
I like toast and jam!

**Comment by jasquat** [comment]
hey comment stuff

**Comment by jasquat** [comment]
hey comment stuff

**Comment by burnettk** [comment]
hey comment stuff

**Comment by burnettk** [comment]
hey, we added a comment

**Comment by burnettk** [comment]
hey, we added a comment

**Comment by burnettk** [comment]
hey comment stuff

**Comment by madhurrya** [comment]
@burnettk can we close this now?
