### ISSUE TITLE
File name with non-latin symbols is not accepted by the engine

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#944]
We need to allow different file names/symbols, at least with major languages - English, Spanish.
Validation error should be thrown if there are invalid symbols in the input that cannot be processed by the system or the database.

**Comment by calexh-sar** [comment]
@madhurrya to see if she can provide an example and error message.

**Comment by madhurrya** [comment]
This is the file name Sasha has mentioned in the chat.
Captura de ecrã 2024-01-30, às 15.01.30.png

I tried that with a test upload process and it worked. https://dev.app.spiff.status.im/process-models/misc:qa:file-upload-json

Then I tried it from PP1 and it submitted without any error.
But when I try to view the uploaded file it gives 'Internal server error'
https://dev.app.spiff.status.im/i/6004
![image](https://github.com/sartography/spiff-arena/assets/110527567/e623f436-6f32-4287-88f8-01896b6aece2)

Same with PP2 also https://dev.app.spiff.status.im/i/6009

I tried another file with these characters - ālifwāwyāÇŞĞİÖÜ.pdf and it also didn't give any error in upload, but can't open that file later. https://dev.app.spiff.status.im/i/6019 

In the chat Sasha has mentioned that the user has got this error when submitting. But that didn't happen to me. 
![image](https://github.com/sartography/spiff-arena/assets/110527567/60cb5603-20d9-4ac7-8b49-21af65be5900)

**Comment by madhurrya** [comment]
I checked from all the browsers, chrome, ff, edge, safari and didn't get the above error message.
@sashayar13 do you remember exactly in which process/path you got this? And can you recreate it?

Anyway since the above file is not readable later we'll have to fix that issue.

**Comment by sashayar13** [comment]
> This is the file name Sasha has mentioned in the chat. Captura de ecrã 2024-01-30, às 15.01.30.png
> 
> I tried that with a test upload process and it worked. https://dev.app.spiff.status.im/process-models/misc:qa:file-upload-json
> 
> Then I tried it from PP1 and it submitted without any error. But when I try to view the uploaded file it gives 'Internal server error' https://dev.app.spiff.status.im/i/6004 ![image](https://private-user-images.githubusercontent.com/110527567/308441738-e623f436-6f32-4287-88f8-01896b6aece2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDU4NjEsIm5iZiI6MTcwOTU0NTU2MSwicGF0aCI6Ii8xMTA1Mjc1NjcvMzA4NDQxNzM4LWU2MjNmNDM2LTZmMzItNDI4Ny04OGY4LTAxODk2YjZhZWNlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwOTQ2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzY3Y2UyZWFhYWRkODc1YjY3ZDE5NGMyZDlmMTNmMjg2NTMyZTgzMjIwY2QxMzY3NzQ5OTVhMDMxMTNkYjg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YqVykyL-tG709ckW-OlouwQPnblPFM6u8kYnPl-kX2k)
> 
> Same with PP2 also https://dev.app.spiff.status.im/i/6009
> 
> I tried another file with these characters - ālifwāwyāÇŞĞİÖÜ.pdf and it also didn't give any error in upload, but can't open that file later. https://dev.app.spiff.status.im/i/6019
> 
> In the chat Sasha has mentioned that the user has got this error when submitting. But that didn't happen to me. ![image](https://private-user-images.githubusercontent.com/110527567/308441591-60cb5603-20d9-4ac7-8b49-21af65be5900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDU4NjEsIm5iZiI6MTcwOTU0NTU2MSwicGF0aCI6Ii8xMTA1Mjc1NjcvMzA4NDQxNTkxLTYwY2I1NjAzLTIwZDktNGFjNy04YjQ5LTIxYWY2NWJlNTkwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQwOTQ2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzVlOWNhOGEyMjYwZmUxODc4NDk4MGVhNDYyODcxNTEyODc0NmZiODNkN2NlMjhmOWY3ZjJlNmM0MThmMmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VovAzh9-l6Cj0i4nDDJT4JQ0gx18bBxQtxDoRr2VRcc)

@madhurrya users experienced this error:
- a Budget Owner couldn't see the attachment, and they requested more info
- a Requestor tried to open the assigned task, but experienced the Internal server error
