### ISSUE TITLE
Call activity for Iplicit Integration

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#953]
Iplicit API integration requires:
- defining the Spiff user in Iplicit
- generating an API key for the Spiff user
- authenticate using a session token bearer token
We have already managed the first 2 items, however the session token can be obtained by creating a session for a user account using the API Key credentials:
POST https://api.iplicit.com/api/session/create/api
The session token should be reused for all future requests until it's expiry date tokenDue.
More information can be found https://docs.iplicit.com/dev/index.html
As part of using the session token we need:
- to generate the session token
- store the session token
- include it as part of the request sent to Iplicit API

**Comment by calexh-sar** [comment]
@MarD0607 pls let me know if any determination has been made about storing the session token as a secret and adding a new issue to programmatically update the secret.

**Comment by MarD0607** [comment]
@calexh-sar We definitely need to store the session token as a secret and refresh it programmatically

**Comment by MarD0607** [comment]
@calexh-sar I think you can provide the technical background better than me.

**Comment by calexh-sar** [comment]
@MarD0607 #1044 to programmatically update the session token secret is awaiting prioritization.

**Comment by calexh-sar** [comment]
@MarD0607 did you have a chance to find out if the current dev session token can be configured to last more than 30 mins?

**Comment by calexh-sar** [comment]
Cannot be completed until #1044 is deployed to dev.

**Comment by calexh-sar** [comment]
@madhurrya @dinithihj these enhancements can be found and tested in the [Iplicit Process Model](https://dev.app.spiff.status.im/process-groups/misc:service-tests:iplicit).  Per the session token discussion during our 02/29 demo meeting, the session token is not stored, but generated, used and then the session is closed.

**Comment by madhurrya** [comment]
@calexh-sar here don't we need to use PostRequestV2?
https://dev.app.spiff.status.im/editor/process-models/misc:service-tests:iplicit:maintain/files/set-session-key.bpmn
![image](https://github.com/sartography/spiff-arena/assets/110527567/a9a66079-b5c6-4776-be4b-f230265b7c23)

**Comment by madhurrya** [comment]
Tested the session related updates using this model. https://dev.app.spiff.status.im/editor/process-models/misc:qa:iplicit-api-calls-test/files/iplicit-api-calls-contacts-test.bpmn

Do I need to go through each request/api call in the https://dev.app.spiff.status.im/process-groups/misc:service-tests:iplicit model and confirm each of them work? I have noticed that only some requests are working.
![image](https://github.com/sartography/spiff-arena/assets/110527567/a9da5c82-0ad2-4a01-a461-690cea7d321c)

**Comment by madhurrya** [comment]
@calexh-sar Please let me know if I need to go through each request/api call in the https://dev.app.spiff.status.im/process-groups/misc:service-tests:iplicit model and confirm each of them work. I noticed some are not working, but wasn't sure whether those are implemented/supported.

**Comment by MarD0607** [comment]
@madhurrya @calexh-sar 
I think we can close this issue for now and open specific tickets if we run into problems with any of the call types.

**Comment by calexh-sar** [comment]
Closing per @MarD0607 comment above.
