### ISSUE TITLE
Process Instances All tab does not load data accurately

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#954]
- Click on Process Instances. 
- Wait a few seconds until the data for the "For Me" tab is loaded.
- Then click on "All" 
- All tab data was not loaded properly

Video Link - https://drive.google.com/file/d/1_gSCHDLQ5YC-uI9-zTuQIEMgbqSGB0h_/view?usp=sharing

![Image](https://github.com/sartography/spiff-arena/assets/123297840/5b2b45ac-fbf5-4f6d-b0f6-d17116a7ac45)

**Comment by jasquat** [comment]
Fixed with #1069

**Comment by dinithihj** [comment]
Tested and verified on dev.app (version 337/339)

Video Link - https://drive.google.com/file/d/1eFXm-mEh8r1NpMO6EF0w6f8DlHC18Dar/view?usp=sharing

**Comment by madhurrya** [comment]
Released to Prod on 2024 February 26th
