### ISSUE TITLE
Iplicit API calls - Operators

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#957]
Review the Guides and confirm that we can use current available HTTP Get/Post requests to get or post/update documents/catalogues in the Iplicit.

- https://docs.iplicit.com/dev/guide/ 
- https://api.iplicit.com/api-docs/index.html#/

**Comment by MarD0607** [comment]
Check please https://dev.app.spiff.status.im/process-models/manage-procurement:vendor-lifecycle-management:metadata-synch:playground-integration-with-iplicit:get-account-data
I have added in the url a contact id that can be used for testing
I have also tried adding the token as part of the header or body but it looks like it is not the good option

**Comment by calexh-sar** [comment]
@Kayvon-Martinez we were able to get the HTTP Get/Post requests working with @jbirddog's assistance.
@MarD0607 is there any additional process or dev work needed for this issue?

**Comment by MarD0607** [comment]
@calexh-sar If Get and Post are working than we can close and I will open a separate one for Push, Patch and Delete.
Please inform us of how the access token is stored now.

**Comment by sashayar13** [comment]
@calexh-sar could you pls link to the examples of the processes where you got the HTTP Get/Post requests working? I'd like to test it with PO processes. Thanks

**Comment by calexh-sar** [comment]
@MarD0607 closing this issue based on work done in [Shared Resources->Service Tasks->Iplicit Process Group](https://dev.app.spiff.status.im/process-groups/misc:service-tests:iplicit).  Please reopen or add new issues if you find anything new.
