### ISSUE TITLE
Offer a way to create a bpmn unit test from a completed process instance

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#965]
the bpmn unit tests are largely based on task data. when instances are complete, they have a bunch of task data. See "Create Script Unit Test" in code for past attempt in the smaller scope of a script task unit test (whereas bpmn unit tests are for testing full process models).

**Comment by jasquat** [comment]
The extension and code for this is on dev.app now: https://dev.app.spiff.status.im/extensions/new-bpmn-unit-test

The process model identifier to use is the modified one with `:` in it instead of `/`.

This extension should only be used on environments where process models can be edited like dev.app but NOT test.app.

**Comment by madhurrya** [comment]
@burnettk @jasquat This feature is great 😊

**Comment by jasquat** [comment]
I'm not sure how the process instance that the test was made from can work: https://dev.app.spiff.status.im/process-instances/manage-procurement:procurement:requisition-order-management:request-goods-services/3179

I'm not seeing where `resp_XeroCurrencies` is set or pulled into the call activity https://dev.app.spiff.status.im/process-instances/manage-procurement:procurement:requisition-order-management:request-goods-services/3179?process_identifier=Set_Xero_Currencies_Enum_List&bpmn_process_guid=299dde61-4333-49a5-944e-060a543163dd for `Get Xero Currencies`. Is this variable a Data Object? Maybe the test runner is not handling data objects properly.

Also creating one separate ticket for either test case would be a good idea. They both have the same underlying issue but we should probably keep it out of this ticket.

**Comment by jasquat** [comment]
Dumped mine and @madhurrya comments from here in #578.

**Comment by madhurrya** [comment]
This new feature is working as expected and any issues we noticed with the test cases created will be handled separately.
