### ISSUE TITLE
Make it easier to test called activities independently

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#966]
Recommend using data inputs and data outputs for more called activities (this is unrelated to testing).
if you have a data input and data output on a process model, prompt the user for the inputs with a form.
Could be in the context of bpmn unit tests.

**Comment by harmeet-status** [comment]
Create a new ticket for this: Could involve json schema specifications. each data input can have a schema as its item definition, per the spec.

**Comment by burnettk** [comment]
closing for now. let's file more specific issues.
