### ISSUE TITLE
Make it possible to test Forms more completely

### ISSUE THREAD

**Issue by burnettk** [sartography/spiff-arena#967]
Should this facilitate browser-based testing, like potentially by allowing you to enter input (pre-form data) and verify post-form data somehow? The ability to actually fill out a form NOT in the context of a running process instance might be interesting for testing.
Should we validate with the json schema on the backend?
Is there some way to hook into the bpmn unit testing system without just ignoring the form and mocking the data?

**Comment by harmeet-status** [comment]
Deciding to close this ticket, low priority.
