### ISSUE TITLE
Breadcrumb navigation displays on Process Instances page after deleting a process instance.

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#988]
Open a process instance.
Click on the delete button to delete the process instance.
After deleting, you'll be taken to the Process Instances page. 
However, breadcrumb navigation is also displayed at the top of the Process Instances page.

![Image](https://github.com/sartography/spiff-arena/assets/123297840/43e1d9c6-9ae6-40aa-8933-94b33886bca0)

Video Link - https://drive.google.com/file/d/1YRV2wG0xjn3iYN0vk5JLjbVrT7gy8R4a/view?usp=sharing

**Comment by madhurrya** [comment]
This issue is still there. But hope it'll get fixed in the new UI. So closing this.
