### ISSUE TITLE
Test.mod - AttributeError: 'NoneType' object has no attribute 'bpmn_process'

### ISSUE THREAD

**Issue by dinithihj** [sartography/spiff-arena#989]
When trying to proceed with old instances created before the test.mod (version 45/47) release I'm getting below error.
However, when I check after a few minutes the instance has moved on to the next task.

This happened for PP1 and PP2.  I also tried an old open instance of the Request Access process and got the same error when trying to continue.

![Image](https://github.com/sartography/spiff-arena/assets/123297840/a66faf4e-e793-4d03-af77-908e4f903976)

![Image](https://github.com/sartography/spiff-arena/assets/123297840/90d28a80-d895-464d-aca5-19281dbd7a87)

Instances created after the release (version 45/47) didn't encounter any issues when proceeding.

**Comment by jasquat** [comment]
I think we need a data migration to fix this. We need to backfill task_guid based on task_id on the human_task table:
```
MySQL [spiff-workflow-backend]> select task_guid from human_task where task_id = '60402d72-9b82-4df9-aed9-68c7ab2528a4';
+-----------+
| task_guid |
+-----------+
| NULL      |
+-----------+
1 row in set (0.040 sec)
```

**Comment by burnettk** [comment]
we wrote a backfill script to ensure that task_guid is never null, and we also wrote code in the controller to make sure the object in question is never None. the code from https://github.com/sartography/spiff-arena/pull/1001 is being hotfixed, and then cherry picked into main.

**Comment by dinithihj** [comment]
Tested and verified on test.mod (46/48)
Error is not getting on old instances and now I can proceed with old instances.

**Comment by dinithihj** [comment]
Released to prod on 2024 February 12

**Comment by madhurrya** [comment]
Closing this.
