### ISSUE TITLE
Upload expense evidence - process assistance

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#990]
The process is WIP, creating this ticket as a placeholder for process automation support:

- assist with complex automation logic
- fix bugs
- aob

**Comment by sashayar13** [comment]
@calexh-sar 

The processes:
1. Coworking, Books - https://dev.app.spiff.status.im/process-models/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence
2. Travel expenses - https://dev.app.spiff.status.im/process-models/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence-travel
3. Procurement expenses - https://dev.app.spiff.status.im/process-models/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence-procurement

There are no specific tasks for them yet, but I will be able to provide more details on this by the end of this week.

**Comment by sashayar13** [comment]
@calexh-sar, we can close/cancel this ticket since no support has been required with those processes so far.
If there is anything needed - I'll open a new issue.

**Comment by calexh-sar** [comment]
Closing per Sasha's comment above
