### ISSUE TITLE
BBHR integration with Iplicit via Spiff - Retrieve tabular data

### ISSUE THREAD

**Issue by MarD0607** [sartography/spiff-arena#994]
When retrieving tabular data from BBHR the response is XML.
We need to transform it to JSON.
See link:
https://documentation.bamboohr.com/reference/get-employee-table-row-1

**Comment by calexh-sar** [comment]
@essweine per you suggestion I attempted to run the Get method and am receiving an error: https://dev.app.spiff.status.im/process-models/misc:test:bamboo-tabular-data

@jbirddog please let us know if you see any issues in this process.

@MarD0607 if we confirm this request for tabular data is indeed returning XML and not json, the devs is provide a means for the XML to get converted to json in the Service Task.

**Comment by jbirddog** [comment]
Added support to the v2 http get connector for calling apis that return xml.
