### ISSUE TITLE
Decimal support in Compensation fields

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#995]
In PP3 Minimum and Maximum Compensation fields, when the user enter a decimal point, it goes away and the value is shown without the decimal point.  e.g. if the user type 100.50, it goes as 10050.
This happens in all the browsers (Chrome, Firefox, Edge and Safari)

![Image](https://github.com/sartography/spiff-arena/assets/110527567/aa809515-2fe8-4613-8f6f-83c6bce4b81e)

**Comment by harmeet-status** [comment]
@Kayvon-Martinez have you had a chance to review this?

**Comment by madhurrya** [comment]
@Kayvon-Martinez what is the PR related to this ticket and is it already merged?

**Comment by Kayvon-Martinez** [comment]
@madhurrya here it is: https://github.com/sartography/spiff-arena/pull/925

**Comment by Kayvon-Martinez** [comment]
I don't think it is merged yet

**Comment by dinithihj** [comment]
Tested and verified on dev.app (version 351/353) using the model https://dev.app.spiff.status.im/process-models/misc:qa:forms:test-numeric-range-field

Now decimal values can be entered in the numeric range fields.

![image](https://github.com/sartography/spiff-arena/assets/123297840/7a800ed7-4e53-4538-9146-9cb3b38e7aec)
![image](https://github.com/sartography/spiff-arena/assets/123297840/74726613-b8a8-4c60-b085-d410f2e61c6e)

**Comment by madhurrya** [comment]
Released to Prod on March 18th
