### ISSUE TITLE
Array under array - JSON form - UI fix

### ISSUE THREAD

**Issue by sashayar13** [sartography/spiff-arena#996]
If an array is included in another array, the component layout needs to be fixed

![Image](https://github.com/sartography/spiff-arena/assets/104367255/db47071e-2634-4b1c-bfc2-c736a4c8e115)

**Comment by burnettk** [comment]
if possible, please link to a process model or include the json files defining the form.

**Comment by sashayar13** [comment]
sure, https://dev.app.spiff.status.im/process-models/manage-finance:accounts-payable:process-expense-reports:capture-expense-data
https://dev.app.spiff.status.im/process-models/manage-finance:accounts-payable:process-expense-reports:capture-expense-data/form/upload-expense-without-request-schema.json

**Comment by jasquat** [comment]
Fixed with #1068

**Comment by madhurrya** [comment]
Tested using this model. https://dev.app.spiff.status.im/process-models/manage-finance:accounts-payable:process-expense-reports:upload-expense-evidence-travel

It seems to be OK to me. Is there anything else that you want to update here @sashayar13 ?
![image](https://github.com/sartography/spiff-arena/assets/110527567/d3b9e833-1276-46b5-8281-73c4ee2e0ada)

**Comment by sashayar13** [comment]
@madhurrya maybe adding some spacing between the elements (title, button, file name)
<img width="676" alt="image" src="https://github.com/sartography/spiff-arena/assets/104367255/4ff3334b-e436-419b-8f24-0fc432dc8fb3">

**Comment by madhurrya** [comment]
KB/Jason, please check Sasha's comment above.

**Comment by jasquat** [comment]
@madhurrya @sashayar13 I believe that's how the file component looks inside and outside of the array and so should be a separate ticket if it needs tweaking.

**Comment by sashayar13** [comment]
@jasquat sure, will create a new ticket for this

**Comment by madhurrya** [comment]
Released to Prod on Feb 26th
