### ISSUE TITLE
PP1/PP2 - Requestor can't see the file uploaded

### ISSUE THREAD

**Issue by madhurrya** [sartography/spiff-arena#997]
In PP1/PP2, when the requestor goes to 'View task', he can't view the files he uploaded. Only the file name is displayed. 
(Jakub was trying to view his file in Travel request and he couldn't. Sasha asked to create this ticket)

Kavon to write widget to display file.

![Image](https://github.com/sartography/spiff-arena/assets/110527567/90873b13-2e3d-4c99-8134-116d1e4e2e25)

**Comment by calexh-sar** [comment]
@madhurrya do we have a test process where this is working?

**Comment by madhurrya** [comment]
@calexh-sar This is related to the PP1/PP2 'View task' feature. This is not a generic feature.

**Comment by madhurrya** [comment]
Still this feature is not supported. Only the file name is shown when you go to View Task.
![image](https://github.com/user-attachments/assets/a671049e-2672-45cf-84f3-069afedbe087)

e.g https://mysql.spiffcrm.com/i/111

@calexh-sar are we going to close this?
